{{- if .Values.gui.enabled }}
{{- $merged := merge (deepCopy .Values.gui) (deepCopy (default (dict) .Values.default)) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mender.fullname" . }}-gui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "mender.fullname" . }}-gui
    app.kubernetes.io/component: gui
spec:
  replicas: {{ .Values.gui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mender.fullname" . }}-gui

  # if deployment is not completed within 10 min, consider it failed,
  # as result deployment Reason=ProgressDeadlineExceeded
  # needs to be big enough to rollout to complete
  progressDeadlineSeconds: 600

  # We are executign js minify at container startup. This is expensive and time consuming.
  # Give container minimum time to finish before it's considered ready.
  minReadySeconds: 120

  # Rollout upgrade one by one
  # In this case we warranty there are always instances online.
  # In case any issues, they will be detected early and deployment be stopped.
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mender.fullname" . }}-gui
        {{- include "mender.labels" . | nindent 8 }}
        app.kubernetes.io/component: gui
    spec:
      serviceAccountName: {{ include "mender.serviceAccountName" . }}
      {{- with $merged.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $merged.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- if .Values.gui.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.gui.podSecurityContext "enabled" | toYaml | nindent 8 }}
{{- end }}

      containers:
      - name: gui
        image: {{ .Values.gui.image.registry }}/{{ .Values.gui.image.repository }}:{{ .Values.gui.image.tag | default .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.gui.image.imagePullPolicy }}
{{- if .Values.gui.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.gui.containerSecurityContext "enabled" | toYaml | nindent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.gui.resources | indent 10 }}

        # Readiness/liveness probes
        livenessProbe:
          tcpSocket:
            port: {{ .Values.gui.httpPort }}
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.gui.httpPort }}
          periodSeconds: 15

        env:
        {{- if .Values.global.hosted }}
        - name: MENDER_HOSTED
          value: {{ .Values.global.hosted | quote }}
        {{- end }}
        {{- if .Values.global.enterprise }}
        - name: HAVE_ENTERPRISE
          value: {{ .Values.global.enterprise | quote }}
        - name: HAVE_MULTITENANT
          value: {{ .Values.global.enterprise | quote }}
        {{- end }}
        {{- if and .Values.auditlogs.enabled .Values.global.enterprise }}
        - name: HAVE_AUDITLOGS
          value: "true"
        {{- end }}
        {{- if .Values.deviceconnect.enabled }}
        - name: HAVE_DEVICECONNECT
          value: "true"
        {{- end }}
        {{- if .Values.deviceconfig.enabled }}
        - name: HAVE_DEVICECONFIG
          value: "true"
        {{- end }}
        {{- if and .Values.devicemonitor.enabled .Values.global.enterprise }}
        - name: HAVE_MONITOR
          value: "true"
        {{- end }}
        {{- include "mender.customEnvs" (merge (deepCopy .Values.gui) (deepCopy (default (dict) .Values.default))) | nindent 8 }}

{{- if .Values.global.image.username }}
      imagePullSecrets:
      - name: docker-registry
{{- else }}
{{- $ips := coalesce .Values.gui.imagePullSecrets .Values.default.imagePullSecrets  }}
{{- if $ips }}
      imagePullSecrets:
{{ toYaml $ips | indent 6 }}
{{- end }}
{{- end }}

{{- $pcn := coalesce .Values.gui.priorityClassName .Values.global.priorityClassName -}}
{{- if $pcn }}
      priorityClassName: {{ $pcn }}
{{- end -}}

{{- with .Values.gui.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
{{- end }}
{{- end }}
