{{- if and .Values.deployments.enabled .Values.deployments.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mender.fullname" . }}-deployments
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "mender.fullname" . }}-deployments
    app.kubernetes.io/component: deployments
data:
  config.yaml: |-
    {{- if (typeIs "string" .Values.deployments.config) }}
    {{- fromYaml .Values.deployments.config | toYaml | nindent 4}}
    {{- else }}
    {{- toYaml .Values.deployments.config | nindent 4 }}
    {{- end }}
{{- end }}
