auditlogs:
  image:
    tag: main@sha256:36f43dc0670414fb892b5d7ad3543d7b5c942a0df0c5c5fc564e0080f6b1aa37
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:8fbd8d6b762a50c24bc19f21bdbc85a2b2db102ef117112c9ac2e673a70e39cd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0f8dfe302997f677d6016da05c51b8d65b89a7a8f96a95894db3909b7b2506d6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d68473f33b577e57521c849c5aa4e10b5ba00e82fc4707059420878108010af9
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7dd4338a2138c52b27b786400781809c9bf50e50169207b92eefbf94f8e666dd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:8e627a7ac469a6e9bac3cef04df6d4f6bbee0f575a3ee963626b3002e056a6f2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3d93dca2cc91e690b8a2bd151b473a70c635e263fbb4936e6010da5d5b8324e4
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e5c5fa09de95690572153b99f6e42cbf715526bec663ca54f237c5fe9fddb97f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:86ea217315564e717a9e40cffe9a363e97c72bb0d625009283ecdb322d394384
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:38e51ea83ec586fe4b313ddfe5205c87111bb2690aff1db667bb81ebaf27642f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:30366f41b060774fdc0fb48762d39fdde957f257dbbf5252163e0a6eb774801e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:830f93810c95e401dff5f542449f4723075345ad971d756edddcf83d7ffc250e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4d7274dfc08de5377c7fcbf06b48ffc597eb0a3481d77daa5ce2a5531566fc7d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f1729bd6a07035360dcfc4a6ffa5790378cda9a65ae05d70bf8ce12a4852002c"
    registry: docker.io
    repository: mendersoftware
