auditlogs:
  image:
    tag: main@sha256:c5dd9d62c72229163f5c0d0a0534ffd4a15ac02dc7c5cd2571ea20fb6b163f6d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4fdd49952a7f9be75fa2a7d916dbd69c3c9cd8322814084ccb829074ea197a73
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:169fb439d5df994cfcf02fe1e81aa256c1e3e8ec5117163bd08df9ea75a714f5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e4da3f50c215b09795b232d50b5283dc00dd26c874942206fcd063a4bd2b4c78
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:bc70d9bf6bc9fcb58989a603a109c3115cd51725158933f9561ed07671294d2a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:222e1932c24955bc85abe0b371a9383f218ba49ebe8763cf04b31dcfc04dbfe6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:768451f4f8b6c4f813860c9d9c9145027b30121b0e203166227f81794170fec1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7f467787505a8d4b2847d6ae2526822a13f567ae8e6c9cc62c302a49ae6ba9f0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b085668322dab245ea88d75cc248b20762e8b60ecee723954891940a83a103ff
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c27390d7a0d9ebea3ba5164b5b41267e1601b20f82342b711236d6739ea6439c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:8b7bbb5f4120085bf98c493e52f16c71dae55e6edad7174391c34f7c74db14e9
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b9cfff5f4b8ab690b17a4fc2e14ed6dba3433ab7b52b46657d38f042d2a0da35
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:78db53fc65691cd4e9409d4ecb2f960a65c2ee72034c62ce5fb284a41af14e58
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:15b955a0c54464afb654c7fb9eaaae2fcc38326e7cfd0cdb830f4af6091e931e"
    registry: registry.mender.io
    repository: mender-server-enterprise
