auditlogs:
  image:
    tag: main@sha256:b8fbeeded105728784276c14f18a104ef17301c23813fdc1500ef42e3000b228
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e808c4b0f05991a2b405c506650e59de38a60ddc421fe481b405cb9a0085157e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f3e29fe4722f8f452012cad46bfc09f72df1f1587e72679d741b124cbaf9527f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f5b92a5078a8820db46b69384de62c0011184df6c0988e634c4c1d2b1580de76
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ac961dc79762bb6b1e69b4e57c5139c04b9d23d69c7ee47b6bc817b552fbe289
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0df23c563e60241fbeeb8bfa2f8ea3448418bba0091c544b5d6875173ec56664
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:69c63597fdc9aa3118c2813d050a8b63ab410b2189de022534ec0d7008ee8ed3
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8a4db86c1cf94ac22b602206fc37633b1dcd6a34b5fff6ace7f540e2b720902f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d917d4b37230b27fee370b25c07a6d8963a7c5d73ce335f19417626cc5fe74d1
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4031baa273f3fa99204f51c614623435e53288e92d6894c3147c19bee78b95c6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:28ec792538274c352d31c445233e513860463f800fd056ca9f040abb151d3402
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e1c1f6be9ddf1a03bbcd10b79f74061498e6e735cfddd4839833b3f8ec8a8ef6
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6fd47a6630e1238bceb26ea33fc6720b4492c5d083a171a699a4cba0a8d7866b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c9853998faa9801cb481839f4ca40269ba6f3fed5bd210b0712a341a05f4cce3"
    registry: docker.io
    repository: mendersoftware
