auditlogs:
  image:
    tag: main@sha256:e6c42fb741f574939b955bd37a6554f9f70be8fcdb2a980712046267a556945f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:749f1ca2ce0f4eb5dabbbbf2058169dac82645ec7ffedd714af11b1fa8fc15ac
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:20a1cd7146412175206046241d4264772948e8dce201a5cc28874bdda2351776
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:52877bc01fdab7ec446a51f48b2e62cec5a1c3173e3ddfba4079e7b7ddc5b182
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:81975f5952b428ec9db1d0409da71cac8ca2c7dba3ad3992335c18bf6fccf245
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0952a2b19395685bb0d8f1a772672a75cf7097b94bd76aa282974ee640351bf7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a9f120503a1aa2d525d497837eb57bd3068f93ae5c52b0c48e8e5ddb5ce59fd9
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f8f2abf534aa0116cf9ef81d6ac5ff71471e30afd0110ac8a047c3c4a00ff884
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2ae8aff600571d4013236d9ef9fe905b688186b158ea035f32ce79b2d7aee6b1
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e93110e7c4c88bb2f2f6b2e144026053b1b21a82810fcc77e28ad6d637df6061
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:34e59e829eb2f64fdbe6f422653082dbb1175aa0ba808d3f1af6e6a78ba89301
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c5eceb549bf35bcbcdd838fe5ff24c8943d8db9bde69b6e43b0cff9b85ff7a19
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4b8a8710883e5eae7d003cee3349203323b479bc7b9a7da873a731c27f79ca89
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:32ab476f45f929840d96b69738d500ce1bc8d864c1b25f6f123b790df60afc8c"
    registry: docker.io
    repository: mendersoftware
