auditlogs:
  image:
    tag: main@sha256:b1dcc3167fb0be7c8429d0d56a8b615a9df2d8cfcd167731e2f686f7b998e439
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2103ecc4bf8ae9a0f9e11d94c403e937f94168ad48bd06842375dbb0521c2ab8
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8cc94103925e0b88c5ecfd9160eeabd5c3de731b3aea0b602c59a4917f7e2fd5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:78db1c98bd5eafa9aca0449bd7d3836a5df5933c11fe189a72a07a57a13382b4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a14c7077d41cc6c2b33fd20f0c4b6d165f164c4bfd781207d85ceabab178b44c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c091de122887e3b13b6e1e0bbd1e573b4b567ba2dabe031f525d243d70bc7b1c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8de3ff9f1461005c4f16f73ab358052400d9e326abc3e688d0c1d330df726960
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3d300eb948833ec02e589838e83a63f4548787c4beac01ebff1256233ddead48
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0ec55099945443083f586a52cd92fdd4ce75d684bbfd4e4577a9bd4ab5afc110
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e55ecad713846e1a306924d908c3ea37b08b04854ae5332808d763bb8972b5d2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:8394c25bbda2d3245ad41ee3d3db41ba64c03441f0a3c1f95a47fe69fd40d063
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:493e9f613b6ec577758b8f7a2aca6bfc10432ecbd8d44f60614b683dbb9dd997
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:705a87f0194fa4adec359679ffc5c8942178974ebadb63ef7cac1a632dabe6ad
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0f03618bc1f2ee90ad223ae1feaf810e9e591c53d5bb55f6bb9a24dadc84ac99"
    registry: docker.io
    repository: mendersoftware
