auditlogs:
  image:
    tag: main@sha256:d9bf3bf14dda77dc56fd6f94f3f8dcffca8c8e8849a822b87354dfd401ba305a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:07df0fa16bbce1fcf5e0c6ab109d5b67ad0d8d5819b7c10c6c61a8d6cdd511f9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:88c8e957e8a35cdf617951f8b51ed11647ebdb84b7c27f25f424cb5e0e1677d6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:01095c3c845d95bd507a8730bd0f49394aa76e8ee21ea48ef7378f55cc6d14f6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:eeae1087108bfc27960a0cd65e9e00e41214f8d787d75e217d83b1c84b9ffb37
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a790cb7b467f2618a0a3295dfce28a4fdca9500341aeca98dbc155d4261a5fe7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5e399309b392f32e737b4e329d730e8a2bc9d69d2f662148b6f462fb74c66f3c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:2e6418a5957ea992305f33395bdc21b0e606e2f83322021138649fa304e807f7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:16f580eae701ce28b6953b4c4902ae25b4f38e081d522d0f3c7250902ed15239
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:483ca8a1fc5b1e2db7e3a641545412e4737f2fae7e7d52b5b17e21c2f03d520f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:da6c9213a78683d58f4c6b3c4ce0c84edd879926350199c9ae3e2acd29c34615
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b42e3292ed983f9a3ca15ece176d90d251d9ee6aced5f2f0378e7fd31bffd216
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d7b37abd38d181eb6a26cac2947c98c9fa8d64a65b296140fd80133153bc9230
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a4c0156c10a2b55537fe7928182136a459e43365fd36dae8b9ea0da0a0c0e094"
    registry: docker.io
    repository: mendersoftware
