auditlogs:
  image:
    tag: main@sha256:d2ba7b544e3f35e4f8160731db4a9ef25358e66c0f48c6da8ace9a711ce8c893
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:19ba380721d00ea6e2f88613896f08e0b20e91912820cf48b18183fb90172c57
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a2038a56aef6edb1fcd8c8e877baeaba3b6b65fbbba734b429595196aceba06a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8f5a2eac3b46174e4d862c8b5c25f0727940f1a85cdffbd61352e39e0cd21230
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:00fe708760d2f5660f4585e77c3e88e31f0ba6a440030184c230e4be105068ea
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:35ea1dc9f9355b7bb61e498eafa9df1b545072a5f3baef7b1f8c8e9d3661b9ae
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:37057cbd9fcb2aee2107847118de624fa6515a9f9aa40e792a73583172b3a857
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8888f28e3508347dcf02d1e3d47051db6564657dda541c6a17061c9e6e6dd08b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9e84b3efc93480596f12ed787d7c9b4b6ac7b3341f5e4c4773aa1aa5895819ea
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b575243edddedf23a74ae4aab6460f84423935986f63665219fbe3faf0cefb70
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:92939d4b803e7439669e3ad73197f3ccb6fdae37e4424d05d52412d6370ec080
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7229396ff4a0c3eb5191430b5a094198e3e1aab433ed3b347be77d958015092f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d98a9e9a2826d26b25713a5a8ce5ba597a2858a2845b0d6543e5c314286bbf9b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:80a7f2b6f368894a3b605ea14e020e66b3ba7c57687bbf5307c693e1e27bd1f2"
    registry: registry.mender.io
    repository: mender-server-enterprise
