auditlogs:
  image:
    tag: main@sha256:c0a19274922156ceaac0fce855505c9b394571daf128df254d31f2efae3e0904
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:8b1e8a247b7159237c1bfa10f1d21de52a8b45f9571f4e4ba97ab5c8d32529ca
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ceb678f90cff2966db1450f73f9cecff9415da101431cd6133fcc011c27bf30f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:67acd3902088c442fcc906a704552dfc5a3bbaa2f43d9971ab6f2271bad6c6ca
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:04019b77493335a3729f28c0923e8f32c22e950adc9bf3974a4df98bd4d80899
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:bbe56e9a51a90c9222aa0ea91187b577823080f340eb2b6485049370738d27a7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6c938995822086d80f5fe04f94c372c1700f7985e41702de5cf01f16c89dfd16
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:25572907cfaa6cd92c32cda5e65616b6c76761f054d1273048b65035c08be4bb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:857409b2d2d7f314375c4fc543efd4f8ac2c98813d43d8ef1a8c71a38759a431
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:bcf8fe76460e52a70d1e90ebf96aba33c82fbe25bea9f6377217f4c8bfe97ef2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e5711b14fdfa009a665564669d850be0d992073efb0099fb82621144fcc67baa
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:eb9aba9c27057f2a5b326e7c616f8bbcf42df204ea300cb170c1f50e23fa1b8b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:cca20ed6946a3182fc3df0edba873d721737d15b515407e3a11863b892e4f9e0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f8545835f7468cd152c4a03de42d5d3ebb006e3e8810ad20ac680b4b036a959d"
    registry: registry.mender.io
    repository: mender-server-enterprise
