auditlogs:
  image:
    tag: main@sha256:67550de9f8cf5c97342fbaf18adad036745e47facea7e103b65ac71c09afa0b8
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:521cb129e93d67fa7d537b15326d3da5d0a8f5af4b8539e9560d494f3f3fb0cb
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:aa657cde2e2bdca2bc9a99a7b407b791d45821bd54fe662182f701d9b42640c9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b2a869120102bcc80dedbd2036719dde3c7f70c6839d26274a4f4cda09cee6cb
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b53c9e9d2bff4667851754d02f50ca7c98a8ea2cfeb20c8b5361c0b0b7007fe3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e52d63a33a20e2c04b70a6a2290f14435014a3c611e171861d42e70ba495e2bf
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b37a0a79664288cb39fffb1695ffe1711ed238465232ce09c7ef267791f62939
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d8574e57a49d8b19019222bf2d9b79d4e176efa0ff630fa65392b96a762cb41d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:49400fa67ba29a887985b3d13435b923b41a7f04c4420bb5c73ee840fba688a5
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:620ea7aa0332b4a64b5332a278c6b4650f790702cb81ef840920c26d09386449
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:576155005eda81845d091a5f1dd423f49b3249b3be23a1fba99c221c74cfba7b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:31cb51f317a9e2bb023bf21b6b6e8750befb300de27bd05371204735f08bf098
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3b58067a1f2803a62d3f7481d69417a7f7e3e34643fb48e23584616423dde3f0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:30ba58e47b775a71c28d5ee6cbddcf1b20e14c0173611e4e4c4284db4daf41e0"
    registry: docker.io
    repository: mendersoftware
