auditlogs:
  image:
    tag: main@sha256:76fdb346c6cc18275775f1dee2ed66fd405d58f6efc54146a7c7c1966c2257c2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ad6a98c908af3aff0d1ab05af2f35052c05198b56b7c73b8a29099276694a7d1
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:deb03c53e6686b320267c181addacac9762617d4f88d7e44ffc31151b0680e6d
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:4c7b6894dc2ca94f367c5a4b3b6795c82c496a6faef2bff3699de29bf56fc4de
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:dc5d2ba78e9ec56e272e8bd46a591aecfdeac81b72b5e277bd67ba4ef70e9fbf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:9a47cca0456096a95809f3f3875e2184b606102c29a9d08977e2a74d7ad13f77
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:855dce0560113ce46bc61e778bb36eb9d2adaa2e603d4f6fb701c47bff859a01
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3ff746b6413cbd51e81e08a715f0526a8d1af467a02d0524d14f0982b2f4fa55
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:74fdef4b4203ff0b14cb0e2c4420209446514b31263401d7f025bca651d887c8
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:99475d9f7a44eca7d9f67b33220bd44758dc2800013da070ac3a2dae95f45887
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:3768abd9e1db5532dc95f874f9fb8131d5d37e2ae82243abfff825ae11d79695
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:50e54eae95055ae1d8d02846d041ae938f37cefbde2b01e062f7a2bff46fa0d1
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:960dd6635f7c53d4e3061e03bcefc86f592dbe1d32a4bb529b5d2eddea7a761f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4a8a44c9f3b0c682bb885c725c0015648dcf9aa1332beed829fc0b35f248c07d"
    registry: registry.mender.io
    repository: mender-server-enterprise
