auditlogs:
  image:
    tag: main@sha256:16fd95985d96aa240cb05600e9e9c0e47d10e2f071fa7f3c46945306b5bbf8cc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:55818243fe5ba7e9cdaaf807d2d8ad062a5e198fcaee350f62ddc6ff5d92c465
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:100bbb67dc5e3c8b31ce2898d32fb566bfbb26432e31aee34d5c8c35f14b7b5e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:78a4dd2e05f2a8176c7ae6c5be45365355de3feb29a982f314e6ae51a865f54e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:488d335a648835786b4473bd2b7c1d6a4703b48910f496e7b8f0b3d32ce23974
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7b6d2303b3582458e3ed1381618157b397bbdb9a1a55c9850fe11a30d72b0a53
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d95bf1b8399f32781df450169990a0c8acaef7e5d365b1ac0accec828f1b09a2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:c60e6f4d43e107aa220a9bdfb31bbaed86e7a4da086b7076ec75f12571464af7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4d72ab17248340cdf97625d75aa86aede307c196c0fff8b92dac7dc1db4bbf74
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3ccb4971c3f809061d132a0215859ed5219c6524b1824bed1668badfedaf111a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:422cb2ae8833d66480e52cfa64b5101ec37e768703e4fa7e5bfdb943870ce15a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3bcfc94e3e9a11e181d815a67034497daa122b4bac53c5cf52b29a708850c594
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:af32cc60021b964b495c98a2a023cdc4f3975978deea66a5bdae3a1df6092412
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b7fa0dd6507fe86d716e9053e37ff751e9a8ba77a06523358dfc2faa5fd3a309"
    registry: docker.io
    repository: mendersoftware
