auditlogs:
  image:
    tag: main@sha256:49f4add7f4f22063de784798b581a240ee3b59e5679f545b5907720e5e3156d5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:27b7dd6d0c066db9e7963d3427687e1d34b7de9af4abe80b0f56646f1e0ffb09
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4899c0283550e0346158f253ada1f62343f1297780006ccfcbe938baff7d7258
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ad8ad8544ae277a6cc83e1792be6755b3d912a90b4c4e0e88a783d6ed709a74a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1b5cef6a8d1ca9c2a6bf552e1c5fccc4219fc7382273989f28f05229cce6b95e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c3394a54f9506229059025dfa3a2086dd0066150b983a8713d70cd9c1812fde1
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6ada80e6b0a0e4436f3da57621dd599331b92e2fa194e6643184302bfc5f7500
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a6425a81dd5133dea04d128d9fcd3a5f3dbcb2125e5ce24a35c0d90b87a4dd5c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0610ab57ca23449c2414750ba3df59f5ec87459a917ccf398be31759e567cf11
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3c30e719cfffada3231b0a9b294b404bddcd93ee588294a620ef37d9ad444d82
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1b0860278f34567a09be9e650007275139c9960c6c257f91fb006d9e2014ba20
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:36104c9842b473bd291ce1f97833711b324826979b90dea5cfe9de20a773fa26
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:caec616d20ed730d76312052654ecd3428ea56c51190edcc455473568b74f771
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f1221c5957ac0a560bb43edac69ce71cf67f6a59b6d6b7d7d99910b7203eb7ab"
    registry: registry.mender.io
    repository: mender-server-enterprise
