auditlogs:
  image:
    tag: main@sha256:6c3094e4a47756af5c2f5cb28d8964b4de251b4d03f42152c610a10629660619
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:56aa3777051bc02ea42d0a139372f7b7fb23a2d119ad327c574e2edc01937c22
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:06b60b75ff01dd79630ffc274f781a21b7004c4c5507b00635fea80c26e62a61
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:36e2dfd3a766fd6df30752e64734c41c84c583018319e505f512d1273d6da801
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:284cea8a3a54cef174a523e9daee20454dec5b6e71c4b57c8050ee9057ffb7a9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d85ed84c9ff710bae5f34b359e7cc6946032007eabc948a813000e7b16b47431
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e92d9b5df0e96fdadc526c1ab4c23fb9c4940c5aac62fc229283b14e1449196a
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ba739df677311ba7106a18af09a14f3b5dd868acae681766f09989e765e1cd23
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4985a479b5af9edef2f45b00e633648d8da21f875d34ce13f26446d51a8edd67
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:84578256dcfb1e3bfcf7c35f3fdd9b34df4c2cdf751162178c5f731067bc0442
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7d9657949ca18496fad2f86812ca31590d943f74d751132f92481b3d3b7f5db1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b2ea58cabdbea4355ebf0df7f5c33f9abfd16ea759672d3481e221b9979fd8a3
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:283376ca7c28d987dc3bc9ab6fe3c989ef76dc019fb0eeea39ccb09cf3f15125
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:91834c6a0f683aac9d01aff80757f40d3b3fe2d1458a763c80b3ff455a0d0877"
    registry: docker.io
    repository: mendersoftware
