auditlogs:
  image:
    tag: main@sha256:97496c40b5db341a4ef886280bdf6cc959df2d14d3f38165a21db25c6cbc3afa
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:aa738d2576b348d0546f09fbaf71ed4161c636b0866d4db0af9bd1a210839ed4
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4849ddebae9ee5964afae4b6743b869dee692e4e1925007fc6933d6ecf75b57c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1a95b0ea264d87e3f784ed8e3af962e2dbbdc7e1043d206cada6f65db1ecd473
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:6302522fa535d9e62e1538348905835cc2ed1103c22402bcbeaeb422d24c3557
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5bc8fd279d4f7805c0dfa9c66be322b600cfdf068b15f75b1dcd3ea3a44fb749
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:fe27fb78461bc6dc6fa9955bcf73f001c374ac85d1b8eb56c0f3f3a4d5f215f4
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4874db6fd21981393c9b3a735a0f7b4a3b157769e037ae413ad7efb832d636c1
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4ca3350adf56d3e04289fc55bff24c4fad35332800752e9ae0d6e6ef6a24fb77
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:47c48ec9ff4282f2654ff5c1d4b59ecb086ba5dd839ff90a43f8f186471531e8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6f66b421fae77bd69fe6edbba38b58b40a958335335498fb9c3354fb2233df1f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1633b647471f8dda63781243bc2327231f3f68a0f0157cb2bfc76e7dc10a2005
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2ca357f96e89df55a6b8a526143705507a7d49107f0f95b4ca98c60a6e596ac9
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:334eda2114f8abf4e30cbd70f74662587092a6628f0db0b240abc155dfe3dfee"
    registry: registry.mender.io
    repository: mender-server-enterprise
