auditlogs:
  image:
    tag: main@sha256:ef998f67013f5769fad1055b660aab7dac1b59e052fad589b110825f2049332d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4e4df2e77b8b51d96e09291e0778ef7753d1d055db084fff39b1899706f79c10
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2cfaea4ab6f0b1336f53d6e652834a9f3f4caf746b48b396f907d4b79c8f3dd3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:05f132f2f091ead734d91cc6bc1a9963bb5f6053d3b084e1a637cdc3edf097d9
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e04ff6f7225658f7456108f4e4e95f7d821d60e1ca78300bc3efc56134c49983
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c0293ce17037478416662e65d7722d923ceb0c28c5060c956d5b291ace381727
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8d8003930386bd10aca05e4ab2de642d07072d685d4dcc19236842bfec017f8f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:23decd7d47be9ba1a70534f08fb55ebbe70bb4aae54592d1668d21079f5a67e8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:284c47dfa0ef2961a65fd9cf59fdd674f793ca0cbbf6bbe91a27c0ba9e1aff8a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:70aa553e17d3715e62bc65aeaeaeb68bdddfdaa12ed922a1a3f477e52ea4ec53
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:599d311b9ba2b9877a75c6cc7e0acdd94eec610ced04b3e12efc4dc8066542f8
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a09df401363af437b6451f90f35c5fbd135150ca170b0f9ee0631fde016add82
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9486f9cd71a231b009733c613fd41bfad2562aa71e67d35faa6ba976f43b877f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:501017fa9e310c89958c8dc7f2ea6014b5e48e57c9a4513fb26e29574bc51e92"
    registry: docker.io
    repository: mendersoftware
