auditlogs:
  image:
    tag: main@sha256:000b844b2690ec471ffe007d36ff25e86be40af5f092d16dafa5aa90e72c3370
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:66d8b944eec040c48bc837af0e16d8dbb163072c6303b6f84eb19e12d12419d4
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3d903dddccaf2ecd9cb831a056cea00e0982904c8aaca0b948f2a44468b53c90
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:294e56edb37eee56b5abcbaaa9549ee8756725be4ae9df9acbd339b8846c4491
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:0b82e58f768780fa45ad3a716b297b5ddb119d7f2aecb8a2ec1b64e4a17ae1ee
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ef292001ccc6ed08ee0b6e510d2c506faacf1b299c48687d178a7ec78eba3b8b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:911c2b89cbd643f87d4369fa125ce85380e4bedcd1ce703d5113879564505bc9
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3d48349c3f85c2545cb01b6b69d13c8f43d804fb476c3dce283e0b1d0d1af958
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e861ac03b5dfabe939c08c92906fc4600159649385759a4bc7f2feeeb415e3b7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f94df4ae85c1b58482a07f2c2e465205b5684e5eb67f617fa01bf033a7bb9521
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0f6dd6b67b4dc6258d15b3d83aeaf94f3f2a606bee80b7d3f07605f1f7959c81
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:2b6f31dc0cb149d54306078f253fd0a6a9c3224d7068e3dbea21ee354bbe94f8
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a08fabda363b6799dc11661b378a7b676aca4be4adf4c0c40ed74481222eb3b0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:703affe61ca3293d613dbe33858f6afc11c6d028c2f3e7c5e44cd5b7734ec30c"
    registry: docker.io
    repository: mendersoftware
