auditlogs:
  image:
    tag: main@sha256:0286d81bf48bd20a16ffcce466f03b201fd2bf7938507f6040157525a9d084cd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:decd0403a656f55277042ad7045d0a68f9e76ea89ccf8f3a5626a8fb28acddb7
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0cdddf40fb5a4923edca197ee7fa687fd24923585c220c6e1228adee8c1b3b41
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:df87e775fc31876dbfebeaaf78fac7a5a5d6f791ff0441e8bb687f28033f2dd5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:da78436ec24d17788888d678cce5a1e5d4643db3ba1c5cc3f0e50d5d67c2b2d0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:87b74226a061fd52fd2206d9a0705f101250fb9b15d994621124272031f91229
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:53cb4d2e5221b486fc38af7c4fa84ad6c7d28482c77ffd6579e66e505cd647a6
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e2fa5c47db3611cbbeb306fa2ef5755907462bf884b968d08ea42c7d4ce72488
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9a4604ffd1fb4d44ae5b95ab29f42e2804bc4477942f943a777d4517afb4aea9
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f36af681d012d521faece1da1043a4c60653ef4892b05374d91106efddbbf0a9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c8c0bc70e68e6db60b8255d8aec892bf77bb43114abfc4491110711e148d2db1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7180f9d0169fccbc710364c6ed8008a23677186e5bfa3a0969d57c32a1f6e229
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:25765f1967e1fd6a0170e005d53d3361e6337b3244ee15fd5c15999710fb313c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4ca16eb0a28ba0118534939dccf63b403b43ebfa26dd4498d316ffb89e20972d"
    registry: registry.mender.io
    repository: mender-server-enterprise
