auditlogs:
  image:
    tag: main@sha256:999b7bcde85ce63f87e1e2ad2ebe644c5cb3951d791cc1ecebfa2892fd5ddae2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:aa365a425e7d35fd24096ef6490ffd29d6e20b9707e0b021b030a07f80540b08
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:50817229769f490e5de6bcbba36836cebb42d8e5cac47829c7491e8ecb7ad823
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b8dc1309350a2bca5332d0d189c476de7d5269db7f16e53ed6d77bfaaa06702c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:39fde085d365ea1f14bbf9fbd7447dad52dda933d1443acbbf258c38c5404203
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5906461855cf04c3329c644bd53be9be3a7d46c6422da38d47243bc49e1b32b6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5c522bf7710da071af06c2dc09b756231bc69aa208fec8d1ea21442fc27dc1fa
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:13830c1e3577c8d89a9c9cdd6e66c181d7f69c8ddcc39e1ced37c3dfd5a32d84
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:6091016293c09430744b82bd8073884bd9efbc3ae079198ab2fe72a5a567efe7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:cf3a37b17c64f603e3ecaef2ea6ce701cbc8e881ee0b48237279b7ffd62f0124
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d3b7438b5e7cc0c7a2a8748ff417af2310741d5a862144be8d5ff5368189eb11
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:702c6ada8ca53742aad6fb260507632e4253f7672c815b2f19aecf5ae3d09376
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:edd228318c1f566be17bdddece66e6b59659a5a23fcd2a4376b254ca0796795a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d2e72f035998d73a9b01deba2939ac94dae24d5d0573d4ed61c7c0a24e3f266a"
    registry: registry.mender.io
    repository: mender-server-enterprise
