auditlogs:
  image:
    tag: main@sha256:fe6a22fd1afd05ab22f7cc749ed558c674deaf7b96675d8de460e749a06e245c
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:959bab9ebb2e39161f148ac79e6236744cea786d8327c4a0c15b97f4e271f51e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:17e514f1ca69ea5c0f59079475252aaf25223f50aca6c57b07b2a8e26d6fb4e9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2c92486126db9f57a36557065a6e5df7a49cb67733588e38c58adea9062c9455
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:019eb5498e5ae38753dacf1f47ea0b7a6066d562587f7a1b8cb4a1f4cae64749
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e362ad9567adb611b4bc3f1918d345dd5c90614766b4a26e93e7acf71845d6eb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6f62321e9c659ae9bc02cace9249623f0f2262b0d56fdb67d6844922b23f5816
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7c00e46f4e791fc6e4496be02240a371d8d38c5aade70df967c9db002a87d42c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b9a80575b076394580d6480aef0e6ecd092c5d68a87fdea9a1122356ee865484
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:23ce863cd1fe65af97c1e140f7b2620aa55aa4894e5cdfb7e9920d18ba066f41
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:668ab6c1262f10790094d28aa3b9e8d043afae3b183de4b7d7a74f8d097a8c04
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e99529805c7b2bd8fdad7c8fb05477736ddc0b81bd770cb11b0889d9ae572c44
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a32b95fda6cc3ef055e366a09cacf03a3c09a5c1d1aa1d87c7e9e6e299a9238a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:987da2d4bdec4eb6bb04c63fde11b900fb73bd128d1907bf1da74d707d11c84d"
    registry: docker.io
    repository: mendersoftware
