auditlogs:
  image:
    tag: main@sha256:5f737d065bcf0eb366d423c123563ffae5f3ada650993747d166b438ff9c2bac
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7a8609a4a65db598fe4f39939f7de5ce295d75b6daf5db117379ca486c80b0d7
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:65136fa0c3e672225ca6e7bb751031cb4eb1762e6c91ac772fd7e21e3fb1769b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0ee51ef725248391b1ef392ccb14b8feec785371ef80a112ad145e50e443647c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d17b981cd4335cca79b7013f807544a194a7a39c565dfdd43d1dafbf2cd6b1b7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cfc1a86db14124e33a79327719a3930ee9d71deb28bf4d846c0006124e71b86e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e4d129c5f55e63ffe6e580e4bedd91722ee7698f5f2cc65f8662fc541b79394d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ecc8d0b1c64e7aba940f8185b2b98df7f08879092b6c65822af5a942ffafb881
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:301486c6137f1b97114b20c6a8215d01f1877c3f897301f50a1aec75ad9af758
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e4c22e255b9218ffa1ec7f3218b7a5ca2c649eeff86fb48c5a348e63e42551bf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:3a131aeac14e9395933becce35e673187deb4514deeb0929d84e24a29552ea4f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:9551f836c33619906644111105b4b48405d1cea2c443abc1cde19dc9eff73582
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:32a133753811b4f76eab42adecd385ecbca0fd5459a396d66e3584a024ada010
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0c178fe33ab240164cdcaeafed096ae02878afdb3ea6b5a72efda303462b1b7e"
    registry: docker.io
    repository: mendersoftware
