auditlogs:
  image:
    tag: main@sha256:810796a5c381e8e788705497542d27d57214140a0ed7c28975fc61e497baf1ce
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3033addc117e0386465e4de73b9fbb9f346dae46e69f7e94b599f91d7912a7ff
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:e69a1f0cf03905e45356b57e912d70f47bd73c589eeea8b87470e858eb5e4a39
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:02bacd919593186da1f95aedbf646a323450f2e116d1fc08f6f0332ad32bf142
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b158d4d5de6758f8fb334eb4e79d099dbaa26e6aa30791abafeecd051603d777
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d16c8887800cea12e405403e117f1334c9bccdbf29d2011aecafe6fc917bb4c3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8fe6d137a8eb89ff8099bd168194d20998151675e59eb72286f02a760a9b8d7e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ce7553784abca191d12959c3edfa21b7a514139f63b61e1887ea3bd26cdaba4a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:51a867fa445d5788fe858100de7e7704a40942f3b9ebbfafe23ba04fafe209cc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:000ee9d11d8c49a1a2b1f6608fda66054411ef74c3606f5eabf3c0a4ba51ce15
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e3cec6e6e3de38bce9960638c92a3cd8864c030ed4b28217dc07b075d9cce175
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:cb7d604c3c0706bf4379e165d10af95c2677a2fae8d545e60d319e42c39df131
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e9a463a7c595bb1acd534924ff6ce3a518d5c2bdeefd5a170798b9c99c35bf82
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4ad21d69fd6f9dfa7cd158e28a17d8c0f492396b03965e3cddb3893d2ee41e77"
    registry: registry.mender.io
    repository: mender-server-enterprise
