auditlogs:
  image:
    tag: main@sha256:e7861e0ed80d4c49f5dd70dd0cb6aafc5eec2b0bcf9ff7153a662ea68b6c4121
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:90389acc3c379272bb36334e359d3a410de7414b26a9be6a1a12cf58f928329c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2f859528bb0a9cad2d4901d96343dba307fbff685329408207734c96c6756676
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f227f2912fa7cc6dbd1f7505c07545ee069279f7c545a527a5dc2505182e87be
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:66b9053ee52d7926ef2bc556d981a3b52f6ce3d1ff54bf3e73db215158a215f8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b5a4d3b54c0a85b6d5866896c7f69b395f1cba18fab5d1888712385471c49bef
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:bbaa126c59ace4239300f4cf2d00f0b34b09c71b85065df57f91c69253a4369c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8f6f7d813b866ceca41e7d3cf9ec37f7ffe31264483bc5ed689060c8f9d774cc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f9a32a11c2a6c3d8caf9bb4d929d06d8c4ecc04a81d9e4b8e0b0ae8fb4a2494c
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1a1bff5c732d708aa448ebb2bb29d13734b9c0b3a9e62a78e7689e6bb0e925e8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:afd00ab2784632b749dc80c7ce2ef1c082cf0c84dc4adb57b230b47f1e86e6c7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f0fc7fdc2451c0c0ae5af7b13f37ac49344759ae88ed121e1e55aa42e266ea14
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1c3fc1c9b27776fac8d29f10ee453f82cc2b9df6830325370cfbeb53002d4f9d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:bc4d7beac12a3f4946ae24a393aa016ea4cafa041c6fcce1fa3ac87989ef2351"
    registry: registry.mender.io
    repository: mender-server-enterprise
