auditlogs:
  image:
    tag: main@sha256:7abc09bc01f4de2996343d846104145ea729792ffe85c821da62b27724ecf2d4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d548b39e9bec2ae4e3d21f89d3fb79ac2cf65d90c7cdf06bfcdeae3ddde8cb87
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:711af65b276dab7723feb274abd4ea07f8f1582310bca2aa702727bb6bb83ba3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:be659877510f87b6cd4ab7d843aac8527963899dba28c3420429726aea82fae1
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ee6a31398474020e8d78a8dfaef0bce00a1c95a53e1c5516bd75067240aa5290
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f5fbd1706236c518126dff59d5427aaaf66e390b2281d47f4137173a3351faa8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5e48598b9ba39137bc3172495bcae0e21c9d7b7c2d510af52b68e7e9e685bb52
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3b1f1daea4cfcc594774f90beacfcfe3091a6ee76d0ed98b7585cc843b9e4c10
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:847c2eb9ae9300162e3b253bc885192aa365eec103f56a47e2507fdfc26cbb88
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7c07504232e23698849448a8c9c7aad3f0caf6368c56fe665520a4477a0b8b4e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6007603ce0421aefcba51814faf4b5cf65c170e8c554c62a5c0e649865d9fa84
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7a8c46460ae21d6150bf5c38d36ae9d1547e4e4204ad876a7eb1dc172e198bac
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:55adfabb17f8f5b8bbe04735f33d701ed9aef96fe92f449168ff6e6637074279
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f07488b9d501c7a342bc3b6e37bb1f3f891799d5cf9fa0ec1c05776c98eff348"
    registry: registry.mender.io
    repository: mender-server-enterprise
