auditlogs:
  image:
    tag: main@sha256:ee84d6b5395ad6f457e16a5c9e717fc289b76fc87226829a83fd197ecfd101ed
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3ccc8818b6a5de412f7a2452ab42031329d6d2d7de6a584823bde1c9cef9d188
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3c9fad5740360750da2199527f9a9cf7a682845a504726b02eeb68a9c0cada77
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7674a9327b5d5ee555fb2e711043762d0b98a5140f6bb817f75e08ebf969fc80
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f0c39834f5b9508f157cbd408fb21fddb2e0b7f39247a852390a527de0954c87
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:bc815c137164d3e9456cfefc53e8b908be8d52501948d809a1841a1c1ab43f5f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:212413c2ecbf061e14b929f82c3064a25ddefca66db82abadb66db7ab2125ce3
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:083c2357b454ec307a6a03524ac19b95ab22ad51fcaff179848898ef457da8c2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0d3fd5acfb5f21d842dbb24cddda712e1856442c9bb1121e537e5155869c3c06
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9cd5d727daa21c8549b15213c57dfa9bbe55862b743a96cca40e51fd7ec1a04e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c06c69a33d5de03261198291faa3fa3137a5f538d3160bfbc7573d0372a91c6c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d69d5fd76c0082ab7ccdfeed103a0f7496383df21094cb9f1eb08eac2331c865
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f7bf5d616f0e83ea0731e7eb1069ad4df4f71714e388d410287f80e50ff45be4
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:bd4514b470586f66912e3f320facdc1fd5d63e6e7e055c8e93ad9e078d587cb6"
    registry: docker.io
    repository: mendersoftware
