auditlogs:
  image:
    tag: main@sha256:9690c2232fd3ecc9824ba676af476e4ce11e3f9249de336273c072706c37b44b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:182f828881ec0524b5efd59b81e07460a257431f93cdaac1bd329cc6464807c6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:234d2e6516d82e7296313c0d149b7807f0deffe1a6f19bf75bb8fb8895fd2220
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c61296c5ac52168a74d374f19d2448ac40b6df8d7481a19b80ef5e91ca316ad6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b8bf45af2f0a3784f576b14bf17f7fccbeed027e7a6098a50c955e61c1e00886
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:dff1cfa1a16fa2bca58815ed074bba5a0df03f059916f6fb2ade68dfea26e0d5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ff5dce8f86ffc337df3acd6f79c9d2ae3b7aa18a2914b4e85d90d9d3c952592b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4e8a073179c684e6e266334cb753910af6ac5dd402d8b671446d975b42bcd5df
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:720105f01553f1b92fdc8795ec1c026d3cb610b88a57521eaeac23b4d0a742f1
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f579fa9af925be11c9e023fd871b2d0e4541c045f5d63349d61cc1a2936f8849
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:126da7cbe27c41b0460f8479bf08b209379b78823c320312de3a0dda0a722154
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:0b801b10a298b7f68347e4fbe07e2e672e4982b2c9b225965d80ffc5e0e08188
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a05e5c0855e3fa1c1426d00798a7eb981a71b7b5f963a7882e4800697c972363
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:54b7d5fd4d2ef434186b9379710958caee856580bd4368ca63d81fda9641b085"
    registry: docker.io
    repository: mendersoftware
