auditlogs:
  image:
    tag: main@sha256:94d178748c8dcfed9d22ac8f9ecce4ed293318c322eab1f1b48fb4ec63df9116
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:8b128951cdfbee6a9114e894ee733b91a4fd4ed91edb50ef5ed26ecfabd5a167
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:db3fc0f65898583b8f46ec9988eb4674b6ef7078b2828735463d7d7012e8c292
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:66858822d490e353166d640a15f84cfb9af5f2b18c6198f45686759ad1d490bd
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7ea77abfc47aa619b7d8cece58201efcb424ce55b22010a38c278e3d272c86c8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d0aa64299c67c51c7db0a9d9c5f71c6b217451e69a2b370895e1dbd55ed33260
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f86fd9e48b25b6ae42c9879f6ba8a736477d9cd0a2bb8422676ea52ad972f86d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:66b6b723f0d5524a997898fe43858997a0559fa43305ce9b19a11db838123c98
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:47bf30efa30ead25bcd67b90979c8cac5e5241bd82f1fa0584c1508c29a3ca57
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:37dfd0b0ad222eff1d3dc1a586f1fe5747f50ee79c79ce5d48e0c56d0e2a8bfc
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c4a583c3b038a62b31d2891a3d8df9eb931a263bf1e2c006c8aa917bd193cadc
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:18106a978b10200b81cc313bc8df14490f28b152c28f9c31362b3c8c7e76a8f5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a8e1a84680e5b25f9296cb1b6c3901befdfb00b0a38046ffec71b701cce4bf83
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:dcc2e885dc8955bdfb957dc9f1dca895d09ce19044cd620d7256336e5913cf0f"
    registry: registry.mender.io
    repository: mender-server-enterprise
