auditlogs:
  image:
    tag: main@sha256:464f9e7da51b35064413e4e1820abf6c347e295b7d95f721515d4fa45d07c3b4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:35707c10a408c0f863489dda1f6bfa077b664da98762489f47bd752465e75430
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:374d2a8694c95eefae794ece05cd2530a49492b167aedcd15d2158fa4798d9d1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:808958f7e5aff3e26e5438538789e8f1cd48c4d77dc9235b0b58df4e97d80238
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:760ee596233fb0516b958683210c05d9758667f6ba49da15ee8f1a676ddae698
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:9bcab073040da859ec4c8884c2f355cf6230c7dacd9edf450f185679a925f033
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:de6b8a602b1445bc59267ed037836e93330808f00ea3fbd3d4580cfd6917d613
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4c0583c34ef0435c39237eb46ebff156c5d6ab830d51fb78e4e17ec95cdc5dee
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3f7ac7bc7dcdf919e6dc6cba4cffa1381e4736efebf5c8537c8b17963350ea7a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6df6de7bdbfc1e480ad67aefecbd69b8a3423d4a65737f44f7deee908e6e72b8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b04a4f52fc779f4d7d223396628c43402575b39a3dba417b19d744c225c808df
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:80218aad4f19909da54f0752c4cdbcdf17c56bba0f0f75ba4cfb8c69b8c4d158
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:87a04cb253a96a682ce3abdf07cd5db8bf68d14c275a9bda7058220a97a697d1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f9828e5a47c44f83ed5bf7d177a0df50e47aa0cd31779d26730f76e3b5c701ec"
    registry: docker.io
    repository: mendersoftware
