auditlogs:
  image:
    tag: main@sha256:5b004dba359aa58972a894b30e8947a3f22754fd440be6bad999b460d121f88b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b058cd7d6977e5a6020835c3cfb894979c6be298a8dd1f262dfdacae8aaadff6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f70ed9682a9bb98d0911ae5180bf23abaa46798d3dd89ef0f8bd05cde269ea86
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:865dc70adf7ed806a1cf40d8c363382c6e793f1f0538d2f0ecc65cc4fa19c73d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:371b2266c855a464d4990a029a1a1c3f74f3035ad9bc32fa7970bf12738eb250
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:49b8316c5e2d750bbb48b0b9513c10c3965cdc1ce0aad8036da028c219b24782
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0fe9183fc1ec9636b2178f969701b6f0a09a7ed4ca0fdd7b2356d7229840821a
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4ee12e863cdf9717ae2867fd01dd4dc171020cdce5a4f37fb9cb36925902c3c6
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ca501d7e5f9df6b770f03013fe2cef701b98aead1392c0051b2d517720cb0747
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f8a45546c74a4e76bc530bac303c44d7da4f968a8871f6a9bf2b989f1f5989e4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:51bcde9d1fa7ff98b10c9c0e46a631f9c8642f77396087fc6e8a20df6e6a5712
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:74cd59d5fe1fae2fc7c9f59dfa4c296ddb6864478586852d9e80b8d4337f488e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6c827f5666cea42b0a630f8c61928d1ab91affaf75935c453086e708432391d5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:efb0b8f6d5d287350f92628c90f7b5b9d85d1106baa3fa245eaef6f14d188468"
    registry: registry.mender.io
    repository: mender-server-enterprise
