auditlogs:
  image:
    tag: main@sha256:4709610fcfdfff3e1661337d9d6fcdd4f41ad04fbbb70410aca1a3cf67b571e5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d70f43be6f33c8aec0687d653bfce70b43b22220ca9cfa48142c1bd1ebad2269
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:e1904a80ba095b36fa16b15890892417442402cfbd5493faf9ae535f1c9ca4a9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b2ccc4c6f709f6751577788998111b282cfec34b50b41625a0db311c7492cd4e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7dcf5ac0b38d1cc1cfabc224d869318248f961ac5d1a11d355f02389c0ffcca3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:171cba432911ca6cee07ec544e4bd399dc7be18f97e0ee70ffd5b37d765a250b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:2629afa4b61e0b63e555f4036f11ade0da817e3c185a7e3eafa815581ee267bc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:60b46e7debedd4027c04eaa7bfab7addc3873f66eb826f9a86379c70ca76175a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:600f599a2ad9f0dc2ec8ba6a7f2704f6ed99f14b6c1630f2b418dd739811aee7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:29ab7909c34c8ee44668b3a0cb02311ac5c1079f1a8263b385f068fc263f863c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:814f1afac9154c4317caf801b92ccff74a7fdfcce8e19f53357edebfd1eda99c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b2f05a1b5e60fc52f7e09f8b7635a115ec38660c41d38ad0ed09730082acd266
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:af9668e11f962fe7d3246d081981eb86a2abc92418c518146d8fbe13a1ae5579
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:93fa4005af3633a59eaaa841abf031cc29f05c685eff0f31b1c21ed28c389cbd"
    registry: registry.mender.io
    repository: mender-server-enterprise
