auditlogs:
  image:
    tag: main@sha256:4dbc867a59486d486b3a3fe0c65582a200f5e917263928475501b6d03e6b2e40
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:996febf67d4d8a8e44b1d5f51c3f3b65512186ef1653f4800951fca287fab364
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:9226cec1b17a04a8157df7907d1e60942e18d7b2e77c29895704a7786a0588b9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9dad7ef9de8928d34470d2f46781a42e1d9c1163a6c4888de74312d24d43979e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ff44e8ba188cc5a5af45291e86498570676f96944f496fb171a1a8517a879a36
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cec6709a422aa986bab41be057ffdc508e1ebcece80c6941cec8fa2702f32e85
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a42acbbf8bfdb5c14236523c50db3e9abe18cd35e2f11466f3f187cb6f1100fb
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:af1851d44d8ae4b05c36e7eb998e059fe0f5a37d7c7e5d40697ae296b692262e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f9a33b4740dcb88d280563a6777965303726692f9b4801fe419d627ad25b1ab2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:89be5a118ab5d1892b6000c45089ca7501b7b8649a629e56d9c3a3f8c4c3db2f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:8b4a751f8cd31f3cea02186886979d02d80b031001602f01036cb87a9228bb1f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:0033c56cfce2b2260480f3250ac176588c29209c3b28ad093ff08169a1eb76cd
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ecefd04550659bdc2eb6994362b86c89263c837dedfb039945a210b9f385901f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ad3cdcdf6bb2eb8e9549d5e4a919943d13a759fa43ba6afcd77771e5359e9e08"
    registry: docker.io
    repository: mendersoftware
