auditlogs:
  image:
    tag: main@sha256:a5ecd2195b08ae1c6db004a078a938805c66e43c13f31b8246ce43c6b2fe4b6b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:63ffe342ed3504ffdabe11c97bb494796678f8c1a9a0e56d2b20c35080d06c54
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:01792855f19069bb921259d3a948f3469823225c33daf4dc2e001f33de1840bd
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:34895ecbd0c39801b59cf2e843fd25474fe743b4d2fcc6663c5c09ec131958c7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5e7b477441029a93e7dd96e5d0b786792341686e43798fd715785bf59c2317b0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7f3a2ec4a4051bf6cc61984885bca7d0bd2fed4720cc48909f6e56dc85171fe5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:86c1052500c9aa8d571b7372fff02eacc94b1eb13448e16ad9281c20ad770844
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:77b3c40e20fa02c6031da3e36308e77104a0cea024f431aa5a47ce92b28bd6fc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c97a630a6911c690da94d323d5565d5db4ed73b35d9467d2df41479eed3a584d
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5932bceb826a93349a433aa9b65124d70d75f7019e05a51c27e62df150ae6040
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7043d718c04f0164f1dcce9c639d74087e39b9b545e5e39b266c716bc5c25f32
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:882474fab72d2b1bc2c26b4bccccadc73130b67f2f4422d29015cdfc7ea5a43d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3970311724c0701d079be72d7758a62652aacce39b34b5b03a58ec00e29676a7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:97230d47bb1944de3fe6200a4c936e31425d5da966c76e6e672a744cc4058385"
    registry: docker.io
    repository: mendersoftware
