auditlogs:
  image:
    tag: main@sha256:9a6ef5b267d171f7f6b031f9e216e3c378517701836431c47308e90884d55c55
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:77760f97174c69f64dc9ae5d552a1fd3670a6be946c55139fd2badec486e34e2
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3b69addd94cd7b0b0fcf9e8076368fddb9ab18c006332cddd728256c2e4608b6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:207b4e6c8a207c6b2ea2f0f5d13f47a1061b4c03df27224ce6dad5b20f641a58
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2c2c2aeed99e403a2be9ee340ffe0b96b3340aa7632d385b919114639075acd3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e778656d70fb367426063a5b72f68f0fbfe5fcd6b2d2d96724af8dbb12e8ea82
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:004978dfcd314670b7293639e8e9485a1a1d98eacb10be34b4c7e975ba990dda
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f2dd0b698a46e8497829131731e1c9eae88b6dfa67ed0f02ba237ae72797ca10
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a638c1da430de589e98d5bba18e5ee72c92dbdcae73fc85fd397afc9c9f9ae47
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0044ba5bd21d0ea9f5539d16beefed910ca28557a31bf5b9c8cb87568b16ba31
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:41644e318c726b632924430457630ff3e4b31c26bd0115ec63792ec169232c26
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c2dd5856862e6c5110374d0cab8b58322b27a412f62740d43e462b27fed5619c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4f7f6168ba1bdcf73d4559086b82d308922354728d1e559d81349acd6b4c5191
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9cc8fff6fe63d12443dbf49e6bcc0d8162b56288eafc8adda0a5b9682f179b80"
    registry: registry.mender.io
    repository: mender-server-enterprise
