auditlogs:
  image:
    tag: main@sha256:d7d9985ab0cc59c52a7553bd1cc315545c91661f2d493e23a18e458119e3de94
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:499603a3030a50bad85bceae7a0ec7f496eddf4cd9b07faa81548567ce6b16d3
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c4a0313c63dd8e171fdec35dc667cb208d7492fae030b3aba9db4a32b1053513
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2ce01e0d4deba59133b58d1fb6ccf0211c0c32adb2bbab6170092a87704d6090
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ab8b36bcae7b7ed43ef8789ac603df91dbd894ec8ed92f20442d6f7bdb14c806
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:3b713964cc71dd0118a74af71e5a43b38d94704a4486b73447be910dc26c4cb2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:556c48ac4733b4def38566f58f6b68848e86886cc5aa7ef379094c92ce217815
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:c8a64876b197d13ecce900fa57e5941a6ff95d22637cb2a466b0083b3eab21b4
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3168f2ebf47e6894cb67aa9d1c2f1702c37337d4f98df1b1be5bd051755b1463
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0f1ed720019d57dc9108869bb775ea7dfc07b73c8fa2de590ba39ae43b63c5c3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:886728ab28d3f911924bb13b401925eec2640cab1a7014bd8f6ffc2e14a724b1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3ef6e1456fe1b2d9d7511b3e256242383ff66a962ce4146abd212602f07c583c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f9f2974f019aa23aa2a2008e9b92458173e6e6f0f33fd9d3d4ad0c2ef2d76c75
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f3d8efbc2de6e02a9ca8c62bec061625a8eab566877a192c526aa20768c6a9d7"
    registry: registry.mender.io
    repository: mender-server-enterprise
