auditlogs:
  image:
    tag: main@sha256:d15ac7f608d62eabd81838c8c203cb7efc6be9ab6cf043c604f631a40a87ef36
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d54b4a4ebd647d5d87dedc6766d6817224f8ebceb236a07ba68439ac185e38dc
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:582775858161eae2f7223b7ef0b5c296da06f8252d735b4a7d546480cc19f0c5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:998a65904036304dc22c7e7050c82d1b3581f0d9416bfa4a775ba5dafc6be91e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:636b3559931aeb7bcdc88b9c9e801361499d25c2fe0835ed77df988e4542d3b2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e3a9927a3b982aad92e959c2262d5ffc14a252a5b0b859c23282f43a99fa4d66
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0118ed889e29ddfb312a31c4c6c4e7dd81c05d8c29d35eb3d1018d7eff1ad26c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f8465fc3aac075065eb4937eb0149dbefcbfc8309ca1dd0ad9e02f27e9976d46
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:1b25fd2fae5b0262aeb120f65392a3dab377c8b427f3a984362d05d2ba52045a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:abb9ff542f1ff09d3484b1c8122660cdd12e0b0a786f8d3e0b54427c87497967
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6dda78a5f5bd5358d4ddb6a05f08918014e9d2f12ca12ab55f1c1fc9a16ccca2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3c374a9487160d602a9b7aac73496c23f2b576651d652085578508801f7f0855
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:db1130c8cc7591fc726476bf95ee90fa4b6bc7122351b24e23a895151a1ece91
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:137b189f995e735ad53a303804fb5f6ca153bf8f245b57019b5046c75665fdfc"
    registry: registry.mender.io
    repository: mender-server-enterprise
