auditlogs:
  image:
    tag: main@sha256:9f2c0df01cd21fd8168887b3787a87082a3aff83b8f097940e033590277fb607
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:778984498b2d1990408abacc67675e6e14174c4ca63a0ca04785546fe50c5af0
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2eaa71894c19a279b25ee7d1539890fec2c1787017c5d44cfee6338dbe4e724b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b088e21062a8448cef1189ee725a3fad234cdd0d70d393ef254741f8ef8f928c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:197b31d38a33c662f42a2ec8c1f8932c5d88b959f401cf57678948da59e18611
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:613215f8f8be7f4e3f74e89126ae27a25355da171d86beb01f347ed96e5dcabc
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:653f0047c9edc538d8394e644be21606a1f6f61f242688076635267ce62b6516
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:94cc9a566d5e441aa5e7404d98bff1f794ffbf05e6930da75c016e2efaf2e4a0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9babf64ddbc327999088c7b4bf52b9fa93e241e0fc55e3d6dbe5e94d00f87cbc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ce87cf2377538924bba3e4acb4fafbd754bd1a529b13b3469ac1123a327cb3f8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:182de3ed23908a967b0af3cde1ec782c287b5d8a4fd48f7394ff31c6cc204f42
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:28de7e3982b506c636c9e291cfd4d2b092ba3bab0e7a1ba0d731dda4c52ce4ba
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ace15f65b2ec6711db2d96a1d0bc50106f9520fb1362b28a126272a0a81ce837
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d3fe89eb1f6feb3840b8a52562ffbe9073b0f2ba864702c4db9594e60f3106d3"
    registry: registry.mender.io
    repository: mender-server-enterprise
