auditlogs:
  image:
    tag: main@sha256:4af53642df0eee228c0fdb175295962d027cc6e9b8d7789b35f2215c3f8cdb24
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1a4080c870b42f05b839f75347d3d15eb8001c350dc2a3a338d51212cfc4f589
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ff20055df773ce24440ba7aeeae83e5d460048da1a3f588e76085d94a29959f7
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:4d70adb7a0457e0502c3d1811bdc38028b4674ccbaa1401311882e8efcf11c45
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:56f54edd208bfa8b4459d1bea2ae3f76a7c05e1cae7e968a258620f65a4a6225
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:51e6e97f95a2c241a50634db9e52c2587e6f939fdacdf15f8f595d39daf6bb3d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8496ef0c931071d9661469c8a2fffd39905397ec46e37416a0024d61a912dea8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ddfa977463b1de66eb567e0e43e3dc63de2e3c728d4fcaa6ff1fe3b576aacf8b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3524fc5f9dc8ab9999d7731fe94aa46b6471150239bc36dfcf64fa07d619e5bb
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:34b3d69935a70012c776c81d3c5887cfd8146ab9012bd5e95ab8809ce9bef095
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6a28af3deed8add29f09cb7eb4d28cbe996accea9bc63ef33fef3f291732db47
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:48bd81c8f71a671431240a0e1982ae1f5019443c8d82af8458f423f91328e93b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c1c4adfa2a40a5254e5c3357b0c8699c81fe39f663fe8df01674bd250d2e7e45
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a6f6fbc7c1af0605d3e223ad4ddc5dcc1e251dc61cfd96f3a27af14681c467a1"
    registry: docker.io
    repository: mendersoftware
