auditlogs:
  image:
    tag: main@sha256:4d4da08c5f4c80d847e8479bec9d1527d0f785e64db36ee82099cb7bce233dcd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:46c0866e86dc6fe18a1a3d859677caa5914e6e865dfef65e553c8912cf382a2a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:e7a0999605ad181e2b9bebba276bc8d58a37245ada4e12392443379b31e1f1a3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:aeb42f21831ca781deb4db081b13232b552293f661aef7766d5678b09f0909b2
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:afa45be4e6f7378baa075922035dc3122a71f77ad3df27923f4db095cbdf28d7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:011024ad90982489f6a9599cb775a5520c869f6e66e9ec6e4456f1e7b18bf493
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b98ee0c25039f418272233f3485e14bcb84230cdd09c8933dd38026d030b00c0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5466487773e4932780aabbb44f438e34de73f8ead57649ab8a753227f9c17d93
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:15ee96e336fa5b5c291d6550608aff23865b0f00ef72365b8c0526e18a372458
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5fdf0a3bb89c92c0b5739418c9edf80fa4e860001d36adce423d17a4a783e76a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:56b0282f68a43106575389e21b50a1de9f1961010d3e83123e2f67d7fdb0dda1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:76583766e71547ec7e0b3716ce6792bdeabbaf5df42e5b159d3ea626eacf5453
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8355035ebfe6146965517319fb4a62abc75832e1337ef14f72c0ff596f8a1920
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2adee1ba6a75b509a16daaa4a3b888d01bb74fb62121f15d374b8526c5a5473f"
    registry: registry.mender.io
    repository: mender-server-enterprise
