auditlogs:
  image:
    tag: main@sha256:ce85fdb67701af67218126fb7b51816c483eafff85a0456f45700e04e9d399b1
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6765cf00ef2b830e8a27fa3bba48a2a42153c837df584ae1585fb9a49dcb2c6f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:471b48b85cc6ea8acaa92a84d271c783d7ad35b0c2981b40460b42b495887de6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:a57b19b2cd670dc925b64bbb3bb97af29a2c2873a8a456ec6574ad291548c589
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:20d11f624a20584fdb934597c52b2df6de00de9aa600e2931750f985fa2fe570
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a987789276c077b248bb7252625c2aca830cbcfdb8ee2c47dec17359bb2d34b2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:2d2a5b31db77449be2513c984fad35154e4ac5c6b6c1a50bd6d12cb47f04b8dc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:6e1e0580b47a07f8cd6b50314b40505812364a5e3e9f3f3da7b95752c4f391ba
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:62fbe1e8017f3838372b0a69a4aa705893f65c3167006b1a09b1d6ac3cd28637
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:473a150a7b692a0b7c822e6daaeb24b5b3b56107f643f3935cd03ec60e52f545
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:80527bc471165719b9741483f2afd423b60f8c1c56cbd1759fd74c8bb0f7da3b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:86311cfe6f4ebc220dbe4ff7f1a54c46fb3eee0b701d5c44be470807396ee8a4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f73aaed4dae2300e8562d6ce14371a07cd3c8983fca29d10ddb2cc4c6f936ec7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:018b71ab8dc3f85d85ed083c0eeab9185e8a59110d5da00653a1a3f73add052c"
    registry: docker.io
    repository: mendersoftware
