auditlogs:
  image:
    tag: main@sha256:1d9ffefd2ba39440bd92de0a1a1eda73a7ac0d4171ad15c411afc16d7fbd4ceb
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b2b9a3e729bc77ee630cc95b6c2e819f2c5e9b3661e58a705d073a567e7916d4
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:74c9225546ef130d68709d88ba458c338971a073eca55296cf983eb96d05f820
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9137293692366a30a930299820a3b67ade5f221e5feabf97154320def9a4182b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:aad65db43b02b81900a3cc43772d0ffd5771109c01bbc4d8871fc1e940e4f5c2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:234674686a50e58c0d8800b7c375c62733fb23fd42457a4a12a87e49a8f7f44d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:7ca0664a263199a50ce40142a30e3c6dff02b8358c68ffef5860e2d4eafc0845
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f6f403c21dd2cac2dd6449244ea11f6aeb568490263959f08f9bb5e7d54287a2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3b185373ad4b6d70ea471887864348373ed925eceb7c1850146a60294e3c331b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ef1cff43680bf03bd14867ff525408b86eca48457c8af43ae374fd47213234d5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:18dda59cff1836761d9505ae14fd4423250a29f662c88d4da799ffd0ffa96ff3
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a346c0bfa2e2d140ab02eb6125ca4b30c2b385d498f3920226b4a81e1c9c1469
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c3cdf97529ce0f096317adbe00a24f8523231470dafea71106c53d8bded3851b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:6f5fb5ace28ad4ffb3190d790de46ebf9475ddd993854760bde2106e6d619eaf"
    registry: registry.mender.io
    repository: mender-server-enterprise
