auditlogs:
  image:
    tag: main@sha256:8a4293e03dd463f811b51a2b7b47caa02f921f3012009bcfe9852eacc6d740db
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ffea9aef9cd7e3cc09a9d0923948a00629943f3d6238d2bd5a8dead936dab762
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:33949bae90bc1a0568d955c51d3151f601520dcaaa3f8ffda64cd55cda2966ad
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3aad6359f01bbc1977e0652cceeb5638f3d9376e44c221f5abc058df946ae033
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2735d7203904ef9a35d9a34d30c4554a76a21257e0a994ce1393a435851c1e19
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2d8bb7aeb66899a900fe60d3935f187d1ae1a3c7e9945a77a66e3ff376ec2d5f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:72115d90c0b2872b510f0a681e831252cadcab84c1e4a38e54217382667d030a
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e182c84b173ef61bd292c2d5bccf9396119a897844ca98ac93604b7b017cf0eb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0bcaa57779ba5f7cf9f60949c6c1544ea5d598c17ea0704acbebe2c719c68bc0
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c58187f03bd6100ab339e83e11d18272eb3a1857315602227e1c0222be1cf1d2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:12ab9a3cf79eab171a3f7a767936f1c37ee0bdbde36a0bcadfadf4531684562e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bdc1d0a8cf7fd6c0cf32ef8b2ff9de9419af942ebf162ffade7f186354e665a4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d43f0ab7fedb9e436de30ab2fe25c0c64ebd9a6ea59740e50c9423ddbc6ec3ee
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:de381b5cb363ebf6fcf208057900dfb7239e49f5124d5e070944b66acb47464f"
    registry: docker.io
    repository: mendersoftware
