auditlogs:
  image:
    tag: main@sha256:f1bd982a90da67adee2fe1416bce0d5ad1a5a486a2c449eb0591147322c1697f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:146fb00f8912e08b77c79561b8815ea092060fab9c8b9ebbff3d2b73f46fa9b1
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f1ec6c7d2dc6f9fc3b9c704e4028ff913018d27c59af4cd815096cd6ec8c20ee
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:460ea822053243a4df69b65614253c7bea126b560497c88f766e60da2c9d696c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:6b3186e7c1851e52607511e9fad8bfc1520da9039fae72677d9a687c85134cd8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5d164fd601537e02acb06131030b548e9d7675b02edb908997f8ff130922dd60
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:bfb7480e4b685df79d40388e87e659722de5885765125ab0cec47a36af882c2d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7071bc295c5f05738dd80fffb1185c89921c9e455a4ef6bd9ee0467b90075600
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e13b50c0736ce1f8f6988a43a5890cd18dff1be219258cd65874b6b67c945276
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:46135d607ef6bc1ee329386b532eb4c34cbc1d1cd181712c7af73b21c0a35ffd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0b20812afc23b747ab93ae42f84b725f417a13ed937c5cceb757ec1c80263135
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3d1384320cf881e84d915a7b5d8ccad0db36a794eba4919bec1b78f0f6cbb695
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:91f8a7b2acc2148fb6b1ca66314a7ff92455fd780a0a31038e604b19bd37d114
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4b561a3b20d34f425ced3902554235a0290e285dc575806e5b212231290c37c3"
    registry: registry.mender.io
    repository: mender-server-enterprise
