auditlogs:
  image:
    tag: main@sha256:dbe020ebcb2a2bf951316284def85adc4f04da15b18d1b05bb519b4c9091370c
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6e7b272f32e3b2ef90c9d151743c22e7d3d273ad059fed5971ff8ae7af882dea
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:b5fa71c88dcde007233f18412a43186413813d192f96401ff2c9c57b542c7148
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7ba06576383cb69da629c4811499a0f87c2220ee59d4aff2cb64ebc333c7b36b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:3f1af9645209a58f3e9df2162fb238c14e406f81117fd76ce5acd33a83507fe8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:df0ef5887a684364b3ac2926d928976e2f33c8b6576abb33b41f1628905545fd
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:89a031e9c7f4c8842c561c0f78bfaf3f8cccb2e9ec21b79fb05b8ae8947b3c60
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:29732842dd1f119028462cb34ea2e16a4c5d0c0899231ec70fa6688e7c225fd5
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0c234f9db356f5bae001c32d3ba5d75f15c0b0d4edb585f324472b659a7d63fa
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f54b43ac03d5277b6e9e7b846b5af310d0dd19cbfbff1fb2f778559f9a0c26c5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:547c69f35314dc42eadc8d669e03593bedffe9a1a565a77e35204f2d51043911
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:febf9498daa34e9c9f11c1df9315461f6e8f27ac4bda7fe1df91f8160298659b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:70a9b48ecbd53fcbbe74c62c49bac89c15629f67083cb208928b034ec2fc1aa1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4971511538eac2a192f4110ab550ed8efab9b89503a267ee72cfdaa51bf5f8a2"
    registry: docker.io
    repository: mendersoftware
