auditlogs:
  image:
    tag: main@sha256:86237c55e5a4546300f3ef591cfc4b22ff552d318a0fd28618acd497bc80fb01
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:935d37faaf0592a5ca078450182a7655b6a7cc2ca44e12dabca154518f447fdd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:653cdbd0a7e5af8d213201c7fadc192a67d47971099c67a2fcceedd7a4f675a8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:79ba4287e4e2d1ad060e217d15be095cd5c14379e0ac65dca945119a3d1ff790
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f2dd8875ffb18ba78b7ff24c4431c211cb13f6c637e68f64b8d8e823f7df2829
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:3419d4f84105ae8edd72461d2e5bbc5be7a3feaaa3cf6a9abaa4ef73fc7c2d20
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:031941c7413bdfbd3d782d646970d9dacd1ed43fbacf7c29ac8ceb3a482b6c06
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:03e63ab0e7ed53e1f5d29bc7de5d00481e18e941318483a72738dca3b9f0e677
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:53aab286d9a8e87c488de45a81cbd9f0db3d4af04f7ee359c7993094997dd6d7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b88f8eaa212cc733ef21346f51fb0446c8dcb6a06a08f9b79cf4543752067a5f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:83611c37d38f27f98109ee343b919555fc97c97560bad7a073528cc1df6cffb4
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:93b5799ac1a886c5263dad9ffe88075d84f65895f9bdd48d3b8b491f5d4982a3
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ee1ec060a3f676015556a6dad1d57ae0e3669bd5833df3e5a3f067cd66f0324e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:855b108119d884186aa151ac608b2226d054dbcd9c35e38d7916f57232a696e6"
    registry: docker.io
    repository: mendersoftware
