auditlogs:
  image:
    tag: main@sha256:a696bfde03b2ecc98c4a43946a631bd940b11327a6a94030c4887065a8a4d9fc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d31dabf8b3610c6b33c9a2f21c08df565ed77d6541cade057574332807a43156
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:88ba6dfbf84b39d7e231cf06f79434089b0972c3753caff98607faaa945bc38e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0b155d47759d6cd38d2a6bfb24a317987cf41a7aff004133630354dce578716a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:af839f8935928314fe092affb609f7bec9ae64794038b253ad4ff2121564be1d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a386b13b7922a50a7c8ef9f928090b782e9dac4692d54bf0f9ca1faf4c3ca739
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e008f02a4afda68e8929c110ea9307e95adde9909b63934fb114d6a79054a734
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1382f6bf00e817f891d9d58e9577b94195b1374062f00c6408b425dcc2b3d122
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:1622fb48f550a0b42c49daa2aa8e797075119f0437a41dd5db83fb267cfea686
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:485368bcf824978524069ce5fa0d235dddee5000610951d24bb9788f14366970
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6fc3bf52ccdd489fb735dcddc6a2208f66f681ddbc47fff2eda91f065922dcff
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1ffcfb60cf6e03eb7460d4b75ad3109ccccccbe468a893b8b8449f3145411b6a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f6a9646a3b5dcb896131bc61dbf849d8d567a7541d856eef1cb6303989290b16
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:96c0637c2a9e82378d9a124289c95af50feac77b62b2a2832f587a9231ec65e2"
    registry: docker.io
    repository: mendersoftware
