auditlogs:
  image:
    tag: main@sha256:8922c6fc72847258aede1e2771cb86638293ee3946a0aedc3b8162c4fc69489b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:27b18c38a1675d090d4ecce175ef6a806696872dc364d9fd4c685e82148dda92
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7b41eedfda6179f43a2d0c0835148b04712acd7ccb265bf9010d8ed11932a254
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:fffbf401f8e6c9d257660ec20afb2253d0a9efbc182ad2b31bd7c75f29e50dd5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1c3a43082f21913d35fd160893502c2c1eecb7288cf53e77dd804001cfe6dd54
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:74d7fcd29aeda441c8f887159a2c39a9059811c94590fc65555e8b3f669ab548
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:58921db1a692545176d06e3a52151b417d1184b78364542aaf2adc48d0ec33ee
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:112044f350ff313d8c3fa78c9f200ef65b50b440ffa367dffde4ad6bb7c9b04f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d429fb45737fb88d73e4e7510cee0c372fcaaa54d28e21e2552e1c53be643400
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:da2ebaeb7686e2ba06642413aafa2a024d0cb51381765cec9dfe9b60d5ff5541
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:508990b30ea544b9565b8043a22c38b38e323bf602d67b9b57f2650ab82bf3e5
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:9a8d435261d817bd9bcb23abf7a202037570885668f689f394e8dc0817c28569
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:75302c0d75fa81cb3a2547aa62a4b5f5d31429b2df63084dd89e5af88875e6af
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d7735d61f74a9feee9e4c4895f39761133e8846f69f568a7d9d7b623d920f164"
    registry: registry.mender.io
    repository: mender-server-enterprise
