auditlogs:
  image:
    tag: main@sha256:4aaaf450de2fde62bfb8f36e29f021aa1fa0f1e98b883fe4b7c35f1e118184b6
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:aa7efb53d0084021a4a9d6478c9210bcbb03ffb6f73448222705f623aa0c0d16
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f1849229cddaa5add14c6f2611333de8b3654c9a6df8ca8599ceab263aeab828
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b02606a6c52ed862098a4e0184fedc894f640cc2cbeb23d6daa0800fbe10d751
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:dea17f1fd0fc6b95115d10416aacf6e61a444767821fe0fa9c1798ddd66ba888
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:396d27f5a9e4373e86f53ce95e864f022133d5ca6bb5efefd2bb9ba0c13a44e9
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:835d7bffbc0df7abc9a949bfe40d52e56f7de34945fd9f80e5b6b8030627f029
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:2cbd35a86e024ecbe278eb9b3ae97217ebee71c36d0de31ab603003b76432009
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f03f4cb515c564ea3a3f6a4905b9f5cb562ed5ac1fee9ad1beaa42795fa07e24
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3afd9109684b30b9d3cfcb3d0376fde309fa4fcd2ea4a38e69bc506400b1246f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6f948d789ca6d9f45ee447840e25c2505e324cb12a2f72f68b1be42d9dc8381a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b8bd1779fb64a7d47eaa5b5eb513525eae5309bc92c617d657a54863a8f6cca1
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:09e41166ea5d8901e7213a35b8ff7e9da136b9d5ca077d91d243b41242cb36ad
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ff9b31acd99401fc72b938e2b989cab228d621e3ef34eeb48cf2721cd0fae123"
    registry: registry.mender.io
    repository: mender-server-enterprise
