auditlogs:
  image:
    tag: main@sha256:3a208cdb07b156016ffe06c5e38e910838cade0a8cb15e663fe8a903a0375dc3
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6acde5c3b5988f87124905388fe9b191f06bf510daaad55aeffb1a199bf74c5e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:feb526a0815b61c089417346ca3f39cab55dc0703024e001c2b26475b2c61829
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:39f3c60eee5729b2a2880ebf3b0054ee9d899b5dcda78a81bb56bd687c1e0428
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4f2075e38b6937ff75a45b9fbf4328bf60ff8b70b9c176d9a874d85ef322b779
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4cb1d29bda47021fb7a010b83eba7fa9e0299d68d362007b56977ab6dc1fe778
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4a7a930d08c6f6e34aafa362f69b78fa2c89d2f926af0f2bf3e5dff4d1cad918
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3c4e609ed6667aa8a652985e2b7d5f4a55667f3f60284d2f1f2e7e74fdc5a2eb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b7cd53d6ec3be872a41bb0ace269912c89f9199a7a665c6cd77da9968c4ee6d9
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4d1f557b7df3b2e46ee84bdd732c8690303499f8f8be23b0b7f44ca3521ada5c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:fef26c5228dbc16622e0b018363f5f2b790a180b3387a0acb198f30480040001
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c8d05370954996c2f7d48500eaaa800bb38b316e74e9a2759808b2ea65a4b40d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:fa7b63b7aafaff7176052476ff428bea283f5a9088394981fa178153b8a9e1d5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0980b8ab4e96d6eb8330f64f6d3af0528bc3fb2ecbf504341c8c35ba7a30a7fd"
    registry: registry.mender.io
    repository: mender-server-enterprise
