auditlogs:
  image:
    tag: main@sha256:8a7514182de9ef9911763af4fa518374fdc17f7bc0682d5a5cdc88b6fcc09c9f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:bc067c7e5d79cd243a6eb4c74ee9fcd3df50c7e3c9a34f1601be260866384fed
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f3025b3dbff3a6118a13ae9fd8122307aa96585d5f89533cb6d6432501d76946
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:33c10f60565377976b10a03f9311ee736aad23af5136600a9176c16516dcadcb
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9cedd55de63e122c4b06201cf16f3b5fd049e936162e8af5626dbb466b9ff345
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1af6e3545ea3bbaecbed51b697c929323f60c81ef3fb76f0ed9b58c4a17c64f5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:40b9be42bf049cc68ef476e6e781fad6b9d798b8b7628510ef9cafa258a98f79
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ceb9784d32b44bccba4d37b97a2f0fc8cf273ad47e9fa8f3cb20843469d65419
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a7db4753016779630a29dbcd6022788d19c1d2116bb33782b0321b182a95d147
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e9753038db79bd0e3864a0b6698721eb851987830fb381323e06bc2a20950329
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:377fe50e19a6b6c99ff06c929193616919f2b0a1235d5442c6e83e7951cff218
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3977d2bae85e2c793636fbf809fe20c87335f4b63c571f0a64918ac4a162876f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:122a54da89998037ebf5c8026fd07213c3e3fdd5d0f91801a556f9eb438b0147
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:61afd43168901d376ab02abc57fde89d87fb4f5d1a187707aeee77eee2d81b0a"
    registry: registry.mender.io
    repository: mender-server-enterprise
