auditlogs:
  image:
    tag: main@sha256:86ad57718823f05e279cfbb9a66c7e58878305db170c6fb36061544e75dc0452
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b324db4a08a0792419af9467d16b8484ec75f571be8994a5935b1746a7c03d59
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:b4f1a4fa51cb33b43b4d608e13557ca6b280e338291542b29b59056d24aaacf8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:983ce51d577a57933f92d5ada63685999887c55c1e4f78c70a16a9c131642cd4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f66a927739059d94c0df4f20588a6b3d1290194635587d92bbab136ad745e94e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:605b412919864f83cc6e4e0953ae9f91f3245e2a7f27b2d4d53d21486f70341e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f63fc025762fbab73282618fcf8464cb03e04644bbbdf8a3b5ad2605e5fea865
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d7a2aaac1deaf3f3c05669227c126ad13affa31b54cc542eea9ed423ade82418
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c2c7e84cf85482e30648a49d89804177345b71488e74170658f8a97c199c3547
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:427c18f23b198e6fd61fb64672cf970ca312379cc784fdbb497d11577fbf2087
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:dac2d57fe01f882e7d59e532075f2b2855c2fee64d4ac3b6c5636ec9c7f98234
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:12450c6bcebf1dea9bd4fcd51e3da2bc5fc9ef2ae786ee57b017621f6d0e13d0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d82cfa7b3ec8ddd77a73df6a1c6992d32b3d5ae4c4f7c11f6ed505a5e921db8a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a5cdd08dd1b7412976a301a070731472b15f13173268be59a58f13ee0b0b0d6a"
    registry: registry.mender.io
    repository: mender-server-enterprise
