auditlogs:
  image:
    tag: main@sha256:73d5305f39d19dd56d5040081309ae54ac0ce8c126988b7a5a3651723943bcc9
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1ae86ad12b8f5e88fcfa2084aaaebbe4bf50554c54084a6bf16b3ddee8d7105f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8e85be0d4da6e699331a7d57dbcf8e7c8d72c6ecab52af2d0d39c83da91e5229
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ffbf3a6769b7824e113203a725ab67b6a6d27f01b933542322ce39f1a51c0855
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d3af7a567f281bc7fe2268e69d784948ffb2107bff4e1efb86064fa6c9652b16
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:80dc588e4e8b3848d6fce97e1052c87d036ad22fa56db70215d3d59606ccf959
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ca58b0693f733deec5fef8ba53a333b8c3254273f219b66f58e6e7c45ce5593d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b2a71316bab81667f0b7c665309b0c850ac75778ef6a7683bb106ea610b1a889
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:391b8391289946df85dde4460b3a01e0c4361666d877a641613c9b0fdc400479
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2fd37f57a83133ae94d565d3d5dd439ed01888d37c0323de3440ded0e06b3cd9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:a527c91d903780a4a6b7db989cee293d3dea68028bf5799faa11d5f914bcee4f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:557d8199840574638c8b3ab31308690a45076f81f224db98497cde97333bfb4f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:85d588b03bb266e959e4fd12ea2be714682344747f85ec4635d75b4c00495e7c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0a92176b57cbfa28cdba4fd2f362db86d7d4521dc2b7766e021dcf309bb9610c"
    registry: registry.mender.io
    repository: mender-server-enterprise
