auditlogs:
  image:
    tag: main@sha256:8d5871c54e9261bc8721ad4896d9201e7aade6f67afe466212156643c0a18af6
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6689c16caddbaf9afec5c3e48fa654c52943a6b3e0d90634cea53c0c77bf8e28
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7f135c895f2972736852b2285427473aaaf0d2fe6c84c70aa90d923dd708b083
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3bd68efd34e2f1084e6a9422099101c5cd9078c961fd841540832064887b54de
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5f4dab5aeab97127f376fb672c131459fd6842ea5c83b232ed61f03f8f58e347
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:fe42791b74c1d5122ca5d1ca857c5cb531a2b1deed23bc2c978ce47dfd9a9b65
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8b793e3fa7d42c3a777acac3db5d4e6b837697869aa5ed2de85089f56a59bacc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:6bbf566f5c82670f52fefd477efc2be6a22e0f776907b1f209b1fae787815a19
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:542ca041465103f96b4a9272febd4a059ab3a9fd984332b6ee064d5e14c748b9
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e792cbc4393a971fabb4977ba4a8cfc378307fbfa633dc264608abd84dee4d96
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:419025ab4331c6513124af4309ebcf1daf15b36cbeaff85c4e75d44331683637
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bd7e5db904bd8219903245635768434ba451faa7723fe768760e4d22e6567109
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c3ad0d3c81a75b0a2e13268d6bbe806f6dc4ac03b4001232b30d4c5fba98e012
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b0a05325e229ed531b4c19ec8235207fc0f512fce87b3350047527a06ab156c5"
    registry: registry.mender.io
    repository: mender-server-enterprise
