auditlogs:
  image:
    tag: main@sha256:4db178ed38e89b592407480f7784eecd3c983c10f2367eb86a4c772742c02c59
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:0fae58db759101ce57ec01922763c3765f803f17ccc199dcc8c55a444d88003e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:432310a8546d9f77b2f621117f2be2ebd74e752d81a13fd001364fb04f621f87
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e90c14522cf846550f958544bf18c4d4a28b7ce491033527e7cbba55cf771089
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:fc5cc68b346386fd16014469dc865936b628425fa09d739589640f854bed2625
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7265fd178cc7bb3c11a58350f1fc3f4374546a61a79ed53d24b1f3d6a6512e06
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:679301196c73923d5630edf83edeef2d91aa7642658fb7136fee9c50467b821a
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3a65243c4da2de1da9f1b6c0de40e9386358295e8d41a38d65ab250afa6ac9cc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3b6d4cc80002759f4ed97c09fe4ec5128b59c325573d5c480e8f7442f6515b65
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ef0436d304fde682b28c7076b3be2add57010b05b32a6ee57072351e0d23262e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:585d77c93df4eeff19c2127cc814cbfde53468cb5d4198e4a16a721bf4acecd9
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3aaf3df7a4263267170f1897d83a72a017145c7707726938b9ac60d686b0bd2d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a6599311a9e7ef2a060d63e25eb052e4aee8d3f8275c82dd25ab5f050e474108
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4c4f630f49efcf34a376d002069e62f092af019db89d5df05c4d880267577c03"
    registry: registry.mender.io
    repository: mender-server-enterprise
