auditlogs:
  image:
    tag: main@sha256:913651e1bf68d9f2f94d2cdf54c4f2bc7c2b71e4c9206f73a7dbd8307e6e37e0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:66d3ce1575a32f5e4ab40e2724f143e094975108b4ff3d5d6ef55167b47339ce
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:242665b35c9dd386c8482fe6db8a2b27acd86b5f13d1feadcfd43976b3bc03a8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:948ce80d450424baf469f0cef4bb39658e99010db1a5c56f2b31f0755c85122f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ed14eebd49129470944732f1595e3a33a4484ffbc00bfd3548b5e51a1327c155
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a1eab5996113512aab655e1d84a4ae81a2a1207fdf0fd2c4135f63de89611ecd
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:73608a15f1f0a753eabed33d34da0b0e419adc29fbdc77d01608a4df6307c032
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:abae47d73bfd6efd1d5ceb016341f38571e62fd06dd937bd3e37a5d6e5a42e00
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:6b255921c2aa749bdbcda0bcf522a596ea056be86aa6433ee4796c4b3b805a52
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:897abeed8d0dcfb519639fc80693af7abdd1a35b3d5bb4fbbd56c73188a1eacf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:19a90ef2a7b318bdf28532de25fc086b5b46da3a105fda71ba63371fce42d5b7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8595b2d08d81cc31cdc5a17ebb0ae544f5dc374b3254cb97c2307dd8be80f00b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:262767eaa71dcdc0d5ae3ae9e2222c528024aafac0aed813503b8843ac2354ba
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:5319dcfea6333c7355d775407c7254495498939be392e4d158715c72c91192bf"
    registry: docker.io
    repository: mendersoftware
