auditlogs:
  image:
    tag: main@sha256:a4e62193785064e7897a5be828f34a466a7b65ba45448b0b72b29d54f124276a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:aa1698797bc46a4ea925c8e79e057bc5f8191eee3203a1aaeb23f4671fab3a14
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:202a26ca149fffbf2207c870c99ba4fa7b4d82e8c849c2e015e8a8865f8b8afc
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:846676faa920f7f7a735b523993880b5baf0e6a10d702a4a4b4d64cc7d09bef0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9d673c155cef069eade3612736feacae3caface1e5d42a26e3341e81ab932270
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7e5e3ec115cb7d2232ea4d1d84a745804c437f26eeeab3f31afc616a560b6ed8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a49f8c3892a86d1fbc537896192ffe885c727ad25a7e8660d8ff5c9e99baf164
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b742ea2175e27a279131f1c266c00ca9e2408089abcf5676c9650ed525c67466
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d8f144f856b30856c184d194a3f5f9f74106c5243857821e7a9164a856d2ed01
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e70e5a0c4222b11a09dd29de134b40831651bb497775ef1db94c2af007ab6731
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0f9032f06cb89e515a6fd89678e095aaa330be2b3a0a2a76a00a8114d048bd32
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3e814fbc31b27c7548c522c3f0ad1bdc5595de06ae646fd1bd99907219437939
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a21784693da33450a11a5841eee8b19a32d5e12a59e01add48ddc128bd9b11d0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ce502c416900e19a25f71cfef90d09a995433fef42cc641525def0328f48cee3"
    registry: docker.io
    repository: mendersoftware
