auditlogs:
  image:
    tag: main@sha256:101b0083cf26301d58c58bdd1ca413a6b15ce7543eef787325f6e47c368c4602
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2084d0d5e94a519b1078476523a4c154b855105fd15a92b4f4460d5d9f3e6edd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4e573be5016249a018563de228befb861cdad47cef303e984f5070c9cd778cca
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:35dc8791f01dbba6c4c29d11a6a1d2a94df7e1122dc6c3d200b732bf01792b49
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2845e57a9ec868be1b3ba3169f9f92e74b73004e271e4bd5967781b9a32c2a03
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e26f4eae14f7772970036a18b14a4838125f371098350705d65d9868054f78a5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:10631d3e59cb8c6e4e925da9d13a231c8257caffbf03351726c3673c37bbe957
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:808a3450e9fd1e7082f38417642e065785bfada7fc02e77efc9fa1ce02c64deb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:6474ce69c1e5fd712c769eeb0f630fd08f6b65234e718135debb38ab51463417
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:bd4764a7d292b8a2154f173445c46fa7b7d74b3b00c2937a994152ae9ba09e4f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:224f1f8433f31aaa2c92f2f34892a143b84bc84392c2443fc785852b3e6455ae
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:655e3ac54590b5c9a1a78a74b0818345f6aeae26211c2ca93c5192ef81a2c45c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c8151036ac7633905e19412a045bad8869e7f4d651dbac952dddd38163e5f560
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:df5aa01d5a0e100e0c3ad3d37b20e20ef16a21f4157b1b1214c3ea76b5faa665"
    registry: registry.mender.io
    repository: mender-server-enterprise
