auditlogs:
  image:
    tag: main@sha256:73f3c1ec55b8011d383ad7f869813fe1bc84698da60e7c6b5b2b8e31a5a11098
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:338b83e84159172039a0e14d96d87b23502c8a35a148c935b7e6544bc38673fe
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7a8412654ecf062ccbbb7b73dc5289edd8f8b6677f371b9b094544816ffae7b7
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:207f3844833cafb5f38f22d6cac60cbe866c9fd199ba85aa604a32fbc38fe509
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:43227f3f4b4c946ff35a06c3c2b58688e4356f07bf19998174a0f74725eb0f7a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:293f9fd4500fa0e94e7ee55c0bfc5b5336d4d4193ec3c078975172617ce56481
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0645b9c5d2a399b48806df964c710ccc42a65187dd103e2c9eb4e72122cdb329
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:6fde0b5872ca50c57b1265aec52d3604bdf680c1d2a3d2ae14fe2f4a2e19411a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8b82700c3c57ef6a3ef11773110f98a8b9fa0a22ee6f77f21bde91dd8ad8e725
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:97c21082eda4300cedfd4ef011173a82e92e3580fae8163d7e935677eefcc8aa
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:38eaa571f6f37380df159c515039dc14dee53b7bbc65c4f6287775249fef27a6
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:64d1ed96edfa7ed4f9ca0c2dad1d9e5a39c398ed3e6d4446a748c14ad5dc070a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ad73350dadbca3852945cebb745d6ae19ba5f3edeac592562582d3804b5b447d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:fe94c23ac15a48786147e983869a7e4db0fd1410ac0f577c918e8a7022db2a67"
    registry: docker.io
    repository: mendersoftware
