auditlogs:
  image:
    tag: main@sha256:0cfbcd733e65b1b74fd2b52104efc1cbcb6fe7eb2264502391a905e66ad31a7f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:23d872107fbbb536531494694eea032ab6d464a99762622c0f1847aa4d3f1dcd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:05da80da12648bb5d535a0e21c248c0bbe3defd17bf9d6c0160e586a6f06792e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9e5442aed0bcdf59671dca8e3af7f303ae454ca24ca415a166760d67c67867ca
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:925b5dbf355a83685b3760e6f718d16b5a049aecade1993cc42d61f834be8ea6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1fb4fb481822d64699578cca58ac3f4c4f2afd9d4709c8b5f655cee9e16303e4
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ac0e29780ee1c308917eef2f00fb442532b9d5c12cbc0cbb3be8eb00341de005
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8cc6eab480fe774eaacccb37a303677d3e7f198f04120c1987d0a245c491805e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d11a45cd326b1e5ffc2d2488683af40efdfaa559d3372eb7ff879ae34c8be97a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1fd8c358fb1972197403bd8eb1c0f56db3fb1ce6559f86ce097638e54ac4366b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:61168a405a6e741cefc4e2a406cc8cc16161b79e492d0db04e54da7fbc91a8f1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:90c3f35406d01e6ec7ffd85786e38bbb23c34af5c50d4f6c673b0081144f4438
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:01548c5cc7088d6a2175f328cd07849a37496ab34b19ef19a953c9159be30be8
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:770ca60215baa067a2edc20f04f6e1ab1a3f39cdde8227b8c204ceb5427b776e"
    registry: registry.mender.io
    repository: mender-server-enterprise
