auditlogs:
  image:
    tag: main@sha256:430a751b0703af2f19a208a379f48ca978392f6bf7d0abd948f2f78bbe1adcf8
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1c28559df91ff4d0c5c703bf6e3e0970d70f424b2a1f425791929bc8213c1bac
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2d818df144483cf7d4ed264e6bb10875efd076dec0855ccea8627dedd05ec084
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:529c457bd000b0658112247b13f6334cbf912ee42c4f8a6b7e9c221f10b208d6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d102f9de50eb67d3ed1ec6673fb386ec043a16df12a248f74e74aca9f921cae1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c21a8044b3316a82d9db83169ccad27c6e31a39061a0e532ad3119dbd80ef759
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ebc910ce7903877d83f0c81e2a9e3b7087a11d1e763cd3f5964d8ba66d45ad22
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:52e287b700f34add8131bcf19bab8286206a64ba22f08cfa0888df30fcb4ea0e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:10ae6c283d3853a0a4dc126b1697d252ee23784498570a64075b77dfc6bbc55f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:24ac12d8aa949bfb2b46509c22a27301224f6546926148b21a17d8745f0434cd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:59bd9d91318af285e6159ed541500bf98b5a94e317ad986a6f063e5670a1ac35
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4dd8d2fa319cb32e0b403404c0a4b0d4c86d9590826d3abe248af24293a7a85e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:63105f575d90d64e7171f062464956e4460bef236bb357ee7fec1e438ab1ad3a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d819e6e322650b326d188eaab0a9191f06e4a101c0a29c467c437e7056adedd4"
    registry: docker.io
    repository: mendersoftware
