auditlogs:
  image:
    tag: main@sha256:f55e384687190f0562c2c82925aed360204e1d41f3512bb2cbd308b271272cf5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3b71f23173a33014b0b4f20534ed3db52b8c3295da5e24a94eaf5164c3771c5e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a8d80591fd27b3da81404f249b65809e66f64ba0d6f70acee3406c1cf71dbe1f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:97a2f8db9fd49e3a39d000457700c1905dbb06d76f835e2ddec4fbf62c95be32
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:42c38b2994988c314de1c69a870494ade705fe50bc599fe8a7195e698bd9f488
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:719581e25325fa74c375258dbc56b14d35f1bcc20ed8882ba35d88c5dee0aa44
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0297691b310b1e425fdfd217a4181fc1fd3256605162571348071176418c9070
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1757d7d64db67174d5f6c9dae335d9325c478056d6f35514b21d078b09aaf410
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ca863fd764585847a239c261820acfe17225f098413f07a4d07d5abec4f55a75
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ca55175fb73293336ff36b87e8dee7ff318547eafe7d5f5d2634ce8b62621ec7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0da026d7894938bb1c6f1d345b188c533d69e73a13b4e375324cf166d7e30e6b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4538eebc3132e0a8befb92cb2d1b2285879a6a370b7c7b830c740d349261a748
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:923dcee4481a2485db8cbc36928d3f66f91941b041aa9252d0deadfb77ef23d5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:64e7013b17abd4a2af57a144dfc35c106c7d21f18a6738fa1c0223f5c3723d70"
    registry: registry.mender.io
    repository: mender-server-enterprise
