auditlogs:
  image:
    tag: main@sha256:49eb5983fe308bf68b59aab51e0bd26e32ad0ab157ae4fa9aeb0ff4db86422d9
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:edbac4596eb5b8073c3083aadbcecedfd1299e2ead9c01ef0e26b18b6e0785ea
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:24846bcb8d3558305014ae461f532a1f4fc95f81ee1e279e0e70ab84b4c8a510
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:290bd77349dfce07f0c2d417518b361f432eb94b7795976be7cd73eb9d06c800
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f5ba3caeaaef9223c86d37267a987d4981e33875f578ccc7729a872efdbecc57
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ac60e05e66c12f98f530fdcb54970b1558db46770f2238f26e3a0a5355515cb8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:478614b3b62feb7e15a53dda039de60ea269776ec6028a2afa45f626831278cc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:131470b13126cf53d15390619a48be72f1f3fd6d76436168eccd7772e8aa85cc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:89616978d2a5e249f55f3f05556d3a8663089f1a3dcadd6b2aa42e63892dc99c
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:fd550655d630ee470d85a4ab950ebd8d7fe3c377fbaccab46db95193be44a56e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6e6e05835acdf8796956070c8b583ccac26a1ec4a9968de918a8cbf8579fb1f7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f3d6d0aea964588d5841ccd824d50250797786e8117d9c2d097d7e3da35edbd4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:561de81262cea522e0d85be5c7b6c2cd0b5404d57cba1d9e44f0cd03bc5b749b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3362cfa497f24ec21acf1d957f38cfdfbc73ead3fb9cee1ff4b0afdc9c6924ec"
    registry: registry.mender.io
    repository: mender-server-enterprise
