auditlogs:
  image:
    tag: main@sha256:1f499544caf0bce309a9a7a81b5b8edfc485a40f687f8125df955018fd6073fa
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:556353e99e9b874181784dd0df9b9717bbd9dd9bff017677b800d803d1feff8a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:824633246325b9379b5e472a4c9114d28bef362d491154ded8a316a9236e3a9f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:42c7724645196911a8c569168c90aa664d1c7c554849b94b8b34fe1b5c26fc6b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9fbb1367219f3c94721b6501aba43b22b02c8b2a893a639ee070217ab03953a5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a58f5729ecbd160fb4261ed405424004a1e8e5171d363f000ec5a7e90d09ec70
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6f739cee85e7b317e4cc187324f8d82c31e11cb73273fe76a0ebcf5aa3f8d0d2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0a3eb4158608692c617b93acf800d9bdcab0773b20a5d90aa9872518519b6bfc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4bea8983be790bdde0decc6fea9335d9a25bc241318c5f3b7705d3f0fdd7630f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:85ae4e6bc829c231738a828fe827774f314989497a64c1ed425f0d7e25858251
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e6e03496114a62aa8fe98a97ac79197dd488bf1bfd1cded47779352cf845dcfd
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d8c2475721e01ff26a7b52cdf3f96d3346828d6fcc446701df89fffa07241f85
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1a61827291b10a178b759d3f719adf5d212c6df337826e4d5f671948833efb6a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:02b9929d12c26c2c5df8a32c2468937902ec02dd73528a334a4b748e427bfaab"
    registry: registry.mender.io
    repository: mender-server-enterprise
