auditlogs:
  image:
    tag: main@sha256:b3ddaed3f0c6bb8c2261933a48f6514a87ba5259d78c03690bb9c7e12174b092
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d825a30a6e0dcf60ab341a5622590107d7f9cf25b731320dcfd00a2bfa390b17
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2ca2c24e7a23e07a5afde42a60125255878cd4a60201e76ef04798e23a72bd13
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d021a483efe3e431f926938e63f71dcd48f7628eab78f3c759dfa78c3788d3a8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a1fb3c116e41302f2f47b2983c525a1969341b71a79c333b37fae0cb709fd488
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:867b7bed2fa1431527d492981dea2587ed9edaa611bbb44b94c9ab047f9ddf2f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a3c2bb67c86355a959592fbf4be2e1f54318dcff461710aefa8eeb2db0e130ea
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7fd3b117e3ac9838d8c731449dc9fc2e42e150f7dcedc3ba2035610435dacbd1
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:378315ae14c6cbd39695b4cb7f7ba536e6fc25731cdc30a8c90530f9de7b26ef
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3ca8212a2bd849edb72188f7956b2a1c2bafc60fff658fffe970ad0a4b518818
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9f440504fb37f3ce2be75d64fa596d9525222e6d1970c635f9aa34cd9357375d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4ffff0eb67be36e0a5170d2b3c7d5931914164a9b629c76a1cac6c14f1e4a151
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:dff3b47f42219bf58d617751269b8aa0f33eee9c6d575c8a1d816cdfc818b91d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:cd576ea3dbcf2316af2826fa780dfef6f2386de4b2b452506f9a2cda8a56637d"
    registry: docker.io
    repository: mendersoftware
