auditlogs:
  image:
    tag: main@sha256:e34b02e44d02b230c424b0bc3b6ab0433cec01f5a3ea11f56a86dda21d6181ad
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:468996210d1f52eab329e3bc742fafb36a63998b1e11f9ac5235339029b0adaa
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:97ac5fc2feac69caa1c4af65a04999e42d44b1b1002f79d712cf74fe467ae323
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8abe70c3a6ea82584fdb361ed3028906f4eda3abd7bc3f9189806400930352a0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e831e5b35fc56488e93f258d14bec63ac37d8a693f9150aff7c288951a1887be
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5f672c9bd880209c2f1ea0d0d81b95312746c763f1a04a96040e2d3ecde32b2c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:bc872c94c1df8b5283b219eb03380362a0039706b787da098169a6c02930adaf
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:c480a33e352089ac47a4f4f61839e8d4c8e49c89af239d6a76b8b5caea94c6fa
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:bc74f09b7bf31234817d16b3cbf6e3b27088a665d6005bddd78c48aa955c1fce
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:74dc19e6bfc7d189785118af2e8962d6a99984cb2c60ae8b9b8aecf0fed9224e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:21970d196c350f24c842b33cf91c028445b926edd2e6629f6fb19f8a5beb68ad
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:28af82c6dba43d8520fe4cfcbfbbe5a7d31202a214824d3616d47ed181f712a2
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:49472af9a733b55065d976381e9d4d3e6be4cd72e1d4004aaf916aa0f5891ff3
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:50b751b9432b030ae7156dee5281023b81257dd49cc3e80155700b8290554994"
    registry: docker.io
    repository: mendersoftware
iot-manager:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
create-artifact-worker:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
generate-delta-worker:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
deviceauth:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
