auditlogs:
  image:
    tag: main@sha256:59f5bd96039786b4fe200df4dced0be12a0bf7f3d57aaff6011cbf316c75ce5e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:da1ec9ff9f29effb2fdb16f9c3a07540c64675386e334a8b995bfd8f988036c1
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:9dde8d20bfb4a4fd86dc61608c99c14a6211b199af85c146167f027a4898e415
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:4a87b37defa714e3f5e69a7f51af7ed281305984467b7d9d264fe26f56f76b1a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:124c9a17404cbf6f51e6586d438557ff84f77ec5e9fbe14360d94e4d6f56a656
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5dfbc680a2ae4feab91d4a70669b52cf8748cafdbb1af77b5f49cd66428a9749
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:93813fae794e4e04a652a14bdc25342e838eb76f5e7c4b44bd2e048d8a0ea486
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:48c4c6d31eb1da24cf3e5a564bb480fbd37859bf9261bbd34c32bee46ddeb227
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d3daab251a42aa577d49e7c6408124af00101f7df5c01e617df9d272d32e23a4
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:77d0134724ce7969f36e6b9e6a50fd7112b300eceb18c39a6073987fe47785f6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:588fc07ec56432790d5c05a0697c58f227610fff66df9b4e930f5e9704615731
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:6ead936cc0c1c2fcec80225882abe7e1c7dec5592f96798b038c6d172acd0ab5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3bd45662e0fb72e9cd585895662c8c27bc8af86f868ccc7c4deae6f7cfa6156f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:aed8e21fd6d07ab884bef5106d4470aea62555295748aa48a096478b6e0cc374"
    registry: docker.io
    repository: mendersoftware
