auditlogs:
  image:
    tag: main@sha256:2d1e7046a2760d6cc381e342adfcfe2d5fa6064a063e5c7e87a812b5fd018b27
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:21336d6c119a86b2d83743f54eaab434bbbf00e8ed7a50ae931c1d7b6887150e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:718241ee85cc2ce0887bbdcd9ac64cfc806b553281e122fac7d62863fda70ea0
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:08a664340432fcaf393d1d93f6402f28db798dbcbe1ea26fad813399867ba54c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2582e3ff43f59ffa5c24dc7c60b14861dd7f9083048a87354c398fd617e0a3b8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cd013c9aa72c099cf0f7bf16cde838bd578b3b6a3b4a673cd940e6a5157f16c7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:40b7a0e2cfd843799adddf0e385fa9e52cd40660213aca0e3de5586c8d74f5cb
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:24f739bddc4871a175fbfae67570b583ff53a9cdd9c11e23ffb07a996a069da8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a6c586f65d141958480f934d2fb6afbd7482443182672252f71ceed0097580ad
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5401b0f7c9338efe7b8201f3ef6cfe55da31f8f92259755601a0e33370856d97
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b925845edcc6259556021a06d2a104ec504f99064b794265f52b0a9ed1dbaf0d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8cf97aa43b4aa22405b7fcbd5f3ce2beaa0e91f8dcb6ff6a24b274bad021ce6b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:62e47ff81d73d1f4d03e6532de7b446a4c10286a9cb46b0f9dc51e999221ebb5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:696f43eff90c6cbaa83e58ed2910ee1a78974f6781f14d5322adcf06d24fbea4"
    registry: registry.mender.io
    repository: mender-server-enterprise
