auditlogs:
  image:
    tag: main@sha256:955470161e3bfc4be53a783af65c07be698ebf96df2a64e91f031a982a9e7c09
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1d0d458534ead99870e51c2e07a689736617697e94c8a1bb2ac37d33d7ee8d98
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6322302acdda76d607322699e20a9722cf284d73a4b97ffbfd270a68cb0827a9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3ab13caaae57995e08e040bfb03c9ada6d7bfc5a42fe7ed78e6e55e80d1e00c4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:87e35c19e07f6ea566c3918e0586463835d29f4b6eebf6007e9a43149f4e4781
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1d5964e68943eb1796798363cea0118dd4132c76b4c19715f94dd323ccf3e03b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:20cbe307c7ff1a7de8824f5ca232b8225098fabc194ef48beaea85b292dc5caa
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:67748cd637e0d76ce7caa93219dde4914cb0dedaba8c48a747ca2cf7026cbb09
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:6901a243c0f06ceaf05df7d68918941111edc0944d098f8638b7e309271a5c3b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b0c6ae9a1fe15201e607e4023ad68dbf6e1fb44e374a1f6abd1c21cacc824b74
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:060bc284f207fc76e9029825aeda56d64ad7171459e7a0ac612d49fd29e94ee0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:55c52a5a85facb170a58f58a6c00a2d0c5d85a0dc98b673041afda158c5668ce
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4cbc819ed245667eabb18d2c4ef3ed9d5e539804fce89a324ecb24272b267e96
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a90608ed657ccb7698dd92cfbf023296a43f7dc134d3ab872f9eb47fa46a3ef1"
    registry: registry.mender.io
    repository: mender-server-enterprise
