auditlogs:
  image:
    tag: main@sha256:663de2ecd18bee43c2df0e35d4be892f49c056f742bd70d507917231a8d71a6e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:502ffb2a40564aeea7ac14857391ce95628264f34a471792134a1f9fa0efa6aa
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3e83eef60474606a09e50efb1cf5b805a9c024259f40854e876924dfead8392e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:68284e98852a84e6935c98e604d4841478244bbe5069f229d83bbf690e6d4451
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:cd6064bc9fb947e061ba4067b8419ed054448b644fe04a70c20573680845eca4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b0094c6bc70a32e4aaacf517c01c6a781f3e4924a85801d7843d819532c6022d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:020aed17ab010e2a8c5f75c06e1e615d89269e03ade13361ad695767fa4296f1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:95559c7e3c4bb8c4a1473b570b66053fc2deb13e86e49c7ea07946eebafdc5a8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c8393372db9c36f220d3a39a396d1aff5288f54beb5d8650e134d91d2dfe9692
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d68870080b33038de00d22887a0f9ec9608f2ba9ec0419f1d9edda806efbed95
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0461ea54ad9699813354983813b653def33ebfa6059cd11bf630fd6d3dc3f53b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:ff18a0677b2fb1f3fac4bc7d115e75c1ffacacce1905b84d7b69452321a3856b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:51e78c7abd94923922d396b8ecab56189c079176d5bf1196d22b6dcea0da1450
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:36f47341840e8f0dab7371a0e392fd4e916c9d39166dc16f8dd5f3d5f1adb2b7"
    registry: registry.mender.io
    repository: mender-server-enterprise
