auditlogs:
  image:
    tag: main@sha256:e9d0f7006ebbb7c5f7c4db0e9819d0be0828436820aabd65f72fd539fced21a3
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:15a11493cff7dcb3963e6abd20c6e636ad1da337736a2eaf35b21612ec664540
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0730be72179a8ef65590317aa78e60bb3a20f0f742761696c62d5b843872e20a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3319016116c3faa07f299b9fff0b46ab510e00841296e1ea79d7bf3f9a236b76
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a476431a18cf9951446e3842e0ec5891af2690ed1ab22d36d076c6b33b0e69dc
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a46a15ebeecbc8e078c4b8e9a0d4c663b364e00d374f63b7f0a323e7722d41db
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a128542dfd902168b198f2c70ef9d4c2c4a948b198b9e04f2daff34396854439
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:89a48b5f9511fad39024c81be5514fc5a2e2468caf2a375c5a19ececbce8465b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4b90eca672b218f2d046492a2fae890073b32a228c5bfdede5cd65e51a97d8bc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ccd66b0cb51e5f6f4f57502b8cc123b387b9b555c009417f59ff2ebf84af4074
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d823418fd37290f434e1deb18275f58d099efb5c2249095fc249e2fe826c30b6
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bd2f83179771c365fdfd37563da4c6242d3359f5c3626d152be0cb2e06030c12
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6e33f54361a30c7d6b486b4f9f8ab32a709e8d0d8bcbc5d2acc69b56bdc5d20f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:13fd3d1b9050160373e698355c9be943bb2b7152dc5941221bdf41e30b103a4b"
    registry: registry.mender.io
    repository: mender-server-enterprise
