auditlogs:
  image:
    tag: main@sha256:5ace31babc471bfbf4733c6c13eefee80a7d7de9f2e0df36c1cbcb5a723896b1
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2a117f16089a4c0b41908484d8bb4a8d559eda63dad3dc47df30315dfa8d8297
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bda1117929039dfa6392e50e6706ac1e336c131979cb8ff7faac171b33abbba8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1740628674798ff609c465ee791859e7c1ee9a2fa57fcfccdd382354ec8aa5ce
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:c76c2aae20f891e11646659d6680fec9f2225ccd8118d219945c76e268075848
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b44356ba1ec6535963fa7acf7af4df5597e598a385fba1963acc3141d5fc4c01
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:75e5e042742f9a238489ce5c075499ba02074e1886d28a521f52a1bc5f19772f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f1d0ba99609d24438b7f60122d8ac3ce50d06f2b23f0987dd9bfccac286d7e1a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3595cf643bcc73df1056ac652e6ea5a63ad6b8af4ca7f519496843e1808325e2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ede1369efba4c6f3baed9eaad961230ba8a4701d979f9ea3d29daae4be5946ad
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:fd3bd2b018ebb4ffba02324bcf5ae96a3794b1859e4a056e779a6dbaf3f00439
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a4538b7467b41c139a849023a4f43cda43bc09aad44654b6144364297e6992d0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:01ea90c622ba26636b776d51b232e0f4eaa9e754fd850e74e3032b7e697b5623
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:fec707f363bcd362043a2ec46effb072634aad9475e20cfdc7324fd33aac7113"
    registry: registry.mender.io
    repository: mender-server-enterprise
