auditlogs:
  image:
    tag: main@sha256:1cddc392d6719ceaacf2f66b211fae3b62da9485efeb5dbb2aca7c72805559f4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:66849081b5bbc5e44de597a117b7aa45261b51ce7c24b7e06c02d691f394bdf6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:96a720d299995643b8913f28d472e8c77d497623a841585e4184ea003f7d7550
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f7d0a9e9350d49f7fea47c43889753b6a25e0be9ef5435127b356fdd90f6e15c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e3c572671977a5e05a64efc1e18c849b0c25961249aad7606c894a2062424898
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:46a6b7081ddd8d604f8d51d1cacc9c090cb9a3c305e92cacc1ad6906df73d9eb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ee00649b385414cd7afde7ce9d4d5b490a3020a54c1309e71c617e8cb6b5e131
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:06c88379c4007bf5abcb00bfc97b66cd73b389f88a5cf48ee21a0ddadec95d18
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ed265278c10b5fd505ece3e505ae1c59d9eb95f6e14b82ef636dbf46a53ab6bf
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:edbb10d79ee1bf2028b5bb14ac7a3eb43c77d0854cd2b501855eae3dc0d4e200
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1c06f3253feff4390b8bcd22924299f9627a69ab70bce44eb2d865d120df6b14
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c998e3be6e4c6aea55f518b49e2872b91df418c2e2b3d67f1a72d1ebb4b8d723
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:7f5aeb38e5835edc712f2fab73466a03e61bfd1407ef5bd0c7be8ae0422df51f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1acec2de624445c4c95d10205eb88938be59f7a44fd4ae089dd4ebe4faf4b0d1"
    registry: registry.mender.io
    repository: mender-server-enterprise
