auditlogs:
  image:
    tag: main@sha256:93c55ecc426cf86076a71d98030c84e9a17ff5789f4334c9352c2206a44dab95
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:0f51ed2645d76a2e8faa676338eff39e58b48f54e07ca7be8f19e70fa08dfb21
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4cc3f2a825f61d81710015ddfa8a0eb19154ccd0f51797dfb11dcb673568487a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:de633733836c39c7c5411e2d8f6893ea91178cba7762c5752cf04e09febfb9f2
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:c8360b941b4794e47355a02960361fe08e9f5eb21ddcb9e772bd7845d06a183f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5a0620c7edb55329f7271a07a15eee56da96b10a6fbe6c664f1742956776ad67
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:65dff5018d4175351a45568a8ea435783cbfbc8acb1db673b3fe86133eaae4d8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0241d884617dbe77e62cc6a257b24f29b2257846e82a1a27eac4c1d9313bd270
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:7475e04be49b0395fd041a66fb22cde1343ed75c8f1c2c9b9fbc6bac5e610006
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:97de8115b09b8c8b9903aac1f7d9c93a40ec5bd33f35de6bf45eae44622d097c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0212f3a93546014aea7b67c6c732ca0f102c9bb983b7028b8e071db2a36aaa93
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:76980b44d05e68125aa131f07ba8ffbb4fc81c2a85ca6ff6375bf1b5aad7448f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c04911ea515c6ac256ceb77a9792685d46c43c7bdec6140f75061869d03257ed
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a17bb98707ab332366ad26e45aa62631c1db6e99367885d2ad634c93b8e1b710"
    registry: docker.io
    repository: mendersoftware
