auditlogs:
  image:
    tag: main@sha256:7650d9b3626e589951c7b32eaac7835d6e673434a30fc27297c7f29807a98cb4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:88dc752e0c806c3fc6909e87d72dc57f14bd8d087ed37e6167163ca58bcac01e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c51c55d5bae5e2afe15bc1076e2a87cfa67e45e75d1e4b59af3a0c6c39c20ac9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b31ed637872e18a07837ad5967747db2fa0b8a85b3aa377de9e3134199b9ffa5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:534b135ac83646ef0508cb2b91ad7ff80722ea962badd37dee97b44a465e84cb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:83920d081791d51ab21bec612ef5d75b80495597b6e5346b8430a200636bb3c2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:cfdb5309307c2d875c8a63799fb208ce0d7b3affd2b7343882bb6965454b54eb
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f022b81c89cfe85a8972f1cc191b6412caf9b9aca1cbb293f854a734571b9bff
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:24c3f6f2e4bd64bd3783017d367e527b111f036397acc81ce80b5730bbbb0e5b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:25072a47740f16ff119ca201b0ed7a572b041f66cbe2513cfc488b49b7be4c4e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6c2c99890b0a42f919c98f007b96bc5e8265171a066e41e744668d2edab29e4d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8d54636eac969f73ba2f89d94f3ded51459cbeb494b5990e498e7cbd40de68d4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9da13751da41244e8cc2b028f8babaf7abe9fa0b38976344d23b79fa0b360be3
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ab4a85576762e05328e7e359b6d0d66a0befc40726dfa10702488dc3ebd0ae0c"
    registry: docker.io
    repository: mendersoftware
