auditlogs:
  image:
    tag: main@sha256:034f91c842e0ca66ce77bedd2944eadebfe80222ca8d7c87d64eb62890de613a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7ccc9575734e5fbdca65723164eccf7701124b970debb40833045f50d73a58ae
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:de82a7d2e62cd726b7bcf042cf3f5ac350505eed13d02fe6f8b6d403eba63189
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:5f033fd75d9706e9d63be557ef7ad5600cfb0e580cfac3e0d62b61c5594d4a8c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d65b7cbcc71cb28533cab421072a930c64e7f2d08a5a65d776b29e090297a4fc
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b9ceb1dbf9addea0308327b50443a16cd2e11267cd365e58b612b261ced1738a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3a8064edeebab9e2509e45e19eab36c9482353db61bb860aaa4d930d7d2f4b1f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1180da698805f6e1ce94a3b6bd52871fe3b52f5d3940e9d20aec19c42cee178f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c337b3fbd6dc2a8bed42f5941c1bc72ffb070b0678fcb9496e4de6b4771cf20e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6b1acfdac6ed77df439e2802cd91f8645853ba5bb905300e1aad88b31c5e2580
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:cc05df1760034916330e7ba3991ec58592c8be077ec51993c1911713c1cef2ca
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:2469ec5e44127f7ea8400023032f994093664c804e98094acfe85f711daa2136
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1f4f353ff000a31711e9019ba9244dd7f4678aa33e76e5788d4c2f3f5c5fb426
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0339efc4a735cf3fffd41b6ab1b2b5a133fcfc3f64f808b726e98f0dddbe476f"
    registry: docker.io
    repository: mendersoftware
