auditlogs:
  image:
    tag: main@sha256:360716ad4a4d13679dac1657203e9d834485148510153e244e41762f30810bdc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6e01a367ba53a154dbb679a79f2f4712bd3faa13699d596f06991379f8e8a03d
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:26649f1616dcb85971f3ca5d2c83c9c1e198223473fcf81cd70e340b4c94cf17
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c8471076abdafbd1489b1d515c0cf8600b9a1ddfeac9adc81cadfc710bdbfe9f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:bff2edce3b0bdf16a8a755ce8a15ca50f43636d6a325b0e8ea586c7ae086f397
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0801b84a7bcde7838d10218b686b54497fb2fc6ae64eea5b3fe3a11c2916d895
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0e4de7f7bb6b3b031f03b4c8285eedf194a2e3fedeb3548c9e6ba27c08f51415
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:2b9cf486f5f6b247a6122253d25d50262596756187ceb0b90c2200615e5b238e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c49b1ccb0ca6a86d9d3b93dc6dd991ea8c84777f3fc234604aefa1b3cb4a2986
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:a26d6fe37bcf759cdc3816ed50530fdd347b61e346fb0383d386bfa656f24ac0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e4f9c1fcd811ca24d6c963d5f9c3f1e48aedb5bbc2800bf146ae545e410f0c38
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:fdba050152a995cbb427d30032122ee5319793812e137bcb6fde27f59dfd62a7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:efe68d2f88883de8b84a68117dcb0f047fb838ed82084f9ae349423919c11e5f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0d38f25be379ff840d8e2777b882a4db25a8ab4ed872afdedebc354f4eb5d57a"
    registry: docker.io
    repository: mendersoftware
