auditlogs:
  image:
    tag: main@sha256:f434fced9b602be5b1d73a69784b5b4d779d374b7f333c7f5db4feb1dde5948b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:c6e9f5606ad29a6f64879ecced2ebe3376e593dc5988c0518c5cdb8515470a6f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:907e5cf42d33a4e46e0ae39fe337ebce950f13aaff7a9f0e00bab5f153875009
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:83260314f6de4ab5dcf3056616560ef3cdd8bd0dd0e0e695430fd51a7edae5ed
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e0283bd90f4454fcc7d5d8d9a03eeeeb14374dd51ee08bbdf0a5343f24d4d2d9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:372504201e62860c767dd9cc8113737f5f823d01c7631e5cc9ff21a02f95a349
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:7a128e7a607812153c11685aa3023c16042f55ddb9044685f7f31e8da2e6995e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f1cdfe749b227f7ce22744034bbe7d9a80b29e1d780036d9f627beb843fa9914
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c0916b630e56c23c92a1afc47c27c23166d76a940a6c522af3b5d8ce182b9c29
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1dbf42eb66d9408a6adad262171826d371645d566eb774f77eafd966f58d0cbb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f6ae74bc1408083ef5d3f3435f042d71bca99d99e0be0d6954fa5121a94be1bc
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1ce93e4f72067c4d76a52799becc18d5de3a477074301d96388ccf03b57f2593
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f571c828465de6939c98b2d5b96d4e4e8d09d3d23ccaee73eb6cc580fd9c2724
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:98a44c8b68eedba5d5fc86a95e1ea234979cc72041250d18767b9015af7158aa"
    registry: docker.io
    repository: mendersoftware
