auditlogs:
  image:
    tag: main@sha256:77e975203d9ce4655e55742e2964d61ede72c4bc3fd243eb102db2b40bb7f7a4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:dfc72d9cd773c9aa3c2a78a44a16543b708e982a3449a11315058a040a7db12f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f3f6f464ec8c942c6d0fa57556f21bf0469e92e9ed8e7f879e306932245b6117
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:84eb827750b7ca94cc16cd4639a3abfec95e42150b8acdf39c6779ed5abdd27c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:06b3f8c361720d8e3a06e02fbc905a1a9e23695c1791bd4bea569996db1b8b42
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:69d5f35e43069a1f4cbf90f6577c3b655c31ef82078659998382f22391be12a6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b58b43c1e8135ff3c496965727f75b64353b9cb070513fc6b8660ce20626fd83
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8cac764fd47fd172e93d44de178441214954d277a51811801de28d3d7f586d39
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:325c99fb5aab4b88429b379bb2131cd4ce92b078068e225afe444798d8eab013
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f0ff11d4d87a957d6bbfe6940a1209eaeb4d5fe3ad966e6069e1867a2127899a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:30db16df4b09a6877b6f19e442ce29f3412335823b756cdfe9afb9cce493a46b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:cd59d2e3c40fd83c56a7612c895fa56d162df3f20afda21d178178035f89044f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:90f6fe60ea223c05873bf89c1764120e5e0b0fb177b2b30a3617424080470038
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:77c7036345137721460b4a7df30904c7d8615d5c19b51a0e3968093e5a5b323f"
    registry: docker.io
    repository: mendersoftware
