auditlogs:
  image:
    tag: main@sha256:7c43a28e12881ce786977bd25e52d589cfc4ac2ee5bf8eb8ae785167f2ef980e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3990261eb70a053e30ba6acde61923fd3b6e875f7192e445d6f5587fb089b182
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3fb5df9747b24747e533eb10c284be87ab1914c3677b4a90e345d19eee66f87c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7afd246289bbce4337250f9e7e66fcd9c812545f5ec2c18a63fcb0bf1eae5f55
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:397bdf254e7acc00a5bc4bf9f99c62759120dc0c971c46a13f0225d328d31f3f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:392b25345b939fe0e8ad50fe7a66fa9a15e617ae8635d879aee4c88329abf27a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4ced50b1bcb769e49eee6015ed697b332c532322a7bcd711c5a524189c2b343d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e37d2073f1c0f7893ecfe9dcca75b0fe803087ccd168cad5d986436971483f07
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0c384343e087c114373d11c5b108ce9490f804f83c01aec53eced54fe8d4f123
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:a87ad7c4cd2115256b65948f2be239b1e7c47fe71844811357acf0496bd8762e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ac9e738631517ea041f8e642d4792dc87efa8ce25547d8fba55e713b5cef2340
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c0eec1f0f19d2b12437f54280690b115d6276b7f651d70d60082c907441cb506
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f53753555fadce5c3447fda7863b80fdb307f9b8de6884e56d762f464a2e7c80
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d2464bbefc2815925890df5399c7c770ab7376047a40607ee788290a18e877ce"
    registry: registry.mender.io
    repository: mender-server-enterprise
