auditlogs:
  image:
    tag: main@sha256:62106675faf19e72f666c3a1726158b97a2ee8753c41e38c749fa3b146d704b7
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:fb50399b80b84bbdd0a0b1d3561943bab0af36c1185068c9e580bb45f774cbda
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:44159bdda5f04384bbdf6990a1538e5d9c0b4de8f1e88a39414f5e78b5b33746
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2945eeab82bab8e21ec24de55624f31cd2d7df8a15cac0a6c04fb51d352ca2eb
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8efacce7028c27d8dfd95a6045bf4ed8de92720f713e1e9d12827546eef90dee
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:69aac16e94ab50f4872fddb53e7dba63dfa88041e9f0616d0b9862528842fd7a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:53eefe81f979734dbc6972b3e11889478f3af476b53678f142fcb241153d7060
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:964a3ae13cb49f05007cfdd0a60008e379d40ae71e044ce5f8f7672ad6c714c4
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9c35871e5f8e786793e126b70800cd4d2afab7a89592a6f4b97771bfc4def061
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6af85d367f1ac9dade5bae1bf3d3b031fe22f6edd40928679637f1406af817b9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:acbb3da4d54a9de62a7ad60a582012685cb2589cfd037db3c3a3552fca9a0cf8
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:eaa7b77a3f74f84eda794b2ad7164b8301faad250cf17c722894c1038f10f830
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:72b50f48dfa49859927518fe0d322de2c116ae304af35bf029e98daa5b94a521
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b1796ba34eee75e3ec52c70f60018bf4d51b3155576ba83b943d8749e464a866"
    registry: docker.io
    repository: mendersoftware
