auditlogs:
  image:
    tag: staging_fd2197bbbe27df1965e55a24901f973a493d58f0
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_650374036d4b0d36969d3fba4fbf592c4697c95c
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_be08a64b558133f05202c5af83535bbab06afaf4
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_7bdd1b5b6b899addfc39bb21015656333734f576
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_23ae8454267be41e3c28fbc079e6b1a38ff722f9
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_58307e18071e96432f1eba76453a8c38ef9d0f9e
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_67c3bfb073b3486d777c57ef82c6a5afbc88b542
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_fac86762ca8cf3cf71d3e90f7007504a4483974d
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_a43b62134d9538fd98e6f7c7044f9109eef93822
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_1d2c3d751fe56e3e69e1c8fe8b59d04b51d1eada
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_630719591b75ae642b822e9221161213b713ec77
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_7e4b0a94405f4c622c48b5ec22446e79d3c681c8
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_557648e02dc09bfbe7118d8f6f91f919249c0105
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_04d0a548b22a7b59483c7a3f421147bb674ece6e
    registry: mendersoftware
    repository: gui
