auditlogs:
  image:
    tag: main@sha256:5276cff6eea114ccc592fd2e62e6d2f924a7b31114c13c634cc19799fd5c4d7b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9ea4eff8748df8161b4373339ceea686683047c05fd06a975b2b19e74b462fc5
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:95015601d431d010321f5b320844ba307c20b6e870231472d03145f45e42ebed
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d39fa56d60f8c7c5ab8eb74d3a4e147400e9cafc16265316bf89811237e40400
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:60a66a1d83648d255789bb2efd9b0f04d45feacd1b30268e0aeddef6c5bb1590
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:fff20943c8900403abd651f05e3e8442eb4e88aa3c762ae837b3682d44992464
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ff4ce16bb6fc552dbc1a5911b585050fee86f58de4a67e365d2f10d46c5c93a2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:235b6d1aeb467dd0ec3989192369833b600cdcfb2cdc6d2cd21470f5b3fc8149
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d2189f8639b820c15b46afbfa5aa8d4e85a0c976377d83c0f4fe40ec853601af
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:85251b19305db5f582ca88f0f81ae72bd8b73291b62fdae308606761be842277
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d5777830716f0ee070c9835d3ef8f4d8a66802f06aa79886fdf7cbdfd6bc1ead
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:238a072448dfb31059f670072855da602dc171cfa1360b420599476ba4bd8272
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:cb6ecb4d8e96b02a84a0a8bca438fe6900601b4658f4a9f085e75cae6094ccf4
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e18988a823415d0ca981c62b6d7f5bead741c1d65bcbfa2990d06f1d23ab3199"
    registry: docker.io
    repository: mendersoftware
