auditlogs:
  image:
    tag: main@sha256:dcbc52690eec37d1fc8d72c031c26241c6dbcc30ff79fd13d5fb2e46f6b92fe4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:c62a8ec4da962b69ef1427064466561a69a308f6e690bfa5c945bac872de4331
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:172b2253bff175cdc69b626fe32006ae6a466cb3b4a3c4e9c5f448f414734b26
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e6abb16286eb9e52445a6fe9ba41eaa7ecd8815b81025e392e658658d2828f45
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:28ed2370a56cf0600629a1f1d7cdfb705ecb55ac3fe93c5d2a81af4edcd449a3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e9b5a57972fe793b069dc3613e32dbc4e771bf5a6f21506f2b299e5d2d4a1a9e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9671fb90b7eec5c21ff8bb97cca783913518004fc733d55b2f7f32cc8cc2509e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:50af4f5129e1001252b3d0a2cc4323617adce172a0310401f23f4c4328d43fff
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:bfa75933de934f663408191e9e28f7299dcbd77728b33da2ce74ae0d2d7c390b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:74f617b17014a964766c671c4a5eeb360ded382fc6bd0f882e9dbb7243b0d87f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:29bbcf4ef66a79c125443599d10a2d593afeea8b16b973725f71f932616f722b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a3b8d8a32321672bf09918584b9def014fb748a163c75c6ed2cbe4c168b5c595
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0d53f4ce0fc908e9a2762ceda5d2abb5cd21be36fbb238cfcce37ea7bf291057
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:6149ef5c10774d760d0a012720724370ded2739235fc69c9595153081ae119b4"
    registry: docker.io
    repository: mendersoftware
