auditlogs:
  image:
    tag: main@sha256:196c1c51e3eda95d3d905eee7447170d4e33443f783906c0e1aa0aff0721ec1a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:98bfb010e813f7cbd0910078d1131de746a9b9858923bc8cf5c9e1de986865af
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a12db24f4f5e7422ef319d35564c926d6e86f4739c397b5c798b43570fe87d57
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9f4d8a4f39ff0853ce1298042ccd49459aed77b64aa5e84860b855a8c93c630e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e94c0bc3cb407e1398372e5026c03e5ba7fe558e32f54f2783bb77b6faed7739
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f7e2bedf44737e343b3a60255b6f473d01b891726af8512e525e0675e32a1806
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5c93750ae21d179b295bad5beaa5f0bd6d119f65e526d9a246662703d3fc164e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f68b4c604b444a8d8b28eaeafcb89c4cd5e0c17cb245dd16f5d991f173cad55a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:fd03cc509e9005310efa5e8e56abbf0f45485f22d97879c81c47ecfa327d3e57
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2eaf2cfe433483e0c317e148b71e9ab99ccf42b6b5945320b736eb373e9d70c4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0c10f402b8a097606ee455aadef23d395b8d4741551bda701fc6494e05fce9e7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4c211624609b0285862eea9241c36ededa7d1b837dd115ad5660f6a5e1981cd4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:94d58c4121e282f549fd194d2b5d6dee62553deb8673bbb30d26f36b953b112c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9c1ee8b13f94366613b07d81d8393b49a10f18d8af2beccbfc7c3a2d78b89c45"
    registry: docker.io
    repository: mendersoftware
