auditlogs:
  image:
    tag: main@sha256:1b6859241087c6f4b41636d32aab576a853ae266b23ec4777ff6c0143f74b7c5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e57d477c8a26cff6adc9c10f7b7857924a2960ff1ac1c260598a9684ded45a99
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1e667cbc06cf1cb73c00bb831fbeccf4fc562d4fcc44aabf97284283e4abe177
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1c3b07cd683e7d67bf86741bb69bc03923c2563ff189f1ee9562cbf1d81e1a0a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:402fd069f9001fa9d8ab4d8332a49b4b56e90d2d0f05cd5e27e91030f61ef86e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cfee302145042778e88d444c1b52f3b0406b15defebb62d2db3b00e931cf8d21
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:590d20d21d5545b350c44bba9a026adb64a9529bb44b59f0bf59c50632a67de8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3fea135be7c076d2eb8cbcbdc3de7eee367a00daf7cbef3acee184db8d729cfa
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e0b171abffa11b60ba30a18ad5fb2f37bbc00691c9417eab2886d4a47c9de8d6
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b24cb743dfcdf43b4ed7f547f0ece5c5bde54aa5b953b06ba42544959b9488c3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d7c62fbcaf250aa95dd0531a9b4e9e12bdc99cc71db1c3a768cf2ebb80d85f84
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e1d38d751133671e2195d775d65a7a54ca8527e45a78181d23be61f98c137756
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4ab455374e9e9a084b875853bab941ec6d2e3f0152c895ed2c9094c50c8ea03d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a6451d0f1b884d90728d619747ac8b1720e81249676b0be3d6d4d5ba77a84b9c"
    registry: docker.io
    repository: mendersoftware
