auditlogs:
  image:
    tag: main@sha256:2a5aef91d55cad625d9d10a783f70088fa1dbdd163077cbe03af9f14334dee81
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f32e87689a14921df16ad9f5f1a70c65ef0b095eb8e9d18211d2daefbeedede6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3e9ec3a1f1cfa3e3fbcc0f16990c89a2aa7ca732c5e07c681735b6a45bce235a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e41a262f3310168554380dcb5e5865f8644ce9cce8e26df1577147e5443e87d3
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:77072dfc5e5c1993a2da5834e87bdd9aa6bf67a5b18b9cb70ec5d91d1a137e83
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0792e4ed06433d34d9164eda9a40add9e76793d830db4d2b2dd62f7161b7f360
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e4f850061b7f9940ff61386c2f171a8e58ccccbf37dfe0ac4719007879b19ccf
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:015c9a7bf6ee7050798b8d2ba5cfe550ea866af25c28930d0e2d34f50e56b33a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d01ad8baa7dccccb2858f64c8655266616f48f984d96d07ca516cf2b6fd01451
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:25a04520e2eb0db26010fa073f41bc6a95208afefff7eab1234d465ed1dbaacb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:34b80838eaa572355af258945c0260dc2c65a2dc0c13f43e6e344b1135f6bee9
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:18ecb896e7a81b387e98ee3788c3e5817bcf6c4ac2c37820d967952a5f5e6acf
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8400b0d0081b5bbda4283d4761f3620f66a8005ca8a007431038eacffff2e1ab
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f8611ef1e9de98ae966bba31fe8099f1065f8a576a5ddb18ceeabe9f8e485ca8"
    registry: registry.mender.io
    repository: mender-server-enterprise
