auditlogs:
  image:
    tag: main@sha256:52e488f1c01b06b73858d7d0e1b9062367210e414342b8af13909e2a2e06c9f4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4fe2081ecaef810497f35481685fbb69ac1abc2d1f4d22a14f0dac4cf8001227
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:61c2bb65ec991fc459303cef73a17b4b7606898cf7ab884cea8e628e20b3a968
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d3392df51b59655450b18aa0936d20edaa2877a316f73a8b5b87b9b658b9fe12
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:06ea630b3354a29eb759daff85d5743097c758d5256a64d106757efd65347994
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0d96fcc14a3340d1d2540c91fa753a4912c8bfee526042f452c358c8fc7fc227
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:625ca5e800271e6a2ef7a23638f5b00e9f1d28c38210b7545aa4d0fc4e93767a
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d9a799e25ab4bd1091a4606a9d8d4ee03b5136a3236162699102fbd7856bfb5d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c0cfcd24482aee40c56985234abc6f8f00d277541aa9dc0c58e262c5c7502075
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d2f6b29eb9b2b21f3ad0d9a77ff7d5926defc45dbc60a8aa3fbc189418af6495
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e1595a191e16aaffb286a8c7ed7baf6f43b65ee862ffe4bf5a5b8c2addfb7cb3
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:aac2bf17d5d5326e1d8e118651b78d491cf15e80292758a01bb691b1d991ce7b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f8f2727cb89d95c9c2e0b7d9a254393d40eaf920708d79f840b827c25fe2b874
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2ea44f574279ca418d959d207f28eb8308d6aacc75d54efe6e1b91b8a54af0a3"
    registry: docker.io
    repository: mendersoftware
