auditlogs:
  image:
    tag: main@sha256:15dda158d13835206ba8ef6d5fff54512461d627b26de8c8dab884cd80a7e63a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:8a239881c581cea5ff630120a8bfddd604956b5cb8679fe601a86658e3ea6d92
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:11d83406ba4f0f2b0a8ece6dfda530bd05122c9847f684bc3a8dc28cff86f8d4
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:bcd8bb586c1d325f659b642bfdeee5f8b7eeaa314a4d2239506f063e62d0eea5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:cb8d7e28bde45c2526271937c9c01cd6aa54b4ba62afe28ef288da1fb75fb0f6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:3f1eec3da6a94ec1c769feccc87a48de66e7f39055b513e645f7b7cdd1a23a0d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b079014ccf26ba6d45f5fb3129a754e22766a1d242adfc1709da11a1c89778b4
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b7ff0326beda47325963388a76a06cd449b4597220438bf8b608c4d044da5432
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8f07bf2cdfef8f779e6c076aad287fe83eea0d647370a6e4417659d9f56f3eed
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c3a8cff90c60e1f2601ea2ce9839728df0756d34b483979f063003eff1316043
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:420cc0fc423f68538b1086df1ece6698bef1ecc8cc425b37dd221ef6d3d7c13f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1ca573abf9203451437728f11120f73e5b46660510eeae8f226130030264bdef
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c7cf49e8f0c8b1a179fd33e5084c874d9fcb8eaaad1757645cc65d21d53a1162
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2c1e4722d4712df84a5ffed1b578b578acf594f003bdc8bef7bd4d3c48c50572"
    registry: registry.mender.io
    repository: mender-server-enterprise
