auditlogs:
  image:
    tag: main@sha256:777f2d0499a37e41443a8ed59f9b51f2e5c1ddc984f1290271593e619e317d03
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:94de661e7ff4d284ac13601e48e54a92db23d84acc3fbf93368f78c60f722131
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0615516f74399ea5163c9e7c01cb03e2d3454820333b273d4099470de9577ec1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:bd18c5823dea54732a55410328f89e3e8e2d7d79086a85c1c9eacbd0e3df38c0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:18a81268bb0eccd30a198dba2819aca00d08062857b87649ed2f0fe6bc483611
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5c700144e151a0f25df5c39b338bd985b71bf9b55c42467ad4f575820054f87a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b8b60d2ae8239dea6355e3eb3c6e450f290bf031c28cedfdaaf6fe0e6a53b0fa
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:83a050163148eb499f34eca9e2ead223248540ad1b422761f70c36825d143f0b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:94257647fea47a1f6c03e745357f5462405788465e3f72bbf562d88116b4564e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:68da1847ea4f91801ee6515a204d3a07d56195b776390a6b494a3011813cfeb9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:bcb23afb5e3b8cde197b798d1ad108e68e7dab485d7ec20cbf21b6090fe3c555
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1dce90e3d4eabaf0c1911a4e031cd53b63ffdb23330ec54aa47a873bd0d2afa2
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:73928f2430e6c6766c954d7a7e5425ac15426d64448d45ce9c424fff88f9f3e2
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4d947884625a853e28e3ef29eb703bc08592062edad7546ac2a2f2afee49a9ad"
    registry: registry.mender.io
    repository: mender-server-enterprise
