auditlogs:
  image:
    tag: main@sha256:81a46773e7d04db1f04ab9944f55b054b54a33d52aec67b7dea88a393cd9b77c
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:cf0b4eb070ffa9cab143d95bd9f1fd23ba146acc1ed11cf23c4af161107641f1
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:627af7f488e095f40a9f118d0a6cb718865d4d36e9f1646f533655ce7d1e91fa
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ca24490d3fbd968414c24740f1946548e070de88bda5a84955b0a628e5485bf8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e49c7aaf20d19170c5e74aa9cedecf6485aa6489dedb56b5adec455ee2aca439
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1770a7c51555c7c95b59c1457176aaa0fce2243b6e01f169c899e8ad39dc54d2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:469c016669e0840d59bca83aaf6a869bce46672f753421bfee4245c9c1add33b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b5aee6774d7a6b971adb43a106c9325b75696884685a2bb1c0ccf2511aeb19b2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a17bda03b0bf93e1e0a4185f4a268c59e40a258ac0f5c3f3ca174b564632d945
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9155657f891bcb1ab8d6140db9ea3c8d07a5fe35c4437bd032e2876ccdd9da39
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:25dfe44ca0fb48f81dd75016faf85f061ddfd86a49377f23438100cce8a64825
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:73a3bd5f42165852335c53a61ee9d171d5c6969f8f2660ad800959402d3846f4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5609a0ffa4fc608f5454ab284d4e2d19dd3fa67367b9be96bb764bdb35c60798
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:858aa56fa6e410e206f028bea32b4c1907fee08d46ecfce6e5f0c410bbd89e85"
    registry: registry.mender.io
    repository: mender-server-enterprise
