auditlogs:
  image:
    tag: main@sha256:3556a8736c993e26d99cc7964b13b49595e7fbf955eac1a77e27ddfbf718efc1
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:be74b1b43cfcf02c51cec0c5c6470ea1553887362e8fdebcddba5bb627cda1da
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:77c4d05c2a66daf35c02510f173af9d67ec04d2f43cf4af4a831525caa7b3062
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0400f291eb099ee0c72e8a08a97c39adf6b310c86db983e2e32e4ec0efc69072
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e3066dbef2eb82c7e5e1bf0dc38d6eeb42b0716f415fd2284e22ce78b6328c7a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4f19ce02f7d1be9449f7620aa4a3b24fe4d0cf0175da8ed99794b33910dc20a0
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4654cc4751eb14d95efcf55a67d073cd89291a71a0ab01378169f3ac09ceba9e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:47bac8eae573bc2f0bd77ba763909e4e9813d64c9d2136bb4bdbf2883faa6239
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:37022e3ef400a948e002f1cd1a847d64306ac7a03e24fc2318e5bb8820a383b3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9266bec9bbb38df5cd9c1272efd6106bad6cc4fd8fd7e9261e4afbbd5c7b1dfe
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9072678951de3d6357d4d0357a417d40adbdd153ba2f24da1bf8e3e2ba94c267
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b3831d546db7473f4cec65c5844d0e77acc1786c5ac7d67a262390a05a93b2fa
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c912bbbbd997856ec9741bee2fb878b9b1da3ffb509ff87a0cf5250c5961802c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:fd3070654b77e55ae0a80faad5aa953d82a179af0ce36263893a1ae4a8f8d2a0"
    registry: registry.mender.io
    repository: mender-server-enterprise
