auditlogs:
  image:
    tag: main@sha256:dac8d3a060e7db0406799ba46b92e8b289649bae0b3940e76d0e0a4a51d92a8e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9f765cd5c3ab52a67798621c762b60796aa49eed413ffb923f894797a8d352d4
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c6b414202383ce9b52dc8d4436520ec8d962ed4204672670396dab88424475af
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7e56e02310143a7ffadd26c0151308e693c80f3aea6309b93f0dc7fba09461f0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:10dd2960291e061b79f8d4ab3f1e3f2e7e0d01e4fb1b710d1a3f8daf78d8e6e7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:196aca3330d86e4016093f7f1de00275cb06b645eda63b60661e8b88283f3da9
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e409d42182195f9efebf5de2ad4ffb09d5f5cfdcd216b3510825613730cf6295
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:adde605a5624488e087542df870474dd040b2ebb94c5b9e0ab5ce0fba4bd1f44
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:5cbafd244d8c5ade9f46de9e4bfcc6086d2bc6a85478a0c96ec84014e81e4ba3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6d6252d0535aaf13f9a770fc33034ec90af31379caa81d92d528315ee41bb1fd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ed60ccb0980ce012bc114067860ce822e18fa8ecbcc417e9414048aa9d1057a6
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d440d2a115f216d2f1af8a09c6393754e58e6b68941cb3aacc08f8e3cc2cbd45
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c2efef3dffd44d93fde2ad6304fc25b25910cce176584ea318423df5bd1b01c9
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:258ffcf5996eebd2f84aa7da4656bbff37b96f25ee196ca3554be818f1dd8aad"
    registry: docker.io
    repository: mendersoftware
