auditlogs:
  image:
    tag: main@sha256:8822b1870f7a28460bbfe0c5d3cadb6da2054e4ad76697c2bb68162f02a4f4cc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6672bdd683b5187045251810b1b79c46962cad60a3f3b1dd015cf09d566c4e57
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5259d4426e271c48f569fdd803b380df49fea9dc1ff056eb59d5da1ef4d9c4cd
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d3cca11eb608b2e82003d2840e3aa11824429a88bde788f9aaaab2a07570ab83
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:0c94550d9e347c6145ac9c369f8a0250049c57703ca0622dcccfa6128763cc43
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e963cb4a6e92ba4e29c5ab090671e8992ab57810f53a9bb59bcef1f4bbb57245
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f2e5c4c254beef761fcd06beb557db43e0fafcc869470006dcbe4bd6f80fbcc0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3037da9c556bb14c7250891afac37e282fd9478538c83d93053b08d133ec220c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2a1c7e3f70d79775ef4a81440bb77aad7fcf2525343d8e89a021639e8e469b3a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:024d82edacc43b849de0f78e6f034d571a3a6d300321d7cc1a4bea9c60b99376
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b5c803c9bdd6c5d914fb3a39fc17a498146905f3e432c9a251ffff9f6d823dfb
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c7cca480773017d7370256218fc4ada73ca1323b313467b8c22027e8a4952922
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ecc61b2394c6db9e3ae4b6f6091cb643f8d54c205e44522db615b9d50a0a3a19
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:6369765ffd51c958090e184bf37c024262f9b70d997219f03421d27fbf377b62"
    registry: docker.io
    repository: mendersoftware
