auditlogs:
  image:
    tag: main@sha256:56ae47c913e002913a5b668aa2d87934c44b0e20192955067754d4cdf6237ac2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:fde3b817494b9308bcbe6f08ca618ce3898290b593a00ca01296ce15c5365d89
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c95dbda999b5007b76e83441d337bf8e206ee651e027f736a23d6e8233d49524
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d78cce3b5338c552d9a03bdbbd67deddb87495874322e4a03ebcf1f88e22b4a7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9399d5bc8f84fbc64a890b858470d51b8591194b498ab6b08217529c64569e70
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:63378139cbc6bf089f6da1783db3c1d3d50ef801fd2391702999c41e521687ad
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:fbbac1baacbdf853f46964a923712b4258ed3feef3231887155a0e998f453384
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:803ce6b16cf792dc11a74da243c0ac57cdce5736e5736b0d96a10d56cf909bb0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:651624fb2e0c3ae118c2b32d55c4f31c4a5eda931ba7f32b992aeb4023417073
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:79c2665562aa67e1a179012f8e249ac3653d3f9e817f133096e40f1b8f3d3b55
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1b747bfc0c334126fedb8fb12cee42bdc53b25f1f9c33fab8e426218d227d59f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:6ee68474bb98c294f046a40228419517a5a8f882b9b343a53bb13f0c52852355
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d57abdb59bbdc27fc1110c6d5272f5c6864bac7e3e47f0d5f025c00f061ab411
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:751ee49c8218a0cfba07aa1a6d1952d45066d3a53ad07e34c09428f8cc42937a"
    registry: registry.mender.io
    repository: mender-server-enterprise
