auditlogs:
  image:
    tag: main@sha256:8465946be4470d3c7232c1dbf77d7f733cbbc17af1fe9e60bab08e90bdf3ed15
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:593ec5f45b41ed8122c4546c1585bb96318321caf37155efd352152e0cb2ad02
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:985c72216276aadd24367247c60fcb6cd95f52f5801794eff4429366726dd412
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:adecbd508be9af2c9f501d88ef65ec43e532dbd4dfec46f0070a67ac82d0a127
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5660e93c9ee2202cc03256527977d28a55b2a8d20d0496e9937f010462302a6f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4c99a726dd957313d4aeaf809654e36adef69b174fa356f69a6754ff26b98ca8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:98ec4d54cb87226eb35b31fabf8761af6755e6b92e2cd91148a7d8d6b98d54fb
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7e5d035f409e0cbaee81512428f78cfa7c076c693e3413ab558b39612b36d41b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:fc47c46d65bef60406ad26d4527864ae3412878494507f06564196e774ee2e4e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:07d719d36f6e3d80a1624e1de9f35fe43322209be4f5818e45828ee436ebc400
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e25e17b40a11b202e73b958bf261e389170e6627c216030730f76b87e15853c7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:2a1420015bec19179f9c831a45f48f0b6d3dbcb642541f91627d057251312443
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:37eae8ae1c5fd57a71806d50fa8b408dd66d3e3633dcdb234d00cffdba5e1493
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b5d81e155562a2d24b6efffdfc55c68e37d8723fd1096b7e0b85622713b593fd"
    registry: docker.io
    repository: mendersoftware
