auditlogs:
  image:
    tag: main@sha256:4fb759e90feead05e4994be6601b985f2b71091d08154612b087dd23b607d33c
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f2f2e05c53665d3e974809d5045fd44af223f39ec9f0158073320532a70063f7
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:cedfa024d2284d848355fac15948987832ded2d87050a56cb386a84638357599
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:88e8273aab44484d09745e4047c289b1ab6bb8ecec02ed66e7700237be1713fd
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d8cc2e64b144f98d9d61d55688fc6ca1bc1df763acb125daab8f58e4a3e991ca
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2f4a3fb9b4c163e3abe84b38a4da79db45d75bc3e6b840d54bcbdeb9df51f5fc
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a24702865aa195482db68ab6c48a599120361b2a923092f09ab0732463340031
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:77afc8e41c8524a540cb1acfc5b6b9ff93997fefe76d457c6428b282a8bff066
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3d1b4503d7d9d274ab9f0af71ec2b0fb8f26fb93aa61b4612a7f92129efdab6a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:acfd32e4d8e506c08f384493bc1a92415a4f8162b38f61443f253419888677f2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:35b804b142a6001a2ca807dfa490fb66284145fa981f8e2dec589e40c2d293f1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:99255c310088e5d75005df14d08736248b1f0ecaf70c745abd42059dd5525343
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8b6f30f4262d1544c9e05105f8b929cd8543b38b2ded0494379d0daf51bff7cb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d714d60ce93e3d7eef6ded56c0a8db0a4b02b8ae88d6832db8a4350f7b0e142a"
    registry: docker.io
    repository: mendersoftware
