auditlogs:
  image:
    tag: main@sha256:90ccd9f1ba8171ac72f1547d011c7a516715fc22dd11ace3c03fe67e17ebdca6
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f7f599db41d410c88e396b9f108c3b660da6159ad79c35675a00f8397394143f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4d287a5ac666e00136b9521a9251a33dad88ab23c4a7906b3ef447cd723b6da3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ac9f2542e385e1af2edd7fd07170b21dcb90da5bab59bd8b69068db83ca0334d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f1865586f5902c6b50487b85bd623ecbe1d2f0a0b2e55521164afbdd1a7a8861
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ee2214c2c2ba126c1a9b3f4c2da0b171b499918129f7b3e0beda6e715c5c5efa
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9ba5759a9bb66c5cf779a78bd58093dfb7e6bef17905b7792766b47f911c88e1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4b668d87663301d31ab069b22cf0d06e19acb76711cbf5e4efa9da0a90f22606
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:64f38a580215e6b1fdaf5133be2937bf6d2809bf61497f579403c98f79120caa
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7c76f777ddbd393b8e318b233728bb25878db5714deed8457e13762bc2025519
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1421828694798c51749ae73e2fe602599c6dae1c4b2ef60b8962e3d3c95c83db
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:cf9f38855ac8c13a862de7a441caef52f2e061a04d14b445efbbf46d8b46139b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:906c7f2b7d07eac580fab38a795c5db68791bf531c89844a6e91456a0e3e3666
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:6fe31d10489ce53b7f14cc5f3b314004a3d05ca3f40dd7dcef0797020aec1a12"
    registry: docker.io
    repository: mendersoftware
