auditlogs:
  image:
    tag: main@sha256:4d1669f7decc5e5648393e1fbd1632a39b04a64faa3a932e12afcb74b92e4a97
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9c0596b5fe962ebb06ebe72aae878083cd7245370de49127300689f28be0a22f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:9ff3a149860567ffa91e1d974a093c7757e290d8eaf3260515ca5baf942e9499
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:005ec986024231ba2c5959626c39b5932c13f1440c51cfacba0c731c0068b8b1
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7d4bf9f7cd01ffc0142d58689a2001bb8ba79b61b0a38eeada849dd2b9caccc8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:77c0b9f4b309c4e93caf6b75fb44b1b83480e1d9a2584fbf68d85c51c9408878
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:78bf39fb91bc41104ff86b4fd694426a1d8fb1287fd70f29d0d8c01ae20411f8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:31c7820cd7af537ebc376b36ee466152443cf29f003bd3889f0f66bd11063992
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:53c02e7114f02865cfc7646b3c35a49f31ba3e89116c7ec821952885917dc018
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4a2a37bb353b4e5f7e1c0814ca7a6be7b5e1c5a1011210bcb99b4d47de91f282
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b9b4c3dd93a213fda6b52a248a24b82b0018c175cd45764b1fb12fb842f82814
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:186f8afda0cf219f697d70b690a82130b3d3f76e4c155278a0ee91ee2ae47d4e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9b8b645123807dfff6cffa99b0d2d8133310bbd3e2758750fd09c5b5f8d1d7c6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:915bfc3b6083888d21dadc85756ad9e9f8bd4060b11dc8a69ef782cb1376914e"
    registry: registry.mender.io
    repository: mender-server-enterprise
