auditlogs:
  image:
    tag: main@sha256:1ec3d04c3536ea0b3309eb6dc661e40801afd58239d9cec168159d6e720044e0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9945951c1e5b193381a69914ea54e7eed736cb45985031feb1bfec09f88a7953
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2c413a6f99a9a74bbc942ba2df42a68379b5aa09841cb0f9cbe0642d4c832d37
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:efddaf4dd0e45cb40b33e4b24cfeebd1268d9828aacfa0f20ad6b8183d290040
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8797147fbeb42ec1f2f62000206da67e4064fe8a5bb0d40fc7125fe332342063
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6488029b8b2ecdae69b4c3913117590cfc07698c2ffe9008fa38def93104ad6e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:80eadec94d1648821051788f4c0b002edbe3f47879d0b55a32abc0d33ea5bcbf
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e5e8660780956c7ec00f5135e410186bc832e0794828138b7909239e5dd201b4
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:1c111b4132a9b7da77e9534e67d1594c8c77326c1877faf0933f83cf3ce02df9
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9eb28a32807005f670813ea07794b17e84c62245dde77a44af26d9f77a850820
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:dfc1a200982220b15457a66cf9fdaa2b113a2ebdb6812af732e00f9d42e8c0fb
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7a1b651a6495ce819f54fa3466becf8569718c3934e835ee6ac9b564fcfe6c54
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:35f7ec1d9c8d59c3920b2317138927e844ccb225f1563fff44821cbda153495e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d97c745f2ac836465a97477c64985e300e030bfa30f54b8f57a63dbcb44826fa"
    registry: registry.mender.io
    repository: mender-server-enterprise
