auditlogs:
  image:
    tag: main@sha256:479e7db5ec99393ecc189fe570a3177753a3de2fade502316b2ed54f9e6ce01f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1cd573d30569a403e27d4377355fe386a1068076a5223e4667ea87635c330b59
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:d7fbc44edc19c73162217e4dabdcbb15ad18606dd72c413cbb1817657b7d719d
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f6fabc2275f9af13ac3cab2c8303f62cd2ba2b27452c6dfbcc411c1149259e13
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5a25feb7e7fa4dabbb4eeb26b4db31d86410ff1cd7fa7eb14faf782802829744
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0315bba5ebed9def02a99d5191608f12c05289f6e90cc3385903a13960ffb430
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e75176c85def5a61bdc4da56f5be5508dbedb3d5ed0f2acd2dc064436fc19f0f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:61e5878f23ab7d88a0ead98ea21d576ca4112f78280b08fe831bbbf376c8db74
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ce10c42cf47cfa4720130f1de2b97a0a855ee67e6e18080e0207c96a1dae629f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:45a499bdd270083a08f142f636622169716e1bc07437ce45409b81b08a9d6abf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9e62c7de094658ddda4359450bf2b0bb2392b671da761b63bbcc786b9b302753
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:dd7b01f17b7fd8f5542a46d5a716241e4a61b94379f32b7e955ec56cbb83c0d0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ada4c778012b1196201681d8b28958d7d925ac713dd1d4756b72a603c4f48a2d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2ac66ee23d3902cd217a2ba3595c58251ed4f70a12fa071454cbd88badb0d0ce"
    registry: docker.io
    repository: mendersoftware
