auditlogs:
  image:
    tag: main@sha256:4182fde823eda4fb27c057961d0cfb91291560239b2322248ae51f878c6be938
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1eeec7cec3f24a16eff50f2d7de4fe6b5713a042715bca56fda3d6671e6e853f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:fa6871e96c4a651f9178708801af66f3a95e9187f0174c0d4ffe7d6803964248
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d8b74bf97fc18b54508fa351b1f041edbb5e260214169a57215bf6b2368b3f9b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a4e54e2b7c1d61087465601eabab74c022023c0251963391cd877b5544834df9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1f0420a8a77a75eb8d12385dc09bf058ec799b560cb65b7d757592987047231d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e6010ea317a88806274013d1927dc17bed638ac67069f6483aca36b047ddd12c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:60651261aff73d9da5c00711de26dc001ccf03e736f79a26d9424b711c1f79b3
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:45685e204c9e31bbfe3a01883c316bc9a31518cbbb9e9eb2b0f26611c609716a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9707c43082e6a2c5dc940ba71ec263ce869e2063996d73d439d9afab1b5701c9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:15a55f4b00ef560368d0630842337d600bc7cb153802b147fa48079996381b90
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:191e17d8e9dead5b38edd89b5e1c56c0b66176980496d46eefb07f42d9e37960
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9e96cb4ae5ed19083b86d8582db7ac7da6e769645aabb65587ceea80b4e7a3c0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0165b12bb226126e4f18467bd7f2464b8b382d0922b13cc00b7f7e60ebc7dbb2"
    registry: docker.io
    repository: mendersoftware
