auditlogs:
  image:
    tag: main@sha256:9abfaef24846c295e4f03f6357d57abd8f2c8826a940180fa24d2d12ed00a171
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b5e58e4e2ce004fc0586482af56a933ccbd363109a25ac3e29d3c2bc65f67c0a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:05148dd544b42d526e05c6eec48fb4c2ef3d271b63b4b765b0afaeb7ff38856f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2a93098dde29ab585ef457861d3ef0e94f04883dac7ddce942071da3d6e36c42
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9ba63d276ea15203c90e1999f278c0499bb0ed6a2d77e499ae77512f4bf27411
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:02e8c8740c60ecf129f7f0b1b64aacea4c39557d9cb109886bc26cb10b15fff3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a3b452e85559df0625dd25a086acb8708dd2394e08d4449483adbc902cb3d1f4
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:70775af3bea42b757a10c3747135d5fada956b6ab9da76932778f42dc069923c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9b11ed90019e38007b51a5a2e368a1a3b1156fe606b4358c52dd47ac4afc97c9
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1836e6e9f551a5b070335ab2eb4b83f7f030b93ec409e3c88f7d88d62b59beac
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:959685741782e82329ca6fe0996a0dfd2bce316baa1b54e8bdf8a0bb1db26f3a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7bacaf15607894bc308322df4bb089d7a8b34da4ee7cf2b80c87cd93076f2ee7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ecacb872e3c96a58ed9d87b9805519095219ac9079665dcec666f156d1ed2926
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:004d292122a549969a07688bb34f5d9b8ddfb4191b8b4f8d78d10fc5ce63415c"
    registry: docker.io
    repository: mendersoftware
