auditlogs:
  image:
    tag: main@sha256:9e7a3f7f5cfd965bd7a148232c905976f72740ffae72e54e5063ea95947dbd1d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e666adbebaf357220c208a281d3705a45261d62f6f49a7e30f5e29820e085235
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7c3792b1633761ceb0bae464d676fba42ed8ac855e1a426544c085f4b5d91b41
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:eb6d914e50914508f9d47cb670c0f5703819b9a875722509795f0e686bd6f82e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:605e4734ff8d9617c2baf77a4b6e7d770298ed30a4639065b16d97a77f824f70
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ea458d4d4fd7fdfdfbb01b43b24cd381c309618352d3d0984b4e90b669760177
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8c8851de8c748f763422621a685aba7f880e19ac422b99f7b7779ba81d5d9c87
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:798f43602f43cb5d84b1aa8f7cc3a7386208414cd672aa3ddf3686f96ec3fbe0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f74e95f6eac53f77b8217d939ae8ae312d46b25ee58304b197660d56c48d60ab
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0c463a5581020c93ec199341bb5a3187e15e4b64bba9ba6c9898b80c205a12cb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ba50b03bb51b760969fbdffa3deaddb59622a7ccabc760cf1fc941cc250d3e2b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bdf48b6caf9fa847d2ea61e59b64b8c9e445a9bba50b940154dfa7fd2ccc4928
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a898590864b2ba93fba6d3a9107df33f470eeb81fa9cfb21b05be51744834979
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:90fff94477eae0c2938177f5aad5b1ffac9009ec0832432f83224a7e4621401b"
    registry: registry.mender.io
    repository: mender-server-enterprise
