auditlogs:
  image:
    tag: main@sha256:59757e7589950122e725169b940a309c54b5051a6b2b9f9456eece1fe02921b9
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:fa29746b6181c0ea0e606e1247e8b8a792763e908784a7cc2d4f42e547e33da9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:90ae9d75eeb8d11fe257d7f5ac3f109276e4f5c45594a3d9c4000ef53aa37ef8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e2aeda0b87947b7e3e3c3d23cb144e695763eecdf12f3aff8f1aae994bd4f76d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2d5eda73ee88e29d35de4ba5501c0f38dee7f3649e8c676acbac0d136388e4d1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:77a87499f0fc4e1c48ea9456c6041e7a5cbf399741e020af72e973cb43bab282
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5583b3ecc2ec1a1b8f2322fa936d6baacebfca348ec36aae4ae72d0cff730fb5
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:502aa89b4e203db0ae6fcc593dc8b60836b5d3bb4535ac972eb3d31e14360e07
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:20efdec77d2205765578e1075149364f1a36c69e3893f962081e86bd1aa5a3f5
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:491e34fdcf1bee8aed9452ab4c0791407d86b1d1e5c85614d194955b56f84c6c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:93aef4d083cfd6cbe32ea2d51eb851886e6208e10cae2c7f2d3115044486287b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3ae75293a67590b0025534a4d98b1b7f37862ba638be31cb6a40b86aacd61036
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3a9fb6e868bc1386d936a5afb953465b205893965833db34b80d3377af0faba4
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3f0ae8672eb39b07cfb4950e4993ba2c4109b6f42effdcc8fba996ea2d5e68f4"
    registry: docker.io
    repository: mendersoftware
