auditlogs:
  image:
    tag: main@sha256:d7f9ca144fee1dd2e6d1186dd2135da21cf4bf8e2cd59d6c82810c0252b4e91d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:624ba752268def4b9b45572f73582cd858b9305c404a79698dbb98ab571017f7
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8b43759486f988069f549f7de6d13f6407a3862e259c67ba26b9f7316e2ed0a6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:4b394a5f1198a9ce0f2e7c1ae7b9284bd39edaf99f7e7a5e4712fe56cb2a47f1
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e18abcfc4395abb7a31c22225d0814a1f1d4d58f96dc515051baf6a8a724aa58
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7f21d918269a24b89082b60898af01de40b0606dc55d259772171331314c2351
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:88f964cf87b7ce99e45a18058c271d6704e3b192bf0ad1b050ce102f936d9a2c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7a92063412bf3ad8692729327e467cb22a1e11599ca796fd09c5325f96988f0b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:108c3723c5e8680277afc0b6d531d24533d249de4cb1659d7af00a934312c560
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e653d49a6ce4ef3cd399c641d381e3d894208dde73d80a1899a893bc745f2c8b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:95848ab6a094fd178acef656bc92968904e4fd044e2ecbd8786b1c22131a459e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:04cd5a2988bc3adb7c35a9df969d282398fee1a4622831ab3647b2ebe1646bb5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:bbab3dfb8920660afdbab3c839a1ab5e57cc026b7d1ea72fc508ffaf84b83aeb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ebb757bf880e43eccc6747e0bb8e71d93764b346cf6702789d3c32157b592400"
    registry: registry.mender.io
    repository: mender-server-enterprise
