auditlogs:
  image:
    tag: main@sha256:5cac639f1cad1e21acb5efca1c31243eca98308a5ae859c02aa41b8461db67c7
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b26ddba8da3deea17b9c61d9f04845940a6631f5c09960a1e3bd63936b45070a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a10c90452f095ae12b8722215f1033cd5fb403f9543b96e0173c532183a062db
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c2a5dcd81049206f55e9c7296fb6c94ff86450a6ea565b6ca05d335675e4faf0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7b67960680e76dbacfe6748fcc3f410c82f513e8023f340e8c01e82a906f0af5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:bbd4a59cd293545fa498e90adda421e946abae734eaf1515e8b382e5e8236847
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8046d6ba85f0adc7f78050f1ac2488570edf07974a52849b7075f6113ed10b37
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:cfce20c77acb84dc2f910afe920f58d79abb382edfcc4ed5694691b8e2167c8d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:19bb35069d519de2897b4dd5ba294c64b25989645c12315a7950234043ca86df
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8e060a60385b2e82deb071971c5b5fb736bce13833abc39e8a0a78959d320e26
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c5a22d1b070a51f4293d5c712e8890bb5ae97c2dc13271acd884869ce3c0aec2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a774695aa6f0cc501f59926657251064fad1b62b3635454b724065378293ebf0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:34293c40074b1a67398288275da7b36fdc16b8ed1202b7d4359609d1bbf7dcfb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7c085dc0b788b189fe92d83f4a2948128fafd3f9e6e9f49d34e64875b5284272"
    registry: registry.mender.io
    repository: mender-server-enterprise
