auditlogs:
  image:
    tag: main@sha256:5fed6de2752433749a38577cd13269060ff517b07a84c827ff45e930bb9eca54
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e124e456f429c907565f157fde0dedc846783326e8731712968394c35f4af8a1
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:51c358ac258b18b409c39c854de11ff95af45345f6c94edc28c6c3b6e79c6ad7
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:93b86c46834d4cb7f272523f3e13e33a6917dc7963a2c1a72427f29f01e647e4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:88a56599f64ca2db93d36dcd0a097cac6612ecd74f9e4df21dd1e5f31d6a14b5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2e666197d3a10e9cb96706443870d1165f8f06c988fac42c74b28adcae2e53e7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:873e560cfb4437642b241fcb3972634ce6a9a7c1510e89adcde483203f35d93d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3b3be44d43ff349c9ae2ea073ba3eafbcc25535569d201e6bd0b545677102b17
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8382c45e854ac432859188cb13222e7461d35fa62d5f47d5d46c3c7087cac84f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:641ddce74a48845c9af7ebfc65e387a65175e2be617365775a026d6adb74a9b6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f8bb8f1f4b54e8a141840e731929852cb726eac422365df2967dffed0beddb72
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:52ecd985aa7940d527be6597e71ecd88e4fed62418f2ae87e419d230b123bfff
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ec1035c0e8d8853ee897f806af30c28966f5ed772f0264e634ca4f13b8f222b3
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:936dafa8c4785f2b0d29acb3c5f3480d85abe497686d358dce68c6e233db7f12"
    registry: registry.mender.io
    repository: mender-server-enterprise
