auditlogs:
  image:
    tag: main@sha256:9a462906eab19997297db27483a8ea7f7345b03ef8405c6e90e126010d778f20
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b2bb029552cdf5c016053a437ca28ce2be5701c8d9b9b3243c08306bd08e3d67
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:646736c4185982520f8af1abccf8532cbcb25f102dd8ab06f94c9f9e4956f555
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d1c6df570ade750eeabe268382fa4fb7c1bae66fa48771966799b26b63f14444
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9d933c9be3f3627e2d3e227a89eec076ab49100ed1073e9ddd8b0722bc417ea8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ac3c8738a911b91b4f83026c7fc8237d9496dcbc3630a336d9393e4ff000d3d5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e6933bf7dbf9127d716c5a42dba75b8ed6b271ca90be44941654babcc1c9d6bb
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:fa8811e8d49591f56c48bf92ed95251f84f60dd3b6e69aca09e6359357457425
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0c2cf03707e6d6a96a98bddcca2cc1981ef550a942889b2d5ea74fef0abd9860
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:62b587942cbaa1041b3efcd92ffbeafd2faf57ef00238b8d8fe89c84c8e98021
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c31312cf6b76f3d625e2f9ac33b8ab92cdfa03b7a253b7e7739ceeecfcae6477
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:dd3731f573b7d44a5bff2137a742461f294dd08443325db42bff6cd1c3821944
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d8c27bc6d6dcc8dea0be9692a477a299c831841ad043c09f47f8c48263f5f043
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f69490c6179d562d8d1f71c0f90ddc4683d71fb5af9edb63f155900c15d3c789"
    registry: docker.io
    repository: mendersoftware
