auditlogs:
  image:
    tag: main@sha256:8fd83959a9c9a1cdd6bd8869c1005191262e390feff31c669efbc4f698f967ee
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ece7f271f12b1f29a26df97e747251d99a3aedf5a186445f74fdfdc1fea3a844
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:cd918455474396a8762efcbba1a2f110f2e59f4e6ab63bfdddae4c54d06624ac
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:de581c78c12f05f5999359c34cf838a4e95f1135fe7c24a62af1a0d7a58c69b2
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:3320b9aee28a030a3412e815b4676d86eff89251892ef9ea8cd8a90440287b61
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7cc3930ffb7386c6e734836b0aad1dea2146f49679c4b0f446e9b11d083368d3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:496a040324fbb920ad4a799a221d6c152b07a43adbc4fcf5d47d0aac6b762128
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:04e0e00ac9dcbb000be2cd82738d0ae58307e8dcf35116766af4b07197250705
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:1f6ddad1f71352c70da912fc47d05aa8948692cfaaf25663e8ce1d60c46ee624
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:87a785f2236d1e8c2e4db61f931710ac213f8c42b7340e4703dd0741686dc033
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d75de31601534a22800bcff54c4101de3272e932d6a96b4c8b22de8e044aa0ae
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:35dbe3330d80e4810aa79ab89cd6688232203725325ecd7989baf6edd757350f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a638a4b0f5e608d9237a23e6d8a71443fa119cbd10c9c5fe06aa16296a5ef0d2
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e374fce03f5a13cfe8deaae741079f3a0cd4ccb73e783fc5aa573ccb30bbd9b3"
    registry: registry.mender.io
    repository: mender-server-enterprise
