auditlogs:
  image:
    tag: main@sha256:e85e20d2312b6bf15fcaf41939ba1142404b7ee7a32e5590090119d6e6c2a912
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:174b924ab26b1a2e9f9922864ad27fb5cca8364d48f165c6427069fd8ab23929
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:774157f18a026f352ae1b2f93be6ade2b5262723161d89e343567d79ed758ab1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8213f7daa086f4ee526410ac2dd8677cf764af402fefbe3651e4891ca1395da8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:345962bd03254e2b4f8814467ae4673b1d32d9c33363477d204cdb5e8fd822fb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:691dd2f277ab035efa6bd9190933e0b96d5e574681469fcae42e92ebb58f3121
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d36b00d19f5a8d707fe46afc92cdce69b36031593d4b7a2fb4c991971dd51829
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1aafde4d0d7067c901926908c20f7df066b7ab8c99e84a276eff479ec5d56381
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9e80486b0fbad5d01cfacc26be95f64c877b728c99dbecfdbeff889b6379a36c
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:81b0c16f78796cdaf752f352d3a3b71047609d1250e099da4869f04562aea092
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:5bc804ad3ca5f2dd930ba4ec1d8c9f6536a2d7b2e490627a859a5932f5a76133
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:6c9095ed113742f8413589716fee70dd9cfd5427e4d00413ff0ce7757658a35b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:15e208ffe1715f965e7c267b7dd6ddb2cfb68e080c55edfc73f83531bbff924e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1b0fe03c87473066be427f0cf288922a253ec20fec34cbb36bb33c9a6b9bb614"
    registry: docker.io
    repository: mendersoftware
