auditlogs:
  image:
    tag: main@sha256:73059e24929254b260bbff268b62b9647e74e0ab4bcb978bb79d0fe3b9534c81
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:cb953af8e8f399a92fec643509389773ec6a78821dfd817a42d8ddf52dce26c6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5888594c62ef3aa201d20fca42f7e339ea5f8cfc00844d7932aa7eea27dfbd63
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:95ac2f3ef14af08504e2af3c669447218fa6eb4552e05f21f921015313ef64b8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e58f54877392c5c01a770b7bd917fd686c3afc44d67d0f8a9b2ce80f699d6142
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:bc7f4afb7dbd51ff34722e80be793e076614716b59c84215f10ac08a557063e6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3d165bff299184592f4508103fa0dc0722fdd53000975e79a6aded946b26ff9c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8152a687d1231b25ee1266ea9fe55ea6fbcb1b12f7af00d13ae86cc4ebcfed84
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c040c2479bc1b1d2beab83a4d6beee318fce4288ee4e6c668167fe25db0014ac
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:73fb725b9899bb9cee00ba3b833f9ba4f16df419ad3c46f47fdb8c42da65795d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1c8a80f7ac23c9228378672d535451136fbcf366e4c3bd7f5a308a296b8edc11
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8ed24130e7ac8eda0781a33570702e0103388647b2b05a5765c6ffc3bd2a0186
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0a35085ebfffdaab6aa57bc12a68a4869361417fced2897fe935a38a4518a6f0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:06140bf642415efffd772e42170bc192a131514a4f6293e2b2e3b7ad4d26a6ac"
    registry: docker.io
    repository: mendersoftware
