auditlogs:
  image:
    tag: main@sha256:ea6c9ec5b0c49fb248cf276c6bd19a1434bc4c7cf0593b4cb84b95367e76d88e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3917b0eee0ab5f9b3c78e6ba2fa0eadf7a2883cdebc0d975f061a48e6472d7d1
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c3d7989f7b44d3d2ddec8cb4a1e937bd19f3bce5606d83ca94eaf7059ece0de3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1d7f9b57039ef8d6b7f2e64b8b2bc319e2d46081b88a80b25c3a6eb834c800aa
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ea20e6a8b8021bcfc26a9461075befcf9e38db5858de238c69e63fe591265e67
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:65fffb5b13bdef17b4d655e3367834f11050bc71cb36e77af68e833fca415c7c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:266b0abf56fa7db19849507e47bef1b02b4936577b8b17300539fcdc8bdcaf5b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:2e89b8e4e3ae69383a6f531e6d7df42d53065e7dd3359ee3406215bb6671577d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a42ffcc30b753ab48822d569fced859291171e4d31706b54822928513a23a198
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e98f21b28fa55544b6a42d02821fa05e7dd00d18de53d99c6b6b3852c93de4bc
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:da91a9ea53e9472f33fb831e0c45d7e63cb3bef217c024da0d177af0ab5acc38
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:088da50ccb0cdeb23b83762d1dbabf172ac46f4675740f295bb186c29264388b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6c041c1dab5d3f6ba1501eab2cf3c164253d6973fae3de853bf5fd3d987cab22
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d242b13d3e96960df432de1337e5e68d5afdf98214b0c71577a8af44686b48b4"
    registry: docker.io
    repository: mendersoftware
