auditlogs:
  image:
    tag: main@sha256:9620eceee6d7be1369af6a6e749ccc50b600485454888e22f1d76715ec443619
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:dc4572166e9aa7c38374fdfae9ee60cad0f1b43998bb80bef706b39d4976d733
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:872bbc442aed5d014061bbdc67ddbcc469f4dcfbf597ce587d8a3173ef01523b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9d49de0e4bd195e9ff4e17882a65a888c370dcc7447ba903897e66ebecf9c278
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7c2550c0d90925c5bf4e097470a0d16febccc67a67e2bb61d8b04dcaa3adeb18
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e83bb06a8238aeff617e912f1661d15ae9f40aadadc2e0d0d5860509b107d484
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:baa54ba430b39b022a4424d9f8dbc859448e765d9f60b15b675e64c3e3fd3e23
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a0c355c453ea70495241017b4deb2b496bc351f3d55fa13ad33b599585dd9961
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:27d920d2d0ebfe61bf3c46179c414964116060c2ac719e32eaf8ca53df2d212a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2c15cc1145d03051252bd5d68e2078621260bb83e74fea4ccf7b36b707aabae7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:20e162a2bf214096ae8761b97a5e5e7e0ba6a4edcb9f2537935058e862672971
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1ea7578b78f774640e3c8b441870a3093fc21265d8c79f5c657d009e987aacca
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f1366be9cb2f179f962926f33e0643871415ca37720db4febae21bc5e19b78a8
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9021e9725ed41c8efcf53a08a70f39890968bcd44a85f2803867bf024a056ea0"
    registry: docker.io
    repository: mendersoftware
