auditlogs:
  image:
    tag: main@sha256:a9e233ee4f394104807c0f0c7f3f114912f2fdc96e7fb3c1a91e1a072df7d240
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2f6472ad3c88928b1f5c7d2f8d1a2233e8925f29ecbc14f24654232e55b5a996
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:61a33286ef49e65fac086cad84018ddfab381eff5bb693cdfc392fec00dfbab5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e29302cde2a6b554b26a706bf579d2272b7031da8aa1dd5311c2338ef23e9bea
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ebd595967bf34f067c5c4581ba2eedc94b86be357c0146720f6785b082b74332
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:94071663c240f5c3e73a68ea9467e4fe8b377f7482ce360fed4401d0a9782c11
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:55f951ab410eb38ab94b2ac83cff2e5d4c6ef8ef29de5eb4ba8c78e10657f8ca
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:85783687f1809a2a3a0b6ee49ce16265e996d73b938a28841fbb4f601e2e4d22
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d98fe4f5ef856f80b014d1b606a3c0325c936486047e640a106d4fdd53c1cafc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f848424a68da5c96714755f633342f20836f82bf9cc9fdfd6cf1b87da2c56c9d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:5024e395113300d86b9c80e569ec6ff8c8c643d8e1e0a8b37816cb5cd2cea3f1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:dc8cfa68deca30399cfb8eb341a8f024c678cbb76bb221d3b2cbf6fd2202d727
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ddac764b47700c382731b3c3428a790e752ddf710adfb8221934cfeaea90ed1c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9563e446e073180c36e1c6f4e39c033c4c04d99067122b777d88139ef3efcdbf"
    registry: docker.io
    repository: mendersoftware
