auditlogs:
  image:
    tag: main@sha256:e076f23fda2780f7b2416999c0106321a5960f6eb1513709d72cef6e115bc4fb
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ecd172bee3d7add9c17b84560c7f80410a295b616e0944d05b0cde73153c746f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3598a02a28519da2cff20e69e9736dfe751e5611af723d1f440610c41936e2ea
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2fedb5fb8ac1349742d1684f2ab4d421cf44614402369991a065f1ddb658fee4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:13a177fc89a6109ff8b691656dbc6be8cba993d03835f079d179c5bc13ee895a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1daf4d8aafa5691ec98f089f87dd5f52d4febf8a35fdfc2579bc742aec25a236
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6913ccc767584de14910b5c3d31e1232533f1b1902a9f0ef2f6c275e323820f5
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ea0e3334196bd42e2f16a09fa3c1e577a99124bf7c70032276ede9713eebdf42
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4609bdb4d82a61eecb7b53652e5a9fc34df3e62241fffaf992c32b9fbb55b4bc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b05867c0ed30ad43328e536a69fdfdb0317ff028e996952a988a305165b22f22
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:655f7fcd6fccaf98e4b4eedac24de1a80d1a6154a38ce1aa1bbc874122f8324b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b95a5ac6fb464f29777b8443a28c65993075c3bd48a52c53fdb7e8e3cc5bb549
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2136072582a7e6d664a5a7451210adf5117ff7f004840a1aa279b3b29d132cc9
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ba7da8120dec0adc87c4500a76b74daeabd9312f3e8feaed62129ca01fefdec0"
    registry: registry.mender.io
    repository: mender-server-enterprise
