auditlogs:
  image:
    tag: main@sha256:ec5b6cc9ee5d07638da8f663c7fad917150646868fdf26f5cb88b7c48806df3d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:55945f33f6c8882ef868b4d7c5b4370e02872511e03f7dd5421c63e9c1382fdc
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:47e40c130f1c7a6957e84888d6445b69bf221fdb9314a997e0b6cdf490143ef0
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8e4bc8c90b0b0ea2b78fee604e319cad1c4569f0ef4fc827d04e3347a454ed32
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:55f78de62ed88e579370bee28d8ca84463e5e5c3f75516ef79ea0b119bd806c9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f269210da4145c1ec4b143971e24faad4100f6dd71e0829f5a343efaabb6a052
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4a5f1adb77e19414c2e44ffd5aa3ce6c8665ccbeae18a2430b8da4fe779c8b3a
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f411d69b729b36d59f33d2007f76898a9b8b5b14ca7dc4a7030b1561164623eb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b006bf8871b3b2e352998e6994fc068558ba2e0985f39f1ff8ed7c85635e7bc1
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2196e5296706e0bd577d2e1f1f0ac43cc4397ba61331d4675578c861fa54c8ce
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1c1c469bfc65bc8e78fc0bba074dffa01fc7720062b3763a5ec8952968cd0991
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e4a86cdc42feec92956b7568506c82918600c00720318298f535cc94b53c503b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3fae315150c5b268c7b2f569ea3a165bdc52315a44b3997e2ecf4cbb0ed713a7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ea91ed7969a774f07da83313bf8ba7cd6d0b664dd81a813c37c8ecf4a5c2f275"
    registry: docker.io
    repository: mendersoftware
