auditlogs:
  image:
    tag: main@sha256:1d8167514e99045a5b1f2cd7b74607951e28d9d78db998e97b018e8d8b0a5aa3
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:bd41a0f4f988b6353a01672c3c13627edc00a25859ad25c53b09ba079252ff59
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:154e3a6bf8b30f42adaf09f471fd4e819c27e1ed932258f7ff68ead68d67dfd7
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:45144ce6f9f5b13d156b518be420ce89becfbc4cd426b4d622f893bfe43ab138
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:676975ad072d56831f8f7054b24a3ccb7413d462d0d1713e31c418f0ee456a14
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:45f4ea5d3ef12f1625666acbf41821e6f6ee64deb4ddc412f6514d25b3c6302f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:04bea4503bff315d9adb533b6e525b42ce39ef6c6195df43dcd0bf83e2b41c11
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:9c427dacc63fbda2842224e4ea9c280e6e076a0680459d30e73a8dbdc491d6b5
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:86a0af13fdb2894938b8b4ad8dfc5e1e835890f527439cabefe8bce6d32a64b7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4da83efcce916c8cfe9a64fdbead6e0a567e2c481f779924794550927aab050b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:68fee00f073c8f7a67b2a6f9af1cd006be3b356f1c56f025eff3441992756333
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a7f512f3f8487f18f492f9ead7c1454c819b54bba065d8011b59dd1866dced8d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:117dbeac1b9336cf91b77620fd122300e231b8eb2c90c398fd881ce85d5011fe
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:bfd40fe2586bd79e963c32d985bde7e6919c06ea34cf00bc171ca1b6e3742114"
    registry: registry.mender.io
    repository: mender-server-enterprise
