auditlogs:
  image:
    tag: main@sha256:8c3f42e2d6496ff40cfae392ba19b9057a8769173e28b733f6c5479bb0b00400
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:a7f62a9cd78fc5d8222cc617dc9e339d7739ecbf82f3bc9e6106c33e9804d248
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bdd4f40f4baca4c2b193d029a728de1c379d214fcd137ca683ab38a4b4634ad4
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:fc27eae21e9472ff2d25ba349016fc6fbdee17001fa6cb0088e5b6f0479141b4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7dd2084d04ab43047f00158fc646a3cc49a89e7c4124eb799c2df398418b1b25
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:54b7e42ff886dde26552bc0354380b4e97a4b3a92ae37ebe1d13ba1a5fd0b7d4
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:716460cbab27aeaeaa0b4fd97f0b30e0097794ac5d1a0cd6f2b6301dd3e15338
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:39bdd6b773b32561293955c14b08a53c168e73863adc91f51dddbcd23e5866e8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e68948d9a7a8abf4553d47744ea16d47d6f2a70596d3bad20b6050cf0dd5264a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8c3c4cfbf83596e1bdc5073d91488c5914c58ca8e87a48925fd78805915d843a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:54f852ff410091f63c3597cc8c1afa9e868405702fd11c6d890a0f3bbed6001f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e458d811ab7da121dc6b13ab883e0896eb1a28ddfb0c5c058a33063f44b21b2a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:688b6814405a721538668c69995cb5c89169e045e65d2741d2f8be1521f2f4ee
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:20e2fdf9f9bf1ec5178ed3f25581d99996f850eedce6def20a574ae0e5a01a42"
    registry: docker.io
    repository: mendersoftware
