auditlogs:
  image:
    tag: main@sha256:12762e6679117fa247db598e850d1ddc4a42b855a45b9e61cdbf78ac7d3d25bc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b3f7c1fbc85c96fac1985b72aadb43ed7ab8bec53357a69b497391c67db02cbb
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:eeaefe1091a5055f4cec61f61393872b7ce25d730c6dbad9e9d13d5aedbe7403
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:80d17f5e0641619b112b7ce0113cbe97040aaabd8df852424fb932f000bb3efa
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4658424c98344eabeb411daaabbe1192ef6daaa98bfdb4550100aa52eeb3d365
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4c95e0f281e38ef50adbd7c76e90bf4de54834b4052e8d9ad97f396452eae388
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3e990ebde07108ec9003c236f3f3e64f02fba6ac8973825573a05b40a634cb9f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:37ba37d24bde20b5dcaec2fb75f7b3ecdadf461a198fddc73530a26b66497f31
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0cea35e3a85dfe79732f8f58b931e17862b60c5224a8b96b4457cb426d5c23ae
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:de9d64ee7d787962a977dea801d44459f9ab9b9c75f8dfc25cba76079da2e0a2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ba67c0f22d96883a59f3bf792ec2cff616eb04e9aa32aa67e2736f1f56e2a3b7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:699ab8eac98f3b869aaef76306fae06875ff3853b004aff04a46e72140c0e3c9
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:7d1da71dd8702790448726dcf5e5db2b9bfff65a7939fa2edd4f1c23b4aa3a11
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:67de06c05ad82e3b8273c1be53658ee998d22a2f6fc5a852890548ae4f7f91a2"
    registry: docker.io
    repository: mendersoftware
