auditlogs:
  image:
    tag: main@sha256:05ecddb5c527b3e9cbefa476bb205480762ae6119702abd7a8561cfa5872417b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:855bc3a0fda8395e2ef5d9c96e6d5ebc7235a660465138bc742ca8cc4750ecc6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:86fab1866d393030e0bab1913b10d93f5c9e419ccdc96b5cd40c7da003564efb
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:14f383abfe36d986797365e22ed3b671c92854afabaf5a09b0ba80edddb299a2
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:96d7195683735ce03a6049cfada3832466c6cb4787f17101388a028561e65dcb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ef9e991dedfb234f59f074c19d0114db4cd2008dc19e2bdee794bbbe1dd93b63
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:79e49981c7ba4a7d148aae53fb38cb7a3042cc17eda7601bcfb7b121ad268b86
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:45bb6811c5bc8e484a8709ffdb39e0f421da0bfac124ac495e6f582bc2be586e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:80c56b2af0440abb236cfb00de8caca2393dd50d6327267fc7457a2000ff57f3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:21acbdbae9f78de2ed21e99f9024658ed6fe28a149460e5c19d89d0de5d0e51d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7ec7323fcc9750ce5abce9f32cfd5fe815f9f59486d30fbcda80351048d45943
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:cbb9c215ccbf29a98cefbe2cd200c7cab08aa5bdc5fdb4ab70f96dbd1a4ec83f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5eb1acae4b84a54ceafc1f8b558fae9361a338ddd6a7c4c78463c8bc825356eb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:90584df9a06d33f9434751c93ad2c4e0bb6667ef75d1c2ffe8e94ea0a9a041e6"
    registry: registry.mender.io
    repository: mender-server-enterprise
