auditlogs:
  image:
    tag: main@sha256:d9424b4ad80e091fe67351e259d84024a6b7a99dcd6aeb910de93988b549ad58
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b7d43bd3a82adb183c488ef53c1b6b776729fb52fc08f3536b298809ff12e2ab
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3926262a911618236c35c458499379aad66f12dea248da28c13a07a0f58299df
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b64e9398c63266d516f6b48403605e6a4bb2084e2861e6e929f809dbf1085577
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:990c57c0a6afc5d3ed71bd3c1c012a0b59c487d53ca468faba5f9e71dab724b3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c7cdba3279495a202fff7c014cb6d8c234f977b5082fad5a0b9b1b0ab11597cc
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6dde4beb132265c00e4b60db65fbf788599614f8f29c5e1b8dbe880d1e3341e6
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:54589f87225859987f81f9292339cd1c9a09c661219e56d7f81b8ddab63bce58
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c6522098e18a29fbcfd216afbb20f651afb3173af65b239a9d466ce711f30e67
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d2e8a4bffaddf5724f1021ce988379295b7d32093995019328dab0c956aad02c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ea29618e4cce69fa7d49e94e808c2e6013991f265827eb84f5d06a3a97431e82
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8572078f0b575a7c11c1fcc8e011a52c7c52e15298c1fdd91dc25544bd51d518
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f744b35b7b3fcb359d0453ac30ecafd7082b263d17cac52d62ac8d3ff949a34f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:074f686ed85eb1d440163c52e0666454f9f963f453055ff9d160a6079a714a5a"
    registry: docker.io
    repository: mendersoftware
