auditlogs:
  image:
    tag: main@sha256:a802839842972c103e890272a4077a443bd15226f4a7de3294d53861550b44f8
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6cea3fd7828250757ad9b47e69cbdf5a2e18a5149db093a9e4aaea58cb0ba4bf
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5f651f482404d993add9d6853eb9687d668ac12bfbb9259f09d62708c13245e8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e00e1fb91eb9e9594c644b1eeda8384531021275bfaa9dc75576248d3d53bb07
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:fe31bc5a2c9523a40a22dfbcc1b3635c888e7546ca41138eaa8cf826c6118a42
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d54fd9f121baf4a9800998898086eab54b064593d4f580e38e091324fbe8d1be
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:66866a22166deacc68aca123c1090059fa64db1f12e52e728c2255838258eed0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ee05deecd96a0435207c05d781e90f23ed58e1bb13eb3616355a251620c85710
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8529f0f40deea950802762fb6cbca92a07a3bf55e70b1ba83363d2bb979ee89a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:92ac12cb3cc64d6663be9a9a07c8caaeddc246a41c39c170cd192ab59c20a052
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:a6144e889f4aa2c2197d10b32fb834dc8039fb06692aec2d3df5ec16efd9241e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:548c4501d8720ac03d544c015a93a156a63f31aad7ca41770a9c15e9fdf317e8
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3bf9ed1857c25c2ad981c1c513502a889ee7dc04836920a46b2a567fa1393c22
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:27714b6b5d2bef942a9f53cf493e12d8737c6c9ce7d5f80b5a0509b3da687e2e"
    registry: registry.mender.io
    repository: mender-server-enterprise
