auditlogs:
  image:
    tag: main@sha256:1353eb5fe7c2ddbb4e47cf865644e67819ae1051b4760ebc35f54cc22740fee4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:8abf9838160c7cc70efa5790f132a1a6b86a492d46600a2263406abb451ecc06
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:61720e00f638b7823072bc16c598b26db452894ff7ae8b51b1b9d9691b9637ff
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3f7f61b39094341f0e5b5f274cd7a4805e6663c2704e517791eb33f4ca254855
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:76b4a96827b541176fe01416263df47b4e86817589c7acf46fbf5d9cdef15aa2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e8c26ea062694ddbcde5af891bd706f1a568b771845970b9df8803b07ab2eca3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c27c7d5fc294bcc1ce170e0a80a918ae7f6c999ad876c6bb51368a141e281da4
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:86e4836cc657d62fd2c52b255d66e507cf3e49f8dfd455eec72df3c7cd3a0f4d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a667a567220041ab25cc1d3b80c696d48fef0cb5ba6f6dbc498bdaeb6211cb2a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7be7c75d556e0e3ea88c4b533d8f0bcb7e076bcf878e4850fc7a0004d08f906d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6d39b591532d4ce54553e2ede796351f56236e319fab554eabeb3872539a6db0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:477f47a5fd7e3b59a369dea0d5d478d486382b1e70abc41f5fd9c24ebb09c1f1
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:cf3dd2c27ed989300f473a0bad160a10d9fe0b71a68f2476539f0886cd21f785
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:6bdcd750be0fdb753080eb0a6fa0153d7239862812b9cb0eaad6f0c14e79fb15"
    registry: docker.io
    repository: mendersoftware
