auditlogs:
  image:
    tag: main@sha256:d91cedb5bc6c590b52386e4c16c34682c9c4195a1b4973ec69878aeafe07bb95
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6f0793b1748e4953238c16e1c352c454f244c159ae59840f96ad4367a0bbdc32
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:227ecbd3e7a75e098c6421299cb9f627dfe7b3497d66dfe5c70cd29b2a972e56
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c0291122b029d585f26606b8984b16c5f2eb6e8b74bacdbad04f541b1c691703
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7328d8c088a8bab85f4936c7e3e64293b4d99c6f58ee6dac89b964275021eab2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:01a446e1ff50573d02148c9e1ba3225853f7eb1d05096518425618221c371352
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:1cf692be97474342020e595b89188cfc2ee956c4a5343b4e31d9fbb89bac1174
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:458e45a85cb30f5126364c90550de61f26bf2c1e62fc2deb13e2f33e7c04ec6f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:86e20ce010f4bc08f3763bb6a8ac5afc63908b46c5f369a24f1db82bbf69bd05
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:85424442683ad16b22bd405165042019156c391a18b952e49d625f96b8dd75ae
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:73ab11a52dd276e0d371e7e4ee0830ce80f5eb4f9bf5ceed0722dc1bd6dae2fc
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:04cbd9953b930442a70072f734e99e226685f10d0168a47fc273ac9b9d5521c7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:aab9183d3dd6aec4ecd450d32e213d34e6d586130d64c09d928aad4b7b154cc1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:413018cd43d2694d3bbfbc25018a5da0aac96f91b843bcd07e8e7b808bfe25fd"
    registry: docker.io
    repository: mendersoftware
