auditlogs:
  image:
    tag: main@sha256:2c301e217660024fa31976adce14aeb75a2052ddcde6be1114e87fc39bf6100d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:41961679af1d385fb20a0145af2a6164d3a3305d279c8e39d51411151436fa9f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:35bdb6ddf079d7096f7753a8fe28ed341172f8e59d7d816dac3dcc20378eb27e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f95c02be087e8de8ec0a3a22c9a8648f40cbe0ebadf3ca3d7c0a533ed77f98ea
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f4a77958fbd7341c7a3c164e2f0d8b6a8be117bc2bd341fb620a0f6f4c914b8a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a2880a05aa2f2f34bb25b8e2bdb98f1710b2a6eb2afc77fe37fa13ad218d8eb4
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e85e3e578f6ff905a8f0133f94ddbc9f5356e03cd5e2c7e81ffd3996b60b0fe1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ada40be324f60400f8277b63314c6f155bf3b071d70116c67d9cd04aafd6ec1a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:12cfb9516f91e6ddc7dae0c0763ce1335def73da695c4b91aa585a1bb7e4e12a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:59c99d44db4b364fb9ea3ca0b717aa13806cef964f5427e6d9cdab30eeb874cf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9dd666a9a41b3942582f2a7aaae5e2fe3504f8c2be994f02e462ec040a643b64
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:9e8e50f85d41e37164327e4eb51b95abe536622339fbf14f18334404b2ff1047
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:85800e0c988c28312a75e6f688c40309455fc6613f873ecfbca45efc52befd74
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b88de592c771097596cad2898adcaedcb629f553c05ad63048da24f758d0b3e0"
    registry: docker.io
    repository: mendersoftware
