auditlogs:
  image:
    tag: staging_30ef14b41e93112296a60b254dbe173a03d05f3d
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_04ea477e80d233e09e8a59406a513cc071758d85
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_577f67b1a50ae315ad806dac56057d439b1768d9
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_cefd1ece55f7aff4d32d9f57fc485a84ba7387e1
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_325a5afd0020bf7333338699789c39c16f3b5ab3
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_92aaa95434687a01ed4450a9d1e79aa6803a836f
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_d8ad3ee94dd5c4ab8678fdd4cb7b7aa3486cb880
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_92382ad5f8bc0caf2984139f4c8aea9ef3d2f7e6
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_07ab86e98a67280af2c1b5d54f9983a033ac9ce1
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_b3d893efd72215a3f480940181de981b72f16908
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_506fe908ecd9f6f2fb50ac0dd98b5e54b6a1fbe9
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_e6b259372d7f217984a47864374cde46dd096bf5
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_415a8e4bbcd489897df41728f090af668d661a05
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_a408616743bc97e5f8d5c81a426193b4b71d9033
    registry: mendersoftware
    repository: gui
