auditlogs:
  image:
    tag: main@sha256:d50fa8e4aaad91d8323b7493dfe04370489d3c6878a99a5f98dd019148995066
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:c2a9c915895101181e75ab9932be15f8a846c6015b7ac36e2dcdcc1012cc6e39
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:54b701c31970d0848e074a353c832b3be9665e89ba6c003a287057feef83d3de
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ac77067e736408945d27901eef9ac13e251b90b13159e97fe385d52ee7481f09
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1a354ebb1a602d8c3522bb2ce38e6f9425954a8f9a070e6152a3864dee688062
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5d63bdaae4a53948f7a158bd8a30c2c156b376e230ce7c375817a4de9098d16d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:66e28b63698855b3d85dd0568fb3227a3faef407c421be67d96ccccf01bfab2f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4ab2a8c13600c51ecdc7e872969a1a3b61c4ed214b226f60fc84f1f733d79249
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d69854c4695a0233f0856f1d72b2ef12b9cec41475e585dcf3737a4bf2faafce
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:76e932d4f4a3686744d1bb9913d5fbe4503d02fca250040e20ce34f9013ef3e0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9e6c5bdf6f2dfc42a9f2cb666fcfaef18119bf3d32c4949a858cbe4dec15c2a5
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:97061e2b178d7e08175c4851115667a66bdbe073b0c95208653b730a7b3919d5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:83ea36ef04584ea20b310fd0cfe5fe99d98c8f3b5e90e01bdbd1dceb6f244016
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:49ad5a827b2fef7ea46cb7059c7805dd8dd91d4cecb663866c3086936ed6a769"
    registry: registry.mender.io
    repository: mender-server-enterprise
