auditlogs:
  image:
    tag: main@sha256:e8e51ca35f4a583b9b1389da57ddd1ddece9ead4291dc62f32c8a1ccda2c1266
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7cdc3f3ad473fdbb46dd926009524e60cbdf83581a2bc4423dbe54a53359743d
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1a78cf5c460966cae69cef27eae8c40b308cf528626a4c0ae9b838b18ce6cc56
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9d0e02441cf9db4c35bbeb31b10a685ffadc26283a0e6e04c7f07027aab0b664
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:075734e6290ef6afe22e46048f132c954b510a8dd1292e88756f11232fa5e4cf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:66c69025ee78934ca055bdf693334a24b961d22e51638e2ae4e55897faeba9d7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:911550f237f17aee4d6eed630e4c860c80371c3b529f7aa8438d004b5d099bf5
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:efc12b259b2424be6ed5d221589395b1b899c22166528fb16017b7da8ed3bcc2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:286860dd5365c64e03b49a14f9a29adaa9336702f1faedf069a7201b900a7973
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:37c1d90f5bd20a810fd6aeffa7b6be4ee97f6975f3be6b24c48f9e0a728adfa1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:4671c61c1e5e71705b510a6cee259dbee50574d5452725ca677892e91581a4b6
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a727053a9389547adb6033883a9dfae99d040def10e249be6616f5d790399c7b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f435eb6e02659d29841d09c86f10427b801b23eea5626a509db95cac0af5250a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8aa2db6ce2e721a9d34d4347c4137284f114396f71b5288213b45ed4007780fc"
    registry: registry.mender.io
    repository: mender-server-enterprise
