auditlogs:
  image:
    tag: staging_a3d45bf02b189dce509872419b5266e77c53d526
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_e68a3e33fdc358b05ee9179835938d3ce5a08fee
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_48ff767a6b181e49332e0ce6213ef81328da478a
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_6ed128633cbbd0105eb7932ae89b387c8a6fef61
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_fa6db36949d5b92c7ae5212ba010fe11dfe9e84b
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_7e19cd16749a2c8922085362391b3bc526675249
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_165dd2923f6d01f5a1289cba7ef9c2edfb60d715
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_dcfe313dcb921837fcce305506e085e71c407d69
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_8d2aacda036f936445d6bc4ab39537f43a019886
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_51f6015f45242e7312bbfe780fdbf11c9eef7b4f
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_5d0bbb3cde82cc01c4afa712156c29a33a216228
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_8a1ebd2772f0ba1f06a8f916db68db3c6eef7947
    registry: mendersoftware
    repository: iot-manager
