auditlogs:
  image:
    tag: main@sha256:1aa4c700071f64769aa276fff7274a71c8950a5ad34ec160a40a0cc91e50658a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e39ea10f45b64ab7be1eed6545210648252b2c8a8ce8a7f32acd6a9d01aec1dd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:b92210a66226d8d748659331bc3e4d63fe0cab06aa90ab0a3a19aa3ec8ef98b3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:48afe6d0dbb7a9114d02e03419dac8410db664d5de14866caca0ae690cde8930
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:fa9377a78be6e55a491b53eccbcb2a496564b78fedc4c0925e39af5a138579d1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:215e1b3391c29233933fa5faf15cf68a80fcddf55918eb6af0a65f34cf006b9b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:32c43bc9ff9d025084499a9ea1137bb194cc8b2e711863804d34d64351d22ae5
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:86e3ea8486c2a4171a868e19522d492b027f5f1da4c2f95632fbf316514a7dbe
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:710252bceb22aa7b6a1c464b74fd8467e38580482f96f035804e816006b50a96
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5e57df8c2ef98ece91a22aec4ac3b8aea4ec8dc8c4ea285b983ea24b15036780
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b2363f1cf5a2df7740bff734c74d6ca034e0bbd92aa0f1c49f3a7121e603023f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:346e165049b9542efad192868078706c45ebacbb4f0c36e41f0ccbb561f57df1
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8f738f4490e03160c2763afaf40b3a42ea5ca4a64a23bc20d6eeffe9255ff9fb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:10dbfdd3205be6c7f489c2e6f447ed86985a2ae006b718467a6bb9b0911e7682"
    registry: registry.mender.io
    repository: mender-server-enterprise
