auditlogs:
  image:
    tag: main@sha256:ccec2e7641039d91be3d72ac18b7b17a21341636b74b6c4dbae3fb9999854865
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:c69f28037bc7ab167f4ca01eb9d7d045c5165fe875a01aaeb48027a139c8da4f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:16bfdf7474842927ed646846c194e37406cddb3baf16fc25797f950c45830e58
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2506086276f602afcf45de9376aa15cfdd3964ca5336f692155d083ff7a864da
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:edaa0c329fb266902d55d91596d0dc651e805b2079d61691fdbade350d15be76
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:23b15f0577a44f6ccae7964bb6766caa184048e595540139d8d8a3961612e286
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0b24cc8c894fe8c9fdd560e7575856b3823c331fe880c765cc7798e62ad27a3d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5b363e7a7576b4c141e587be624e4a4a4dbbfafaafd46f809b2c2fcc2be10b2f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:bcb4a1a18edd6f5e9d97450398176624f4ed8eab2f380a60e42b1c21edfd1314
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8ebb26131572acd65c14bd3080373df791b47a369e67183991dcda4027c7932d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:65e0ad634584bad06c587fd180954364bbeee8580423134ba9d7b335044fba9c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:12d359112ae976cee63ba10e0300460589e5c04049d8fa188dcb46e78bc9437f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:706169e1b0b6e098de0634e1f26000ce4a73b891c1ea5a9bed44c52224b8b063
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:13d66103f525e67cdd2a9e1d3cd10517a927632b2a55be334146bdc28c589e58"
    registry: registry.mender.io
    repository: mender-server-enterprise
