auditlogs:
  image:
    tag: main@sha256:943133fc4ac50e0af12e3250ed82a6f02161e1b43ba75e81d9f58004d6d9ae96
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f0dd5752acd11103b9fbe24cc81025a8f40de916491e6d4f1774baf40e521595
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:52e6a16e5eb6af5d796fb60e87182892dcd666ff223074b5a41ab8f6422327af
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ca7282642a08a0e45d198475e8c512ccdfd5841d243ed5b0931381507ee330b7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7032ea1f5b619dbbccad44052708240c07dbe9a0f8db439e0db3f73835a6e81f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7f2e3ff78cca7ec2031a572c300d8ee48b1abeeccd1d3d8e439f8df2f43f9d5b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b8705c9902e48734280971456d9493e67e875cbfbbce26c71b40c139ad684ed0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:26d400bc505b3c61453b787cc728a27c3d9caec99dd5f24ef256a872a81eeb86
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:acdd2dce1fe097692c548399eff8048eeef292229c49f0fe6e9bb3f9df8047e8
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c45df1f5faac4dba70dad8b8e55e610bde9942ae8bc6a727997a21bc1bea4aac
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:cd25e175a50521afb44422aa329dfefe7c183cb9185ee9256ea7d340beff2456
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a65f77f3f96fc65584f9e2032e69eb136cf8914b64bb57f2ff5053699f028706
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c66cc09ec60dec7fabe8308146e9f49abc9508c9932684fb1309e812677cdbf0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:5b87ced776b925d48f2d82b72ac6ff103a8831b764dfd2f58bffabfa4b8e3cc7"
    registry: registry.mender.io
    repository: mender-server-enterprise
