auditlogs:
  image:
    tag: main@sha256:0cca9d957932850ee95807064660da4b0197262370f7ce4d42075c95e625910b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d3bce31303082ac689c85f81cf165f4f28e843bb79bb79588ac2dbfa6e6af4fb
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a49f650a9d1fcac76fca79fe2bbdcfd7c9141714e567078fea39c0e39451a2fc
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:a5b8e1cdb44dc1504bbbf27fc702670f089b28f76e00010d70e3b4108b9f5df0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5a14555183f30c92f45c40e1e80a508229bc3f7def18b429dbe60dd0d956ed20
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:33623f692a41931ba9999cf5e26cbd4a8637bee9be8b2d244b895cc554b971e8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:99e9380ccf7e73171d01fd645ea907fab81b3c60ab06e91d57a5b7d35e53b380
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ad62cbde27e4b5e92b5a5a62c2aed3de3ae4cfd32007cf725f5e11b1dc6f4542
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b74b83736cca9c6c4acffd45fd34aa37259b64b872a0b9befe9498123ef6772a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b4b6198584687f6a94355bb78f4ca01bf4fbd433c103ef4f9a4422f1a2dae271
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:113dd089f90fa9dbccdf6bbf33d397c00db00fd9de808872e1870740f61c675b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c0ec72e23190e46ed8f7606ddfb69476233aeedaafc8b578c50dd1b2a0461c5c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1cd491a54a3ef8ad12521aecb37ffc126007d4b675e48ad6d5f5070d6775e59e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2c4c24d051943b27df833fbf93b36540302281d5fd4c98fbaa6036b4f7850532"
    registry: registry.mender.io
    repository: mender-server-enterprise
