auditlogs:
  image:
    tag: main@sha256:75e66fc620bd1154880fb9ef28a2ed14f062444f19760a5ffae9ea1746890cc5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:aa998ea6a78709f51310060c96d7458e76cc2770e0a6dc9eaca29195b6561ede
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:093876c074b11bc6e138291e5fff543a244349c267eaf4f5f57b9e92bd6b7ca6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:811ed13293886df1a905f020c764553550e456be7f003f47dd62d9361eebd847
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:322c3049312136c7dc20f9f7a84e97142cb53dab10293e2120c1c6f33a5272ea
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a0849df9cfdad51d08281b99102e794b0401b5e37f5d13b72b063e4edb28dd1b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:dc45e800889f35eb7476efa6e8a7070394ae73c2aaea26fb32d1d73433d60a41
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:758a85204b16325d55ae4b67e4c1160a6da3abc7f59f146cfa3a6cb05fd852b4
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2e50aef4885b91f8112c3d24643ea8ebe381f4b240502786c67730bef99c0ff2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b6233a154966f2c45ec37ec82b9923970d13cc50c1a8509707cae0d9e663bf80
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:3d5c012d87d80fe01d9ad92840389281a03da5a517bed8b91623541c8196728a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7e095df95cb4b08487a11c5e320b0a5205266833cc4ca46e7b494f1fe804b5be
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:de303618192fa3591b4e6fdf5f2950ca6d2b0875385c446a3a40f185d1e3d80a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8e0add6bd07cf40dc9f54f040d659ab280171731c1b3cb43f90c865048997e62"
    registry: docker.io
    repository: mendersoftware
