auditlogs:
  image:
    tag: main@sha256:4ef215409e57ba89328fb5690fa15cd4ee144e9a4fc051eedaec3b040b44396f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:95ff49a1194435894bd169b2b14b5e8980f2ba18daa5f1df287d2d7b8bdffe64
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5868fbccd8d5abdf1e5d0059e6409adb68f3beca3331378f76938d3b2a6142a3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7955e383beaf83a71b078844d039d20689b496037f5b22e364b7b2ee0e2c24a3
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5599c08e06fe3b9af93e7bc3715ac6890899726a31f1112db8b86fa7e7e73cbf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:37f81ea588e3aed781c851bcf5b627150e6ef1f61885d809ec89633aa9d62148
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:015803e332051de705333f4b28e778d21efbab4f8f37d9c00a556aa02badbcc5
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:61bc0b244d4a6be525aed1114ab9b60aabd17050abb13b326425f9d5eba17b77
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c32da8f4d0e4e27b36606f9eefc866fdb1b93ea7afacedac3ac203bb746042f3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e17b7e24006fdd3f5d32d8a4beb478529b54fb445b3c275ff085b653d2ca3843
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e616ec17150aab30d556696e8c88a0cc4a7158c8a6906cc95d26a8706ffbb0eb
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:772a740ab22fb86b00acaaa2986e719a898c2347bb069cde5634ee41a9fc07e8
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:fd45be5a8afe73e769495547c7158bfb46326ea5b571ce5da6ac2f5e33b7a8cc
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:fe4118a464d08e2fe1989bc7ab491c7f4bc5a8904ce1d73c48a9da83d724f34f"
    registry: docker.io
    repository: mendersoftware
