auditlogs:
  image:
    tag: main@sha256:97364502d2dec403f02eb1c68c8b6638dfcd17463b9dc8112ec2b323d14c619f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:981f1267fa6dc483ba3c2490ad5dca2831ed2a0a61760b872aac5cceaf52daa2
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f954593685595d056e1377d32bb7aab153145c70e5b218252733aaf1e301f526
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:80f9e35d45f31d3b64b95f5afb27375327dbc4760e5123fd4f321fa50ec499c4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4c7a2614581ef7aed71bad5e9fd3f4316a64b73e826715eab7b0bd94920d7224
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f27e359583242f423120ad6d69dafe89ea672cec41b0239d886271eda1d649a6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5b4ffaf05b9e0fbbf223fb1c557713a3ae4b7e4539ba5a97026e3c4db2897836
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:25ce5833edfe9b3f3a276ad64cb9802345e712abd2cc929cd596ab4959445ba7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b3bed213518905496760548811feddbc7579a9cb9317502c8c684d2be0f2076d
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4fcbd7cf990d1bf030dfd42e3d591b4f297c8da5ea2b8e1d2a9e23f360ceeb5b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:33830baf7a595b15fae2adc60615d33664185f71e84773a43892230b4b308adb
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:001d0adddf865b1bcb7d861eb974dc222b3f1349c5acc8499c9ea3671804088c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a9434c67bd6f507068805aef0f4ec7902c63579f266e5f33f78e474d3ad9145b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0efe8add44c67ffbfa9aad48c453c4903e766d7e0150ab3bc0277477ec0ac106"
    registry: docker.io
    repository: mendersoftware
