auditlogs:
  image:
    tag: main@sha256:01b6b305cd2dc2330891277e2dcaa34ddf5eba482efc723f3e50a81f3ff8741c
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d4579d85dd567e9312eef146e7df054f85520f5f543811dea2511b280863f6c4
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:498d49d8375e1b0cd30779cd3e15421a0c4969a1180f860e7301dfb10b7f8fa5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b524b6fbc217495af55b80df733bf06d17d200482f2fcfaec796ad5155a9ad0f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ace1ee6cee743714d8e338914f16869793c67239ef06b903a464fe8df4eadba0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:afe22bce801a19580dcdab5513ffb7e659b3639d5cc3f4f509b8ee75d82b83ef
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:74f1931332e8abe75a08eb77f76b55966316efa44090054840a43feed116173d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3d938fba32f17c1d555d422323c254d4b6750a1f7d39ac4ba092398aefbf5e5c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:792c2b8c6b4eac2ad1488c451499ba76388aa386905681847871d421d2a2429f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0b6a4e21c2b96fc410b8cc721f9462d22dbc18f25ded6ecd996fcf8cb7776397
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d922f891959258bc07673d9a4d8f2b777357de2a4d0598240e30f5e615c49fbf
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f1844b32f83427e8d164f87de62e7fbc6909983eadad383d5b8f0b5f02c1b359
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c9cb4fcbf2361e6f22427c49393eec9a8280541524c24b9a6ae6b98cc4ba929b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:5a1b2e565e6c59befd4646f2baa64f721891db9f8f5423e006322f1e09f80adf"
    registry: docker.io
    repository: mendersoftware
