auditlogs:
  image:
    tag: main@sha256:f4096720999905341dce93956eca958c7efe0bd32d761bc24bd62d5da07614e4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:77accbd0ce2c9c005233ff1b0989936a6826abc95ebf13c410597e958a6ad004
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1158e3ff88beaedfdc23b73ab416fe467f73f87515c4a0130749912696b6c762
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:81b14447f921f3d421638a5c2f346d5f15afda73e5748c6cc6da6811a8df6212
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:90c9ad183b4f3dbdc208e1315e59cd296dcee37b357f0b14e7ba3e0a794cf543
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:77789e33b0847c76813d0e9634e2763c2084ba7387dfc54d804eff033490aee5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8bd7dd667c41c99e2e467b714b8272a79863dd2a74b9770f896e2de4f51111b1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1df6e48be6ee9ed18ba77aa01b5f7949856abd84ce592f6e4efffe96495081ed
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:239e54caa56f7e5389142d69cd4d33a707f08596acc46413bcff06dedfb766a3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:df6258dd7f129dde33059bb1e052e67eaf298d2ff54adf5ec0f7c91f84c96abd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:959bb932a0d1a0cc8169c143b5d39fb42431da7c55234162ddbe555b3c7fcfef
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:6174fd8b85c6dd5b9a9a8a286e2a01a6feea43d52eb1f3ac8fb85de47c0ab107
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3315a8c6134f6cc7176f292657565d35531913ebe8533ce49da4013981273728
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c8d403bd726757a0d4769a526a51dd405c2faceb451a108255f2aadeb2048281"
    registry: registry.mender.io
    repository: mender-server-enterprise
