auditlogs:
  image:
    tag: main@sha256:011c8b224867caab964435fff51694439575ed7e84274086ca5d7b161b1e900a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:cb91ac033b981ec5bae2c4e2c2e18bd5187cca041b86357ff262c96de73e2909
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2c8b8f9f8ee29b1dbd464c61880f6472f81f9e0bc5e13da58eab6fa04cbb7a0f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ad0df4e9a6d1607c124041b49f3ff508f283ced8be9a1b4b42049789ffaa8aad
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4fbfc480a265cb24da9185198074051a186801e3decf4274c5ab5a5c33d0ae7b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4d52d18f8ed9e22341d65766c61f7244435e1fb47f4ba43cffba1e008ebdaa58
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:09e98f02fd6e82eb990110dcf954646bf13c9ac3cdaeeedc9f8c3e611152e6dc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:6ec3270d2354bef188ecc74cdd296994b6451bed69bae9cbd22267404b16ca9e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:272a0efa8864204f01f977b197d2331b30ce21b55e5c2cf5646df56b2b6e96fd
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:39718cb20467ae8a71d13bbe8a6ee693b78469841f79a580f3a3a4378e4f0c2a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f936beda9ba0fc15ab09a8249d83482977d2f62844af0f2a33271aec6158bc33
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:70f3d69623187635896cf37740a08327bf16f43d1c2859c866ccc7aa17514fc0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:fb9b1670ac5b63a69a5afe3a4104f99be46447b8d2c8d9d8fb9793620710d131
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1cae7cde9d60578c1543d5f15898b411b87c6cc5dd9c525773bc56da7765ae3c"
    registry: registry.mender.io
    repository: mender-server-enterprise
