auditlogs:
  image:
    tag: main@sha256:adf9ab6d67613ceb264df6179824c5fbb6b0173d71c7bc1aca73a65024047f1c
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7a93d96d236dbbadf3054c299a461c0ebe0c9b24d82435851ee03796d92fc68e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0ddc91345933e04c1b5cf505ec26d9b004f4b039b587ebf60b1f562608b3e1c6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:21938209e8a984eab841a5553a93de2d692c38d91651ff39f56b0eacd8a5da76
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e42c7cf526c6216f290d22e5dd8f620a0856e3d06a99d4317637043cce7ec98d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:27840b7072876312c79013d7aeb6e7b509b5dbed003f200bfdc5bbfa354c1968
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:58dfb188102fa3c1839d9ae6b3b4d8df30a0de3cb4627428c1ba06c5bd05b28b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:38929956cf09ee03e7ff14ac1534446b191e9f76facb3d8ac18e2fbe6623270b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ebe9de128c98b823b6c71eafed0c1af1b0fba8304109204b83734da3eca04a83
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c9f23c2a2e57a0593f92d8b2828eec236a038393166431713f5c90d959f76621
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b0ee8d014a9b53ea171cd77bd63853d623b4cc59162ac04092968a10304c47b1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:5adedee01cf250b373cbbfad5c6405c76cd112043a9adc3870876204c9a664a8
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:339f9f7252aad30debdfa34723d8f58243824c7f27aa6092fc0092fc4b294733
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:96d088a4cf4f6e447d26494f004f1cbadc6151b17be76ab6204f06f36149fae8"
    registry: docker.io
    repository: mendersoftware
