auditlogs:
  image:
    tag: main@sha256:34a64252d2cb0a9362975fb2e79ca77275e3396fa3b3d0e714f9f0972eb64204
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2a3fd85266e7b136608e3e90875410e385e8c38341522f296d71728a5039a783
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:cb23d821c1bed5b94a8c05ef56e40c22a9e654d961be57338ca2f54b9527b9a8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:88b64acf5055eee2aad4efd50172a76cb86a9956f3edac7d6ac289ac23e6dacd
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d018cce870824015de8dd17b82e558c6b6f2084bb81bb6bb09319ee6741d5b3b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:787cc5501d17c51d7757ec0df11ad9464961436261af72c7999074d8a461b39a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e5564c17ff5b9d9ac82c889df9e9bd6277a8c053eeea51540a808093c1010a79
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:befed87e15b51c1a5bb803b9344790bf48012edf717127bf5b4a170772ad2b61
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8a5f42fe09fe57a107f2d39940551a65c8e5e593eb1f16408e747dea09f58f14
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4d178902207c4d3742848922c723d4b5e63c2606d5f63c4574f7688f6b24a792
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:91af04e33d7fbe55b3915ea3f5edaf42aff88ad5551b0c214e0dee0472cb9b4b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:5bf60a890c6e92c514063e0c934cee7b612c21b496642ab2e5b645eba40a5867
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f234e56a5993d3deb6ed5fba9000498b452ea4cf1cfd71eab2c9793b56558739
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c8389a11d71dac1ae13879b5035dc562fd31722e3bf50d49112f0fc481d4a158"
    registry: registry.mender.io
    repository: mender-server-enterprise
