auditlogs:
  image:
    tag: main@sha256:10b986faa93f9cf000c97698c43bade4903449835b0ffea9578215023ee98b0f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:8133b15c6db2585127b5228468273722ffe19e5fa3f1cd59cdb920e3c20ae8fd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1da7693405804f02f89338a2588edcaebaa6b2d1dcd3063bf093ba71bdfdc94e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:432fc0d11ba4a0a460ff3060b1c9487edceb914398e9cbb4241d71246053a28b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:0466acd70010a2b978805246e77f641a90c41132f0b784a67a2f6359afeeea50
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a029f75fe8beb6445052d0a925e7abbe3e4f53d5b6124cb358633cc8e7680eff
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d92ad36b15a3e54f166b58a332960a1da06c9e358987156f22f5f5141b59fd30
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4a8f4195d1124588ccd0d07265cd4784757de54b91b9960a9ad996349f3f213a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:5ce57b6da835402d347f0175a380cf8aaa2f63f7bc13649b2a48f1b46772fe26
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:01e69470df0a3876d73b2cf83eb063323973f8c3ff7ac916f8a393f0632fddea
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ad2da7e1a0fb4efe61634c181bf78078d9fd37140dc4733cdb6abf0caa5b229e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e6c59f7ad114f5c01075a962cb82ee8a57040959cf91519007f3f06909317e62
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:54f70da2a05f1956a5ee69cc1bc922caa73a58ed171fbd5e1bf02aed200b487c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0e5136a94da5fd8310281ecfa615afeaf979df95a84af2263d9e8fecf7ac1ba9"
    registry: registry.mender.io
    repository: mender-server-enterprise
