auditlogs:
  image:
    tag: main@sha256:d2804b6cec8ddf57ee71b4b8e8b2a01fb7fabf26f7f6e0d96c37eb1c49da04fa
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:0d96ae9a256641bcc16ee9813d448c3423950fd06dd154b970459c6dc7d30f6f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2cc3e78ab066ad77948cea7856050a0b9969c0fa69d52cc698ac6fe896a6ecc3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:5ea42cc164a054dae69d834a8ff56f8ee3058f7006e6c0c83598a0d58313d47f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d8d498d3ba6712d7e42f1acb44be5b6638f4eb219970a1638024705c063aa4d3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e070f16ed02ca07b0e95630135fb03b277f9a5bf735b86292e6e7b552bf4f1e5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5fce7a55face562b489d421337bebda7f616cb4a55824a63104f632bcc5649dd
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a00976efb63b46fff488d4199e50d44cfa235f994e912e11203c45e6666a482b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:7f3a8b9f06f47ceed26261643b62c611093772655d8076cd6d14a65e733896bb
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:bfdae100d1acf88d093721326b4b936b1de3f796bf4694f894ce0ec1307c9cb8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c33e5450fc60076a439d6e6ce684d17db639f7bc9aa97867031d59e7804a625b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:82742596b1c958a630f0019085621a8f558f2e609f94189c7089fbf6bef0f251
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8f1fd2410fd8c143e8827b40dd7dd20416b9ed590547da153d08bb223a17d758
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:26b60fdd4e98e56db6a4d29f49e0dfcf2a52f7771f5bad48ca95e3832e817c98"
    registry: registry.mender.io
    repository: mender-server-enterprise
