auditlogs:
  image:
    tag: main@sha256:f9c192bd9e212317ccb8a0afa1f5b4da15762eb6ea7f524b1b373a7c3138397b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:863ef373efea41b0223f41550d10757ba0befdd0d8106a1cf15eb27875d83686
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:e8d05bdc4291a88eb9d5986ef56ca7b5eabbcef837c5e3ba59457ac5a0144868
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2c952d28651bf355c0230f9657df55c22df8d6960aca5365653e5410854437b8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ec145c88aaafd6f72374386819c1cc3297d87891792b62b52afce67e900dc271
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:84f044b2cac8ab90f43295318acbc12a756d3e5c8daa6bc468d2de193d85e1f5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9064d99ee51a732b609c5dc2520f217a3c8a527559c34cd5a8abea30e064e4a6
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:62042c3ee025876cfb7fcd486ca6d0570a0309eced26b457d902827a6b772919
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:39d9a7b0394caaa4f4b2e6590995ecded9d3aa185701882a7e0397043f8524c4
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1b8a53a55477ef572b7cc624973094149ba32ead235d6ab917ef27cf940cccd3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:5e62f38e0f4b1e19601e94fad4643b96d8ac21cd5ea175ac05297bba88c8e01d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:2e223b7a0ec966201c43f35b3222030c33eef8770a6be0952b124a6b51b5a9f5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:7354cb03fc440ce002ed9bb766be7c96ffdaa72cd8f67cbcdcd9af4ab5f2fe18
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4f0680da3ac4b4df935605c2157f87c594e452dee4acb6df58074384bc933fcf"
    registry: registry.mender.io
    repository: mender-server-enterprise
