auditlogs:
  image:
    tag: main@sha256:3c85469929c10d8e3e76f30521d59bedff2a3ef67f2923ded5cf9297b3b23b30
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e6437f36e6684be9f765a31a1666394edd519fd3c74fcfe9f5d53116dcad8263
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ed9e9579401b776a5863157ddfdcdf69d88a51f798fe6aba6cd995979c1104c1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:15cf3148f54601b7d9b4883abac9936ccb102aff8027c47be5bff3130b2ae28d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:16e7b14cdc94b6b0eba1ed6cfad78deb9ac537744c39252c15bb5431ae2dd5aa
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b6e8f54e23aa5337980f92ac5ab78e0865a5ed4338b3faed72e68767af7fcc55
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a8d9ba3f75031b93dca622794b7cb9ad2d00525883f8650b8a42ecf6e0e4cf75
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d4d7ccdef3cb30d08df36907bb264a07d622ecab80f8e84e990348b2c49e6e13
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0248783dc0763589710df8127dbdd44c488bd11c96fbc06c0e56130f1cee68f0
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3821ec07afaa7b801dd5a4a8a06ea394a8877cf133394167291075dd9812bc7c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:4461a764a71c695ab5dfce5a7304bcd3cc0dfb4568ba5ae3b8b8b5da755d1a89
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:5c3b6588a7c997f6411f96ddd5811e67a13a11518957f62658dac188621882f2
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:97f4276aaac1540ff310ae4ba46076d177483415a570dd79ed62a42e858979cb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:22bb3bca9ff95835424eb0a25b5e78393248bb7c23a1e6e3aac680f8fe59ee39"
    registry: registry.mender.io
    repository: mender-server-enterprise
