auditlogs:
  image:
    tag: main@sha256:aa11da457aaf524ac2c3dbe99852fd071e376e5d29272a80d661ccac76b5d271
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2dc4cd9103a0899d687996cf6c504766d7367a939eceb67e548a2e0dd08ac89c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5b36f6d93175eba17f246c5fd6d6543f376efafb8d6eebc485d52cf0e0df17fe
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:332f2beceb61efee8cb9db0b196b365ec43f4395e4302c74dfa8718da27dc15b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f752e5b6b5ef504edf7455a83dea8233643a32f23b0bc6eea1b7ee3b85f6848d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ac4390c701fc3d759d775ce6b444937cdaf2d108ac14dd4a0931bbd487743695
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ed6e97f782b5881bcbf7ee40bd8ed1bbafd399910e7b68c4188190096f6ac955
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1489f5bccd22d7eab453ddd0ea5bfa74251724e4039597919efed3b6d6fcaa43
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:eff365a859f2ae2ccf7a71c1e0794f0e72a6220afaa608c846c1e66ada139315
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4534739a217db5837043d280ad9f80345adb572f7f12baaba9fbc9327fed6b0d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:02f5b077d400c7d410eaa8fcc42a9eb325db2b632390af28c66b9f5e86a36102
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e98d225c9095679dcfeaaca8f49f7fa98ac730620dd64e6a3805cb59aaa20073
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:847c4c58137800ba9dd2f7b41f0176fb1b4b28c2033c3c6ef0a9846db58a1cdb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:163ad1805a92128f7132461c2fcc8c4e96bb1aff5de7b04f9c3b5eafecfeaf41"
    registry: registry.mender.io
    repository: mender-server-enterprise
