auditlogs:
  image:
    tag: main@sha256:21c8f9b369dc28027917578a3e6840a1bce89a653d584ab027df45e48ef45fe7
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:666b0ce831d71d167951e7b39ee9a39de0d77e59ba9803218996598339e8b52f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8194f244ecf7899fcef613739ff96f2bf415b16556c59690d0c5224ee90baeda
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b08e990ed9ede204346bfda63d33f2c10cc23a0f8a4cbe7b069493496ad7800c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:124b1a7de48bf5b4fb2b34fe317bdf57fdbae3ef8cc39949955c2b4a33e2b1f4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b81af8f6cf6ff66482219ac6d0ccbe6d460ab75ab65a3ae614db8fd986e50808
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a511af270b556f401b24962b30105d37d085ee97f9861b24d8d302b20d8c3c2c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0666e2e353527e64a8bfacaa995f5b6c8272a10306ff81f2ee58899b799e9dae
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ba5124e53b9c97da0d6068f418c8e107bf3de21764be44fc883bb7027a012a92
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:15670cb087f9b7156aa4201fb93771385b1d566763c91b6b79b6c197bd0216c7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:4016cb7f8112f839223a80ac646d83a3a66bae56a70fb974056a2a0b6fc8567c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7862fa9d6bf54eef53595e0b00bcdc43dc4516cf2eb4d964fe6e6346edc166e8
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1259d0025c4f327a7f81eced4c1cb41224a0d9f55f025a20cd795eae949d5eff
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3f516930520c93a2af81f1d2efe6a827c0a0da98861684ba320a4ad2479792f3"
    registry: docker.io
    repository: mendersoftware
