auditlogs:
  image:
    tag: main@sha256:938f6c73e540a3b630a112edf8a58308bf3cca752b4521fda7a02be1e8a2a156
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:8b9482e6a473dc7ee08f8e95d26a87587b7550a16aa2d5ff4ed5a94fcea58e90
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:23dde2baae14c1f96dc5300b4d74e87d8a16c4c3d098b00062d999c6ee6a8e91
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:dd92b058adb34a961fdf5acf024a9110cd758362e8cbc2bc6af4d4785aac1207
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f3b99f76662dd7662ffd6a473eba27ddf2b43f17ad336d1d274b4fd74353197e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7010ae73d1c51f369106adcb5fd5c59df9fc3388f3305149dab97665524047e8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:af93b6776f289670f14d6b6e77c6c1a0d0bc03ba730f626ebdf31408ec126932
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:89775d8bb0ef090bf5c87090dff0cf573ff58cf36df47988c32bdf67bad6e7e6
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0378c653bded1777e822f2f2fefb0dc0d56c9397b101dfc31798d5e0fb1f355f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8293dd81d220bfc7ac9621d175d3240d339e67306f4437417574b5922d5e7dc7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1f159b1fc291f1387835f5fd37a47eb1a8a30a98b938641cf99c297a6919ab18
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:dfda131d509b248030494a1c17e3067ba268970b24abc942f24aa34aea3e7b90
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:694c7ec4e1f0b7b77de4fd51a165d64f0d6cb12c05b99523bb9a01c8ac9bbb6f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:966ff33181fd8aec1a62bdc9c6f970b73da578e63ae96731ae4f4d7e8202e298"
    registry: registry.mender.io
    repository: mender-server-enterprise
