auditlogs:
  image:
    tag: main@sha256:332f62c7e3493f3cdbd4b7923d9565b86720e13dcd897a2b3efb69a5971a24fd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:82f446fe8b29e8ded4dc2cc849b43d8aded16cef2c7f609f7ecb5236d6ab3e54
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:d55f4d1a7e331afc9cd62ac260b92d9e7fb03a2fef309918cc45eb8735c94213
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:15bd9f36b5739a0c79ddd2c64ca84d13da554e15a003b081df16c24fcc51042b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:0b884a511f82fe421face0f7248e06548b7b612440186c639be991f5df9bb046
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2b3b4e2a7953ca89895844e15a69093ed406e069fe139b2bfb912ca928db9c8f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:7d771adbbac14e55140c5457e78790b55e63c3d5539d1c2c623196086b1ca7da
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1a5ef1072a481e5a4595cc19e86690380d09cb5017f4a1cfd3499ce3307646cd
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:79dd89ce0c472b4de1d1589d9dd8ab9a2e86e70f26f2f12ad72af96f33e7a83a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8e4813c6dfceafa7657d3a01890ad0cf135fa07cd67a23a7f5d42f7d8c4c2ea8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:4ff9b67da6dc0f88d6eb7b448ce14d90608f529322f1dc82398a758e0a3f5da0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:661ddbbcf1c5c23a28ab755fc2e0a28443700bdcd16fdc1505a858c4aa0fc942
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:7041a828c4cc33a85b03e0d8f7592db043fc4525e5a65befb75d387336c7f80d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:00a6b8e2bcffffe724daae00e5ee647a93a3551fa27981de9ab30b4618f5f581"
    registry: registry.mender.io
    repository: mender-server-enterprise
