auditlogs:
  image:
    tag: main@sha256:dbbae03fc2ed8fa41136e312e00b3ebc52d674f5fc91416d9eeab08a18cb91d9
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:51535a38c7e6d5d6358b9a8c26e39e28e4889b1cfa5c35294a78b9b268d2a512
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:92e7d5cccfb362d534e288e932759d754136554ceec7d585c7d2cb0da3c9e0d8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c164467c34d357e46ad76460260621c0de7934d9a144b7c62d67de49227224e4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:96b68e152cd2124ed6e456ddea7a556691d3d1f74b2c59cc1ecdc009e9240121
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:41a73a9ce38a30bb88ec9a240627ae59afb4a814c965d86b4a5b4d2a79500572
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4d08d208c3d839e779a3b197b3db03ca4b2247d74444ab0fdf62ad607bf3d342
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b474ab1c29cdfc987d3fd932b485fd89177c769b32d0e52ecc41f65080f7ba53
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:5c79e5f9ad5394b7eef3badbb86c681ba9dce6b6222ae885e869246ff36d3263
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1a572a42582532856788f94ab6c6a9d6612d0bd1b22eadff55c61a9db09c25c3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:8b96b30d8511855f6fa6e57d73a51720778462ff30d4fd566c6e4ce5b825233f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:572352bedd5dddf7c600c274961de5780f647935e6047a44ee64cc7b33bdcea7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d66abf23325f6d7d26230aac55c37dff3b377bb715ac48444650fdcf4ce253b1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0aa024b1d7aafb651c84f474b69ed7d485051fb43d8ee158d352898e07971e85"
    registry: registry.mender.io
    repository: mender-server-enterprise
