auditlogs:
  image:
    tag: main@sha256:6f8faad5f08c0b9679a73f06d668c6908bf54d4a35830d093343e98f90ce3068
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:18eda5f0893268ea4496335592a9247f0718a78e6f0af9e016fc4e28e591e0fe
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6bf214db69d7f3a130a64562bbdde4327127ac4b2437bf87957d07b52a65eaa8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d72f336eb942eb397161b5642c85b70367a006736cd26c81e8b77ee388e5c899
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a059b2f6b89c94e199e327110d630d992fd83faa06a97b563aecf0325202e906
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a358c922a8f5b99fbea142a61e3c4c9ef7a631938fa229f1d78c647f0ffabff8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b2b4ce7624e02401ea42b02b8ac51dcda487dffe8c867404d823195680193ed7
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f89432c8e91eed61f17199244183db15c03b6998c02067e0be0214dc07dfe87f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:5c3227583ae0623d04f2320eae2b567517db70ff779bf66a9c884aad9f6cb2ba
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9dac37721f2457b73fd920b11857ac77d18e94ef726fd8d8bfa398e19d3f3193
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:dc102b8f11ae30460af840f24585e8636ee18d3f8140b3afa091e45eac761782
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:73cee5f5371b6b83294423036c13463314a410aa9c34336b49e8c045b900951e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6622ffbb82dfe2821a322916493939fd3dadfd593aca2663704dfa42818bfc3a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a97a9111b1cfa3f262ff5cafd78ba102eb2d85612664c1461c1b7078bcd03a16"
    registry: docker.io
    repository: mendersoftware
