auditlogs:
  image:
    tag: main@sha256:37cebc482128408cdb2261a51d93ec86ff82c27a15e5aff7ee85fb86a1d9986a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:47543a485a869e01cb9e66d02f1669b7f7528ccc949f8600c1b4faae24467a0a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:07e06c777cb4f824e635a51673a2241162c06fea6945e3ed235937aabacb9b53
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:679593844de2bd86b5d16ddacc685c5333e1e8e9bf2f1f96289056abb827d308
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ddab7015498d3a2bbb3e3f4566c85825129da0994a4f1a7f95fe59b6dafdff5d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:26e3e221bbfcdb5de14351cdeb385e49a52d567fe074a0113beee71bbc99404c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ef64b03909c48fbc9752d8883223ecf202ba3c695b8968bca13b4a3ae2031b50
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:701d3693f6b911a94bc5bcec9c14d404b023d39aae49d7d248151b17faa646c2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c3dedd34aadd39fd7379ff56d7dbc1dcb7edf7a61a24d3fbd40879e19e5a0085
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0983e4276ca7074328230256a2a7b22936f1fb2fdb5b27817d9e188a62b74baf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b95505a38d7d79cca6279dfaefa421709109e386f6aa11b3f33896688e264224
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8bf4fc5cf48820a50dc674699d3d5538616fa134279aabd5798fc61c78f33c1d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e6f381ac984dee23d37ee4d475c537c89758cd358187510d3734389ac7633075
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d34d50dab0118222d6bc20609d13177fb276c61a178f86a22e7a93b2d1d31211"
    registry: registry.mender.io
    repository: mender-server-enterprise
