auditlogs:
  image:
    tag: main@sha256:ffe88184569b14f1265245750f9d8f3d2e851fdae0a246c3057e91c4f2832f1c
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:935235c7c64b85a47ba9fe010c4cca21a9685c81d3af76e55ab39c6dfd38388b
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1bb3cd48b179df577899eadb4b40687b0e0528f2a58baef380371dadbdb7da8a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b7746a3b52873dbc8e1c547339de6691dbc19cdb773388219af0115c4cd0da39
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:bb013127f40c459a4b53dc11f5bdb0993647627cff01655863cb44ef4a2c6a57
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cdc083de1c1eb79f0e6bf3812be523e70e95ffcabd5b2dbda9e6ba180c3352f1
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:2ef1db76a42c46411228423b67320c433ca94d52a2c7d2de610f2cb924ca1585
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d2dafc017e32ea6d1fbdc407ff5b99ecfd43957b3eb7e296bbf3ed7615bb4ad8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:23d55e12e6ef3f4ba08cfadf5567429b3aeb2cdb1d7635b733e43887468a003f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4537679425e876ad94670cff36356a0830e7dba1cc8b0542fdc344bf1911d53a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f2aacb468a1edacca5b1b3d64de444869155a64e7f659f1099291e8fcd840a60
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4e2cf244be41e6db4f2c4c75279c11556631b5513bc437bad6648f881561b31c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c2c78e5cf574c4e15d90de250eaa6d2e8f8388b1ef1e3728b89a12f6cd5188c4
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:36bd2cd107053da6dbd7db0d9133fb3a3c12477bcf3db6c51fa1cc3e974f9ffc"
    registry: docker.io
    repository: mendersoftware
