auditlogs:
  image:
    tag: main@sha256:03d5d2278fcb3acdbb5498b369d862a212e0873c86a3407685f016c42612a492
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:fa791d40b0f4f0b7b1eb363b555e03803ae8bca7a90733be29119379169bd067
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:cf4a50fb788cafbd2e6326b813d9851464965419062f8437a605e276a88d4f1e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b2f4cf27be5171f2d73602fbf50f14e9ebf985f5edea2aedafffcd27c037a1b7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4e196ceb59bf7da469d2c6feb0521a6756e5db6ffcbca8f57a075a2a773198c1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:30fef753385890035af8ce483263a04975a5395ff341a60e962184a44e21b673
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9470e13c6053816fdf422cd3936e472dab6f818b65364e966fe70391d8312a00
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a679752b94691d1bc22e871572b3186eb6abc9152e91edeb6327550998fc701e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0058cf53a6b049bde76aa5fd498275fe21af136a61e4d58b74881cb817b731fa
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:871c79c3539c050673550d904fb97f2d2c3f486748d4bf1a40d1b289582267ad
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:a75c5cb1985ef7b64bf41cbaf73df149e7582970399e918a777d0c92f2457c3b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:de2d9fa7f3e6e3bedd310e98a4607d68552c751c851bef606ef0c4044da61674
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9535f4ae3887c098f3cbdb1d3bf96e81d53ba8e9c0ab32459ccacd4374a8df3d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:143a54bdbb3fe5f56fa942090e08de317e937a376349aaa59622981c35c4d543"
    registry: docker.io
    repository: mendersoftware
