auditlogs:
  image:
    tag: main@sha256:f80ebbcc43d811d4f0fdf35dee84b8701c90e15bbc39be6b59aa4d0f5c0e4003
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:80ea523d94e07cf480873ac7c489c90f32701528353f2341ac4291dc03be1a2a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8cef4a839edc54cd2892ed8fb337210f3d3d6d864afc43c9435e2df1fbe9e4ff
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ced12be2b0e72b11ecd2860d2d51576824ccd8cb1f14c61270c892dde184d8e6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b54600ede4e3c148304d1aae6432aecdc78fd8976df6fd75f06e424878ac9365
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5d2913c7b034129d7d3a0f969c0024f5dc77f73150c644a8e00c13cdb59e150c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5b6fff2e8b9c52ef0662ef37a602be7115f1e24fca99ddb5ab47340ba5ae6e75
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:60a5afea2f7d623c9c166ef5685db611eb9358d72edd2ebd6bf2e696886af779
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:72855824b39aaf3d79a25944ae3517583a3b6a90e0df7a389f24167a41401fbc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:fe81715d76ad4eaf06a13af555b3d220d99a52785b6b89479a8822c99dbd9b62
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:286ac5338ea6b2ac0e3c06b1515304c9698f85008e8e2f47abb0ee8c3a86c615
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:6ca9b670f0028555af39b180bafc5a0f02ea641624344d748dee56c84c571727
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9c704b386f940789323036a398143462c361cef95e7d161512ca899c65812b1e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1516c9b581617c2491b38a64fb0c29374afc5b6242dcf9dc7aedff45cce548b0"
    registry: registry.mender.io
    repository: mender-server-enterprise
