auditlogs:
  image:
    tag: main@sha256:def05210e9201ca6d33377e192493b831a4c2a739432d56c54d9f6dcae5a2905
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:432d891b96942d796b7efe294d8214544bf51c29a244460c506b9fce5d5d3bdb
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f8c2f3c004123e05dcf964ba27f83a39119ff8db1afc869f961fff90f9e6f890
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2743eb9e6f3fbe2dbc785a1d4bc4b43d7e833f74bf3b88f4dc420068d55429dd
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5f3202326918bf603974fa5a471ba17d82a7642f6cf90eebeb4ccfdf5532172c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:76beb6383d59b90fc24fa34b0b2c157a1a9d5a50fb761021e9ed41d8f84e9e38
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e8bf1c4ce0d719a2e4b11edc524188c8c1847f2a7e71d49b713059e0afa11c4e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:dcba8c3d0d0ef7a3ff8095ff28ee510f099b71e987e89028a44bcac6c87b13ff
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:04853d74e9121d65b2da81adbb9affd6ef15d225510a34d5c05c318bf74f666e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:cc9404783fb41c2c38b3e608a7d885a6bacde916dfbf98ddfb13604f80e40fe3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:607295398cae66cb432dd6736e1faa78c73f11d1d2a02c4a34f1b4c085319eff
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:12204416bbc7e150ac04f4b17a96771e3e34853b5d74b5725a6053ffcd91d73a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d8af5adf8a0cf3c697cb327e4aeb1e73957bdff67a3d49fd05dde14f61c7c7eb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f15f0644a0efb58034cace959f9d213f86434bc40e4bae744e8de9f9e67a0bfc"
    registry: docker.io
    repository: mendersoftware
