auditlogs:
  image:
    tag: main@sha256:27b286163807bb32bb983ca072085ee903af8f9e93147e8983fbcd5c23834efc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b46e6abf8b0417dd91d862fd561518eb7377491edbf4536a9e0f285002808de7
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8a2f42c0a4ccbabb033c8604c3caaf6a861ded31fa493be7ab73ebbbdc850f6d
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8da4d048ed5a30bfbf60c3103a12c06891177a151fcd8c13465a4187fd50e789
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:3f482a7311da807263437768e8b630d7e8ccb13b7f9219716226eda478ef26b7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:88ae2821ee3a10ef6a83dabf27d920bed3cbaf29546cb42b0f1006e485c60263
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e7c8a2e24c14702ed0a34b39b798b61690ccca5779f1b6ea001dbae63be6e72e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:fa777ae235d887cbb8c3a3916a4b0a1f719ba7567c043ad364bb4900b05ab6cf
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:5bb9cd5dee3bba3982f6a1ce971ed76ddc7c12970c8405e25ef64ebd1b1d29bf
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7bb5629e908f199aa7e506b7b79698c00699123bb521fef8e8ccdbcc0ffb1dae
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:17ecf6aa6de61d846bc09540b6b8da79e456cefcd049b2fce3575c154f1fcc81
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:646dbd99924fc9eb7f4c82ec21a79f949ff9f061e1eabcf741582fc0d64db3ab
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a44ad6a6a53785726c98a9b2779e90f5275ffee3d8422803764b4520d3412b65
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2acf19fc94d261d3fe28392187f885a5b42973a4852255883bc697f2a6b91b5e"
    registry: docker.io
    repository: mendersoftware
