auditlogs:
  image:
    tag: main@sha256:b8125c5856c32e3449c3bca9687331af36c620853c19236f2c69eb2c5a29b069
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b74924b8869e2ffe4fcd296aa125568f364f36eae7719f9bffd69c3f03449cf8
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:75b596b0a55298fb4d1570d436411f4d546260ed5b427d1984e8284d70e82fae
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d84d6969f1e0f5f328a50776ed245adf3190a2ef3081074547a2baa750287c71
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9249365633fbc269c5bc187f0bc5a1e73a8cbecb4bf4a9cdefdb46f74b6a7f67
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:46bf1e9e28b8dd6fa45a2a1589322aa8e1779bb48558e723df45b27df02ac947
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9010f83ac58a7fa781914f68abbbdbf2e25cf511bd408bff0dfbc4285a5d9f2c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:80779b1dcccbfbd7c7e5f57447148c519d15dbbaeca681c4ca7b8e6fa6eb8b56
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:229dfa3a3e14dcaa6ea9eb1cb1392d103afc1334080b721ec3bf897f6c4408a4
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c52084e7ddb1e9d8159a4a65ff73006fbc4498d6caf60881fa9a5a62e1b83c50
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ec61d53b4aea900e8c178dfa045f8e0c34384d043b33b1189a61c34b0460a054
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3d636c764138076bed9f11c00bd26952801d4f2753ec156707eb9d3fb1ddab3a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:47a1e693e0ca1b07849b323cb642908fa20892dc7ef51c7744e3d706e512a981
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:dd948c7d4eb71549f1927a124e5afe40b4dab12d724cbb4370bd6f817052a836"
    registry: registry.mender.io
    repository: mender-server-enterprise
