auditlogs:
  image:
    tag: main@sha256:a9d94b2c358c25d6485157a27ac69dc02f238877aa7c9920506d28e17f3822ed
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3528969f6f72c4c66250ea1843d54ed0c6bdcda43e0f360c09f83db92c5ae457
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:83bbf96d0b042635df0f29a5db0ee6e3a77e898a71f1d481af434a51727aaf27
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8b5cf8fc5f4bea4c0aaf937a38409a889bc9f53b2eec18a66478904491532e01
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:595717175648980c5d1c29a6173d6b3c9b3d1816dfb1e66906ec61365ae5e800
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:fd28dc969100bdf3a941926a113417172644433f7431a932097c96d790e22f80
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8b6f535146512787cd6080f60644d287ba492cde1d1a086195ab8ba718453c9a
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:73e9c9e6b5e450a00caa0bc08b399fdb42e6aaeac5a0e0076b378e124a3e09e8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:883e31fcf98bc4e04f9274ea37281c144f5f3a74a381a29e31f0ee4ede3ca3b7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:30e1f89e70a88ae183fc025bc8b6aa3f148994c48c25f31ee9532c9d0edc710c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:b11787a2dd91768598d5cfb2e373c95df61dcfeebccf2c9aa947615b48e08e32
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:2ec31e2710e34f4db2f6fed86044bb9359ce114a1b05976648025c58e7a9008b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ccdabd69c5e5bb1d928bc3410a2a7de7bc7a57796b888c06741d437e7f417443
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:bec8ad3edc39f68f6df5e0d2b5a4e7a278f97e6c26fda688105d0ce00ced498e"
    registry: docker.io
    repository: mendersoftware
