auditlogs:
  image:
    tag: main@sha256:277d5943a8bbe4467727d76f59b6e041d52aa8614e2221ea964ad4bfcf5aca24
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7335ec823d19b33332e6346bee5edea299c7f31b48c395ad87014f4773a62eb2
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:22676f510ba732c563f67387dfc4ac9b92cd31c6628f2528f6f5339800f1bce2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:507c9743710110b9236a43759a20d7ade043dced440cef2d023a80965e5ba30b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f1868a4c788f9c5d034b783c32748256eadba1abe688f5daa8eb54993da98b28
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6d32c002ea1f873a493bee8ad9d9d2e997e4e50074e87078affe91cd6bfc36aa
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c9a39a09490ab97306b99c3c09e3fef94ecb39c1bd4873710cfbd34a80a18567
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b95d3434dbf758635e5535d87c4039f80062fc8e74d6bcd2332c6111c7910520
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b74996771ace2b1cb417503f1c1bcea20542bba01c3881e1f248a73ea5a28a63
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4eef16e2892c3ac8eb32dea451f0e54c41557fbe5a4d629082f11e99eee7ce41
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:17c5fd9db31f36f4307072387d2a11ce178e77351040d320cba04e10152137ed
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e4fb328eabb5b59b2d6242d9e0e24c3be05f04524391bf884f1d5e3fd38fbfe0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:73b47423e47f1a5c9b301233570d6fec4fe9915231bceb89ab42a95940c16244
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:54822edb333536e71cc0aeb1b804bf99e022c67c4d2f7da93ceb7dc488085160"
    registry: docker.io
    repository: mendersoftware
