auditlogs:
  image:
    tag: main@sha256:d89154518439d2ae164fc6aee944591d28b6525722d9acc9bd0c151c00199881
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9718f56120f2b795dd23fba542dc8b8ac9bea99f70e9a9572cf7efcfa6624d0e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c85d98034f8df13c02b2c211c14c80a42d3f04dcc4ea58e11615a1bf4878d715
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b3b9f42d9c4c3a75a56fda3c046e5835b96f168e3483ba6f91a53f58d1cb3665
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a1fbab3a76477185fb33f4265f667f4c2777310ef2d55a3f07da405ddd7c589c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c3762705c1f5a2ad6c1d97952d9b65b82bca8b959c102ee36f9e4089acff097d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a5510499890ea2b1a3b4f18caf1223a95d87b4afe78347afe6ddb9b8145a38bc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:9f9b2bfbb7f117cc320a29eb45213fbd1248d5f92ee724bf6c396d66e0619be3
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:1ebc52f321c511cf57d3dc43985eee8d5be71fa54b5324c254d9e11f59a61021
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d48f14e4cd5bd3ace9770fa78a018a5ca8c3e33ac910c9fb4ae4739667d100f5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:876ff047152d1a26f1d977e462c7f0f9c84a101f9a70ecb2a37ea0ab2f307f24
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a3dc81a93a608b4bf363cab6ecf81be974d203b4b281b0d0e9e4ed112939cc54
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9c73bedc0f798fff9f333f37321a7f27099a9036fc55808e1b79ef099e19ddde
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7440eeb5bb5b8365677dd724b622e54516e946dacd8098dcc2f371a59aeb2b05"
    registry: registry.mender.io
    repository: mender-server-enterprise
