auditlogs:
  image:
    tag: main@sha256:c2f37a667c58d512f1698e4839ce1ed4d1823d40edc4ddf89ab0239601fa1144
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d200ab79936d73e3d9396a580d1fedab54ca8f30dce788cc14fe608632f2e521
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:af945948ad44f6aeb9605ff401bfd39d832301fb7ab602977685a5f52cf53ff5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:61cb6074efdf1b6dba544889774e323cdd650d338f829f712c903311d39a6515
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d92409d8885c05804100cfa9b337c65831676e4ea161d5a2bd72c3102931f6ef
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2af20b22928173fe2ad7cc97c021495fea5ffd35fc0bec6fe08a6d718c201c31
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c16df399fa7c7c6451f7d16849bebfdf5a1898c02ee8c131dd1282279577268b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:67c7895720e5f998aed088a588b79a764df9ce50467ec7afce8de85a0ae7f536
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:24eab66fa90e7f08b31a256404e1fb050344865f1cedb8215d89770efc7fe2bf
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:bdd355888a9fde10da608c5dee401873dc2d7b21da12f7579e2ab4516c039755
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:4852831bb23332c3b2ed530fa2c880505c49d6ce4164d0841a5041e176c2264c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c2e0550120d17e7084675551c9bef8d13926a6f056be0f285f390948a2d882e3
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2e01d31bc6ea5e159a01140c9c177d77e3e2fe0b97e81c06ce20fc5ba1927eb6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:84ab6f6fbb70aa2b428b96466c3f890c45fe6bc91ad79c7a60a920d225a42ea5"
    registry: registry.mender.io
    repository: mender-server-enterprise
