auditlogs:
  image:
    tag: main@sha256:188db910eaba930f95990659af727804155e5bddf14375439d0c757fabe3d972
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:cf5838159f717be32a4164ecefab8c5038adc922f4a67915f00b96d0916c84f6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:916fc631f16c9664fa5ba541e733db6a9eb987322f24dcbc68a802e024d83a26
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0f8c5d0fcd0ef6e099489ccbd423b9fff5f244edb0f66ef6dcd81792839af051
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:939905b6cce1c5a0abc8f6d6877879a176fb1e8a29e38b67ca6eac5d43e4b106
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b0878794ff78a93e82e975223f6fd1ffc8520565e3f55a5d263da3b81e956f30
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:fbd0d81a53336bb4e38f22d3b9fa7589d8f805d5dd3320672c03dedf2f50f691
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:781a858ea383e30dd8719f7c7b3d780ea145c2eee20e460369c28054b76a37e7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2e6895ced58a8b72e867cfe5dda4a701e7f5cf068f925c423830c4a1e553dbac
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:634b31def2684526fe59f487437d3136493c6757432ce336cacfd07d2c164e87
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:47c8fb3eac0a229642ee5acf0d54e4e7f66c3c7cb1a4e6de8b4acc7ee8daa12b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:225e2b55ddf68cadc485b9df7ae051cdfe50d760e252420fb934337eb10f00de
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2508d5cd3ad38d976476d451a0963fdf8a543704deb5bb7805fd9b34a6d607f1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1ecf7e6f015333cedce7a23f311f2c81edd82db696cbf01c0494db09b68146bc"
    registry: docker.io
    repository: mendersoftware
