auditlogs:
  image:
    tag: main@sha256:5cb3812f3247aee86b20e9c7cf269db48edcc6c5842b3c8074fc76c78da175b5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:a5dba8092c533229f30c5e2ea746afcfa19686d8c999157d33752691be497659
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6caecf457178b895dbfe74587b4a74fbb50832b0d07f7ccd1c4e05a33de28ea7
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:dbed25a855b724c28d7fec779777172dfaa82d1bda5c67fc0730031a25089947
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:00b3a1800e08fe5b5227186d1e9eec0e0c365dbc60d9fc574f22de073bb4247c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f7939ef0c24ee7450db872792a103b787ce97c74efcfa2ca49e23563262c5558
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a0115c25668c4d40cfd32aa2f99bb2ca06b573a6278a53f45e817a0f442237aa
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3bf691f7c65d52af086475daf2919979ce6ecaa25c3b7c804c8717291e9a103f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0cd43542491733658bfa5c8a549496eb9e647d39d5927ae09ba32486585f4591
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c30353b43008fceb4014cdad44533a48b277f51886db50176724dc9bf8d74ca0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e4ecc260eae019ddadaf1f800913ce3582c139d4aaec87db4d0f69afb74dc73d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:66a8e50dad10fa924439d110b7f6baae3b59d4afd30c073dc8dd3518ac14b2ca
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e690ded7004fa6a2e687927dd0e056456fc41f9c01321ae5e96b0cf046e6f485
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:897cdd532b26bf644997fb1d1f7a8dace09e5fbeac7453a1128285139a630198"
    registry: docker.io
    repository: mendersoftware
