auditlogs:
  image:
    tag: main@sha256:dccdb34a8389c0f2d0b5d8b14de80ee52706880f8831478ccd0d5caeec043063
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2e7094739e0e9dd8d5695b1713b056336823dc25e74c6a4e2c36a8984ef75b3f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0181849afa0e90c07e1a4a71968c05d8da33a58807481772d0d276858ce9a8cc
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:5d2c7260cc339b42f93496f34e55aa89d49bf1b7ba39c419cafd5c6e6f75fc09
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:fcd8062341119ddb882a6874cabb9ba4d92b88cb10cf1cfc515fbc22667ba7ce
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:304321cf333e1e4493f954f7702b797d8020242f2be2157cd6667abfa8709600
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:84f3c389e922bad7b8867c74004d30c2de7c2f43bc8a0d7cb2b5f134d536f399
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:6831e01958dcbb30f747f7643d09291466c8dfbc29a7d46178635cf384167619
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:645b1417f95f404c0656f54db098db6a418df17e08c425c359a116694d687a9d
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f9450dc4593bc9830d809edb61339b7d20c1c8fe8e0357ea5594f992880c245f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ce14f2605ab4f35203f71c75c7e8fff4f8f10dbd490489a1fdd0a3bcf6c67af8
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c495e1f4a2c09e3b35dd70dd24f8e88185b95048e384f8891e0c49ad7dfae65d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0911e47954a294e28ef909893bb3a8685d77c54f662835f645c3745e43d0ffa5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7a0243cd39ea90e05aca4d880b685f6b321e30f1eedf7a42c847f8127174fb84"
    registry: docker.io
    repository: mendersoftware
