auditlogs:
  image:
    tag: main@sha256:95fb21ba155582562aab17003de338a1f8a5d1d2d25e13a3ae6cee756b5c4a05
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6e78ca9cd7b4a57ddfb0bbaaab468d58e6f42f68314d976d5d212ea517b0a737
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:eb5051d2303b1c861dce29996a8670b2bee3a0676ecc9d2a8056b5245dc38dfc
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9aadb6bbc0c5c75a6f5dc2363fec04a68180f91a16650eeed04421312897f362
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f4d73538be79369d06df23c377e0d1a358bd49e6b97f7055bb6a6be08596b193
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ac7d70110b28eacb95f8a604598d5b836efe0f7a92006babdc71863203519467
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:196b79541f5eb4939a91c8c4e9c4b5a0ef0a33301792ea31a9877657b81ca79f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a4c2afea5f5001a2896e476e049b0d1f7526cd9f395a17549581a9136677e8e1
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:79426dcf371244834aefada582bee939b7eca8ba550054bcdbdf8b963430647b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9b2e27bd050f627151f3f9603f0598e14150cc94290923db7eb1ab6c7deeff1f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f5111dead1b261770e67c1278aefa5fc71c627b177c881d63e848328bd982a45
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:93c2c1ea52aa3dd97ba013b38ad08cedd0f89b9e7ce8b5135ad68d9ef6ad4740
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d99a0125f4987cf4d7eadc70301d29d5a5cabdcac72bb8849f1eae6ef1eab691
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ce4673cfe6fa09bf8bd86370cc9d94f7644f976a6aba0837d5af78a22b61069f"
    registry: registry.mender.io
    repository: mender-server-enterprise
