auditlogs:
  image:
    tag: main@sha256:95ccc6f000d7ab72501bfc3a7657c8defef5ebbe245abb6567c784650a7242ba
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:64f01252549ba731549a087fac9446f94638fb0f4916b7a50263f42e7265fa7e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f285a48ed119c0d4fce5651a6abf584fdc04cfb4a1a3beec81a21a3fbfa6a95b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8fd78b1dd972ab927bb90d9a24c44a176f57bb4f536f4b3aceddc309f2e606eb
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8d0387bce948bb1e43f8fc9374dc93bba070431778f3dc2da0f4691122acf3a5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:503921c51842a0591fc9c27a34c11365e642f1f1701b5097d1710bc3f87719bb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:81f88b2cbab342d85f012420d3307bdb758931b217a1bd3ae1f5b73920ec8430
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ab9b6196827249557d5a7af0476e4d7747590228b83753b6ac88446dd09c3258
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:844e2f1a1a3c83e0dfa05c438328cd12f20670746bb729a22fca263a7b258ea6
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:543a7fd382183cc85e208c42d827c7b3455e6aa95995dcc85cbee91fa61f2886
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:08026086825a8287ba3b8e772935e6d19a02c6bb96088da375872b66b0ee953e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:41b941c89225bdb86611e1c5d78e5d9d122c5c85529b4f8d2f119a95960081b5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a885ea8fd6156b10b5e64f73c440aae9efa5038001d486c6ff99f0767cd582ea
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ad0b1cf8837172df156b047342c5dac1e39046ac8cfd059c9dc6c79d258ccf7d"
    registry: registry.mender.io
    repository: mender-server-enterprise
