auditlogs:
  image:
    tag: main@sha256:afb2ece40ba5d72f749e30a408f8c4c3c8cb86e0f682a633cc57a04804bbb470
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:27a0075f5e62a87417aaab20bac6f9a5d7cc47a0c6910d40b8dd81e9a1fc550b
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:27b2be77793703d9728586615b315b83233fdf2da8675e2ae0446727f7f181cc
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ca81ffdda477e409f8c87325d89eebe7d67b4d74248a2fef6f08168ed6168551
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e5df734a4d694f477dab7921b419a5ddb5ec849bb408d29aefe65778a28137f7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:dc097ffe783ef900ac58acd72f82e427d313440c6631f8066267ba4f1923fd45
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f18f1b9129a4497c22d66b7f246fefbea15a94f5320c34a06ed100ecbcc99e19
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1d215702b31b325382a768fa8f91921f9df9b39a000a62225e581ed40450f5e3
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:89cb0f93e6be4e7f26cb05afc5e6610fe5dd38e093ceea92db41b37182103919
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:84e9973b55ec9259c3924edceea6e4bd238fcddfc8b997e674eb37ae82037c3f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:bb3cd94f501aebb2844b0836304324f2ad89bff824ed1e90765de3eaa21d8f21
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:cc44b18cea37f7438880e4b85253f681674e186aa78e7b21b788e3a3366b6a21
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9d497c4020e653145f60b1cdd92ed7348c0d146764812e2bcd1c330808778474
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2260cac3a328c805a9b31853d620bde73d22e7094aad833ff96fe23492cb1037"
    registry: docker.io
    repository: mendersoftware
