auditlogs:
  image:
    tag: main@sha256:c09ace10c381957971fe6b574782896b606e6deda2ee0eae6ea10fe995c348cc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4581db7d2064f62e7e282e5098eedba6001bf5c01f7e4b3b53e559895d90f093
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7f3e021e3b7696e9cc37b272454f4c9c8f897fe56f3c21789a6f3850a7dce739
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d678586b168ace592b5f83b484b1b54914509581199f0690050584c990f81148
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1d2b4154a3633f132e38e6c73e572b93e39cded485ef7269d39d81a7ec86ae99
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b67dbf564acbca2ac82074e50eb3590b6f20287cd374a901204d83b4fb46dd32
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ba781305723977b3568878ba7b7be5fd6338199162416d60d4435aa672fd47b4
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1aea82e67426361ab12ef0034bec45afb0bca9f4a9bd84a461d3a65d639eb3b7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f105b5be17f16362b307900fb99410bb923203dbf8730eeac30e996ad6633751
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:971c3e9a1db1ccea3505d40fcf5ba8029d890ddb136a4c281a59e4450b2a469a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:73e87ba8b65d9bd442498c64314048ea1d993a725cc77caa499d73c4979f4334
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:23b0c9ca842aea5a6b1216e44c45822c61c29abb860ea929dcc29255ab74d90f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:cbab8bba41593b66d759563bc86e8d428a1cd71d95de81582c3af85366ff31d6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3558f021bb60f31b1d34686163a6d441d74d090c2785d6ddf0e44de3d9b59667"
    registry: registry.mender.io
    repository: mender-server-enterprise
