auditlogs:
  image:
    tag: main@sha256:0ae7be325111ef756a1e6e7413a2d9d6b6003f10e8c4874cbea5ce0d97f754d0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:442bd669ab485d647e7d64e795e09b02713b2ce99b4577f59abe521207c5d911
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:068906edc3d7a1023f713a6586c8776fd452060d8f628e2d1cfd4aafd4dbabb2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d5e63639988b54bbcd7011c157ae7fde2a9ec7530f3d15653f72b90c6f0a9ed9
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:64f47f1b8c2c02c013a10182c7970ab66c3e6449a9aacc3c2ff284604e3fa3d7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c904d3b8c6e6547a20b0da1ac7180a8961c88b78a6fac7f032e1d453d6597c77
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ddcedc1564765802836eb684c9b203af71877a0575255f2eed3022c6b77d6eca
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:384be583517196771b66c29a20cc4fb26ecbc1e067cfbf67343af5abaf807ebc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d28ee8c1945e7c0294acc7f2d8d590556f6b51bfea90202b683eccacab24a30f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:69095829906e6115c3ae0785a9c668983b2f91844d918cfff7f8f54e72f0c1c2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:09d6cb868cdca8c877a3e351e17ea7260e8fb43e85b968eaf720695fef1e865b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c16416707c88853ecf13e72101e5707be850735bfb24ad47020cb10862374b3a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:cf25646e16f4be43f9f2e6381a910db1c04af908d0c98d92dbb214874960147e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a6a0fda362d8d1baea3b0ec6031abead23bb1d5f73347141c21e10d85ad20cdd"
    registry: docker.io
    repository: mendersoftware
