auditlogs:
  image:
    tag: main@sha256:77eab1e6b84603f81b7e632839dd338f30176e9bd9814fbf0940862e8d55db0e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:36f55d8736cbcf83c1f6939189d8e38b7f5bea9c90909d012eb377a2123c07eb
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f64d0e6a9e89bc239ee990e3f5cf317b5107c02ec713e84688d8727cfc24560a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:fd47579d0bfd867a47e7cb71a9f0364298843867ff33281731a4165fa7ae8a97
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:34a7124a608fbb46d8f2560f97e3c3a2bf25ef511d6c486bd678fc686958103f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:24605337364fa71ed105ea4248281530b66e62c80b93566f177300c37e667042
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:7c9137e2237d73c1b8a5b871ed71b59822071404507711a69a64d9bee6ed076b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:2b84506d4170b6dae5c26236cdad95a702bac03e90e11bcca547bc16b9e0293d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:00391343de7d21cbb2b18772faff3496dbc16c51ea565c5409bce287a2aeb725
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:142eb30872cd40294f4acc7302ceda4ab4d77b14ac4ea3b5c4ca79e1605ff021
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:df995d7382810b62a825c7c6de1bb51afa85d4f77e7ccbb8b403ad1a45805564
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:86667e002fe1b32a5573534e7b813c705d309e9d55e6864352b1595ca068f1e7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d1321e2468054ace0684fa681ff950e2925824974dda2d1f7d5472fe97a4bdb2
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:714b947aa34fdbcc0d65815e528ffd2981ee86873cec95467ec57de88a7ed531"
    registry: registry.mender.io
    repository: mender-server-enterprise
