auditlogs:
  image:
    tag: main@sha256:3f0545b3205767a4acb5c149637cb535a9d61755806cd1b88e267b55c36cfecf
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:fe4ee2fe4db002c90e02f49ba4ed39122092a06b70e1e3ca9ad742ee9ffd5aa3
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:108059b586982903f666a005e3373ae2a90f7c8bee37c7937c235a6b64126f37
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:8dce7cbaf873ab572deffe4f4a8712bcd0951bf3666e5cfec6020de6ea5e92e3
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e57d4b2e55f8cb7bc6a4c9407610f26e3e638bf1053f3b24b519ebc5eaf78c65
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cb3e2230592ec33cbbca9ebcea91fde856e701b3e6d16cc795faad440fdc51b0
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:1062e45b7a353d66abd4c3670f5d0df6e52c6bb9b32b28c6334de0488cf2f518
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d26cee89394c795dfd0d13ace792a87eaff77190b593a158f446ad8d71078ab9
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:fb26eb1fcd7cbb916c2d1c5838a78ac763d645f8710f406d7c2abfd6213e8cb2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6c06562e43973105f046da90716ed529eba2371e0307d181c8b5509bf8c934ca
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:683cb08788002904db535aa61dec6a7ec449e15dcb496b3e4c15f0e4b6fb6d5e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:07dec5afdb4ba4b776d4ab878da73093e65947d2c77c5fcc678bde3009b93573
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3732d6594010803edaf93f58fbb414969badbfcf67a90bb75637b7e0b0bc761a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2ce71c9a305947269b52cce5cdebba851161ee2b26f5d7877d55684e60794b03"
    registry: docker.io
    repository: mendersoftware
