auditlogs:
  image:
    tag: main@sha256:a4bd828a2b3557cacb2fc8b05919192d7fd689f110537453022da71e73c4594d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:198d6716d39c423fd99800d9ad3f1b9dc9fc965a31d557c633cc0138f77075da
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:759b800f83bcb3de565077f46261cbc95e0b1a2e3349a338656f6f07bdd6a2df
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:389dce6d695227f5206ce7210669d9abb05ee1f8b3b6149c38ab64531f3b56c0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:fa625c7490af1df9f2c029b8c471e640242d6287c382850a4ac65c3e072dfacf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:19ba53547be6d261a564b447abc9ca2613ed7346282cde33198a7402a2af2edb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:1fc703f5373297cd1683b8e1ac945b4bdd99b038028c0c47a58ac624aa3a17b2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:c596027a1445a18fefc60bc2d25e3537eeb46715b2f9076e238c353632abed6a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4388594cf4e5779f0da3c26d4a727895579ab6fd4f1e75e5a2a93f4f0eb4c586
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f598baeda904c35346531cf4c2b5ba41a4a5fbc64bc31d24ee4bf9eaec917a5d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ab8e079bfd425d1b947e4f86698657ffc095b1d1e667e53c55eec7fba22b193b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:756e2d218aac868030ccef711d400fd341101253dee527b6783a508fd2a86d89
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9b0af997d575c7033a7de3aae4bf6ab5ed6ae05cf94c84e8a51512659c32d90c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7d2987cb8055f2a6324f87a27a1f9e54d10a4751f6090bb2ca923cfb5a2ddc77"
    registry: docker.io
    repository: mendersoftware
