auditlogs:
  image:
    tag: main@sha256:e66124be0010f14d4c1901de5edf5f6af22ebc50caaa4b2694fd087bb5dafc61
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:44c9dd24f45b0f28dde4db91e02760a763f228bbafccee4325444d1ed748eadc
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:9a6dcecba17412928989d930c44fbfe7e654e2e0d0e90fb79acae0cb3124c0c5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:323f7e3d27bd8e38d6ac102a17d885d6f9c7019168e21c2cbddb2827eed8beea
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5b2237cd67d53c010b543a586067ccfdaa45699ee333f7341494e7ad6d6288af
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:20c136fb61169605d850bb7c96bc61de0f562f74747591de2d88fce862ebdbad
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:76ca72ca7a4c4d507c00d0ea29d5f6659b11a2c92fd510e7c88737498d4d5135
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3fa6914bacb8098541b57640a97520b7253fb12487246281ac272ca96220bbf7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2ad14d3de657ef09d78d82169fcbcbd43f14df3e697edc3ccc9c46dd53d20d79
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f1803580d120b888967ac9c07c602c451ca15e8a29274fc6baca6fe6815a634b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:3ed940839347205a2cf1ca165a02eeea20ee756d46415ead19b0754759ed4885
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:cc624724d84668ea02b3878d07e633df686941c824d1cc7ac62a6e188eb25b28
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5b3920061c0d4048af9fb67a7ae2577dc9cccee3871e1773dd18ea4e110ae679
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:503ec76a7c1eae93efb21231b375bd9d4e545f60043a0fe203e1ebd0dfbaff88"
    registry: registry.mender.io
    repository: mender-server-enterprise
