auditlogs:
  image:
    tag: main@sha256:1cb3acb2558a3ecb9e63a07cc8e75d57f0ca194ef683068f75b6b4926d475435
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1dec9492623c48639e27efdcf54b7a01d25b49356bc39273b3e3e2b871154872
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:e4d408fa1d03c1b330621a22e77fde9d31682c7b0d75262f15f2853e1b5bb77d
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:58004b08f467ae5c60dfe2c7dd2de3c32dd2c2de82741e84f80fadd90e5a55f8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d49207147067de8d4a103568106650d0725ef2241fe340c0f63d97f90b15fac0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:08b0ddd3528aaeaaa5f9cc74a579c0d3aeef8e6e36cb248aed9b9c80a55a9c3a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c62d19e4e5ecde554594da3109231cd606ac17e4268efa3aff3c9ce13f71fdc1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:651d5c672a919aac74a75f94a91654b8c18186a01a7fffa4d8b08c89ae3bf1d2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d767cef14867296de3129a289acc5200aaf8abf9e2f65df45252ab3658ccc760
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:befe93e4f42e89d5caf41c8185452aded295c54158c6c23fa27e5980844fcf28
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:27c3974f3dfd32ba67768ca618bd9caff7042897f5e35c6d0b18096c861a0d35
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1b0a1593149f99d7851ebe6a61b7069b560bd3a07dec0be2a82f7f7ef279e4aa
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f76d4a2076ed6f3ff46fbdf0cff31b6821efd348c19de0605ada4930536e3e39
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0ecd9725c366a67da8d92a6d107a8a05dc4a64b36a9668cdaa53418353915d55"
    registry: docker.io
    repository: mendersoftware
