auditlogs:
  image:
    tag: main@sha256:047ed03b277411c1bdaf0471200b31731e57fed599839c5e2c14553468b4736f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e8b6d8324f5f46f4b9a16fdcfd8fed34ddfe62016d2a29bf1dd5c53a35dc8035
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:e0f2288dc1518bd2351c8f100f1d1cb272a037dd0b1d9ee95806b9886c9e2ebf
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d5287e1212a8190b6b5315e589e3849073e979bf6bcf44a2704458be90d27cb3
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a101ce6f398994a71638f171f60dcb3e5db965237ac5d5df8a4414a0f9377ffe
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:af97faf9d7f8132a3a1669acc7608d1d1d94bab1bff688d460f3edeaf10bd733
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:473f34e75eba1761ad1dc58aa9b8223e5577324f3f253ccd2ddf02eccde20da3
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:bb12542f095b814502dc48506321fc6b9e81915ba658a840f2607199764d18dc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f76469e35c1913948fe8a0d178542130f5ad36cdda00f6830b3eb9ba1f796848
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:aaee82377e12bcaf45f6ff4bbac418e3fcfd5c28cb13e21f5527e870ec1263c8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ece854399ca247f108e650338ea1e9438e28baa0b6cbe6b19d948565dbaa7d46
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1d39b64604804cc341b6ef1437263498c899205e42280e70d588ce5ab82a24b9
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2fedb9ca7b662dd8f02d5bcb19b7bb65887a4becc0ca1ec11f25e6db19231023
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8bbcf183efc77b0ff5a401e4082786f57dafc86b4d869b8b6353ddc6fd213a5b"
    registry: registry.mender.io
    repository: mender-server-enterprise
