auditlogs:
  image:
    tag: main@sha256:31455c95475f402bf8b72600e0c6e41e321d289581ef661d6153aa607350c32f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7fab908f260d15f6afcd9af9515e2f9376ef1686ba4fd0ce6202d2e8f1e1da68
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7316da0a893970262867d62dba736984addccc53af0c830262b31a621a89f4e2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3c3a8f6a0c65c977672d43638262285fdf4920ca5b7250190f8d90df15b5b781
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d28d86ffe74cc4296f1fd7d6c5c721c9b8c29c64c08ca1424c0942ded3fe7d4e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d4d77344cf9d2b1b72fa40b68add7eb013a9eb17ffabb272920f81713bafc6f6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d2eac729ecf55588c447a947399ed62cec4577de241f754381928d0a844a482c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0c5123ea436b4ac6a7efaccc11eca25bd66760adf20c8d08e39e7a759208649c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3fa8d69130f2bff7b45702246582cb9da5d8adb8300bf5dfe45d85d2feaff7b2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f5c93ce639cb8f77022f90ac4c6bb33aa51d1cf9e2aa1fe894b8e8ddde00bcf4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f0a3271a2e89abefff673b7541e240c8e60a425b83961856478770a9f48da3ab
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:39f4918d508cf9c6416c7199c3b5453930de1d9514088ee2781e22a6602c2a99
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d27a09ab3e7b9930a744a09acc93c6079b4f0ced1197c9dbbc943b506eebd0e1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:579c9473b02a3863ed7bb23cc41b49ac9518170f511f3ed20efc96ea1416fc6e"
    registry: registry.mender.io
    repository: mender-server-enterprise
