auditlogs:
  image:
    tag: main@sha256:d3e71b2bced444ff11c41dba4e9bf7041ebc8f6b1d8d5b051acdad663091f1c2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ddeb6bdc5f8b739af3fefebc8c8f9de0ed0bbc3b9ca37219dd31174d359313da
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:e3404eda43ad8c3bff9fde646c14b203bcd230bfdbbab1e3436131c925827da3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:78de47e2813927ba0b6e5aecbc5bb70e2b62ea696ea38af865bc4b3e32b5a5ae
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e05f291ebb77663dd484b602d3fe4c2ec4913801682d8f8c51608cf9637d690a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b326b29c9747448cdcf024cc146027cea53800a426dc3ab2990e5e9595e70f21
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b0c5a9e87da6b7a6b0ff9888c8ccec6f288b9174009c87e7d944659418e3d486
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8acb380fc81e768bb1f4196c35d10ef2981a0e62a5d88809245ca2328ef821d9
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:6b1ce05ca7842a0d446324c6ebb666a0347732c38fe6d3f09cba473fd6420e34
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d26a02bcb9b667c6a9d96ea2baac4a47339ffce4b5d93d452b31c41f8b9d6844
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:126edb2e312b3eb963e46e1ee96c5f08b7ceb8e90681e0ce5b67cbc45f25e26e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b2e85027414cc036e8bb076f0ffc60c2d742ded5f4cdfe94a64aae8f09998eab
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:b6b4394b2bd568687e2533ef0b35be2ec118c9fe2a26046eedc9ad350c70b084
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: ""
    registry: docker.io
    repository: mendersoftware
iot-manager:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
create-artifact-worker:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
generate-delta-worker:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
deviceauth:
  image:
    registry: 175683096866.dkr.ecr.us-east-1.amazonaws.com
    repository: mender-server-enterprise
