auditlogs:
  image:
    tag: main@sha256:0bbf39ec91e76c6b6306620275db58610cde029403481c4117a0843d300c3e39
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b1ec2dd4f418fea40df3b44c999c08529d3e0d1626da6f5c17ba5ccb90c5638b
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bbb7b3a453feb3a4c9e3ce934edfb468936325b0d659e791abc89ed8b5fbabaf
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ef0a1e7c7a8f69e734ab5cbf580f6609bb2052e8a805f4205654cc7b2d99a32c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:3c0c763f5585923772fad48038659688c81fa6cce6fcbddffe33e6fee288fa64
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6a670df796258a48430a49ad1639471b0f12e9638732c8119b07303d80a4ebd2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:468da6b9ce43076d183cb940f062c58d97deef9ca058af5c0f970afdd6818dfb
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a8a2940b1cd054f0f831b3bc31496f90b7b093c297b47f2fe360fe010f72022d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:202c70775700fabe36b89de5ea9a4f3fe1d42b56c4b2a39913b9feb938a6be96
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4ca8918e825346840967894f6da3feabfe78c270f79d8801eaa15e302261d793
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:407277fa3c99221c6bba8c001653deedcc0b21260b05d9e3c3f8b9405e3ace86
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:98f03f71eb327ef421162b17b3ed47a50405d7f58da2b6e5eb28ce8606f15e6b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:cefe1ce3c34058da5b7cde3dbb691e43f4f2041d8089646acb1359d53011903a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1ad2b4a6f6ab4ce2a9faf33cf7dabb7f214e99148e4f83b048fe763f26bf8e82"
    registry: registry.mender.io
    repository: mender-server-enterprise
