auditlogs:
  image:
    tag: main@sha256:c79caaed9bd96fa0373a47a6e6f7ca3cb6e99387484af0a65fb8b4855a995ddb
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:a3f192e4a58582917bfdedf9054cbf08c60884972ec10876fde3a2d8985ea178
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7fa9d757e01c2cc42b3cd83f296f2b3cc1cf2ec99248022cba7c6633b95c412b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:70c6c8d5a01291b1839853dbd8c8c12a4a0f4f227c2a5671d0938a202ac1f767
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:88cbcdf92a824d961b6c1143e8d0633d75c9e920c2195dc7b0df5bf43d7be238
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c0eab3eccd09d8b733479516dffcb03cc61d9abd6f72a231a53d46e7d3af6866
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c54c9dac94b649f4ea02cba3187d967f61cd6df8016026d83e93569da9bef426
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b33cc940e0e634e6f6068e261cf80fd8f938a90eb2683cc83852a6727ca9ce93
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f33e49286edecf46860e235e71a8074b0e9115ece34f724c1f9976e7b0574b23
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:89b8f33b83b07c6854adfd0d9afaa0bb5014deacea46f56a4a70a285c9fb2992
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:2653df0205811b6b6ec42929f993a04001121b962bd66a16e096dc968ada9ad2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:fc6130c91e3c6dd5fdc7b4a3ee05f295281c5e24a4bd8357b7ea4b7816ba3d89
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e22627c20599661be21004be675982c9f4f6396427922a4ab044639ea95bca2d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a1a68127176d0244b16ac842a980a51f583f9cbc766eaa866284fcbd6d63350d"
    registry: docker.io
    repository: mendersoftware
