auditlogs:
  image:
    tag: main@sha256:37859435dbb421e80da4abc5f11840a6e88eced133248a74a91dc74f4696a2d4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:336db5f85cba3e1aede0e06c81c07bc97b4414591c5433d37fff75f1495bb14a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:af8456fe3cafbfc651ea34e4e356e492a97f23e9452af22afc73857dcad3c3a3
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:82cbd2891e7d7fac6f8a272faa9e9d8e56d86ab8e4bea011cb56f74147b3ef32
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4b855d7ce3ba35b8e5874ae484873b7291127be0019186ae3e597c8d85ab9232
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c6d12d68a954cd745d54afda4b2bc17dc85b751fce8bed61835564f96fe8dd03
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b51ed3f3abd4b3065a7f90b2d7c6170741ac9bcf66f39c1a4e56e8ad12f9dd91
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4b31401e00371d857e4d38593fe737a2436f35043f96c52cb35cb9706819350b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a92f52198876570a7aec7742cf766e39963fc9757151e526e7f17e070f8aab08
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:aaf9ad25228729d883ef971fe25c3a7f62cefda63061f3bd309737918723c9f9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:befe7c8ee0b9da561ed6d8d6d50fdead633cfbea4504c4ffea22a4f2d21c2b7b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:dbd326d179eac92dbebf94138a4e7d43cf37942e30bc99dc9643b8f6803d5a80
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0260860d72312181604443142b099712d9cee7189349ad1200ceeb818e65053a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:aec410ba3623ec73ab74fc83dd0fe3c7f9d5f280dfbc5df00052af608013b28b"
    registry: registry.mender.io
    repository: mender-server-enterprise
