auditlogs:
  image:
    tag: main@sha256:3f7d2b95919809fa6f67548d48de14d2cf8c1b766762540a9271207095d40abc
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6bca1fd588417612959204c34c31adebf37cfbc8d03ec0646144d99ab29ed3c8
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:eae7c6b2e1c3159ebd8953386e5fd5ea40d94a6e8e408eb5034f5fdb9c154e5c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:19e148c1b464618ed1f504589fabbbba5adb14dd435d8317586b1d197a87c182
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8b1a23e9a25cae57a93a860ef9b98eeb604f288053d1bbfea6a79d52d34b4bc8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1d54673ec5a125f89e1f01306a9c4e1e8151c590c50371227a8b06fb8c8c8374
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3f670e27657fbc4bc37010c5a3a175e9d3ccf67262d98818a5b163cd10753733
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:260d631e7a7e05bf7edcaeea15dd6adce3835173a1a9c3117fb9da97ad4eab1b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:79dc8e427e602ae7bdc531f445e94e8503f6b1232399d9360e091735f0cc938f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5a4661e44c71e3e199318814d0b9cf8bff30dd6d5a1adb965ce0e2503bfb92c1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9d344a366818dc94629ccf27a5c4bee07545e314db066f10bf4ac2803db609b5
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:ea48de0b1ab312d1f3ec40a3a06d8c191863b621f5ed97d2e4aba763c5ae061a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:7573f00e84a5f07177ee2a5bdcb8a6c4dfb64b224dfbeccc5a473235c7458049
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:95daf9a91dc8a0489cad2ae30b4219d9c0cd24d931356656bf3cd8c2006a94ea"
    registry: docker.io
    repository: mendersoftware
