auditlogs:
  image:
    tag: main@sha256:97a75f990e191eb5c968fa2ea788b65d797b55c100956805115c966a6eab1f8b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:00c112bf4a6a4c4048750eccf76fae7a866e16ee7740f3159a5e22d2111686e4
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:513571e3e008dd0612baa0776f33f05a08133d2f71f274e48c42c2b3b797a898
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:05e1ff776e8a2345ab7e625bfd0d7363fddfd0973af63d01c707011124582fe6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b89754249ddec9277aad1d3cba5057510b69495f04c07ba9f4f1491552f92dc6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:9c9c689c6e13cd24ac8f236c8d1d1bbd2ccad889a7f98ffa673e7458880dbfe9
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3e902bbcccb541eca39c5c6e6b8ea9b0034a1561ab30f7423d23ccc48b5a6cc1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:932ab6d58947290b9a0564e82b7fad12e03ae58bbc35d6d9f2bd9576c6bc797c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ebdc8e44e1be45a8bc99a6807bbeff1f83d2817890698b3189d06d1303a578ba
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:eda54ad465b611c9ddb20a6e6b370e6852623331ad6b77e1a860d4b0c7ed4462
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f2fc8e80d72ad032d179f33d41310bc6018b434527380fa994271451a42023db
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:9dcdddc92b68512ea177d08b28dc47f02f059eeaa8d53b28eaf6d8d468020679
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5c369ed215c2c83f3aa8e14127b167fc5ba9955ecba22aa71acd737b53c333a8
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4e7081ed6f5ac46388384fd01d8ad42e50f8b1acc2b94e6d1f9c19064274ab68"
    registry: docker.io
    repository: mendersoftware
