auditlogs:
  image:
    tag: main@sha256:32237c796dad441f92d59843cfb521e4c3c46fcb6f4407f320d09f3d465da4e1
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:29e735e88ff3ef868142f9c7057bccb63065dacc1c3757342e0ed813433b0ef5
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2d63f8dcd564dac61411bd53cb126bfa9f8d92d4c75a53025e7165ac082b1a11
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:fc6151acad0a85bc677063ff3220602bd3a9f75fba4031a64d0d6d53868a64f6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1d051f59196da02c015d30a21587f0ff5351eba9cd090ce4fc335784b8653066
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:fbde8ed30e640339f4a643c67f9b9c2ca7a4c9ee0b08c22edc4c4cb62b360ccf
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6c5c6b677c0e9255f1de5603de6a3ccc19bf2210014233787673f183853a2894
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:247627dd55947a59b9ba5a003a551dc1cc56246ea870322519cd5ad5af6619f0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:18af0b58beed4a97184cfad4811c904a0f2a8e68a1df9133e9287ecc28aa58e6
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:34bc09bad33a3e5d37e4255bee5ea3da6510f37362746e5ca5f175e4674c27ae
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1f3627ea347fbb59620c5d25d64956ec487c8d6cb3895f350c77e98da36bb0f3
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3bb88412246895560b703ca6722a2604c2fbdd98dad4c6c94c3936985c4adf5c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e7be2bf2326e63793bbb25438be7cd09327743e972cd19dc74bebad9182395c3
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:771b67a9d5c67aebe0334a1e9f18f02c61f0f761febff77f4c740da780566fb3"
    registry: docker.io
    repository: mendersoftware
