auditlogs:
  image:
    tag: main@sha256:f8b556f2a36d0d7ec47f690308d6ef3c1c0c738a04f518caebb21ef2c3074cad
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4803736013d0415a89716c16b93888ac6d37249273c2e5d5761fb80abcda64c2
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:52a820f167feddc0031dd111b3f6f1c8398ffc2e6c8afa091c888fddc474f83d
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:a0de23eb29534eae083bf005843ca1a9d785f3b9d2dc95263e7b0f70261bf8c8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f60d88bd98424ae0d496b430a3530cb72c9f45d16c8b32cfca50c5990afee697
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5fb0e9dc27280c43a56e72c6782e4905c2f4337c50b417b71edac64460247bb5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:1fe2feb44f922255bd4b594515d6f47521aff1bd3249e120ad45e48e772d8a84
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:522956dcedd0b92c6795adad452c00346e85e9f978f47e866131bb0a21a18bad
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:82b8e6ed731190f08273845833e10a332cd426e7f32049445297c539aecbc322
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2e8063afb61f707039b3e83a1938efd9bb4f80f796cccc5f75f98d1b06fc41cf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f1999f8e8eff14acc52c5c060ec2508bb8787f1ea1eb8d36f74357159dff63d4
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:84f3f1933749a3a7c32f424bd433221f6dd903e93a49f11ac612cfec73e3cc9f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e9e28c0be5486a3ba5f9207609c7c73a1c3e192a5ce9018d0ba71d7bda1a9bf7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c941e04088fc773610547750f2ee2c04814d902dc36ef4d4701dc4875786df13"
    registry: docker.io
    repository: mendersoftware
