auditlogs:
  image:
    tag: main@sha256:795a96d106027aa02e6d252449bd748ab75dd5bc0f61cb440cc8df59707946da
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:abf8a4db5f71646290393a4fdd39f9907b85b2bf502d46b4feec069d68dc9089
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6c83b3fc97b05d3e801bff58b2fc92911045f9a9abcb8e8d3bf007eb1976c8a4
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f77b5260bcf8c45b4da3b947481014239618f99c97e324f58558cfd76c9fba00
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e289fd03cdcd2c8a58689c11b219119bc74db67894655ed91351d26b9035bd32
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:134d9fc24025ebc7d4611e44f25ddc65a23a14734ca38b5ff4926b6e8a2a8f51
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:49c6ad15ea5b000f5a45a745d0b379dd47a4a59da0a79bcf7697d0b84a96914e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a1b9900ebc317ea49b11ceeed14b054fe3b5576a383b74260e13e9a1c3eb34b8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:427f0d9471165aa076bbf5e750ff91060740580a9863436b9a0f4f61f02c8916
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3bdfcfb19308bb1a715bb0e9737b7f6b419666233927273ecabc3411c1db96c4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0595ca89f99f85c1ea023e0eabf44140da7051dc04407145b6a33bed7339f266
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:754f695b716115ce332f066c02fb0f9fa6c16700950e980903ec014e240e4344
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8b3ec189006d885f048e650c25f46f3868098ab0e401d81cec206bf67cd35c8a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1d733b34936aa00a1b7445ff8f46d38be54dd0a70786f60b374a80c11d13753b"
    registry: registry.mender.io
    repository: mender-server-enterprise
