auditlogs:
  image:
    tag: main@sha256:bfe8de1390816675c47b3f7898c74ab9588291cad0b14c4704a450a610dac2f2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ab912fa2b98128cae2f337a7224944639a8759a061b4aa7deae410111a83c7ba
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:15c49a70e0c6dae747ed317da24fcedb589a92d03e4a7d0c8ef09923fe642b8b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d6e85091cfd15ff76733b815043795f69a756e5da58de4b3c34f79254d18dab1
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:87e84566914d9ca3381f00ab3a5065ff62337c01877b7f94b28f050d339e2d9d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:28992e185b5eb82759e63fe4ae8c54984c7127f2a9651c11436f280a70ee86ef
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:134fd5f0ad6179c65a6b21223308e8f93182d69032dd7376588a7bfc9856dfda
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:86c9b68420c606fe521352a450a045b2b6ba86e0bc68b62edc61cc36857ef225
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f39c5606b685b9c63ea3bb1dbe13cc846eae077383ae229a9cc62dee973d9d69
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:728c37dd82aa58d31da4c76bbf585e4ed3e7a5a1b4679fcba01e6dc50f7964db
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7d627cb2cfe42a40fa7363eef7fcad7cebe9cabc5c6dd72978fa6c111cd3269f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:913fe1834917f6f9bcdbba91676995b72f4ceb38858f688e4bbbaf8d474e4d7d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f8a16b387350f85bc01de3ca0efa69476d843fdc47f31479b6f921e55a47fb33
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e24666f31bf1070a024bb02118b5503af83e392d48ae6a7da6e6fa97bcb60a8e"
    registry: registry.mender.io
    repository: mender-server-enterprise
