auditlogs:
  image:
    tag: main@sha256:591f3b8d3bc9a78ec75bb9d0c0a08a4041300fcdc36f32967cdc94142b47dd77
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f6ccedcc7f23b56c10d3aac1de6f3e7298f45fc780766707953fcb807811c167
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:76f91cff1fc59b23cd2a4cce700be11aa840f34fdc629e4d4b223c5a842891e0
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2babc85ac29e6ca9ee6c154c2d59081e96e8e5cbdc72d9f64275e4d8c67b6d30
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2677ce90762d905e98f0361d2801f7ea0f2d855d7142318ee77810c95b61e5fd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:12aece36936014a9e5555e64bd921d1dd58e182a9c52d5a573de2d077650d638
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:1db52cdefa44adcac0a9d70bea23647a408dbfd9273884f609ba5e8bd04abf3e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b0248c0548c997a02f6510bc006de36169014e6a9f588422621043f55547ead7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:54b074a96faee715f3d1327197310959533f9eec575b964ed80baafcfbcdd383
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f544ccf23f7b2d8f69b474cbce45103bea145cbc5b0eb0396cd479dbec466ab9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:decd0a1aec00277f6eb396174b807e9da6fe906fe17ba3e0bba3cc145a41e131
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:0a45ffc40c74b3c65a4828ae1662acf01f69391949f3d2a550d8a71635431637
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:beb15d220eee3402c3242ba286f583e28190b4de5ad8239e94e8b12baabc8edd
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e9dbe54d4742545b272ddc132b735daa0bfa1de8aa602cb6faa87e5aebf5e754"
    registry: registry.mender.io
    repository: mender-server-enterprise
