auditlogs:
  image:
    tag: staging_8fafacdbc9762979a590a2fe580899f1b9dda5b4
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_650374036d4b0d36969d3fba4fbf592c4697c95c
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_be08a64b558133f05202c5af83535bbab06afaf4
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_7bdd1b5b6b899addfc39bb21015656333734f576
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_23ae8454267be41e3c28fbc079e6b1a38ff722f9
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_9d117129c54f6f1b5a1c467c39a5d2b230897a5d
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_67c3bfb073b3486d777c57ef82c6a5afbc88b542
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_ea56a6aadfd0a0789ef8f736a9e42d6c0bfc1898
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_a43b62134d9538fd98e6f7c7044f9109eef93822
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_0dc697b1ed1f72cd9f85150a578f008bc5769bf0
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_630719591b75ae642b822e9221161213b713ec77
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_a439511e22771149b8f342b694c3f5c1e06c2bb2
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_9f88d651c16dd13c7fd3db62e46c2b100be0e2fe
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_688140a05fcd9625c23c2517b8eab8a7289e52b9
    registry: mendersoftware
    repository: gui
