auditlogs:
  image:
    tag: staging_fd2197bbbe27df1965e55a24901f973a493d58f0
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_5bff60e92b96bcebc5549b182d4ab5976d32be93
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_a4995fdad64fad38efa9c06dafbd3a330b41623c
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_2ac4d25afed00e5b79afc9ac312f099d8d8da18f
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_523e3a240b93c4d76e014c2f7aa4f7ae73e190f5
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_58307e18071e96432f1eba76453a8c38ef9d0f9e
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_f6ebe13223fe5ab62fc84a76fd92c9c3cc435a32
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_fac86762ca8cf3cf71d3e90f7007504a4483974d
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_d1df880963fae87f21783a144e84e413e2246c98
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_1d2c3d751fe56e3e69e1c8fe8b59d04b51d1eada
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_b358833c14e60f41e3becc0b8267e1815e0ded92
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_7e4b0a94405f4c622c48b5ec22446e79d3c681c8
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_557648e02dc09bfbe7118d8f6f91f919249c0105
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_04d0a548b22a7b59483c7a3f421147bb674ece6e
    registry: mendersoftware
    repository: gui
