auditlogs:
  image:
    tag: main@sha256:ce9d475aac7307672855f05797ef24c2153a3ae1b986a54f70ce275979fc1a3f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b0d2aadbd692d94140b6b38d0d2c49848df58d76da161c4be647a768be56b3d6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a30d3ee3ad11cdadbef34c75ea60cdbebe022c0c3621fccbdf84c6e79cdb081f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e8adf30a7f8fe94698670e15cd4f3730045d16341c5af1322ff7ae87ee20275d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e3cabbdf7fcb3cdfb5d28803ed8295d9e07d8fe3956cab2c4bf12c9d57284b3c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4ce4bdae336e67a7645fe7a5863bf47c0caac7ee7cd83426a3849a6ae356e4af
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:506dde9bda4350a8a782dc0d3e149c4e8c96b38514c13b93502fea9b0721f48b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d76fa69e18b4835a1413f9ca41cba0a19a12f959441a29dfece205e8dd66962a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a6d3414635c4636828eb88e0f18816aecd12cec3d6213cf69daced57b6de365b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b5751ad071cdc570d6b6145af2ab12596c6d3b896705a94e72a33d7799810747
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ad4270848deaf38cf87c1165ae347ff88fb13f5a94cc802d3617f9fefe5e80be
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:113e0c996e4d8efeda0ea5bd31288f5ef07a3384d2fbbf555d6d54b064b2bf64
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:10ea0cef63f4890577a331e5c0d467ad528d2fcb9c505e137048818c469196b8
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:5af51892a9c6a32e7770237e361913a3f5af669a2543ea56536b9e316073fcee"
    registry: registry.mender.io
    repository: mender-server-enterprise
