auditlogs:
  image:
    tag: main@sha256:097b6e54f59989ed9bd484fb0c74b7c9b7c72b1314530c60ff6675314737fcd5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:967cac2a93baddba24406fed8d3e8fe93ad4c7aee1cd0f329b5333d7037ba8e8
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:edd766b1c5d18e356b972e7913872eada9213dcca4d19236c7581ecc55362a0b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3147ffbff5f12a5e177e97e26f8bdada1a19a96e4e80f0222b9bb1b3885b6866
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:43d7c2ac94be856d577c7308ed22cb391f2c2bfeadd42c035fea38124770db82
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:508b101cf854b5446684f6071878c75436a315e72211d84ec165238068c7e5ac
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d1ebe48fc254947e8b32d0afd72e8590851c78ce0aa63d40f712ae4cb407ab84
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3b2da7f192b61303c88f58db2bfdae155cfe067574a5163432d3f63ab208055b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4feaeed50c7b793bd48bdffa2926205d73026e8ac61e237284670ccf55c73a57
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:cdff4e8af4903ad32a81cbf7db2deeac3f9cfbd10d011777f99d19c82762b52d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:94cb2ce50cc00ec5e6e2afa4ebf9e7dfbbf669f980b823fd748ca0215f921741
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:069427ef878412c8891b403ea4f6db87c3652284d6ed7070c2c48b4d1d0678b0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d4a7e8aecdc803826fd6bef35f670a7ba31506f48c0eb53dc42992b0f0cf0b5f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b6b417373587da5de322071d29bba0da0873837de312979d8b9fc9cd09ebb4db"
    registry: docker.io
    repository: mendersoftware
