auditlogs:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b4726e77e79e75c63a759dca555ea6ef704bbca59b2370f95bee2593c65a0918"
    registry: docker.io
    repository: mendersoftware
