auditlogs:
  image:
    tag: main@sha256:beb95f700974b1f1cf67e4bc5728e03212e64981df1d2b41ba75faa47badb7ec
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:21d6115df594bbabc44e6d1e1ddc00f374563f4667a4c8e965f3bba2ab991ac0
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:16a451910dd2481de09616ae562b0d6794c83e7dea982df6532ec603fec914f1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:4ade8f4e9aba3c650305f40c8de5c38b4a4804dce11d81eb9be04b5082ce9490
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:860dec730dee7e0fdf6aa55013c434d751026e72fda719d53caa03a1d24cb9fb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f75900dbf30ad56191db361fcacfbae8e80fe3d894069693115e953d9c1bba0f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9d9f6ea2cf305acc5224a6b237e8cf8f1227514ff55a0cdcfde6e109d4bdc018
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:9ff982fcc48c404176801305212b649b0c9f8b9192d3bdd8c3fae64598a1952c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e6b79685e55ce7dc57c382edf1c448e4eac58da51caceaae1c7272cb66a20549
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:70cf2fe48ad3b75d6d9b116ef3afffe0b1659a1d9828325cc215286d82495aa4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:56427a4d45f72e8eeb2cc372a5d43d25f3d6d51facadfe1a30f9f87a45cdfa60
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d5657cb9facc35012ab20cd111ebf5cafe67dc4816fd0553f28e3e62ceeafe83
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ddf15e2ae679e8aeb6739f5dad7d750daa9a9c2cd297ce715a1e7acb151bacf7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:36ae61b1b7d178ecc4f958c48cec401f878c3f96ad0fde44f62684816bd819d6"
    registry: docker.io
    repository: mendersoftware
