auditlogs:
  image:
    tag: main@sha256:6d3f3268fb06360c8667a678bdaed71dfee7787785cc7089d6fe0bdc1267b655
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:eff1ed2934b395e107eb8f6a9083921e4f3ee14dca144aa2d9fa6317f00085fd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a3fc0eea42d64f5cb9b6d966e79ebcf46f4b1704607285bb31c6855a72a717ae
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:166139d1973d98700111fc0414dc100405264cb269c0983e54a489705f053eea
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:04ba446d892cf35be6fa380b21e7a0e71e7fc510aaf1b099b3c4d68a4d8df2f1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:bf6ac7b74b9f5bca5908ba5f36aa0fa320257fa0136e8bd70d2435f1e0ad0aa2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:11b1cb87ead24a5d84d45f4ea6a84e6c99b25e59568fe99dcd4dc73865ee51af
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:80f7c1a234f6abe25f737339d59307e4277de2f34c749dfe87281dd203e531e5
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:36b9c2ae81ede3f9e15ff99396786223a9f2718830395e24d90f7d03f5668e16
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ba706bbe58ec1a94ba5b71e4ca6c5b273f0adb4d003c7204e6dafb69640da186
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:34b165b5d7ff875bd09ae3a9f57e3702964fe270a42249b391671e42cab8df74
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a742f001e54404120047f871c16f5e427b66e2b1c0779b71a9092ec0341870a7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:574d837bf301085a3e09ebee369f50a77797d39be12262f97ad2f3174b992940
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b139172d463f6eab66504176fffd383c0cbc7a061a04dc198671cad11615f79b"
    registry: registry.mender.io
    repository: mender-server-enterprise
