auditlogs:
  image:
    tag: main@sha256:3717ced2a822b2ca6c0642668bcb341ce31cb0912f277c4ce7db2cc20c35137b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:595923777996a5b994aa2019aa0a368c1b637a867f6e024fe8f18b4584cb34ec
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bdecc8910db9a749d8861677dcf8129f7b44a312535addc6d72ba4715689a834
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:77970b3e872cd5656550371253b16029eef6771b817493a79c832ed9ba5cf982
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:72caf369165179322e745cc951aa2b5c10225564bbc3334f1c68a05922275460
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d1017a629f1b697f5e6dadb53b93298d1a04256764ea6dc2896cb252ef78af99
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:72b9bcd35ba537db65246588d1c091265e194e112e9b644b14cbc6a0b2f6d5b7
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4cf7a13c9d8c613a5233a61945e5af5bede12e42d4e0652717092ed57758258d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:7fe1e3009d1d7ac909ce5e6c84dc26996146e4d4dbcaf37249e8a89fb70ac1be
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:a7889ab6608aa1325e2c21a340f496f5d3344e94198450d48d58d2052a957fa0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d5b8af55bf4420f9d9b5f37c4a731a7691f66db48514e1388547f8ada3c8bad0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1c940ddbf0e4c021db892797ae32ce28e9aedb183749743cb92e49d649207a97
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:bbc9181772d93fdd23c1fad55edf8826ea8aeeac3739a58ccde46955a8f24575
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:450df72475db4e777e3c456277e3d8032e6aadf41a50092622b052d37601db93"
    registry: docker.io
    repository: mendersoftware
