auditlogs:
  image:
    tag: main@sha256:420a28930b798d263a359796764ee2b9371c873622086a215d265712b4ea0bbb
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:58e3ce200d5f004f440a39dddd49647e20c31b1d2285f9e730006294a268e785
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:48a4ce2222d652afe6ac7070f83197ac5d360a20fc2b6edf500fa1bcf70a078b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:dd26a03e26b7f364d7e79a6f0ca1531df0e8d99f15def7fe58075412c574ec3d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:69da6ba1e760f8c21819d038d98a1964ef4c6dd480ecec5890d657c6334351fa
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4cb18e27d00b3064b17ba5676002e459fa1d3cc9192cae3c4ceff5844bb2c404
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e29e901d5b96068eb11a52f45de4fdbbfba51bc27165bcec5dbab1271640d220
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0a37e806255861107e60a10602ccd946f6921e1bb47e91f1d62c36431d821186
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2ab31a81355295a16484f356ca4297000fed486e61f31fbb3ca01bb41045adcf
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:05b11c2237c31545bfba191b58977e38b98aa04280bf77db560f57557ee96a7e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7e6c982886b1cf77beb4c98294030b89d33664d7ec8f46dca1569636277b545b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:aeb50ba53abeffdb3cae1848b69760c97a1406d967d36a853d47d293e2371512
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:46f8bcc55f3cd59cb0b1dce625fcedebbe72ef370f10046dd6807197b3e08cec
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8ef34c3b463acd2d5b00cdebb61d598df0ebae832008ecfbbe21749f1e103c33"
    registry: docker.io
    repository: mendersoftware
