auditlogs:
  image:
    tag: main@sha256:88c31bc3459cf385d6fd584b3dae2f549259ae13a8f0b923985ab59234bbabfd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f8e5059526e9690aef22cf8eeb012a22735fcce78e2358e83d5dc848f8fecb67
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ade5dc1cf03b3ddc26a5c50b9de66fbce59b267f3fc0a243d762d6d35ba74317
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b2b7e3e5b6d9b4db1de85914ae02efaa329c9413c47dbbebd23591881a6bb241
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:73d22a3c66cf654469df9f3145e40f65048b8b233ef0f3f9c8bd94b5f2e069a4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:375a5acce0bbe1e57aa5312c4af386aa8182f76b4495539694db51dbefba0d9c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:41dfcab683915e294c1467bf878e4357d9a199eb126ce5008b2f309ad52ca04e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:40946373e8435cbe239f662827f6e0a9e48d099a07ab3a5afe4892439e6c30d7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8abab447c3a113664697ba9d5bad423a554bb902dca47c1b9b3bce8f8f73c9d3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e7f93a1e429424a72140e525a84e8f1faaa7b548f58a934b6321c4c1c48dcc7a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:39d051c03d5ecb2d5137ca0edc9f12155a4d90b2c0dc786289d7241c9bca6519
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:9e0c4a88e0a972761a8d4b3620be57609a86a66fc637e8986183f8f556a8f53c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d5acef6af4d5f8589c29e10180aa0d5f0fed3b40138ca85c7c136ccf32c9767a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:78c2792b4bda7f752c7a3dea7ef188f26953a87b6a43d9b8f2595dd5b8718cfa"
    registry: registry.mender.io
    repository: mender-server-enterprise
