auditlogs:
  image:
    tag: main@sha256:7659c959e7a60533a60e004b0062aaa35b1a4c4ac3de230971ff2a7abb61f9e3
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:099e7733789750747c36126e763b208ff363c85ff921aa2a77b7d7b1dc637b55
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bac94e89d57fd96550622ab7c00a9dfa84f5413cae5299a382da855459ac23d8
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c1ee414cfe5cf0c963575d2552e9668a3ea11caae08c798b8f47a640fbc8ab36
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b2abb778f89f5d0fc41796e0d1edc1ae215b0352fab36e2175bd04759c257b7e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0790277507566eab2b85aac5c1c0d0f0eb8290d224ee5df6b2290662506de9b9
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6d711ab913a3ebd89e47dfb22ae1dedc80a8bbddb8a1edb1ab497fad6571b977
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f10ac8826b01eb8644a66f4a2b4e57855d5eea91f5e6a0670e2e8309d6e74df2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a10818116acf134773e94ae6deeac9fea8d8b9f5d4e86279ac15ae940a9880ae
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:79c8d66b7b81d9e3c238728ceb7aded62cea6a924c6f56ed27b60938af380bd7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:51fde51301e54edae5e020ac0fc09a5a538f5608ab1ab0b2fbaa116c8c37e123
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4ea8e7c7585627069010e4b2ec9fddbd303def817c0d3d078826c2d1b33d283b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:7c7b89aacfe0f8b1114bdf1c1fa799fb0c3102fd49ebe8f31b65ad4489bf6710
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c05b9b13d7c6eb1f5a75f842a2316225f2a47690cb1a0e5bc7e1d94cea20340b"
    registry: registry.mender.io
    repository: mender-server-enterprise
