auditlogs:
  image:
    tag: main@sha256:9cabe2b8494f731aa77b5ca32b3cb407ab28fc54470d7909831f24d6376d05ab
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:512ebae8101cc4d7aaeb48f7485db55a28b6fe4d5207d306b86fa43e4f0abc1c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:eca87ece08c66d0768c7f7cf70f357094008b5eee6997a1f1d1ceb5ece9a453b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:eada8898068d67733a035eff19b2765239c22dee52fd3feb2ccae62323a79f87
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a7972d528aa1ec0361b881d0e215e5e4260af4c57bee7f7db3f2f79d190fb0ca
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:49749e9805297603856f4ec0ba4217524ccf39761a8f719c077ed7821176e7d0
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:93d1bc0dee0a68c1380e1f60e4c1423bcad280b33d45939e4f43f89fa73159d3
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:85b4d48100dcaef68fe7d722b874c1aa3f0d4bb2797b6027253d80bf89986a2f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0bd75c2f53fb051f663ff85a9bc4e5c7cb599dd6c4bc3c1de470fb30f4c4ee5e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7038a610a7334cc62d676a8d89e55cf4cc88dcbc6f14f75c43deb5e2032bd834
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:a0a24ed852fb6fb6804916a3794fd798e0fb7117faf2dfbd993a8d31fbfaf716
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:96f562b1262f634e462fd414fa15a3b686271ba3f4fa09272652322a767bd3d0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c7436511336facb8859a9c1351df63feb24387e7bdbb8b06ef72af8d61bee211
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c4dbc94042e82bc2a5891185ba1ffa43475c17c121bbc5e63cc14822f1a38701"
    registry: docker.io
    repository: mendersoftware
