auditlogs:
  image:
    tag: main@sha256:b9273c1117e99f6de12f8eb59bc989ed20b2bc4f5799cab8cb94e48dbd5858c8
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:0e8c293d61ac8f3a9a5d742b8b5cf404e773cfc5749c09afcc6834c74b68c3f7
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c482bed9d15721f90265595fbc662afef3dc3f011972a0a2435a13f631a2f329
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e91077086ae8c5e77759dce9a76cfc27e0dcc75d318d42879dc1d8a6d05926fa
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8f4c0636730b6160d3d3908d0e82a73d9aba366315d37e3db4aba8b667c31f88
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:819abce874f403323ef8bd84f5b4c6e6848bcbbd3e173e1f28be95e8a6b4eb42
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:90bc2a3bb0df70ddac3b9f961452ef8251b6c7ab0dafa37ea10280c76bbd95f1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:aadaffad5feedd41c0fd8f2e101962b2b0ec3501e94470c336c702f533229ccc
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:83736a121cd5b6301e9a9bfdfd940516c8a92f1bb2888585e0d7b1aadb91f6ce
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5d2b1ebdabcacf1e50fb4948be68299cf5dc647013c27ef312da5a6fd2c6251a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:831d296f4977e8f41be3c80a4c7aae2865c57d7e19487412ec77e6fe0548aadf
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:27688f21d5fde7b28dda262c89fedeb5f25dbdcb804ff496e3622a4ab1654955
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:597fa002da4add9eb22d31cfca7f96148863be76cc66bd329c1d60833ccac787
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:422c76d08b75aa05535729ae23200d547348c7a3684a69bd134f01b9101db01d"
    registry: docker.io
    repository: mendersoftware
