auditlogs:
  image:
    tag: main@sha256:33f567d2fe97228081c4a213b98ae2c6b43db220bc7b3d99912ca72fa6be6644
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3993983d3c80e393a90bad02228ca8b3b5afb75aa227a431aeb0312ccd9e7b67
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:fe9224e8d209686bdc6de131103a45994ef7282080ae53f37d08afd965dc5bbe
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:95bfeb571deee85e7aa21dee1ac0a21a3ec2ed5e125d8c378d7fdf4d12aa81e7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1f1e9eb4ec14d4f594525ac508b6daa7a7a491c9b6e0eb5ec9f3b13da1d2a0d2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ab1a6f1e4b6bfd72fd68c332330409fd6311851569e1d4dcaf4c2b92a2e153a7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f0f1f5be937bcf63bb533c83bc799c0cd078eb2e72898fe6887a81ad67c46c28
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:89148e6e8206672e90565f210146a06d020b4d23f9033651c38b89a4f3331671
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:74857f9b0a7ba195aa418a27256c9033981324614d37a07923b8cf07409f9e44
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:999d1fe6f58bcec7c1ae0ee62e414c70841ded575dfbff14daac6c7e44af2c0d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c89cd3e551d3c69e7aa37f6e1b33a7ce08353e478e591bc4e0c4ff6918feb7b1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:9b0939c460db5d6764b9b49270c0092cb0ab95fbf001d53081c9eb33e6bb374e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:434965f167ee43ab15ae84edb5a83bc2bd5eeb8a041bedb00b75be0864aa93b7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:de7db948fd49b327fd27205ba007cefac2b2ac4b54572f2782acd53ff4b45fda"
    registry: registry.mender.io
    repository: mender-server-enterprise
