auditlogs:
  image:
    tag: main@sha256:a0d6c448b3d77923a13c1943e7229c5eec5abff2a0597960c9176d150f02e7ee
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ea83e5aafcbd600fabe005d589c0e7f643d3bb06a7bee70f19af7f01e218c16a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:04ed9d2448a70f579cd32b372bbb6795b8170d384fb798104de78875313da3b2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c5907c2a0ded3e05a4454c594d1f9251404337874f7d531a9321043fdd00856f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f9185e4c554f73cd147da3fb027aba693f6aec7f69a4af579f947750c51044e6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b50b9df256217aad1f2e33409c2d0d1d804163a1049a60bca32dae1dde541edb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6737f7766621bddf5db6f6d47a227e71aea229e2ee0b2bb1afd3cee5bc38ea31
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:60315da31085520f454748f3c99441ce83dae52e5bb926a2d27548febb181019
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:1a3d13863b12014a5c9ae72bef170e9dbd0ba251d104eb5a6b7198345b70d545
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:45cd4b45ecabce261f5bf6fea90a27da4517122bf1d769d0def5a106eeff577c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:adac3ddf225322a564a6d24cf421377a7216ed20fac8bfb879d718c49a186953
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3f8d3e49af5476db542f4be7dc0954e01873ca75e99c6919f15dd31b7e27d37d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1df98d979139d894a13ade1ec00f84add6fd73ff4f72235185acc1351c93e49c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:5424b2eff454c87527ef9e84fd48330fc71873823ceb86f28ad357a42c1621a4"
    registry: registry.mender.io
    repository: mender-server-enterprise
