auditlogs:
  image:
    tag: main@sha256:ed779eaaf3a53f6a45bc9134f5bc8ab5f26c4e6d7a1f2953dfc224093e3d73ba
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3cd7ac51a4cff1c2716e0fbc8a49a89c4a97d6515dd473258d552973acd19259
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bd4abfdd95707a6237e298369af4b62242c809a2abd317cd5182abb95dd50662
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:a1dff9fb681b6b651aae8045b6ff0be54348d6b9f9dbf23e11a29f15e16f5284
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e5da44ba9f1a686c933f42d254a761048cc18d200404a7eb23a92cd9ba511d9f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1037f13c15ccfe2ab3ae595209feba1f13151d7739769cd30f55f0684c248ef3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8f9ed31f6bac234a60bcb3bc939cc2168eb780a4fdd66acb6275e3cef279e7ec
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1fa7a52c5e5a3a7dcec287239a13e04952a53700191f71dd7890f8b172f1bf64
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:64eb04dd4b7d0fc9061eeefea27f4304a43fd55c99c0e21736a5413cf8536fea
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:03381067bea2871842f7dcdb01176cd84347968a7c3d914ab7e2fb15c1f2fcb0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:dc0a4f35cad0700141871ff8783a9f43829b30afa6b67726b16c091e1b0aa682
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:65e71a0030dcedb7602c0eaee890d0acf420ea550318475221070005df9793f6
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9db2edc886845bc659df81f86c7d702586318606cc16b82a685b6ebc66cc762f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:47287483d4be3c0705cd2d44334dc2917fe327de66fe2357a6379c9e44d6fdda"
    registry: docker.io
    repository: mendersoftware
