auditlogs:
  image:
    tag: main@sha256:0f168dbd7d547b50221cedc5c6765d042f931a676e2fef547193aa9a4af0c3ac
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e330ebf0117becad95be7445192d85ccc7d11bf9ce86de92c7ef040b4fad347f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:67d003c14819e7584511d95c8b4d027471f11633ad8e7a14bf933aabc9c7dab9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:476e36445e57df8ee11e058e76f507ce0a7da6321abe59f6594e0230aaf51ba9
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:6b6faf90209ec7f14ff4e009905dee759e6745be1a5da71473cdf4f177aba940
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d7e83238a400626c8128c5efb9f204db0f5936443ac0264135e5f6bb4abdefbd
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:40233afdd38b703e507e03891bab101521f2a218272d3cdd4e5764aa1de3a72e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a7cdbac247a86a8cb1eea577f8964ce4e6715b7718372e3c057d777004edb34a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:398ee8be1b5ae7516090f4f8c6d8d9f8fcd99f7fc8ea7262e26defac23469763
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:49b09f62f1539f9c882b905fbe700231b1f780a5606672f189d81dfbd4b7ea61
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:3f4c93d89e9f74e5999863b86dc80c9a999d71f05fc191475364defa509c3c71
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:73e87115acce97ea44aa01988cdc6ff806afebe5f72933f6781d60015d98de70
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0e205c0366bc7d577da561da8a9c47065db7b15d79b3370bd19ab9dd4d959e29
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2c6826aed51f048b87e46edab509c4be0f1ece6016949b2e2fe47d8fbd0b0e38"
    registry: docker.io
    repository: mendersoftware
