auditlogs:
  image:
    tag: main@sha256:0c8516590db2d047085457f7d464ccca022f0963ae0bc4f84b99fae778513bd1
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:cfc1cca399aedcf05018f80c024d53ae5b15c312245e086ddba75ae954496a26
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3eaaceb9b956f088e85e0a5b01d9ba93912012dd4f7b00adfb3e1f7d971d9bf4
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:53860720cbca37124afd549ff73e1aeabfeb87655accedf4e9abf4ee429abdb7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:191005891280804af6764a67cc26e5994cc34eaff1e2a463037c498a80f2baea
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:1aa24401a121a3abfadb17b9a30e238e8a564b53f9a9e5e3541b6332b3149b0f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:024fc20984941a1cdfc25aca09056a0d51d0aa857f285d32bf86f07acb6ff2a3
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:95dab78f93ccbbf6d4073cbca718111338eda791bcca7cb0970a57a7183adabb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e75a91ccc66d38c5ef7c81de772bedf901490ec952c02f8e8b3d8575434452d1
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5f5b9fc9c6bff1004448241d6df3eaea563c52156cc775157d4c0e6128792b47
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:70fe7deeb5861e463fcbd9c58970f498c26083d280c3927c03bcda10da5bd41d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:ba0a7dfca999d4172f79fad73ab3b141bf6fe7fe6fd1853811c0e21e51a41361
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:86ed281369a3359b282a006345db8a6fd5bb6caaa4da1f423635f8f65f451a64
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:941bc998f2f60cb839c4a500179cbb4ec51ffb02fb9aab0f4adeaa29d1784312"
    registry: docker.io
    repository: mendersoftware
