auditlogs:
  image:
    tag: main@sha256:3f096a83f1080e44c7b6a5a51a4c3ad158b6059c8fdb9bd67de81fa6fb2f1997
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:235738c15538b3bc6b537eacc50ab1115959476305367f25e3eb3ecfb5d10ba2
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:98dfdd2a81a070055d2c82350cad56753de9a7607a6355a4f0ba715fb59e2adc
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ebb700c4402a1635bee100cb6ab3c44b2b0ffdfdc3fbfafeafb8074217964278
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f2da617138678fe914448f5e565fd4c495b1e1877c8433d56f6e547c5ac6b646
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d8a6e8306a9d71b9469d541627edd045bc2f33c32b542562046665d29ba96370
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:da23db75720abd4671a8bba3b9aa574d58b8e96f2686efb3e219943dafb16ea4
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:83e61cc57ac2e8abab90461178c879c2af922dd6435149d2e449139c0faa2871
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f1067cb544ec3ad3be3bb43f31ea789631c6ec8955d77e262c169a094b18a79e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:db0129b8c259b34d4ce3ec982cbbb646e67c6a914a1e7b7658509459e3e4cdf9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:76a133498282ece7da4d109bf16c9a3b509a6b62f86ede7de6de1295b2784a97
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:723fa6732efd21442dcba750a5cec24da7bf1c808c08f64d98e9b53ddab9bf4b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5f90a1ac6deffe3c9d56befbc13a6c4d43a2ef0b446ae9945c98f92ea881bf90
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3a5c4c2c16c643312baf17ef1edbeeb17fcf63fa0f731d7833d9271dac66ce04"
    registry: docker.io
    repository: mendersoftware
