auditlogs:
  image:
    tag: main@sha256:9041eea8313c0f40ce5de95fd60db9cd2e0425b89349c20788be7a0075fc96e9
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4b6a1c0ee3f9adee24f8fcf06793041470e94f2d1c96cf29a84f77d453f8ff3f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:aeaec374738ca572500af2a8c25c0488063704a3f782ca2b4ab2a7a538c01f48
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2f3a5b62017c3acdff4a0e7983cc510d1def6b5b47216ce04c70643560ca5def
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d6c86f0061bffd9ab826e4a60afa5da68ab51317db910b55b444a3a18417761d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:94d17530befc64e6887672d19c301ffdba61ae45a5ae14f9393a33faf4f5b60a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0000277e810260cf4e3f6744a4d2d10ec13d2dfec4a359cf0396d2c5aae6cd83
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:39c1119c9d20f1f93448312a1cad28a2c4091122d24ed734eab527c33c74ed4c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9c1550254dc0b09d2f220fd452e82f3081a194b16201185e45ef764f6df40cb7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5dd2c4e1229d83ae98d2643618991895efef5ddf3d9a5abaf32fee98c9145009
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:00dacb3b8b37fb3dcef2498bd9b346bff1a5319fde823ab1b59e6aaa3c3827a4
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c6529798f1985c7283bcfa9bdd6f77071884ce986ff6ccc8b92fba05c809d9b2
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:48fdc78ec7c78317b877bc1365d07e7b9aec76323e6c3aa34bddc9c38b477370
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d585fad3da8526769eea513daf059358a0eb850db0628ac8a7e08c16d90a6767"
    registry: docker.io
    repository: mendersoftware
