auditlogs:
  image:
    tag: main@sha256:063eec777967b159e08e2ccfd2d07326e980711fae39fa420bce94eea570e4d2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:66bd854fa3bd9f1cc925d3227d53ee92d4aaf6de4479f7565fc5c085b57c2bcc
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:9a49248c383689e463969bfd405e8455b2dd343a7e2dad1e078e69110fdb544b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:84021a4ceafb5c4f4264fa698a2933b2c3c2e603387035c64fd416f8042512b9
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1b6955bcc3713cd9bf111b2aad5b5426e12f842c190202b5ed753eaffaa3bf50
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7dfe22386c5c8dc99965a585cea5a6b2f2cef7a3187a1880a6a1451a992a271e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c7fc685ac7708e371bf6feb926568c50b4783021bd6635d62c57bec3b9b7b7d7
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:449a96e53b53515f78d699968fc0334bd9bfe22e3207a92e1cdb9d5f5b176f5e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d3a900c70c549f637c808581bd6d74c34fbac954e25ed8b4e4fa64cd9744531a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d5019d10dbfce44a256b4f498ce6819c1154c494c3f2a734101ce141e797a79e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9cb569d6c392bd98f384387a30802a2121eb9434e99936f673f9c07548541b29
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c93c7db8737860149cffec88e0fd0ef894535c1c412b5da21b6712ef9e76cc55
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:15b4d9bfdbfed2a18699403f8ebe16160286be42b922f99feceb2580588c9dcf
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:05f070929d7c59fdf88c6aabf90311aaf3f6675f6b846e0318130daa2b1e73f0"
    registry: docker.io
    repository: mendersoftware
