auditlogs:
  image:
    tag: main@sha256:5e9813d672cd4b88c6c0974038d9106ceb2bc9e4ecd05c18e77d063fabccbb93
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9cf67c897b9bd22ca28f6aadaaf158e6de8c2e44fda578fc919de6ee0aafc286
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:cb09112f4270dc74137369abdac1f0807ef6009564617b2e2b60b7e97fef7fe2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0dc2e969026f3f40ad11843a5145c701031ea022a6b48e8e4bcd2168f57a881f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e39abb0555e5589aa8d73eb4d6ad64ac52dc3e29caaa7e6bdd7045cdbb6ddc8a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ff59608d9c7af9327d91290ba0dcbd3186f6303eec5e66afedc9335b607a1c0b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b57473db66794cf6e2d9cedea51a1d03fb14060a00806551116d60f6c4ea8b6d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5191a6263333a7e506c8a6d140571f31da7b68ffeb57d2dfc20d94ad59e8f3e8
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:66104f5767fba243db94643e58271a84a810e286a484657de86847a216e3746f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:72ef86448924375087b81ec9579f3052f667ba2af0fb8f2e25320e99b3a1f3d0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ed8d945b7ec183654c39a1c1b9bd61a5126df244767bd60cad55bdc071ffc90b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c5c506f72a73397200189d9a6d47fb999581bc89723a68d9a985ba2d36569eac
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:001ab21f7442f9912889123bd1ed84e86ee5919cc12b34ac021b5ef2d985d9ae
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:cc4f934de5cb45ee2b51bd6808351820093f9e83e77fbdf1bc373ed187644fb3"
    registry: registry.mender.io
    repository: mender-server-enterprise
