auditlogs:
  image:
    tag: main@sha256:a2b53bf6eb865c45738328407e680eb26afaec775568f69a5f3c11860813ea48
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:a49d53743e53c0b225136b47f87bf4bc1a502ff4a4990e029534914b2ddaec8a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2e56b37f5d8a1b86d34ac3e711c4baa33ff7a84cef799d11559237e8a563527c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:99ae4bbc867926dfc4250b6bbbc3da144c20c96aa177642ce8ff7bf8201ef7b7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4ce96f2d5e705a0693dc0189f01773801381333260e2348c8b09419f02ed3d72
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ed163adc135af1fec523b15dcb64d34d70995937f9c47469141cecc81aeb36e1
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:af543f6e2b3eb024e8c5c86693f1610176806369ed329d96fa918f743f4c7bec
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1bd6771c0701ee19495304247c86d68c13027cac9823a412d915e07a3550814d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:82555d02cf918e4f16140daa894906ed64061e2166ba30e27df1227811b302d4
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:10ab57d7ba0bd6a75b10d540d7b7959a8b8db9083cbbbaac1a5703350c695709
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7b37c8329a7a3a2f28e5910cef56eabf51c2478c1371c235ab9e604284fcaf02
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:195deeca94d58df2cafb0cd0efb338de62519d599ff27e4735c5a0093939bc2b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0754422fba33d218c41d8c198ca2f6d10cd1dcc730d7d58291e58e0f1a38795a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a98d38e8e0d3c09b13b9f5b31fe1f78f3ad5644d6af60b11323bda660746f62b"
    registry: registry.mender.io
    repository: mender-server-enterprise
