auditlogs:
  image:
    tag: main@sha256:db0ab860dba7e9e6b1d56817523dbaffffd157cf725e3fecd8353a807b525b5b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:44c4d58e0e91d4c33843367a0bd8d08b1c3dbb9687a81a0b1fa4033aaab758a7
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:87014bfc5687fd4abd8e3863ea60aa957aa0fe708ccd55b0782b0555ce001c70
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:974ea684fb2add31e8f9c0fc18b7719beabdf08a730257e174e9d2577c0c7c46
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ed31bed91081d940079a6da1e701e545699b676d18d1b295b5f6b7eb58f44898
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:08ef854246fba40cc89fa0e41278573d58ecbbf76e9e9104a34906e7eb4b459b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f1f2acd8f0d97406e7e5c71dcbac8ffae4c66db22efeab5ff3d988ad2ed25aaf
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f4e266a0853d2b67aa98b040de2a82db43bf20a3131963cc34e22b9d6f21848d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:266450b4c22320a6652653a1113bd3aab17615b8494a397ff0cc48504fa4719d
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:94db579ca8d9d25b71c1f89ef59b71550a3ceec9cfafb88685dd9d3890a4451d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:5d3866abc219b0cd9e009fff911602c4e881bded00522b08034c3fd79f2e2be5
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:70434c75f67b9d5730dfb731849daf2a409ca279d5bef7b926e4583bfd92f009
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:005aca04da9f84eb74800c9e81bafdf1ee3f569599437760d823391e36a2d93a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:293af82418462f2fc303745b91c9e41b5ce968347dfd8505908b4ff582aaac45"
    registry: docker.io
    repository: mendersoftware
