auditlogs:
  image:
    tag: main@sha256:c1b1a28321e128e0c6ea3d505086955c12dfdc4f39d952b311d7dad78c764374
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:095278062dc3c10bb3cc2944a2d32b26c9409bde0690722edab7c8cca6b3d940
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ab1490ff367ec267f32a4d483dbcde1f930c8ff0e27ff04f8a000591553fcb47
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:91463bde4c1bf8677db34905f2b6dc31eb6ddf4069c63dbc6ad71e1f2954c90d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:afdfd9df29e1a550941fa8d020a1ba07871f470f4f1c50d2830980d950d427c1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4f137c09f644409856e82122ec0479b569f95daf2692c76f7d09be276c050a58
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:000b0f6b45d36836b17bbe5680c54c67ea1f91bb397d31c66bc9d2ad986a7eac
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ae03fd50ad986a33b74eb6deda3d54b8b1d7dd623a24462191c68fac5a522815
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a3d31dda82ca1775c3927fdc305406f4b62c514afa6490147e85fa35692d54e1
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c6424dc633512faa047e0195e5a976495788ac55c2698090b01d3e403fcade8b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:8583c1313c395107adaa9be654b852cfc802f0c83080c68cbae9ecb620db9784
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:db2f751d53f4a74b77088a892997a5b482c203356a15efa7e1d463d7f39f1630
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:469ffb10cacb7c7a3f6b0a90fa34bd2a7b761aedc9541533558e2423c5042a3b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:70e0f18d4aa7adbf00e86f1b85682c5c80bf758012943dcb4dadf2888595c35d"
    registry: docker.io
    repository: mendersoftware
