auditlogs:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: v4.1.0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3df8191e1765e4653a8047d2f40b105a3a75f90266a186c49954a1cbf4f38b23"
    registry: docker.io
    repository: mendersoftware
