auditlogs:
  image:
    tag: main@sha256:7f0d4275b15181c2a23892fd5fe0aa92d1e5df114f7f8ce44d19e4421caa6ffb
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f08eb33218096e90e22d71459c389ec05416b14432b9cd89d21f52660085519c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c2bfdd69618f2915c1c8e03f5a6d7689093009e58613b8559fd8811415e89929
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:5c5af54cc51e6a741a7262f1508a4aed505fbb5a183b16bc51a5b99f7a9aa3f5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ca3bc2a2b477bcc8091785a98b17984ce0f94b452444aa6a0538b423b116bd03
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:737c2aebd2fe6d8945baf0d5baa60b913b9e0eb505e3c80ca5b7dc8d774bf431
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ef238617f8271ee05c86be40d9bdf044d9d932414f7ad78e026c391a9ec06526
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4278c23a0c5255205b5f71036c9e01a92fc6d7230407eb39e15b2358553974ed
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:c4c05073af9b7abef722f1865859a6573fb999fb1c0792db5cf11a8c4ed9db32
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ebc76e80a396174e530404054fa1a87825ae470cefdf9f234f22f2df7d444c3f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:bd574f3e383b1b0025b49131b5fb00db2e43fbd81b77f29681f466590e470b0a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:befb774a1b8b2752fa8badb3d9c4decbffee17dd5a69e4747c50f37a38954f5e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:62dc65d54ecb94a3ae07f09e8709e8cf005d33bf084fa5b7540ceb56bd8a8498
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e7d0e40ce68ae0749b3982d4c477839faced4b832dead6c36112b19b44469755"
    registry: registry.mender.io
    repository: mender-server-enterprise
