auditlogs:
  image:
    tag: main@sha256:0b4953ce1c1541761d83e4178e690d77f429f93b4fe09f168616b99b0416e545
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b881efcf32773d6f8a60ce3934e53112a5c2373be7fe1c2fba2b49b5355fe99d
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:647b14783f929ddcb3d7bef88987575e8ee992f26030ab7bc594d2898ad38bf5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f4c0e384f7d4ba71bfe08abdbcd6f242065b15ab7de47cc215dc95e0bdc7e5b8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1d0fe1906b4ed31928389dc1c2c672ee0bbbac451882551fedefa592b9323a88
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:72be5c806947ec639540dd193272e4efea72b518a21eb6ae64bfd4935b9e1ad1
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0fbfb37aa3be23717d8061461b0fc6c8ad0c4246ee27b63d49ea6cfedda597d9
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d268017e2b2f75843aa93afa45e1cae170d418dc932223600c80cd18568c28bb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:674301bacc0023b6b05d5661e770c70885fcfe7eb0e0ef02c817ecd630c24d07
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1eb87fc1179862821ec192b6994441c845d6c32d14eb247385e61fc2ce24a8f2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:45c8249e50fef7cf284181b9a1f27ec46f3c0c702f75bfb42b4e0c198015224b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1890b23baf72029bb2de10b49320ce982daed34895bb72724362ced568dca8a5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9a24d0efe85a13789bdf2722492c20a20016de9ca843423238eec1a0226a4047
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4f44ffb63fed2f0d4f8ee5940b7bbfe1a8a91983a40f8ae9b7cb3a16398f46c8"
    registry: registry.mender.io
    repository: mender-server-enterprise
