auditlogs:
  image:
    tag: main@sha256:087bbf471fb2d89d337c0863f0a98bb968d8ad122cf7de4b3d54524d016ad28b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:0fa9d286eb51f473a11440d42f3ec4b8377e92641182c29e24700fe1e1e526df
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1c71c52c2a0eb03807521d1224ce6c1a0035610a8302791f6f144a1f34781b8b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:49eb437cb27da60039fa126f528dd30aa80c433aacfe2f2f386bf90c3af5c3f4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f6bf1a980332c8b8acc7ef94105577749781081395c3af660a63a53d3d8a963a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:543806380b98a9f7024570a052458852aba81fedccb57ef0f0e19d243276ecfc
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ef7ac2abe45c2779a045d10c808c89b77274df45dc1cde489e7648129dc84cde
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:50e3e2918bd6f32dd1117503a0c595a01f323d87ebb75228616013e937189681
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:24e712fdff1688f487f6633e6f373d7b6c349e0fafa64460dfbf3e720994e27a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f44889db8b8e781ac548790c0fd40ef1226c69981fe0f8c2577a0c58cfb6f877
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:12d66e3a75aace1fe003ee53c73e1480fc275b9c82154b5fdb04f5ed14bf82ee
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a9f7b71e99f2a580f78e488fa075e1ba3e37d0b79bbb274fbfb136dcf05d2cad
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2f38f11f9c8bea17217e85e5d1dc853493e68e065740d74511e1d5f33f67a829
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1eb49e0102ade783ab8f9d4523d2b76f33972c354e89b16919ef4167b490ee66"
    registry: docker.io
    repository: mendersoftware
