auditlogs:
  image:
    tag: main@sha256:2ba6a58a495f72453fb12c55561842a2031bdd51ea0a5f35b35500025c87dc7f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:47d758dba4c245754c21179b31cba1afab8e951e87fb90989f376f5816c1d04e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:fa789f2d6b4a318ba664c111396be14c8b61ca40b23f5332a2618a9ea5407838
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:531745780629b851a89e88de4ee3d46fbabb8f3e6e74bc7a29066db5e8ec797d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:31e07e0251e4cbd2d0fcd1f97c8b60aceb2da9b4721e1de6d0a914dac13ab3cf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:91804c679088a78ad007bf39ad53800e67ce8f56003a7c8dbb17b28faa289f90
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:825f98ea13898b51d8ed5c44f74be102e54aec929bfec4f58e83570afeeb32e8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8691fdea6551e36b1492dcac587bebe935258183f65d26e4f26d016170b0eac9
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:28e4cdcae4105d6f1ebd983c2133ba93fb1a86721553e07e5409dd7d3198a131
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c0729173647952bbfee2f46955f0b5b5e97c039ba11f9494d9f77a77ccccbba0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:5c650a9d46dcdb66f7a6f30d7de4e44cb662d646e40501a1d2f5c43f25514ace
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1297b249bf26e41d5bc8f4e6e971750f0d5d1c12cb9c7da051d0f43eccf1c78b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:37f954b2c14a498122447a19a31d77818b1648e7b21712b6b348bfcdded4ab50
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:07e7a41a2717851b67db8e3d5ebe85f4347b54b255fefd8ad3043be40bb97406"
    registry: docker.io
    repository: mendersoftware
