auditlogs:
  image:
    tag: main@sha256:77db22f4663569209ff5fa353439a496d44e571a0e8a621039c52eb05801dde9
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4361e871dcba612ab2016a74d1abaafc6788984f3aa3bdf069918e81df6b350e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:b1fa211d21f293f57b0c5613db0745ce3f2520a3cf9c87a522b66fd9370e0fd6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1575f0da692477f1cb9af0fdda4b4fc62687a08257297e2691a0626318b4c809
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b1f9b37b6337928d7f0662de8411c6673d96a4c29b14a1c3f85bc3be4fb0cd61
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:54101245cf59deacdfcac9410073a6afefdd9fc0ca7b4dd449509b70914be556
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:77cb7c5029ae1504b76fb5bac95f995d2188b2d2a6b0b36ff092782a089283ec
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:2feba132d459a56914dc1fcc78aafcdf2053bddfa39e930e1cd53ac049be8295
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8118ae72bf4330a0b20a05b5241e436f181d580c99a16d00d5a3df2d48e03afd
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:908aec7be362c26d2583a14f17e9f1009c368662517ab3fa40bff74f9e43d4af
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:4bf39e0d20980affca6c0c1f3a28b8cdc244bf340a2c61763a5d19feb4bef287
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:589e687eea3439b5230b16e0e82d265f0ed2c61d540633a24ac691548790ec07
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:42574a779732e301dad53e63887d53ed42a9146690e45a3ab37dce28a77f5dc6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3e972a9b097e208117d3833453b4bb13013f08c52a10b38aa3b94c6a51790b61"
    registry: docker.io
    repository: mendersoftware
