auditlogs:
  image:
    tag: main@sha256:44336bf30c98a0a5750bc7b4a0c2fb71d275edbb20e18094957a8d8dbbba3e60
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:a1daf1cb5cd42b616892529afe7ba6f2fdf64c89542c98600c44a96eaf0bb17d
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2e8469a3d8f8a2528dad9dbb410bc499d47cb9ad9116e913fcbcadbecb326213
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:84e4159ac837cfc71a22b496137d88e6b09dd99e7461d541dfa4909fff687a4d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:3226eab666ec709a34d01a67421ed7ed11f42610daaf7facb86fc8abf0048dca
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:14c942bb4141a3fcd7f91d7706a7a91ad8438e80e1febad0c46d9dad62c7268a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3e5fbb9f0d6c712f974988ed2a99f8ead1136293c1e36a5975cb15083fa06493
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5882b9eba908b6540578f6ab331a42cd2f51f37e10cfef6e7ad2d4dbacd96ecd
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a9f99a55c33522a0f6e492efc5ce9eb9fb51fb254e4a8dcb82fa966bc1785ec6
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:fa26b8661bf3386f975eb6c76a06feead2cd4dbe231895146a9ac34d8d3d2d60
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d38f5a0e119399a7011f3fcbdba1b5d7e97574b79d06f07f4db537dbead70ccf
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:94740f0d069a987ef36ef0884c9a186080919ddefc8ebcb7c6a61cd3c9c7355b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ba650509d49e7d25d5167736783a2d6244742d6a61058b5cecad48a9b5480a19
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3da2fb681a743346d6e29886666ee9ca5b4b72e8408f08dc2f159eb658493522"
    registry: registry.mender.io
    repository: mender-server-enterprise
