auditlogs:
  image:
    tag: main@sha256:88b48021cbff7961c0829a98af8a54950aed9c9d85999869a9d45cfc4cc1357b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7ea528cc433ce35e4f75eaa66d9ae7b601fc22c101f90d13ed49739ae463f5cf
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:37e75e682c9e0fd9affe1b788eada199b6efa77c3de5993caa4e2ee223f558ab
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2a47326df72e43c30e38cb2ea30a38ebb775a44e753d9aceeef8448a5bad8ad6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:cef91386139841d81360863dfa6d00511c000e7abed3bf638da7168146513519
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:9cf6547387c653f2c30e65f2bc1573a7d0023994cf3e07f3b785421e991b6ba9
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d602b57f01a16ebbafcd9d2ba9ac058c05811841b9945b7502814dcd261becc2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5a560090988114455da50cf56fb6080c18df215ee0aa79455de55c3a9ce84055
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f4f7e620eb705d06e776b17889697c4f5ec69c1903f0d49e5402636252321510
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2e598f8ea93607a70f875a79b248b1568adcdd17c4cc59030d0f59e4ced823d5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d226eecf38dfba0680209aab9e5752b5b5422630fa5bd6f8d4fb103eaef61902
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f4ef34d6fcb1c41b9da8dd55306efb7f53d35b133ce7efe7c4c8af6e00f84757
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5238e863c9edbaf41a0b5ddfa37fb877bb3e6b089ee29e1cb336712431d97328
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8f98ecee32e1f036da3eeae8e066917f42a1a5986e9582082bd7c8f69fe29f4f"
    registry: docker.io
    repository: mendersoftware
