auditlogs:
  image:
    tag: main@sha256:74638e12d6d7a4374fdac2cac23a6af2d0aec2b88cb2832699da3073d26138b7
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:bb8c242a482ac5d0bc91ad655034508936cf1063281e3dc12eeec167d1e2c489
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f15320e47e795e631071b9dd4709fc696ba4a20aedcde28fb60b67c7ef5e51ee
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:195aa07a8410a1b912c6569f5c83930c842ac70e128992b5391fb0f4894a9efa
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7fa753cc33c703a1822c2f73527d4cea8063c3b39f57806aab1f3177e1e647ae
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0012c2bcbce94ae4652e61c460e8c0391cf1d13da0cb65926fbdb2b0a5580c81
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a4bcbfb903168ee17777b6f017f42891f7a682acbc787127bafd36ae248683e7
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a0ff28c842deddf211a71b0b91f7fcde4b0286849242b073c409cd69b93dab78
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:65fda8f8162ae7a820656042815da17e0b82ab00c97a0db9ed4c86c86fc3a2d5
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f5db09d0ab691ac7e99af40b075cfc352d57c71a0414a3d97a4ceb3bca7d6203
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:68b079ac9ec805b5e0ecc71ed9eeed915a868cdc77747a17fce96e3f7adf0503
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b34980743d94c912b4703a5b523d246d9dba97321ae19a59468145b61ab4209a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:425c94bf6b2eb03e74b79397da6af8e95f1e55493f448290ecf581d97ee181cb
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "v4.1.0"
    registry: docker.io
    repository: mendersoftware
