auditlogs:
  image:
    tag: staging_8fafacdbc9762979a590a2fe580899f1b9dda5b4
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_58f24e0345cc2504a53aabd8b6650edf6a81875b
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_e3e924b021131b9d8f473933b903fad81725cbc9
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_7bdd1b5b6b899addfc39bb21015656333734f576
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_23ae8454267be41e3c28fbc079e6b1a38ff722f9
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_9d117129c54f6f1b5a1c467c39a5d2b230897a5d
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_67c3bfb073b3486d777c57ef82c6a5afbc88b542
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_fe23b056bd8d7a56f4bc1daf437c611cee9ae370
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_a43b62134d9538fd98e6f7c7044f9109eef93822
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_3fb733cc4d527e62c22d395e3f342cac3aa985e7
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_630719591b75ae642b822e9221161213b713ec77
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_45d5eec5ea9703edce3ef26bee1426eab730d36c
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_9b8a9b980291fb788e0c18edf779c464e6f95dab
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_18e301ae06036739126572188097758b508d667d
    registry: mendersoftware
    repository: gui
