auditlogs:
  image:
    tag: main@sha256:ecd068e8f63e981142e699c7e0d1cc78603ecb0bbfab30874def118ab2b027e2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3fbd50f8c594925cccbe5a82b4a1bd52c08fd532c8181c8f15c3e3da32a6344a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:258ec7f4f9e56ce3996e6bf7a0c6496c2b31d3dd871ab4222e0eaa50fb018018
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1dd24e3f64b92512974af177adb3d37616d3795e2b98c0f5a700ef617764e985
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ad7e23bdd0e926db29d111443bc73752ed040ca222ce291cc275311db0f8dbd4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e4b234fbf208f802f94dca56ed559f15d3b0459a587816b674b54c71bbf99ad8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:46c89d2f62deb5e6254a16f19746e67d89f471174b1f39fc226e863bce117273
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:65905a51f18f892b455336ebcaa936e2201a17dd21d5ba6bee9040c152dbe8b0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:cd1d7d9640df742b73bced2b6325ce1b382a54531b36c8d449859c19b2f27896
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:45e5e4c9838e62019c573c01f124c26c558d570a846ed68123034b6f0b80916d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d5854a1fc460d6bb2792b526c26f9b49a3fb4bfbb04c3bc2bb53bcff1151ae3a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4c48f1ed18d60d6bd70698a3d030394f982a6db3f8ef5f8c9d39ec475eef5983
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e3f79a61f4260685df5d48f3d5584ea237d2447def66505127fef996b112f8b9
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:381d4be9f87f59e0571b5c16874f6adbc5b8384804692fa414ca31139c85dc37"
    registry: docker.io
    repository: mendersoftware
