auditlogs:
  image:
    tag: main@sha256:9baafda9c5b444ab7b8be68c7d06d8f07ab7ce79b0382e5f7de1f621c8df8ef8
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f26bafdbb03356843d569986acb4fcac15065e42ade0867b81ef3dbbcdac2c31
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ef53d4f819088f8dce087ea24ead6899ea20fe104ce86252cd0aa3530597748c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:888551612f77071d17548088f243dfa653ab64d8ac8e57ead895d66e744386a6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9ae790396fa99117754ef8942954b59850ed819c1a9270642bbc4ee8c5ef314f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:c564a1850f49251fbcd52ed31d7e91a3a2ec625bd3aede69492cae2a4ea55934
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e4befa33c5e856a3827a00ec9f468d77655a1f6a7e8fe28b0838a03f7aeb7273
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e1bb3f2955f62c5e7ee077e4203252f95d04c0f10691b5f815c7640f241aafe0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8611d26da152a0a92fc5ac7ea47b2776fa19aaf8f1b664b7fd2bf5781c72f122
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:2a642a3bfc0afe79ee02c1d0df5733bbb7e249ebc51a55fb7e8a2d68521fd68a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c5431ba3e4ba16a61858d7d1bcdf15cd997b82886932968c28f09134207965a0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f3e4e90e196ebb7b3c4e1124fc9c233d051c5bb1c8b1653aecfcddc10eb968c6
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f110a9d17ff4e7825c54963214a36e41e532884772bf42fed1723853e768a816
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:5f2aaa1c857c6f405214fcae2993faed25096d0553c058c1a1c34201d08a67f7"
    registry: registry.mender.io
    repository: mender-server-enterprise
