auditlogs:
  image:
    tag: main@sha256:7db1f82f7dcd29a160ebcdf0cd08572e8ba7d53af99c1e498cbaec58fc19472f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f2635a891282dadc04f00c562ef2167d09c8c167c720e2b13bc32808bcbf18e9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:043b201f1a683f696d89dd81bc660036f96f44fe914d61056d49170dbdaee741
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2b1f9c805beeecbb02e5166a16b4041f8b8ebdfeed4dde8c948d7c743c66ee67
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:0c2b765f84f04650e46f6493d2bf9ca4cc370ebfee88f40a43cd5e608aec8de1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:324619eb3be9cf96d5cc96e90e1b07cec0b3cc8dae4834f7794e8f46ecaa7eb8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e019fbfe4e24257d3e5cc847975ce3af1aba5afd549a0b241f445505285ac7e2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3ab1907022f5e6b5eee61e8024d67c5c720c4c16614a9f6cff913aa22caa2e84
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0a97995506e2a62786a02ae8151f3ad7fba8a4e4151f98033bfa597e070378ef
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4b7154659182d25d3f05f3cf7086648aaf066d6fba8a6230af4fcafb560ae760
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:70bf627ed1baaddd69806dc19e82b041b70af26d432965f447696034683d9a94
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:922b01cb69bc2253510b613648dbda15ab48b5fecc5355d623dcb8e0b8308948
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1eb2bb832c21a24a8718b508d6e4a5192af607a24ef49389f5dd638e3fbd7d3d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:35e99aa766bba953653d061d2e1b3078ac690b3929bf68f74766d1103f9a16c2"
    registry: registry.mender.io
    repository: mender-server-enterprise
