auditlogs:
  image:
    tag: main@sha256:2aa0b644ec0862bea98e58a93de4f1f65690ecf15296e77dfc97c01ec614d8a7
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:5c67bcd7d2d23f5d886f0922defcda433d4a78ccade11aedd72b2bb9fe0627f6
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:9f097a514cf9d791af32fba510c5fea9d73cc7ebc4292cb9163c431cb414e5b1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:406fd1013245c324ec78ac11c7135e58ee2a7afe6c544d65c7f22240a0c3c109
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:9b84506d8bba29b414f8ec8b7140289671587e9313bce3a4bfea85fdf8979ae7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:399652dd0b973d5f2e5410c43fa78532a948c263afc2e10d56c66262890cdfe7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d6e096bf2be41f9d768018c4f73b1e1842bd99e724380a7404c742350b258ec2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:52eb66dc053c333d3d1056f26e5cce8a56735b2bb0fb011d82175047db1c115d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3ba9f5b2acb1adfee04fd00d1ed5eb170fae631cae0832e436bac766e970d34b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:64e68b42eabb0059784db134a9edbf895472a15394a4a0f5ea4abdb13f8e1251
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ed06a2fc335b8a8b630cac3e13af08459f5e7e2ac24bfaee9189d65974cd7efa
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1e9c9c0061bb2ac7690eff625761f4fc73ecfb710ecaa21fbe91b9b0e4249482
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:b1ad819177028c9749f1d41982cb6dd7682c0969b1c637e668407157bacc58d3
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f9d46af21a3a77eb7154fc63833d030e9556c03d133caea745ccd4c26d336d80"
    registry: registry.mender.io
    repository: mender-server-enterprise
