auditlogs:
  image:
    tag: main@sha256:77785df50f15e08506ee7acdb1002a72f173e8c069c33a447424605b53aaf42e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2611c5a881230eff6af998d0fdb10f95b399c089fed4f06c2cbf55600b263286
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ac4d6fa1a7cf3c1eb7fd675f939ea87713bcac0362858fdfc37aa7ded22074db
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:83144391630f82c5f527a729c2c02f4d9bd84d8529a7940e278ee6460de457f1
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:fe946e2fd92ee9a3e7b1ed8a3f6806786aab8d4048359e87420ebfcdd49a5f60
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2958c9b409760c0d5ef37e1ad901f44ab753ee3cd116dcf0f7d93dbe9b2db61c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3959f362c8b0f295f21298a885aea7d6659afb5a8b606032555d18e8668c425e
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:cde4c882a325d2a4820dc0242181361d23c7e966c1d171c7b2dfa7c72848584f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d0d6030c86f57954dd9b704d8c9f336edb1a8ee98cda2a8209ccc253800a4245
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4194267a3242af37cfaa2bf9f4ed86e9ab89f949ff428e2889c7cdc9115fda87
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:13527e4d5de0bd77d575c10a2643d45629e5fbcaa2ccbe1a1c0d3fa38a5cbdd2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:ab680ef761d1b26dc3d06292be21c24231a20fca860012cd44dd3fe77ec25b0d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:fa4599574114777a8dc65c81bbc1ea278e2cd9a60188e00ddb0170b4d6bc2ba0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3b651630dfed40a40e88111f1be7f5a3220edd04bb4aac2d28242ec750bc93c6"
    registry: registry.mender.io
    repository: mender-server-enterprise
