auditlogs:
  image:
    tag: main@sha256:08c4838154b02607098fbd90621270346243bf641196eb45ada226a5b13d3e8f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:5853e2deebff495d31719613bfaa456f9d3a6b63b7eb5a399218fe50ac644f10
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:2901adbbebacb63235fea861fd5bcee1fc4a8212553a6778fc7793b0bbc3aaf1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:320ad41fe8d13fb47e7a9b23cd4b2856c587d704bae8ce53f7017b120c5b8e9e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4c263578eb3ea8bfecfb6fcfd794e7c494b864d17c7ee5abbb6bd9c80b213be4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ca46c69212dd18e90ee84e1b2bafee85f7992fb772b0c53bc07e657b86c84999
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3726bae8834d6b1a5b80bcb518437402997fbca3aeb48efeaf5fcadd2c4b5f41
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f2e5af9d8ce0279d41e54d1b2cd93041da76914e7cf9a6651fb7cdec7597cd6e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:6796b5a0e5f96408769e22140d9422cca4e76eb1dd3e35cdf8b03a824a262876
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:33cd4feae4202dfb9ad316106db93220779aabe43a55fef191918fe48fe10073
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:947431d83eb0fb6a53378624796123b7e180c3ba53feeae6ecf7fbe4e8042544
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bca6cf05c894fbcf347dc4ff4437fa253482cd262344517e513336b8848b2b5e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:86757ebf5be7e8f09b74b8b7724b439e47bb49909422b5e56a72d737000d1ec9
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:0631aca35242972b0182338c8ccb3ca12f89dbafa4de5aa3b9f23df86e0e92e6"
    registry: docker.io
    repository: mendersoftware
