auditlogs:
  image:
    tag: main@sha256:12be8e1f09cf0afc3a2d4befda99e94a4b945eba29f019f106abaf5a8769c014
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4ac8dc69472dd46ea3ac806c48c6608407d3d01faa990fb9b58f36efe059e303
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:31945836f079aa9ba96d988703dbd01cfbddd6743ffd8d124e955ce22b20752e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:df66cc64e461cb41dda30f845f185c7ffaa23bc782daaf84bcc1bed8317fa182
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e58402033bbb6bd39f042b0825e0f073a091295661a6cb68349b3f2543d75c60
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cc04d98b7de2d3990dda5b7bb261c5c94363388d4d8f8b7adf578775835535cd
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:7379d870ded78bdbc6f0cf46ff044088b4417a7fd3f497490b6400ea4ee4e572
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8d5c08fb831b917525b5e2a2cc54de5316e1cd87be72e8be67484710c7dde900
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4c6275117cf9a882d73aac8492a3ab869f82195853d3ca328c0f5de8ec6e16cc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7dc7f833b951267febfa78916d32058dffa172e7ab6efaaa432d9f7ae2ad31a7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ec27cbedf0ea2b84bd21de08ba7f89c47613329d6d7acac7b631542350008ca2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:0746e574c7dc3fecfa32dc133ca8dc9f960ae39edd79721feebc8a9be356e1c4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:800ca6ae10531deb5a41ff432427c5b7bed1e0e868eb5281df08612c3e827d70
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d91fae774669c9980627a34df12c56094062bc3545f1698291a05dde0aba4cb5"
    registry: registry.mender.io
    repository: mender-server-enterprise
