auditlogs:
  image:
    tag: main@sha256:930afab78ed29e9b5bd0cd29b137b16fac5b1d2601afc8f7e394be10215d3ccd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2301206fee2dd8d7e8c5a4b07fe69ae372c4b676cc64edd9e9324e10946c4496
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1b537ec772f35a4d09e8076dfe2012ec22c2a3ae04e67c45996e530c8424601a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:863a26ffa8e3288ae69b0544ccb9ef876f14fc673eab1a855c87a2efe7f34de1
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:139a0d350b0b1cb039ef376c9907badb7bdcd64a3d403b92bf189b7169c2d2f0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6c1bc2a969116fdba0ce1b6ea9087acac4b82af0f4a4587435e0996947693c45
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e0d75f4966fb4880a5885627be03a59773323dffb1e876508ac35598d0fc7782
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0214eb79eb2214e31a576ca786a2905baa64fce3c6fce52a1d8ac8e294b0f289
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:21b867aec2de10c10c1211e0aef59591ef05538a29d165484f1c4109a35f2fd6
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b24962a8c26bb25f819791bc732ade4104613cb034ab1e76857ed5dd76896382
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:6af1e8b0eb697115c386271120ee87fded8166a71cb57c32f393af5fce7c4a35
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:32483aadcd69028c021914312c208eafa26fad3e1ed109e6dfa912f531759458
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e7f7fe06ce58e3600fc3f033b02b973c2fdb4bc76993d40b8dbe796e8f082bf6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:aa5876461b834c25517e02d2aa14a6b5b107bb6766ce67c44fc1e148e1a6c974"
    registry: docker.io
    repository: mendersoftware
