auditlogs:
  image:
    tag: main@sha256:ffe50b8cd7d297f7fa62019eb6c55800feaf7cd7a109d35ce6e2f82013649379
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:09b0edb6bece46194c311de87e6bd2365c036ea4ee694ac5aaf8f1dcceaa91ff
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:9f11c9d9f0b2d7aba7f079e54158fc11c439c1591cc52e004a90290670472c70
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:862d8d436b961658032abbd717a82b3468d1e2d7144b102be385e5037171e714
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4f56e514cc2c51e530ce2d5b080f46ca47942521939bad505925754e7c50ea7f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:04d26f52929f722d65eab5593d0cf2f9121bd6f2d289279f09f4ad5475d32667
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ac7e8067c64dd67454d349099dc232f313da7ece74e937088140a0e52a6166c1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:62fe3e218f270c5783957f587900dc3c377d0b918a2206ab95d5a46cc2c704f6
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:0fa09c45b8c4a3d39e58c6e1f5c0a8955839c6ce453a73d5a54e40e7ea725134
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:97791cc5c08a3dde1532858f5f08d4b959ad7e70442648a333c53487e7d96ac5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:66c3dcbce8379d26dae06f66cedab22054c29f5c12fc358133f085fa591a1bb8
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3693d71a13eceb731ca88957fe5c91976ab14ae4a750e58a4e32789e1ab37b98
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6e0bbd1e8c63c8eba4275fd2186c365846da8394a75b6f7e2026522d67f20400
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:237880a890e8dd34467d0d70b68a26b38e390453dd26b3281be810a7e776600c"
    registry: docker.io
    repository: mendersoftware
