auditlogs:
  image:
    tag: main@sha256:ab40fdb2d3b0b3149c0e88c2e1027e5580ec1140e508923bd7c51f09d17e8a6a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:61558ca478a3299bee04122f2a0f356bc62ce50d2c6d0769f9b0c6523ffd24ba
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f7d2b61aa0e722f3b6f28979c606ba0628afe070eda40a811ee607ca0dd4c165
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ecd33054c93b461f777edb99f0e9de5b19d1aa341876cf206e62b62e32b2bdf5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e1cdacb05b25747216d625fe43a8ba25400cd974099dc2f534aef669e6b8f9e8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:998557b0e369cbb55a552b80be05e473cdfad8332e63721b69dd70d06097e4a3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:2bf0fa03da83cc0ecbf2c6e5f836428cdf7b50765cb0476b24f7c85b674767fc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:6975436a2fdbcd584737cc1ccff1453dceefde808cb9867ba3cfaf1365fe35a4
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:92bfa8c6f9a2a8bd3a409c7b0f3c35a17de2ff8d14d5d176f664a8a0b79dc56b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e6312643b5870a9239b6565bdae73f6a42b7286b912430e6acb103b4128bcd65
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0386527ff99593a5cba7942ad08f6ea2f58f9b70edc2ea0c34d96aecc8df585b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:79a6fd2a024b035c95f966052277519acce6cd59225c0a7cb97826bce325b6dc
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:0b283020fe5e7b2d5c0030528a5868d1811f5915a7e10bc27aeb3ff88b47ea17
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:12155be3d3d00ca38749e1b62c2cfc9d55fba1a84b7432c02edb17c25c859cb3"
    registry: docker.io
    repository: mendersoftware
