auditlogs:
  image:
    tag: main@sha256:8f93a9de33014ffcc4e1766e0921d95924d2f0c0e4d6f622174d62dc90d6526b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:c5f2c49b95ef3ec2c9c1ceb314e54f0a9937e71844f3929883068251808ac699
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1f4fd3ec5f80de7adbc62339404cd8d352c011e9c4dfb357cdfcbeaa76d3a38a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:39468d1b1113c5eb18a49fd91e5868cce3cffd2740ef57d2cc2480bf62cd536a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1f70d94795ea414f5d86cfafd96f9b7b3376f223ca8d14d0c86a8d9aef34ccee
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:fe2a449ee559ae53a532602d0b8ee522043e755b292eb293b6baed1ea3801052
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0befc2192ee4ab7e813332767e7e24cd1c7c284bcef00b84ab4757720c0e3fa2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:19232a6845e4c99bd6b7158511431617a631186c69876712a942f08c1aa0c983
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:949f63f0569a03faf823264c86b4a06c8162340446bd6653660f66f8ec484177
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d82d4b45e131c6adad6a3d0948beafcc3122ddf4ab8ea74675c964379f743adc
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c9edcfcbf0fb66e69e5b140f342865b2ebe22ad632dbd503fa3bf517beba1f9c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:af34a87840063d7ab605a6808316ed4d79b6a71ba1e186f8b8778f0c9997f512
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:23a25a56a3b5bb3e8a59b08104d5f15bd67b6098608cadc57699a208e5823ff2
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9ff4a83268d9e8afcc3527d82a24702c45395e20fb8e6b36e2a248a7e64df01c"
    registry: docker.io
    repository: mendersoftware
