auditlogs:
  image:
    tag: main@sha256:3ddb714f1714795b13a1ed75ddd8fb6069ed7e11c78105fa48fac378593d6f01
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:420a426cc23d939bbf4bd4bf03695e2ebf1a91f5f77d231552520bc37c422472
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:88c4f520a9ae174c5919bf52ccb0c5a5da657d9fd99e3e5683701faf81430d50
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0b93fff4241e0aca40d98e6f40fcad3140906de5993559fb200a40890689db6a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a89b080958c2ccc8e5c2885591eadec3a2f6392583fe0827b2da403a53446f17
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6f12454a02949c2ed841454bf0670cb9a0f38505a5cf51962ebf10cf78db6448
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:7ba04a0012ba956aec025abd2fbab5ad3e732a96d6cf7761d6b6d42ca09c7175
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:af07247e2989ca718a28dd4fcd8f0df7f89c51b517df1c73fa56fd748c9051af
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:df863f8647c7a3125b4aa3350f33c3473bd58b4c50ef90e30d036c8c16a8092b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9888f25a8a33d028a981210764fd243794d9d34e1033bbd5295fe432fb71bf39
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:a89b8f92cbd83fec316c40014128e96ba0eedea7b3eddb01b3fa44d78e30515a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8f6c024ec33f44511a541b260864de90a5e2bf09a48ccdad78f34868baee4bc4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:39028ddfc69bd879b67a322690fb7d34a8718332bb692ad20d921e2d994f4505
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:768ff1851be9fa6d1db1de0437e64b2337ba3ddc610bbdcf3a58ad322aac5eb8"
    registry: docker.io
    repository: mendersoftware
