auditlogs:
  image:
    tag: main@sha256:b95cd11c46601dd26648f7ef8ce14dc0f659b17bb9191b06d430ee1e0f8ca4fd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d61413ebc26b60674264b07d14ce034534a79b307f109a79f1494cf9f840e292
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a3dd226ce8efb87cd63829903c29549e9aa3016adf6bf9c4603b478c9f57d8a7
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3db65a2c295d121bf1f9e359ead0599a667ffa8d7c59a874a0502e0a38c7789b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:00710634b35c5d708fa7ede26fd180cb91baf81c4e576f1c1d39f670ffb527f8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f768aee8dd2e56833b4df4237bf9af2475b491f446276186e0cdbd958c45ffe3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e59a167c10b691bed0a49738247e66b33cb7b287e5a65720dbc8c98284b0db78
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:8211969282a4604406ca1e6793ea132ae812bff5849fe7741403c6c9fa10b11c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:72a62762b7bab4a9b7248f76c523e1f0fd91a59c3e1ca0679cbe4b537ddeb499
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0226078666af8849e698f38f882ae0f9c93174699555926b249acea272699540
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:d29f9ff958aef7a84981d1faf9c184298a564aea312042590c39c6da9646aaee
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f1a83b588ec6036b6bc14f4650a75786e0fbfae79335e91b1c0f82c92f03d6be
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:08bc75d85cba4ee4b10946262e6d366d5073c756fe7559ed6ea37f23d3eac5b1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:48ff2befb8a1ab32408f7e197ec233771dd57c312e316a8dc8843e48a323ee00"
    registry: registry.mender.io
    repository: mender-server-enterprise
