auditlogs:
  image:
    tag: main@sha256:5b898d9534d817b1819ca80c0480b3e6b2b43b8534ed62c8a25ecfe73724a42b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1aad42c433ec47b21e488252d29b8f9d759040eaf4db32987f3b3a6a29e72698
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:267ff9b3e721788b8c534fed27741d6cb84e1c03e347a316579fe096cdd97b91
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:97d7959226b930f794e5b472cd3ef13ebe34d1572dfcf1281c27d54eceb06c70
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5475bf56fce069baad33ef5aa710e28ed46dc46572fd3b92650fd8179e016496
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:06f3cc6790e25bd9b48c6b65b8352da8cdf97e9aceabaf28335e7fdcb4f526e5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6ce459edcf716655d4ab928374d33e30a13037551b87a907ba0309afe0fa8689
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b4af407d6c3672d969dda86368f3d9d43d0eb39267455c0ddff6edb95a2cdea2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f30b2a1e88693e9b32bf31be234c2e9b5c50072ebb343ce3fa49c8087cc1c69a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9d5a6c7677ee4a9528b8c2cbbe7c4093b57b6df571e9d25406e1687a421d10be
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c0b47bd9a5590a380a84a61b257d270029d70d2a729cf045ccca6eddac7ac317
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a50e506c5118d06589ee14b1375cdc9609e47b9e57f8eb95ceaac051cf1039cc
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:078f90bdb0f0d25ecef99ad7bb120c0c06ab20000d515f548587dd5ac07f7468
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4adcdd49abaab93ea189dd321fc453e5bb21fcca66bbb387e9cda23fa1ad391d"
    registry: registry.mender.io
    repository: mender-server-enterprise
