auditlogs:
  image:
    tag: main@sha256:a861349f420105257aad01d962707d625df7a640b9e5f94c431e05d6c5a900f4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:820a59060be2f25169f2a701615d6f02340ce706c6451244a1936d4ea012058b
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:92628e3eea9b6e3c2ec0af27355918c9ebdb6e689c69d08d5f94fa63578d5544
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:10a475d43ea70a17517acded6a1a5918f21757422072ed24a3d27983a6e23513
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b7ca4dd0f8ddf8423213823c7fbbacf3bf8b6409dbd288b90739935d3a5d876f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6ff46a837f9a85598f60edb29bdb0c37b36919900d62a67b6066314f90be95e2
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6991fd7ada62136e3eeed0bb710292073755e9e6bbbb922d80d015f80de73198
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7ad519e2827f9ae25d5c17dc53b950ae6ae3de8c772922a9124ade7311f108f9
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e70d83db894e878b2ac8927e89fd2f9746e8b1e41269481cd8857b716e4f9916
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8f2a95f8b776424b38f03d2251226addcc6f1af95bf5b3460c02552e76a91ea6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:bd0c3c38faa6f5ce8df9d7370d7057ab4a34dde3f12def6a0d5316b2da39971b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:cd7535ed720dcb3b129a9e825afe18cacb43f6d6e71eeeeda540d7b06705a2cc
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8b63e2db939bb6cbfdc5996091308197eb43592e6694dbf006f2056438e14af3
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4989d762e2cfab5e822b426e12db075c76776b68ffa6287ba6f9586c46a32acf"
    registry: docker.io
    repository: mendersoftware
