auditlogs:
  image:
    tag: main@sha256:8766681bfb91a16dac5df231ed9af16bf960016742982caa43a022a35088817d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f69aa93b0eb28b424631f265db04843839c8ea3992415e416d73d26d90d4279c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:64eb0381c9c6d058d7df98659f022a8bf8c026f5ce14a18444c295ecc36c2e6b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:eb32144f38aa21990f0668dca106d02a1fb7b2b7c880a6a881a1aef48b4c1936
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:106406984fd6c3221311faab0a25d36fa771a8180faa2d05e0b75156bd2f2fd0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5efc436e28efcb27f9a04678c0e86e86e63be236dec84b2a9986f51b867697f6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c38739c669ad4b3cc0a3090779fa9c88a0d0ced06a7a39dbd5cee30f8c23faad
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:62ac543df96ff1b8412f127266a58239a38ce0d3805e5c0adb0421f503ff71ec
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:861f81a47b70a6acbd918c06fdd28049c97ace7910092aa6093611a387a6b632
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:dd9404e49a51440c970453310f6518d8f26f51da22a53bf17915557f0c10c76a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:699a01668819c002037f408b87cbc292d4b838effc573d8b861f659d0f19c480
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:0b32e904c658fa440f6ba6bc21005bc7921feee9c56d1341f56d5632f64f47a6
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c551cae1e31056ae06224c3ad050432af22c75663bb6596c33dae42346aefb26
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:757b7ef4f30c4cbaf4a143df36c760abef068e9a7a0a612c458b88a2af1f95da"
    registry: registry.mender.io
    repository: mender-server-enterprise
