auditlogs:
  image:
    tag: main@sha256:f38d03f17df895281e400265e318794daca372f8234829fdab21fee3f572a08d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:86756d373d17935da2ddd1572ee6d1ba58d7929caa0853e1f66770da691abf8f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6fb6065f556f6cdfa9845f0a2f61b3e577b45caea550ee168ac4797543fad08b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:92c5ffc1273815e04f40c97a83e7bc09cc2398746e4de217d1cbf8a6457586e1
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:6c55baec0f1bc6a4a6990857957039d923a3ef38ad68da029ce972f50829a781
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:490aefbdcac2ba2fe426907459f3b23c1f37297912a1f8f79cc9b9fcc3428bdc
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:545fad81f2a9bac7e7efe6499e29e286f1b7531c2d84131e89ccd0818aee11bc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f7a0e9f91db671d015477314a6f8f90b982f4583d570a1445f595557fd230073
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:bfad18fdcbdb65da707305f653ffff0594fda73e37f1c24b272633041a9d7e4e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1df64dfd1708ffa4a4b42b72dca9f83715802f6c66c6e59639395dd50176e3ae
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:70b1f27d9186cdc10d69a72ac66423b0fc418837ecf9b6cc292c179278ff8206
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:013bc59d8014edb7b60d2f31d4c083b638751eb0dbeccbc901ce395036983d90
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:99f2102a93756e2042d1bc95c8cb127ae33ce9827e8281f10809cbc648383f25
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a30c05c1806a84797d34616144562dfc6ba754a496fa8f0f75be72616d9e48a8"
    registry: registry.mender.io
    repository: mender-server-enterprise
