auditlogs:
  image:
    tag: main@sha256:ff2cddc7560dd28f09a0f8162c78a9b275ad1152290d471cb96fd088f9ef602f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:dd3f1fe1834fbe23f3f6414e123e9ac2e2af3eaa3ca36d91b1013e909ed9a91f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:947b100f7cb3c7aff5682decd6e675320fb928e2f70e4ffe94de52913206b950
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9d23a7baa5f62ec6ab431ad856ffd32edaf073b5d699bfd0e85d44832a2c85de
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5013c6d136e5298587fddc9bf65421234a308ed9efb5c2693d5a2d0c73736cf1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:59662d6b9704007e5b9b39fe955c60997055809f053431402a48c3ba37d0a42f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d23c9a534dad26bdc0034f9d31b782a9c596a580e7be2245b1b43105da8f3371
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:288eeab5f29a63df2c786bfab99d1f2960f2264359c43c41a675b15db8107493
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8804b8f48f360362277ba996e6284b8e3b67727e2755a9bb31eea926190a4af2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:34123cc083c81d12382be636b736dd9b18573e4af8d1468cdb62344243a2a34a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:86d254cbb2c0e47dd8c1f26874beea0c9b5f48dec6ca2eecce33a2d5e72cc6ab
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4a88866c9f4d6801b57b29497544570df30ccc3ab9dae8915a7945501179c485
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c7a6075665bd662244c7f6ebeef0684631298f3a8656b9752135672264219dd5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:5df256818b7015dd818a0aaf7637b926112198bfb77dd1498372aeb948442f32"
    registry: docker.io
    repository: mendersoftware
