auditlogs:
  image:
    tag: main@sha256:e438058dbf8230c0267b99c9a61a596a6e81138d639acee9fd23f8ebe9340373
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:99d3380d211e9c496957cb91eb812bcbbb6a397805185d3159eccbe17edce65f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:044267b985da00d4497ba6ab8c11571e1bc6e6da9438ce92da4c113a378ee8f0
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ae0434d48c2287aad2f3ea6342b283b848c057c9b5f18868d5e2b783aa15068b
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:3f5702980b3e515a7e36fe6e87dbec7915f6054d272fa8db2236a5f172f95d90
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a8e43d0e4fb8b42b111a2bd969cbeb148facdc661f7043ec3f01490afccbb4e6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b7592a38b8a1c2fd9faf79358010add0d79af70469563d8c289fd3b6d7a5fb86
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:aac0b90dd17b52bb2c3aa4c0260d033fc21558e23c85c4b3d66466e49c7fe5eb
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9ac0da07e8e0702ddad17851b68a15424999e24e15628d3e694a5e1b71f6554e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:415a9959cafdd84217b25b9d36c6363e9be724059ce029461be1efa464d98477
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7ae35fcd62e5559dfed531da1bd8ceb89456156f7770b3bf3cdf3ff631481e63
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f8b22de9c8c7d849574aac81c77763a4c7be22513fe08507d59640fe30c101e2
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:05347bbab6cb56f76298b92c1fc6dec6195c1d6e52a5c85dde1d10595c7656e0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7d27e6f52e0147c351cd62825c13636f0888518019b193f54e2c519ab7e3c649"
    registry: registry.mender.io
    repository: mender-server-enterprise
