auditlogs:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: v4.1.0-saas.5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "v4.1.0-saas.5"
    registry: registry.mender.io
    repository: mender-server-enterprise
