auditlogs:
  image:
    tag: main@sha256:1bd9064c11d8c0216b8042893111172f5441a0f2b4effb33247952070d9c281a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3bcb8416d24abc7ff74dd8efcabdf857d84ca65ebb5ecd2f1f9848a37e756c6a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a88ec68f43668dc98aa4b81ec42e41f31d3f08a255e2157c5ae60cf47f590d8e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1bce77408976cd60b018d74bd2dd38d741497689ecadfdb0fa376f99cd115ae8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:94c37c1a63a627829e3d961b0869b7e12501704e1de96a4eba47ff703641a23f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:734f9a02699760286d1ea16053aaba793a52cd09e1d7c4c2110ce3020e5d8907
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f9b0c75cd29691180680fad71ed5091fa901600bc6ba73969c23665a421f7327
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ddf51d31f5d3d5c7caab17b22c98a52f9e852350f2e6ea1468ee251c5bf0436f
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:7d512686acd8204649124f26cd4c26c84ba93a527d9cd0c45a34dc75e5d2f85b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:dfd52212d80fdb3ed9a16ffa71a414fa9840330239b17f0339557bb431e105e5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:47486cdd7c35aaf273277edd3423a8901c96380f29d492458d302ff053c9c287
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:19d46e4e1805c686ea5d1a609caa3a4417db3e5947833550c01e9c92a19b036e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2f5ddd9ab8589f6f9af2f90135105d4643638c35728aece1fec9b0c31c61c7be
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4f4d10aa2e3160824e21ae6088b1ac6306548e52592e3277fcab498c56f36ee4"
    registry: docker.io
    repository: mendersoftware
