auditlogs:
  image:
    tag: main@sha256:0d04a7a60a227402b55f5728e77ccec2ef60a131b6ce8540718eefa07fc79a31
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:0fb53cbfeaf3baf24ffeede57cb551cea401d8980ae3c4c374d12c41b1353d65
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7b705ba18a3447795914689eaf9aae71d53697d59c5d2b22ff6676e584f5e0aa
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:189f007ec7487a6aad14494740c716a93c9d13fb141c3848bd16c8f7ae0f1fa7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f722d33acde05d2d3851136aa9409c83ff06e1fe237f84f35c0392b8a6b573e6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:89df080c682a29e0bedb35b3f67f096a11a5d8d6efa5c8e1bf3daf69e6480fe1
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:828eaedb2e7c48217184bbcecc23cb1d91de1f0e377d85953912bfd47b05acbf
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d3b0771b10d9b4d7db5061f8a95649928f74a1be3ba4d9597ac5ba452ad1dab2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:163dfb5b2362ae8a9642c2cda2c87c64c58b38bb90b33dd3348283c7459c0da3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f4bf3e4ab6671dc5606dd9fac4bbfec0e6e49563ff3ffde11908b37fd0be90fc
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:2aa491545bcf27395a637568922e19e1d36ff0a0f81a6395ecb15997f351099d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c314d4f57f016225cb674a92f4b933f68fec17699a737ffe09e446596a35ad71
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f6776b1d84d962aef17ccccdf968f43ef4fd91f2e0a693ec05448703274e463e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:53370862d50f5ccd5b51ae9e36209c953127fc1c5b01620a3c962660fca8cd9b"
    registry: registry.mender.io
    repository: mender-server-enterprise
