auditlogs:
  image:
    tag: main@sha256:527e539e397b96ab1070f1399b63a1734b68a60ff3ec4ac9d3ae0a13332acf2b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:eefe62e7c929f55513be7ec2775c4698a511158da5c92a0a89f24b7e4fc5c767
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:1e460e455d76da617d52d50161923aca5b89eb080d18516dd270fa822bf94dc2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:2fb0c0e656d213ce7439081be7892d61494f9337c585f103ddaf3e7313fcc4d8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f3ba592396ce751b5131f4769c59f20abc85f121eae71cb023c6079737622e18
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2a11f9318bbbf80c5376d84069fc16b32719dea221b2c7572bac309e08aa34d1
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c8464ffeb6d9326a332cc107ecd3b6274f52e49ae9fcee84126d1220c81f2146
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:fa7bb88d227315ccf2327d56fd9879d1da6fae7639c613f134c3fdace5af3802
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b1cbfef1ad3b33136d6c3657473ce88f9c108322986ce63c13354e6b21b06647
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:21683ab83b43ce53fef1a49b98acfa394f173d0b8bd5e5bb204bf4adb48f0846
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:89d8e93c2f729810247377aa0aba7c4d3337611e7100120c9555c0ce3f65fb17
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bffe771edf77898eb75268ddfe45f666facf1866c6088216a9204a1502800045
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:fd6ea2f98c09b9dd793940d38257600bdde09b318bf824e2cd6787cf413b0529
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1653651176c813ff3adacab298d795a2163a6d14352ef14bc1fdb14c602e1e31"
    registry: docker.io
    repository: mendersoftware
