auditlogs:
  image:
    tag: main@sha256:25841685efe5cfe2fac68f14d734716bd105d3c38ac6e62fa82fbc4ac17bbeca
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2adfbae8ff24418ebe7cdf12c078bed367db478f10946eb7f976d54b61ba21b0
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bb50d84ee899408c1648977c35c388f998a14f5f59f5922df7438e1b1fa92825
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:4f8f879da361119bb17dcc560a83477070195e370e6d71a7e17a23a2f6049421
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:10abd14107b539aa9d608d8f40b654f80d3a49b6c94a879e659ff9593ac75d25
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4ff2cddd7874440ef826931a70ca51876d6435b4e88b53fda59a9e5c588bc7df
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c760d21ed28058fd1104a6fc3f554c226c98ae1105a60a90303c958d65555a39
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:07f6b296abb4e0acbe7c18d5b74c674bff4ab3fb75ef1de15234b22e3dbea2dd
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e1b7336b202c1fccdd67f70a3f7701fbfbc3c546da5b943b11c92b8f080cea38
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6bccdd323c92086427ee23d502e24b4fa34fd0991dac87ade21e7d5bc967ea42
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:2451e0ee7cfa8f2ef628748d1c9e678de7971639581fa86e8fa3e132b7897b1c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:723f56356258cfc8ff095c30f6be25a4bf4087ad3acc0e17f2b257ad2efe120b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f037fb28e16533c06e1c07ade76bbaef50016f3881e292622bc2880a018a2695
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:3e7b8177652f3088a72da98cbc78d7b5b20310fc216c2bb15b6c243dd93bb8e1"
    registry: registry.mender.io
    repository: mender-server-enterprise
