auditlogs:
  image:
    tag: main@sha256:dc95bec6c3744e0a20829b82db2ced7801821a14a96c364436e02debf7ddc37b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d1c73e61fdd59f5c8ec19e3c6b9563699be022ff733f1ce9ca6c5fd28fb7cb63
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ae1a0008c92bc260e4957b40fbb3d8f173cdfe7f6ac828d7d073a0761ff51eee
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:89c9b6dfe053841417c59805934884e66fc2a074eb1e8e4a68d07006c78ab56a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:c98ba2eab47f049b268cf220da9f18af3465d3373c56acc3a66bcdb570159052
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4f512db617fd74d357f93e9c8750bc20c6d82d0e9c4d18366c5df5ed7014bf06
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:04e76e7757381f2cf77b7f7bfad9285812a3938c130cbfbd951be26d6bcbc886
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e66d7a54f5d2331f2d13f89ab14fd4404bd4b12a6bc47136f63027ca9ed8b25d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:30aca807d441adcb1acc0a8ddaf4662f9ebac2b9a247c094b518252673ece72d
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7f42b395b375fd1d88448b1b1bc63f7f8637e03321e8d5bd98c2478fc55ded6d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:a126ead0ffdb4b76f71c181c1673117225b6889979a5b7c3f87da9d3c0d44040
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c61ff5b417d27f3c63f4eeda9f5cbfcb9968bb2c35d6edac91f36674b0ea90f4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:11fe932dddfc587a4dea0dcdfc7b5bce9f4946f0b1116a6a4b3c046374280ebd
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:72752ea014ba03e5ef2d3553972ee83d765e8583b22d3182801b44a4fe0e88e2"
    registry: registry.mender.io
    repository: mender-server-enterprise
