auditlogs:
  image:
    tag: main@sha256:7e1cebeae083d4ff837715a179ca0e8da0d57be3733bc7349da66194fcbe406b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:29a6e68aba93872fbfe1c437b17040650fd8668e4f1e0d0e0b7be2a30da5e135
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3f2f26bdd982bc2ad8e0581423f92b3d6271192b2c9e1bf7525a86db737abe33
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:702f14545dec2a140a3a3e3a889a8293504dd8f518c8be1687cfa2468dc75ffc
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:393333d1a74d8f03fa348ae9dc0fa8b4419d602a10ce2b2dd6718ed15d50a5fb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:fad55f8e90eb48b20c0165abdbc8fced64bb33196d92cea2aa6475caaa6496a5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c511101b81552ecb412d2595a64a6289743fa508f0026b7194ab739025314505
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b409288e70eb21b5e7172ee5f301f42c32614c53f780364c50277852f481e463
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4002cd6cb0ad47381aa5042b2e9578c8051394f9030910cbbaf8957ffefd045e
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:290c402851ed2baeca498478b8561f14802c6cd089bea55bb745877b12a2ff4b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:eec708e1d59a51ae155688128fe71d37e983dac4863b2de088a0b28c68f282bf
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c67321b8e159538a97509b1d019d30ff5af48f13b672d5fea5a49cd6f2ac00ab
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c925a1e5fbad175e089809b3539f006e0aa429d8cc475ca506e1f0b3cac032a5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ea019491a1654d1ca153d96ca9371e71a7e26acb77c0faed08172ab47406a6d9"
    registry: registry.mender.io
    repository: mender-server-enterprise
