auditlogs:
  image:
    tag: main@sha256:08800bcc0fefea80419b1b0f74f0dba63fdd4c71e622d4f74b129e018686e712
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ce68621f80da488176f066666c021c484dbc3e97f324058de30444829ddabeb3
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:7dd13de67f3f4536350d726d3d729000fa2a5cbc4421edd3e04e845aa931fb14
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:07542a73f78f3612c222551a8f71e6849d1e95fff80f50312b1e13d2e51d6be5
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8eceba82ebabd95fc5bb8f49df3cbe43e45d00f6f9b253bd1fced19219e10190
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6228b44554010295475c42d6982a3886e813e534f6673a4a7600397db81bbc63
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3ad2fa2aa97c877cb9e48bd1ed126023409f5abc1a5b2807223d4502b7d16d53
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:67cb1603a01708049995c8ae21529ccd416a68513654e8cb029240639d66b47d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:10f8d97347b891a79ad3287f348b51474d67760a9b1e661d27bcd6fdcef89b1a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c484f00a3a98d3d01a9811d9fbc4068eeabf5134cc1330d36737d18f5e158d7f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:371722e4f565cd2c6e0b50b0aad7325a9fca443a420d415365114ce26f21d4e2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a94fd6b583c810adf9daf7c70baf456e87b41158761f117e0c95a0cdec8217ba
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2cfd883d072c73248dc833a2bdfb405762cdacece16c51646d66d37ff215a2ab
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:02a47d7953f48980f920aafc8ecb6cd239a2bb40ee0668fc487dbf2f378b1b15"
    registry: docker.io
    repository: mendersoftware
