auditlogs:
  image:
    tag: main@sha256:18b1581dcb33e663ee2ab632c8500bd299b480b850a580b251473cf889a62ada
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2f956f8b5f0dbe2b08656aad80e3df402220d8bd254caa840983fe4fcf0471a9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:b42f4aec2f8ae4234feb1f68c5e4b0359b720e8ba0eed544a6d27c3bfc102a10
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:fe3dc323fc9e3b83d6c5c54d0b05fbde0857e3f32886b5f626a57adbaaf13a97
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:c867364147cb5f2878fe32bbe32eb4c32f8c2cf5c92905493350f275a290be27
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:57f1380fe73688c1b5490c2818fdb02e0ce1925096d127ed53d1ae125f85b0e7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:df5fd333e69e70effea981e3ad64e36d5b2ef41f0b0a3005e644a45e88093584
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:555cb0ecf889c4115bdfc776d27f0c5c0a0b95fb59a720d1e46cf0dc79657fa2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:153dab589f5608e48c27bf17fcca9d3af848e450c2735855734fdd330f8447b2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:153a0f21a938e13b10039922a55defc05cd46c620586a922f4fca08b5e028199
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1d9470c63412be205514cf4a9c192a040a634ac931d6feafc90e01dd30d086e8
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c38040bea227fe3e1f854f606136b02fe906374f294b8c7f5e0efe76a55b412a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:aafa043e36bc214f2d17a0f69ba15c0f54f275bd5947d79e36936cce03394bae
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:16a8824780004060cc0d982583f32bbca425828134302914e10afa1802fc0b3e"
    registry: registry.mender.io
    repository: mender-server-enterprise
