auditlogs:
  image:
    tag: main@sha256:866c08b7dbdb97b565654d21c335d7867390a23c83424903dc329c87391a28d6
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:54d2e4fc0db81703bdb333f21476a48044ea47aa5033208e28f1920dff161ff9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:962ab219d06a0b52b8a320a707ce4b84ac7b576102d8e0500594b9cd8a4fa8ae
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e97f26def280800545babda00426c9a03b92cf64a9e0a2de0a79dbe1fc6bc6ff
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ce24116a2f7aa7b8ac27746b39f8137939f0e952be100c6d13b064212e3408fc
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ee5075b9daa11fb567da348d2780614074abca3d685703ada5810abcdf7bfd4a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:18503104559e3236f57f455be33c92b9de6297b456810d84c28719df1f97181c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7f27894d6fcebddefd57f7f5f7942086176eedcc05355a7b0152ad93bdf19dd7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:7286344f94a657dac4b77469a1b501bad918cb2becaf8a4f55e2ba997eee7a74
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c7b79703b611f319978710b1311a72e39f631a3520ec20713c15d7cdf735f9c5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:ee18edde9e8270dafeb37d4b91dbc6b3445222a5a2bbe30ce718652cda935497
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4df319ca243c9cc230bd585026d9159e3368269bd329d7b0275830740624ead2
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:3fde0dc79366746601293ea87883c6cb45edf933b1deec3e041f6c968461888d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:16019d25bf285f0cc610175f2b7c864ff3a2a053e729c4951577b60584aa1bc5"
    registry: docker.io
    repository: mendersoftware
