auditlogs:
  image:
    tag: main@sha256:86c1f78a1f9d5b3fc98040cce1e65f1268e66787b06c8c489a1535e8d73098be
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:7379fbb1f585693ad7914208947c6edebfada8bf63c0c025b73f85960ac0bce5
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:74db5fe315d1b82e994c6da3a469ea531e9e7779757b487c5599d59b97b51094
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f19df2986a1e0ea1f86e1e6b6f28dce60dfdc9320d22ac08e282565293dfcabe
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d5c444fdd05344acd50f865d576bcd5c0ed920b0262424bacd39f1028e98ff17
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:247ddc272bfdc7b0e07162126b2cf9ffe0e69c7ae57b8a727dc2c6a21e13e9b3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0d860aa10c6fbf2c1fd841157d2a8eace5f6e6787889d61a6c3f8bc59581feef
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:9c4484ed150c406d320e9d3bf323197bd31fc975e2ef1055f2c3954b30ffcc12
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b0ceb7d5d331b0a45a4ffdf5344cb740f5ee306d1b0c6b8f064f18549f81efac
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:21c630b3d94b2a1a463384a3fc83f42532f6cca5192e9c83b7d51a787d3fa803
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:fd042e9a4691ddd3ce68090d859f76a9e506f70a73b0e8af02ecc335411df664
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:c3dbfddb93eaa16e8e56698ac8abc44dfb1dd69598870105fd1d53c1566d778f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:58edb50355509a551aa27048dd8c26bed745e952dec38e2a7cd2b53aa216ef4f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:412ab85616161070b95225ca314a86bc51aa6b43abbf1d9912000b70ccc730e8"
    registry: docker.io
    repository: mendersoftware
