auditlogs:
  image:
    tag: main@sha256:04af0672ac276c9de94cd6a7d50f32c4c3fa403e301087b7c8efd606df06a1b9
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:51f061db3eb95ecb5a6b24d4c7c5e5b112757df811889cacae5f75013835072d
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f578bf12c619feed931f01c5d51e941e0fd1e1a66eb23b2ebc11c9de6edbcd5c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f5bdddcf1ace17bf8de539c9359a1a9aa38e8bf66a530cd173eafa0c79cb353c
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:97bb4d450922fed6c8670e12d3c8e35a4ca2ac828622cd77a0ac1e657bb47f64
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:4573f3886b74888a09aaf1498e92f09319618e54b7ea3e2edab9573c1072581a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:fa68ea5e335f5a103f34ed4662ca27e4cd1949cc92ae8e4371da1266f4167638
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5896befde48d061c8f4c65499d5af1498d0b63d94a51be79a5a1a0ac9686db4d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:6296419ea4a118fb76c0e7a0e69cb45a36b873ea545fd5d5a188115aba7066b3
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8b106e8af2ad59df918e38e434766d0c033ef3728acd8c70ae5b1e4af9b7c36f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c417d1c78d5231f982b9dcaecf5afea4c4518cd73a0aa6a17ebdf40326455591
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:67f072270cd54b26f458be9f1726043d51b7c8d7277407efbe1618ba8e718f23
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:860d396c1d47738f620c538b12dd81939aadf97c9c0e72860f05d1d674fe812a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:88b99dab1e5f8218e4499ada770523c31b8934ae364649f804ec46fb8e211038"
    registry: registry.mender.io
    repository: mender-server-enterprise
