auditlogs:
  image:
    tag: main@sha256:45ba0f90881e4717016e6dc8eab84b21696aee755efa368452c4d0a2f87b2187
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:56cdfefb7743d7a64f0e770080ef212606fb83743cd0c40df0245404299add30
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:266742f58d852fe15333739fc6b2daf9faa1816fb47c91e2b5de11fdf19e4902
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e53dd0b342837922364bf7a35dae7c5b1e78ce4ea5c38ca919fbb2b46e60d8ac
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4ee0196bfabf84d7d4a72029562afd8213d4d35a719c413ce7d4c439c138f022
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f6cf08f24425dc05136207c627f84284ca98873d22750af2681928d13a02aa3a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ed065e6fbe687e4e3cb015b60ec44976417c751efd76621979a110a87f302f2b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e5086057ceeda076828b830e92075f8e3d2e576e9dcc67a0402426397b6310a7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:59951de331a5aaf6d8fb12d43946f1aa53b85cb930b18e86e215ca3df8e35e45
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:860231a71116c82d609cb9c6647dcb3ec540cf837b6e2e62d7e3caf04a2db581
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c8a6b224baab932d087591b23ae67282f9f2c7a1b42c50e7468e94ba9f1e48b0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:39ff4ef6cbe9dd6e7e93b015fb69055b7da7c031364a61d127b93ceca5c9559c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6deafa4fa265b07c66153ffde6942dbba7590b094abc49c7f9d25b9b3b432cf6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:37f75aa91b58c52e050fb498a3a9d1f06c1088af8d5f294a1523c40ada583ec4"
    registry: registry.mender.io
    repository: mender-server-enterprise
