auditlogs:
  image:
    tag: main@sha256:dc49082fc9c0df5c3f956f44208eb737848537975b8617079c129a1967d5bd17
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f34e6cee8a99bc81da73c23d789523dd8e67d9222d1a290f3cbe13af3743f8b0
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:131e18edae45847fb89b247fba0d206df4df43b38efda96ab5219c7b1c936b5e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:da1f27b2468f14c8ba72adeec439d16706e8d017a78811e158e320a01f9110f6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1b1e281da30109d5fa109f3693fe91519e876fc6ce9757423a296de1a3539bdf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:280164bd946d2960c8997005eb4e6eb755745bbab9259af26b26c2a517786d4d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b4f48a586a5dd9aa1a0adc1b4fbb05b86948cfafce616ca6d57b4ee97cf754c9
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7fc0c4251e1993bff6e908f009fc7b7ce2d4ad87b8a60c0bfc4e360870de47f2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e23ac7fd00b3ddc02759361c0b61a11c641ef9d2c6c6dd2435f1e574c7e76287
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0183ae4ebfc71946eaeb1ef14848af24061fe377e501f9e01ee86d8ae91f7d52
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:54611631243083b03c2bfc364464a3024cb8943c034a9ab111c5e17776a5f3a6
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3ce07efaafea3aa4b53352d3684c2014bf3d27e923f60fe76b73d5eb1dd73c08
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:77599f743e3057b2703ab735035b394d9a7b1e241e86af786494eefe2083820c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:af2fb63e1e1d6f2fa7691348665b0fcef5bdbf752b261bf5b4b2629a867e9e12"
    registry: docker.io
    repository: mendersoftware
