auditlogs:
  image:
    tag: main@sha256:a86f33406191a0689025074310b3af2f169ef6032f0159d30e6a3c80a7350ed5
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:64dc71286662918ecce6e96ec53dfa1435d8ca41392bc71067dbc4520b039f68
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3dd220c4cc94de976df37771d484c9089ee6ba457c0100ac9206fe75bd8c344b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:6ff2c17a09ceb9907b9e8b29c479e19bb9d21a593ea23e9c307da97c87d3b946
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:81e66c4ff7788ad9ded5313d88bafa95acd2d6b16bbb948678c0e025b487f67f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:99a4d65f82141e17fecf578af18d4ef9c45de2b17ffaa75e324cf07664ef2ba0
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5affafb0766ff916667e073fbef1f2f8c4f052d6e825c5e12aa6938057bfd036
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ff18e5f7d737616991102520a92689ac9d98c303650796d8fd62bab5a1ce4fd0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:535471d093081b5badb6acb76cc51299067618ee3d563892ef3f4774f5016da8
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f23ce42f05543653e60c86f27c3d31c4c55189b3469014812d04fb2e2da3d162
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:288f7cd0dea3538a4e11e69b03f015e6954849161f170a45aa2a042583083d0e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d093e9b2f7c55271dc421c332d8465655cdec6ad565be3a369964b80171620b3
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5e030d0ada7764eb0990bfaa2f90fb51c1e3efd4888448194c3f366db3625b60
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9d2e677f3b1475e5c34263d52cbfdd8037485c0622e0c71432d558e5ed6cc99c"
    registry: registry.mender.io
    repository: mender-server-enterprise
