auditlogs:
  image:
    tag: main@sha256:90492968e28e2e50ba0e05cc20d2471027c813e4406bb5ebe3f4c4fe3d125efd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f8ade32c843f4340f6d463663318079b4014b982c38c16ed3d31cfabbf503a72
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:d3acb32f3142e2975629d6113e667687d45e5998a4b04038878fceeec1ddb255
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7110c0fd7671d818e7d008ec571e60bfed62908a75ccbb240daee0e0544a02dc
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5b2a17f0735b79d799a9e00e443be414644e089c3b557b967f56261b4bf05c87
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ed36374ab12ed9327956aff622ae6a8e19a981fddd59251c7fdc7b892aa47278
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a3be2cebfbbf84e2c1148845c335d795623ae6e939dcd21344d359f4db21e4ee
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:78edb997080d3ffa2ce7cac4e20688358f3b73296f6a3c4a607c172089804a4c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:fd28a34ed4c0c53948043ea05ccd6d53b7547904d0a4f2bc7c4f670a5482fe76
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:aa48162aeb8402b00d26236d4f4887009734910200552d2a37cbfac74401cc99
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0e3d0bad30c647740a407f09148bbed185fcaf799bf3882a90be7cdfd8927295
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:94fb05341b50e0fbcfe32d3643dbfc947e767a70bbeff0f6f7fdb69b18a76294
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c73195be94b4afc4e0d2d07a61b2dc4e28367a7cc171a671ab7bd333d38e92fa
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4e41be62721a59ee2e36b11a55d91f910bb629f06dfa880bcfc6f21dbea63039"
    registry: registry.mender.io
    repository: mender-server-enterprise
