auditlogs:
  image:
    tag: main@sha256:7a7307f516190b1af8105d377b586e6fc879c781172b2779672b57425f21cece
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b8c4e71e6bb1a1a2210c51ec9b35e2536915699b64a57f85273d206edf8eae5c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:61c939b891cbc0bb647ad82c963f8679531fc3c46f3b0bdbf2692eb9360714dd
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:dd48e7504c405458debf911f35d6ad0d25779cef7116feb980b1d1291c1d00b8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4c17086dd51006c81163344f8b1435b602e1d20d12924141a9da8985abdb0056
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:50a3516556f371330fe52669ee857aeab442691b1b13415aff6830054d9f2abf
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e53b41deabf226f0ea0c2065a6952d488743b0d6d9396efc08059f69c12150be
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:af9315b5937dff4292eaecb0902394a8a31bef7e160d7f69eff7ebcb0b65499a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d820615a43c680ca86b6f08b05df25157adb9fe1e86687db933fa710006523ba
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:662c79193dc8f909659493e739246c48286d00568c9be8eebe5b212b1bb457bb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:08efc51e3aff953bd6a561fc5f1518d23018679b42551b7e052952a521660183
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f97fc518561795bb8014e068cbd8cdaea4fb8c8567d6576731bbf90c76f7b2f7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d14871a59c03f6f07603d3343ece824ca187301c16fc03461915af46cc677a34
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8ff31f2a417e5a0f0f06aacb8cd366912694e75c5ce2b2aa7235df23764d8e51"
    registry: docker.io
    repository: mendersoftware
