auditlogs:
  image:
    tag: staging_cdc2e6436d761f0cc425289ffdb9154fbd0bb9cd
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_c446f6a3f6c094834e71b6bb3b6037ce9197f8eb
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_6c3df85a4d6f85c67daba5df71f10da73e3678b2
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_d707e6f254da69cb3139d76aaf6e4f1e79462f7d
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_ba1010d82fdb1f8420fd36ab2dc76252028f139a
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_d6de4e76483e2ca75842ca1c82632cb88c631d80
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_becb543667976e172de6d5ccfe773297e9223d08
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_95fe06cdb6c69da3f6eeb0b2aaa336ca04772da1
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_8053b908ff936aa9c065c47221ddbbd83738d57e
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_396e97c8977ecbd8e0d52b6a4a62ac5a193a09b2
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_fd4d1435b41c3554f09f33558e1909f54d7a0a24
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_dbb4c171b78d8508086e5c90bf2649f33f23c930
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_281d652b33c1b7fc0730b8cb523e01561586735c
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
