useradm:
  image:
    tag: saas-v2024.05.13
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
generate_delta_worker:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
auditlogs:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
device_auth:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
deviceconfig:
  image:
    tag: saas-v2024.04.29
    registry: mendersoftware
    repository: deviceconfig
create_artifact_worker:
  image:
    tag: saas-v2024.04.29
    registry: mendersoftware
    repository: create-artifact-worker
deployments:
  image:
    tag: saas-v2024.06.06
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
devicemonitor:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
iot_manager:
  image:
    tag: saas-v2024.04.29
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: saas-v2024.04.30
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
tenantadm:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
deviceconnect:
  image:
    tag: saas-v2024.06.14
    registry: mendersoftware
    repository: deviceconnect
inventory:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
gui:
  image:
    tag: saas-v2024.04.29
    registry: mendersoftware
    repository: gui
