auditlogs:
  image:
    tag: main@sha256:cf6d26d0a89fb04820d27338a7e5eb7d9fcb23cf781cc8e7c2001d9ff0cd1a27
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3eb26b70692013263a3d029c8f0a56e4f3e847cc7cc850f7abafb0b321071e3a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f5564eac5fc1cd08e8b093684e559afd91042e42957215898b27d72f46fa8598
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c3e227e960753da9a10eaf3e616df326156b8e57f59c4b7761351b3fd721e534
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2dbb800b44e348e2ca0d6e6fa9a4af63d33a533295e8c0a363a725656c3c13f6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:dc02e4f4724fe5e7a44e293465edf19ad692f1d41e2c98aa1651d27f74d44720
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d602ff275606260a2fd01f57511427d3a50e338f96e3a463d3765a81a1533a2f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4a868c4e835ce85453e04f318b5f7c68dab99e0dfe184373b4bdf78776243a82
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:7c9d6bb6c4b11512080ebb5a6eda1eab5156bca7c295cc0d371a025e5017a236
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:e4f6a85ed0c16b23fff32ee3d6b5ca2b7303df4ecd1ec7e7a90b632a6ed30388
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0de9dc382fab219ebcb01568f42b000d1026842cbc747ef5ec2fdee23013761a
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d9ce2d3257e7ae281b609ccea35f6c8193cce0f650f417e10e5e48a4d671729a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5a02f34c865add3d58843a02fd2714878871312512c80ba76b09d2a325443371
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:61328e399bcbf6e4785e478c2c9e92a644fd5671339627e0627dae05153d93c3"
    registry: docker.io
    repository: mendersoftware
