auditlogs:
  image:
    tag: main@sha256:28c2ca933d7f5460b3105bfb5d6b4c75893cce86f6d70911dbcb7f37cdc1154a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:30c23f38f515204c2916e10d38bd54da2aa6eb1e15e50b086b92afb75be27275
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:da51ed05d963643945d8958df3aeb0fb7e893239766fac19ed780a6c5336cd96
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:00ba3b1d3ac4cb2f6b6f7851580d715bf2efd5ce2b45d4d5b0bf5ee916f9eb18
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:27dd34dcc74772f9d8f69847f578567b2a4396ad3d305f0415de134fb29a0901
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ca895906b7ae7abc7d4b14952606960955f4a61cbd653f0d4c37725e48469a66
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4df22242c85015fc3144f9e0ab877500de684a1663124cbd368406f31a31808c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5f9fd5e6d46955329c4e60739af8179ca4d3afe793c5fcf00c5e0d81f87a82d7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a1f2d16b499e80b5ab48389233c4088db02510a45863490a2612504776c953aa
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:46d6ab73311092169871f24b906f69cc144ffd6c3d28c19310ca4184dee7543b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:3a27e7e96c05423c3186013ddae53e58761ec61eaf53647c7c5777f092124b8d
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:5c07cc8942b617a395fd6923c93484da859b7b68018ddf6bb8758126b058259e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a1544213089639fe6b7697f69d7a39661fe673ebf0b15185bcdc7204ff77d434
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d24aa86a337685cd4a4a3a5419b13115284181f72baf4b1f2be680f3e30195b3"
    registry: registry.mender.io
    repository: mender-server-enterprise
