auditlogs:
  image:
    tag: main@sha256:83ac5b7185636b150c270acf37e4d9b2a1758b983bbf5d42b370de6b27c5c806
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:872f4fda1a10594c7f3374c2f8e8b8d31f7b09621abe1a4c0b48f4b28e9c8336
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:806badb977629c27d3049a26c026a99766e7ae2ddf16a061a5ea696bd101e396
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0fe0dc00a1ea175867a812fbd78524de669be2c0ea56cee1f3fbc6a24d10ea8f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5232de54f00e83f320f24f4f2193902261c8c9373323d6f3bff309e8e47f2f4a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:64ca931f36d959275a85747d75d28183409daf7fff4ef58b20c11a4a36a9c19e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ba3ab3461e4f89dcece4f2365ca105c3004a904ac99d000b72d1ff047833e394
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:de9bb797084d41cbd0463d652396b656dac1ae2cc1329ad7e18fbf225d42514a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:216f0500067aa365ce1f52b8e133e526b2f23d997cd3c3a9ccae2cf8c654fb7f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:fa9f7fe79deb97845df617a695786a77844c5a4d3c418ded888267a4bef28903
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:46b6008ca4e26d7a513a4ef4d670b2c3c3150fd03a6f6a564f4dfeeb885e3f6e
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:246588e611c759b9689e02c745629842489f5eaeea1145589adfbf6b1ef423d5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2f89bbed116d509f80e42cec70be69f72df698d209a5176850e33b41586f9d60
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:6ea30c7f12ce6c7d5a4413c318e654270c675b7877ab55385da3fa90f2302d73"
    registry: registry.mender.io
    repository: mender-server-enterprise
