auditlogs:
  image:
    tag: main@sha256:90e2b635bce3e8564d2dbc14652fcd92455bbcf0114bc193a13378d9e7b5dfad
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:5b30d461e6cacf63fd005c6eb1073961b9a4a12b4497cd3075011c286a33d4d9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:55259819bb5e0d629889e550550e89d83e4b5340db6daad64cc298b44f9585d4
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f42b7ec7c7d9417c9d7653fb6b1cd3b012fcb57047bfd900d8447415e5d113f2
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:88179a530392c810cf6f725a403e716ca794ddf3780cc2b7f5dd9933e8060406
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ab5884d7c0f559b454e3a60a50d1174662244d5b27c01b9f03278579fd59bed1
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:b9e6fa2942206e6acbc829f595369d2e2dd12eb1f7450a2bd1bd6e4af177a331
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:17e185ffd6c0dea13bab396b3473ab0e24a8da44e2ea810ece5a60699b70900b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:38ea2553909ec64d64d8f2f482ccbfadc3292b9d6842d6428c5b3a07189f1eba
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:fc57f1c15532255b324a55706cbef790ed57a9d92627bae1fb3afcf5431a424f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c1074e6a47f739867d5f81b6afa195701419286a37d7766741006b70da6ccd2c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:9ebad8a6d70ad0c4532411b4ca5e4c7606c7e362916a5d5369b8bed8fcbfc340
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:07f4145beaed7f7e6850003c951e844f1539fdf59d0971498d6a3d09d7977923
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:75b43b2c5d215e6f835ba9d11c3e1f09d3686fa7d0d1b279b4a5e19c173ffeb9"
    registry: registry.mender.io
    repository: mender-server-enterprise
