auditlogs:
  image:
    tag: main@sha256:104b275816d831e10bf1286a77d64a0b664c9377e026fe214488d115909d061a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:292452b5e8e650419ccd95d549b8fe97486b378f391346b294df67129353f063
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3513b8f73f9db3ab84a94027fe8f2b5af62c7179a62c6f6a1266d1b92a63552a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e854dcea00342c722b8ee051fb17b0c63d24f7bbcd63d586c352b58652676005
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:23ba5e6190b5de2d605e19ffcf45a13dba12f4448f6da263bd4122a8fef3a7d2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:03c075e4f511c60dca37b9da53ba7a73785915c17e5145e9b40be9433ae1e477
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:71098b050c68205f131de5b50faa7205cb719415ab1c4da61a7eed17b0e90ef2
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:294866aa7b6e867c7947aa498fc5c607c38470aaaa4db3a2e7376f428a9ca36b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d5a3cbc5f95e3751fbd1161449166fc83b02423411cd39617fa77024c785020b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:4be84461a963d85c53daa3d663b5521708b62ba74b45accf292ae392669b4bfe
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:e1b6a7bd3e27b785124f9eabc1eb03f66aa6e8db4a7875abc2125299f1b071ff
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:31e3d41483c01abc41ec7ea1e1cbab6d87c139bcfbcf8b72773d33cbcb39a671
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:09d3cd0e2e6b63a70f39c3dff8d742703fac159560bc43c7110d85a17e6207d6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7bcece9b81927399e32f032cd24ff1c7fb415fbc3d42fffa0267c0ff389f9150"
    registry: docker.io
    repository: mendersoftware
