auditlogs:
  image:
    tag: main@sha256:6ba44f54dea43ecaf069bf1aa34f4547265453f7c6ccea29de5f67a34723ef79
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f84c60325e8b40975e4e2784cd92627f361eef1b89421134c37c5854fe7bbc92
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:71fe6e5749ce3df48d55c387b679afd7b7b0c4412501f9e0d936aa6d50b8f894
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:981c8fbef9056f5bd6e923b1d9e52f5609a5f678cce0108db980bf2986758bde
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:aaf448eb8b2a8540549a56459da00edd1ea6455a1d5385cb0ce73636102cc770
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f0a8cdc6e16a1cc83888e8607fa4719bf87d64ee1bf83d7ab28c11cd6a5af813
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9399e5b0bb27c7ddb278c348ac3d23d5b369405087d5ea6955d51246ef3f779b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:295df3bcbbe390166eeeeb569316007a8f8d660b5f9021ca3fb8bc1e7c9c570e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:059f42088a9d5cab07b453047544533bb0cae5e2eb2ef5ac554f1961ca003630
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:9bcc5f7b44a215e0cf373af62c7307db79d2c2cf02b20ce1b63cc7b54bb95667
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0487b842618478aa26a0e7951055c829f1c8d966294f507d2271b1c2e30221fc
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:85fc59beb5c7547d0cf8b9dc2f070a9975886f80a19012374a653c77fa6b3be9
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6bc07c6f4ead21af5ac7ea1d952df47a98db612fe0658de3d7271b3ff7c841b7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c7304177c716e6bff8e7f41afc72e2c104ae8fe5ce4d8b408ed8f44ab5e5aaa2"
    registry: docker.io
    repository: mendersoftware
