auditlogs:
  image:
    tag: main@sha256:9666b5d083292123831efbcf27ebce0ebf0ed187dab07df07363c4e20600e71f
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4a509357242cda2b6ce734bdd12ce551cd9ef9abc51d4abde642a0ef032a8169
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5141ce0fcec5500cc31843396185df5c4601137c34cf3106d8ea3670a8a0a224
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:4f5ea11da93a1b5a9c530e903b14c31b99e4c004fb249e02b42d65995c63f079
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d0b0e2828632bedb5d72ec11ace6fd0b92c3392980744861214dac317ee14e13
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:68241c28042b90573aba032da34532239152ef3f2d687daab6f9d3a0b6c4bc3a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:2686318b2a975e5ae6b2101177bd46c8bf2edd0f41c235e68888311c88291bee
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:32f9a84cc38695b3af797c59df0db54e91fb6ae0079b4496c0a827ca590209f7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3046d8c20205e65d069a92ce6da58d5e7aff3fcb8198032f669e9150c46f9e37
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:55ec9f272a6ef0d7ea2da7c37a5c0beb0c7e143cfd13b3aaf1727fa429db9f3a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:923d7628f81999e8f360fea67539f2b68fd1095a0f98e8f4114032ad1352bbce
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8e2d55547370b82060e54048dc90cd52d581b25add2dfdf72eb90869f7bfecaf
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e95eb9af81276fb666d038734b740821082504092868c1ab018ec314309bffce
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f976398b718d359f1a4f6061dd55d1a273b222c762a1e4a70c85dd506fcee05b"
    registry: docker.io
    repository: mendersoftware
