auditlogs:
  image:
    tag: main@sha256:53944f37c81018d56fadc95707510d3419b6b6de5d6c0777ff606c2159db4f40
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6f059c369b3baae0d56d3a6d081772ef48a3ff00657d8cf58196ab0bbebdc6fe
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:42180d97256933bf5a49dea5d0ded8bc5f51ecb24a033313d3a33cac7e3303fb
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:708626bba9278b65d62d4fc7ab4e416b535f8b3d36cf13adf9a4c64774fcf749
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4dccb825a4d51e9fc9a0c7164d7e09855b9243f7200d388d534a77b0c6d4e112
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:13e85f155315891a57751e7658fc6c19e14a76d38ea7d53462e19a6d157a816a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:9188e51679615e1e0449d920f94b56d50ef947f1a955e0da969ecfa8acc34dc9
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5e5f5259f2afa73eca227a92e94676f268e4115279cb4049a7b6f4b86afaf287
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2856dc3cff8aa9a68203a9306350ced3f5a5a1a2050ffe3b8ae515cef723b5ee
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8dcb04c03de0351cda593bbe1afdfc8605b373423e74cbf8b8d726de08ec44bb
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9eeb6ce407375a0adf1ab991a6d654fb8f69b4be95d7a2ed704f756e252a703f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bbfff52ec6b1d7857522df9aa4f6ab4727fd09b5b732b99237c04b4f90247e3e
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:593d8444040256b6c1714bf4e50d0bc443c43d360b70bf2b8f59365e3867975e
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:30aeb74275a64298f5b094c5d855b7d71f4bccddb1cc2c27994bdf3434017e7b"
    registry: registry.mender.io
    repository: mender-server-enterprise
