auditlogs:
  image:
    tag: main@sha256:705ecba53f8dddb944b47b83e0de963ce763a535b8f330912d107d11bf8e8352
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2c861bb5df083e0df90ee3d5db68442cc2367cff3083231f399667b9ac43902a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a0795b89d2e6af149e54ec198a519691232167183dae6d8cd8ff33532294a008
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:040ad27a9e0c6e936aa675ef9e82d9967892680e917ec5366d366f208e7da12e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:191dc906720f283d484c21e45f2e07ddef63cab44d02575585d91b90a0c11803
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:398e3a367eda716836587b7242775e92b80a1d3f56852eaad4b00c26d9a204cf
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d9eb013943f7ea017b2f08ed38dc405f58992a39160b90477e2157ba1885215c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:231a793209da052320ad16313fb8592ddbd9e6c22c3794b5a9f3d37140217c8b
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:533375b771acf6c2f36126f858c339ad0b2f7570aed749522250619443f4e625
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d6edbe5c0231fd2d8b59215b783e84879b5188def510c46e98c53e561659dcda
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:82fdabebb09728b213b3216b56df351080358e08eb883e67090f7b6e380f2829
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:250bebf57de9e2dbdda47a4b636c06ca9f8494eee0d5d8aa485e1b3f5e31bb87
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d46dfc25d3220caa485375164db125db6b8c59fee24643289de9ffc83d5a631f
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:180804ff821175904a0ec04ae6a9a706fb851793a33dc40c17170e52546afddc"
    registry: docker.io
    repository: mendersoftware
