auditlogs:
  image:
    tag: main@sha256:36ee8366b73beaf0485b7bd1409c8c860fe3ca5aee0dc69a95d9b41d389fa58d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:39d71efb2bfbb8c7b737997a8f6e4fd3dd36130d6763485d897b41b08449dcf9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5ec253a31ff9845c966e46db8816ccc39f72c571335bf89d58ab7ce1ebdced0e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:a62384882baed5b431a1f7efbd61937749b4459c1473e1322def0b425f30f805
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:2f05578c7f093badaa7adc35c2bfd9874528219a1ddaa140a0f96d0fa42d48e4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:45a6ffb910272d3c96619d90eabc92310dc69a021e43aa50ab1fc2cd459635bb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:711611a8c03afbc8907a2e0d30fdffc47a90163bc305e28497971ec3421a9ed1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:9522a8acac7849170f644783c7bb45ab94dfb157425e92c568019ba74b81aa65
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3524a2e12c36ef50a9147ebc00556bfe2fafab03a313993b47f22ad25dc3db08
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:135390d287b7d8a901968affa9a83a1c386754284361b2ee47315493cb56239b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c10f1d18afea8df326a88ee8d00dc9f5e8863875785c523224273414c7c88f40
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:f8c0a4c6fc43133acd1551fab6230b6a8146826ce9045c0f0b32c281a9514e8c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1f60e5de95f4b4cfb12d416c95697281372443a7bfade3e65b062df7aa495b29
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7336f424ab8608f9aff05eded50afb1087edbb1c9177df04515bb385eb3b9853"
    registry: registry.mender.io
    repository: mender-server-enterprise
