auditlogs:
  image:
    tag: main@sha256:9f36602b984f916d1199251a7341619c23ed352379b48a3428bd339cad0a99e6
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b21520b16c74eb5ad3d0bb3d52a72cf4ac309f1d6b5454746b82d7788c26adbd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:89babe63c08283bb091e7c5252b64215003efb844ae98feb74e4a3a31fd4c183
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:3a61511026d0c29bd23c2418c841a55e0a4517bb34f4512e33b812da13046525
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:6b298ae7f4e687ab6052020d99ce80c598aab4e4554b6cb7eb99d609b9fb6182
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f571a471814c0d69c18c7b6494e7da39ffd61a9c5771f12af74db5981de066cf
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5dea97ef4ebce01ec7917bb2d791398928c6025753eb8fd04520f482ce1a7522
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:e51bdc6a613365562c99db9a5f76ae99b8314be06da581b6cf86d3faa5af2530
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2a85cb6c575360a8f91eea78857be8461c7a751da405bab48a5ede830b3f8526
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:42abd99d4bf934a221971844599506ecfa1db899a232831f30f6bcc50b232226
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:3461d752e0415a13108433fb222eb2462ef29ed3c6713dd5010938f41759945b
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d8dfeaa68bdae24b37237dd1ff04bbc770c5e526a94d87a83ddcefe29d681471
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:89aba9c0745e22eac4be6d77a1787bfb7edb15b7bca23fd6e021daf22d01e97c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e6f2d97e80099fec1760db6c168a04eca0cf71197146ed0545b2fb816d337958"
    registry: docker.io
    repository: mendersoftware
