auditlogs:
  image:
    tag: main@sha256:5e6732d3a8b0f0b2d8eb4fb0b10d40a84ecec05e306c0616d8c4f6e6f0ccb6d4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:4019a845960862ef628189ffe3e659678e6f72a32f289b2ea78224526faeda13
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f752af5ee044dc0fe0255dcb6969853b5db54f2c594981ac0eb1cd505d112296
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:a1b429b779f3669836230d80f15b1ba317c55c1ebe6222e6c570de686d41c762
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:0539d35d922e06e6bf18eafa1eb0f9d44d4894597a57e9ed76567ebeaccc7d44
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:3ee4c878b29ebd4f5f00ca6f4bc0a0c256e357caac628869545577cfd63ded20
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0b606fc461bc1b731d6060968b6066ea7329dc5dd87bc0131ab8e5195a1a1bc1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:3f7621aee4463996900041cca28c04e9265284601b9c8c46ebe9c0e1dd957ced
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:34ad694c0a47e8c88d073c31e995f37a7a33561e593326ad28197bb32ca8656b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f30c68faf66218b88b411361e64b87d2e3e6f8e417b8b0742f551a3b69eef340
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7589a6ddbf22db009a514a16c11ee932cd2e4783e84e8a428764804d584a97a5
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b86d47214faac779577ac497c3c3017140dc1e895870a39bb047d1035f24e72d
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:d01b2d4f3c71687380d787cb1ebcaf42cd0802edc9197cc17c781ec16e023269
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:44c12dfbcf1ba79db237daaff7c2779c20060632949e235b2b4a539d01d207ec"
    registry: docker.io
    repository: mendersoftware
