auditlogs:
  image:
    tag: main@sha256:810bd013a130c06f0a62b2ea4d15064cd0a96047fa833b1030a9c1ba928de1a2
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:2e253881879eae69d054cae319c61b07ba076939b4a2569ced5e09b459004d0a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:11b64892e4791d1e2904c31acc1fa753114396caa7930c8c4860a7752c6a4a2f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d6779797fc090e89f357be761cf548be51e5fd15ca774578637bb10581a3c3b0
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a58064783604ee805a8487829de6efcaf9dc0c6d208a8ea46f2304c47499127a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:50024270214cebd3842742af9112447d735a460ae97b457775f1c6047f077987
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4c79e43b2075b186860b97f136fc76d2d7c092a16db519e44f6dab9d5f833a3d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a1bd1bbada25c6ad1597a5cd505a07c5ea1434a62b7c6c00fe66693e7740c874
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d629e1cab10dc3c6f862a3a6b7022a9dd054ec731ce0687b011ed11ce75884c4
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7f81b3c3ebc5be894e3da9eaec029295fd759c2ce49af940f3dd10bcbd8cf174
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:403afb32d5870658cc94d768b7b01aba68ff4798a839c66819059f672deb5ef4
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7516631b5a40abd2c15c79d53452c77b05496f10d49c464a31809a157f2f3081
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:957f416eea26961dd351de425934fa70aea0ff929b1609e788fda5b1b18c9d96
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4f6af16b6e6d11b73e67e9f0f1c971ecf739f3c5e7909a854f1f5579d0096363"
    registry: docker.io
    repository: mendersoftware
