auditlogs:
  image:
    tag: main@sha256:27dea96fedf71745376d1df2237edaf34d05237353da645d8383a78a7d7877d3
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:a50a5e74c9582fe9ef2a3c6aee908635bd923b23fa094caf08c00af8094eb2ea
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0dd1af5cef901c7b4cba5cda70c0b869c30a19de6c02beb4f5111152a6195445
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:69626707c1b9361ab5e11b3e5fb9723c1cdf88f6c2028c777781f0d108ca10fe
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:335c2606779bc4db1a7100a430888fda4a03621cedab970b9cefb5bf36b9c8a7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:9ec0db13f3a178c2bc04019021fea94a39cda967fd777352faac2542cfa61c43
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:761542f4b1d415dd04cba39206a7f33a8aa25ade554b71bedbe93a1716704336
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:50760dc8bb99a1861ffbb053241e4c118b0a5bc420c509c215f64cc1f9675a8a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:954bf771d2d502bd5aa6ee0ebb46d3be55bff7ab8a28b611fef811ed587e7165
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:10cedc5ca48b3d0e563b20bec6d01fbc7fc5f2567c4328d52a49757ac3ed44c9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7c9ffe58960a8ed6d12b332e497fbb270522d102a0ebcee5ca2cd40b87b903d6
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:23ae717dee99c95979ef9cd8491db3132bfb9450af080183d70c838485cc4a6f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:aca441a7ca1a84aaed1e4eecc78de6e2bab65d4a83e0e2afc19e0d1bb35dd42b
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:59704003d9b9ee7bb234679d76261992dc19ca836ddab0cbb9a89dfc3ee5c8ea"
    registry: registry.mender.io
    repository: mender-server-enterprise
