auditlogs:
  image:
    tag: main@sha256:6ba0ab2929cba2296112e3e5315869fdaca92a61ab46f5fc18b9faaf0608f973
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:57e877b770b9e9cad138ef0b892d2fc23a013949db86c6e7e4ac19ae6f57ca28
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8bdfcd801e4c946a36bebab2869e0cf692d2f58033b54b63e12538234035131b
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:feaeb3e8fa91a2661707379a36c6c410d4c890f2e642074696e06344b48d264d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:c7c5c90abd247cd06334f422f6233c285f22cf93a5582a8fdbb0d1b318964646
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ecb7ed8cf95b7ac8301bcc80194b26845f9b08edf07ff5bf46e27b4ec29678b8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:0a7bb6132fef5fa9d002f8add5ee79b3fc73fcedbbede0b6bf7caaa621dcb900
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:59102d69a53ef15dcb053970366137a24130160e2a1645e9aeb48d2812debcb5
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:223fd05a6e82d06f6ad24181eaaa99592c77790026661a732919ed51b4201639
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:916434768c8374ac4560cf9e1e45512f974a2c5ed9a2c50c6a6c8eb66bd5b15e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:268de683c228190752d3a5a56112aaaeb833fed0be8c2428a975adc9a1d184a2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:21a34e661dc9f4ea7e0efb96bf23b48b63c40b4ddbed8b647e93430a776e4eef
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:a08f7d8a628c2959ec559514ee506cd6f16473abcfeb7209d9a5012fd9186e0d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c876e84bc3883dd91048de4c03ef8ad4b060ada6571db580c0eb22156b0c7e7a"
    registry: registry.mender.io
    repository: mender-server-enterprise
