auditlogs:
  image:
    tag: main@sha256:b493d0955583552e9b6e29173e2eb5fb33fc255680dedea1522cb3236d5d9a5d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b2cee51fbc270bf6cbddc7882850fd498334b6b158047e801e8b75246d2fee38
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:350ba6e4bf8b80113aa127f21c8519a51eac12af14450e2615ff4ebaa84a9b48
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:d5be3d1d37874934f7d4fc207d45463ac3afeb27239817523616dfc085100403
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:4b4825ffc4263bd72234675a589ed1319eecc3b858e567798dc8e0b8faf52598
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:42b94103e61fb7677190a4c16e6910bcc998dbcab00c1f733a929a21f61b379e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:cbe5c44452c302ef9776ccf0fec25c6f059f96870a234365b64122eae5b5a75c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d2dd442ae51510d3e227eb8b96b77e31759ddc3bdd3f070489f8c72a22d20bd1
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4ea5f35b89cac771c245d0f3aef63f42b36f8a77aa216c53709b0c402212ee56
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b9f191286f5351d0dd0cd83bc45e7516b9401be40d92343adc0126ca21b2e34f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:30fd1083c684ed3ab7a7a8ee42f4e11e2dd4951d831a4d968ec16f2a287322d8
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:44a5dbdb60b4b518387f3882ce20319a1584d5f38308e7d7ec9e9b63c12e38d9
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c2bac67ed058813f3b62e043e18b04e9b2fdcd07d6c62489502f608489a050b5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9c600a39cabb23d5f10a8134997369ead7931cfe1663e8c0bd3d7c485f4a1038"
    registry: docker.io
    repository: mendersoftware
