auditlogs:
  image:
    tag: main@sha256:c9e49fe3bc30bead761e53db9c4a9882d6a6089fea1098df93a45142cf0ae924
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:504899884f00fba6ec903ffd4c36b693aec3f6dbc70b12ff9d36d3a87db9bf0d
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:8473849118da7e1e9fb4a38ab1dd752c4d5df4b62975cd497d1c9d6e4ff0f7ec
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:7a6fadd405a9b32abd762e827cdcc43d9d8fbdb95e10f0b0bcc048cfd44e5e42
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:16701848aa1672d3586b7c9c35314f1995cff8b4d9831f686d6916371cbd9b35
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:096e1b249eec82b3b9bf7f9f40ecff0ab780bd642c7f6fbd791f41d26374c189
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6183a6500cf0df8fe088d0366a7413ec3200a1c67de0730024629724f3759b0b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:42eb59a455fa1c75ee6a8afeb9e86198c24dece16468a24bdc56540dcfd372b0
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:11902423abd8bc3a724ae4b20312899df5b5c03ac0df0c79bcb6cf5ec5c01e1f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7c43376ec3c5b469077144f7590789eea0dcae45285ddd9686c612ed295d7a42
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:26615f5431a7a113b147f36594b023b91b5ce048ec558380c4ec44bbd9eee7eb
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:fa8c09dc49c32bc79c3a4a0cdd2428168024a2b2c53fcb4cf944128304b85120
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:2669714676f6441afdc59d7c23bf05661ca1732ca2cec077c50acb64032913e7
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d27ac9b2441b78c0c7b77c0ffe45f193f17bc239c5c596367d9bfc16e4345760"
    registry: docker.io
    repository: mendersoftware
