auditlogs:
  image:
    tag: main@sha256:29f885fbdd436fa68b3525c4259d4d6546d731db241b0a62d60766db12cb8390
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:f6a110a71cedae54802472462646a702d1d6b99bee3d46e9e29e664c84d31ad1
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:125a10aaf529104aa77519236c4d5528ad9fe1578a6e370cb714ffa00c8c1e2e
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:fdf922f2f0c3f3dbf7dc308dfee65ec3832063c2707d31123a3cb087568e9958
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:1461cabd478df37b24cd6fcad6e2e36f7a209e94d9de90efe821d28f725571ad
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0fc403cd5c6c98487a3abdc3cadf07e25a659cc951fe4ecc50badfe6150c94eb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d01e7c8e57e635956b5343116c5cca6cb062d6294fc55e612b47abc81453befe
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:57799e502d0b3dd2e36b8f15ca1c8b762f0fb36024f8424ca2b218af89d72a06
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:32d80eebedfe6bfd353826ee05e3eae76841ca51de0d05cc5aa60fc55e0396a5
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:83ddb2ca568150558989f4d4647dd58bcbb4d6dbbe0458a54edde68df2ece2c6
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:1b6e91a08ba710c82de43898565e1757d1092b4e1647224b718fcb140b1ccae2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7ae35bb3eb86c7050d81bd033596dc9e2a9d3f7124bb6b95c556ca84209d683a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:200c442d047a557ac83b9f908a5d9ab4d74d57d03e50421cbe97713c401cf017
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:455036e6346cad62d0fa7a58c78e91f8a06197bd33de6eb3bf24c87c18aa6202"
    registry: registry.mender.io
    repository: mender-server-enterprise
