auditlogs:
  image:
    tag: main@sha256:4063e58e6a6cae2928ff6ae418b7962cf1fd8b03789ecea3df0e457428483720
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9620bc97dd585a088af835869d015147af455e1b43c419bcd73a64bb7df0e70b
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:26848ffbdd638ad2e34cb207ba1077e528c93892fa1efb68935241ffce945816
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:828a2226e8343a81f66d4d39639c52f62164e442b6a9423c331a96836368a697
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:d0e040150809f669d520c8d1c130f8d22de715b09c442fd33def1ead16d01a4a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cb6cb1b1267bc87be6784a1f26c6ba50d94d0dbe7468c7c5cf89d4c2df5639ea
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:5f7374a3e81cf201957c2802adaaf950403a676c65aa09e0dd4482a014626aa0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d7858753c51163067145eed582f420fa106d632ef6c8a16c816d973ca890be29
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9c63760649bdf15b03482b7e07d39cb9fed3a6e5e5c6ba1977f70e68ddd03486
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c477f5086ad1728378d8ce952867299377f120e96bf64f4ef3f0d279c9c63a45
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:65c02a5967d5efce990a159622693eda8e8bc51d6ba82d8066a95337223ac0cd
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:5561ba60148c550f74372c99da8b27e6bdb6ca53c7249e8ba695e7f3d4ed7921
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:478e654ec194bccd769478fed7706887abdeb770ec68aaf8816e797a9f4229d2
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:37f73599da5532390510d2894ccfae51d4a410711e7bff81ab9e20bff249a6d4"
    registry: registry.mender.io
    repository: mender-server-enterprise
