auditlogs:
  image:
    tag: main@sha256:4afd3ad821be04300ff40d24b91ada0409e6d13b1a6493808a23b15d2c654998
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:817061576c9fd1ef607f699a801db0713ffec2d81d2d0e3f23407cb7a4b1e7ae
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c2a24e6b884409b75941c2077b4d165b004854953f9654450de9f46fd1e49d7c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0ca8beae3f70ad5f71f9965c870d1285d6e0150e2ef739514dada0d70e5f21ac
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ca63478613d4d2f9b932f7fc5c19fc9cb97c502bfe01b6ca0d32d1914d7073fd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:9073b3bdf290a6e441d6f6c4d62b8963ba073387900913dc81f8abeef88a8379
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4841d92057f8fcdc8c0aba525c27b0916e41d1746fc860719f8739746d0d9cb8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:107e97c52216f3bf9033de4a12584237fbcea3829014e19ed41af99ae4b43ae3
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:8604a59b21c272763b863e8a2eb3bf1bbf21208442496ec79a223b0e0bc9120c
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7753d11b50064896dbe3c522e3afa76ecdf5c35518f8620e88d4b73dca07d966
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:104b91edd779d5d873540af5f8104163282956f60e493c8162b71665293082a7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:7dbc31debdedb80d5e20d548da578d3d13ed4e535fc4b582a992964cb1293bf1
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:74bffc6f39f23c116fa2fce13997ffd9b0a77cab7e9c905241682a1f429622f4
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:fee403131b035f3de3d72b772a3beae8131ffff4c41ddf4703ec41f004931b27"
    registry: docker.io
    repository: mendersoftware
