auditlogs:
  image:
    tag: main@sha256:41d963b00590fb2e2009266881e32d1e2bf22102d017ac2ab94d46fc44f60ff0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:dbac90b5651b42b164f10b16da0a19b69ff45431e291474f89ddd6fa3ced0b38
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:38567259de53a8568517a84a92fe555717a677c797fab5a0699e64074c708354
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:619f8d0ff30126e9ec5ff1dfba6f52611456c51b8cff7b286214edf8178fdb01
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8be4f4817c60a2984b8eb063a20106c011e0ce3b656c7eea31335a60da21e90a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:442443d3f08766450ae78e982db775258154fb234db55d77c9ed4250bf52363d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:c7b0d45d060e3ebdac08267b1b2fbda4aa46d878f879062eb08aadd98300c281
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:30b09bf051e1fab02a90aeb9a72f3b0a32516f5712aec5a6240578edeee1d644
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:01d71f79f1512c6235b3191cbc38c64594e74f26d467396c1c96da527d4bda2a
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7667f9ce96294ee182acea2ab6a688a86e2a8fc4d77fe2724263fde04a5dda1a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:48ae4dfa2e756b1203118addc9190fec5c39765ffbba247971441190427eecd7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:3c410d5ce569d37b10c994102e6e491999b4676414f06f91d65b276fe8fa8995
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4eafb2da5b945bd4d44489fa00eb27f43a120d1aedd77ad0004962573de5072d
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7f880ab7cf19f01e2200244b9f67e98222873e2a6bc3dd1f2ed43f98f4115e96"
    registry: registry.mender.io
    repository: mender-server-enterprise
