auditlogs:
  image:
    tag: main@sha256:8accc070df93e5bb836ddb82e02c1c132d739add5610f0e7e21b5c975434816d
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:eb4c872e90beeffb298177de30285b4bce835dcbe84d59f5935408cfd45deef9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4d88bd44c9c9ff5f0eacbf3553c44f8462ee9cc7428a16fe10ed7e49c205bcec
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ec132a86925d8b9b18e2adc9ab1e944c9bb574b2e8e5af1a35e17ddf348cac31
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b191438a0b2c7dd7592e263f5c1c622f2d680d714ce97a574990d4f83e2f1af1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f06e99db15608157045f509045be07de55038a74d9267afed8d58c7380323862
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a59b07620fcc220d01d3ed82029bbd2ef2e4d37abcb2b9f81e6054fe0879793c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:63eed0826dc0f34e4618e7b495c8b0e4f40b135104340e2885b8d4f24e75f101
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:e398b061527053bc8ad142bee1d526d1e9e661416889164796fa8b9921ae6cbb
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:97cf8ba6f7d65f5fb384649014b368364573f35f74f56b59328923a1403df596
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:cafc27eeaa04682c5adf52283e4e61f9ebfe4d160126b7f1bf5f6bd1b4ac00a3
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:6fc62c83a97c21e2dd016f6bece7dc747256c492914f6f5f3775a366b5d2d1b4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4873b10ee36b70b1e7e6bd07d11ab241a1f981e47b11b5a211bb3c2e41748e74
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:03053d7333cc9c1e383bfa132265b2f22099893355c52adfee1ea3bcfdcdea31"
    registry: docker.io
    repository: mendersoftware
