auditlogs:
  image:
    tag: main@sha256:3270af40c5258ec04eb2843fc112166bb2379616279bafe7ec2cb71f71acddab
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:167e7bf4615491cdb9537e61a530ef57fb36b5e6b1c472bed8481c90bd9a8db5
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a7aa31166544c6218f6ac6b2da346e5612c2323b2b20f258ee864c0d659b7eff
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b64dc78ab2754bc7f2895fdf5d4d7c485399e1e6bd28aef4aa4b6a2267817fbd
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:c6ab40b00494959ac048aac3ea6072c2373fdb170d84e8b73d3579fd313e8813
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:8210aaf98974bcc236c9cb9098315730c2b826f62e5d2465f89f70cc16965911
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:1e76bc8c476ed56170494bc72322e641dc5f9af5da4532e2b5389e9d4af914d8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:9995859f404e2540159c3434b77469b32c36a1c4eefd3bbd501f7bb0c9f725c4
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d45d3a1767985e25b2c3f776b723d4fe3529576347233a179a56f46313da218f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:a958d307c2f3ad4fae4df8d3cedfc94e2652b09d7209072be9f7186a3a97d33e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:405c1c1c42ff79dca656890be527eab0386d0f7ae197ba3bfa40a3206cabc1d7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:acfb2650880550229bf5d04928bb3cbaca8112a2109f3c0b75308a76e63af6ba
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:777a3e5ed1d8ecf7c588f9dfab388710c6619524a18e6f16247a374599a2f579
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9f2ff1a5bda07e463449511ed457498ac00539c62d9eb89b1c748c30d61f4d8d"
    registry: docker.io
    repository: mendersoftware
