auditlogs:
  image:
    tag: main@sha256:c25c633f327db543ba2c1272541f8815f601bea539a15a963cc68f0926e0dcc8
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:05ba384b34f5aa15e7701049ee6d1210e710e6c0ae31532b57ff47c717a2832c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4a867b61bee2df43748d6a880822115b56e7af0c0cc746c840ef6946339503ec
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9e6160197f5bcb5392c7b720cea1ad2d51ae7684ef6a299770f5dab3da82c1c6
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:27ea471d6ef0028f494e24d38cd4f47bfb6f859463302b1f06459a5bc6fdadbd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:7c0ef568b42779563b761610f3d548a358ee1621f1d12c07e2a7f64241ee102a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:dcf048e013096656c23921f2c6e2c32cb09d1fb493955743192358302b4fbb8d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:379bed9f632b88e4096cf6c3dc37cdea5616fd5d7b105eaa98445699a791dd14
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a3d333d832b55f252c7d7a40811a56ce7ed7cb709d4c171274bf5c3d90e5fe28
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:dd5a71ab40a4bfedf282bf3e72966ac14778205763175e61b3dc5dfa903819e5
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:bd5a90ec560f3e2b9305df5dcf16aa73cbbbf24fea5632f7ae25d1502b574fb7
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e8fdd1d17315d278af85c9781b1e598f00739d929b5c8c38d5f2c18a9fef7e09
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:71891c35465d99e93ba11c3c295d002233094eb06aa5ddc61a04af2cfa45a622
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:1ab79b276fd84ac72290085d02933f80d8ceb39d3a9541d0b4d5660c917de767"
    registry: docker.io
    repository: mendersoftware
