auditlogs:
  image:
    tag: main@sha256:76ad2760c156d60becb586594894f2b13b91eeabab140f77fd385b8d97ddbd46
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:238f7fd31a5bd16ffc7252ac9bd001535bb20f5b5298bf1423753f1dca21034c
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4645889306202ec383e1c49fdaf53d0083ae18ab70ab572a3e8a2cf4e7740986
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9e5cebdf031a69342b093c701015aba9e97cb334da7e4d434d45fe2dfd912fde
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:567030389ae0e32ecbf3f6e138d41a08810257d91739d43c1ac1c23ecfc440c2
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:ca54eb4de1c01795952170030a337b178ddd6888d82d1c83c4876d9f60f4f9eb
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ae660092824a1d860ca7746aa608a75c1f64b863b82ebc6c5f7a37f399525992
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:779c1c133093fa5a670d50b29b10d84af65520e2dcea7e6715ece08a82ba3543
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:ebf2019ffaabe53176c3cbe3c9cf9cc72e4f8d00d18f203f37a9fc2a688b9bf7
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:cc09448ab0c45a0d4255b70c001b0417e9f4ea13467ab6a983fc24bba658d6c7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:196e546217a4d0fb780981b59bec51b83e1bb9ac5b1e8d2b2584b3040c929227
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:89cc5d9a57a61731ad64e2c64f4e61be5aec8a5f18a37e3928f473692572e988
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:497800aef74f6713c262d9e5274749b226e7b4cf6bfc6e4c9158a468e3d5ff93
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:7b0e28ea7349c0b2888fd692376d86a5debd89fd5eb1a898db5edf7e0df31d28"
    registry: registry.mender.io
    repository: mender-server-enterprise
