auditlogs:
  image:
    tag: main@sha256:f6a205f1c3c5d4c5500a0b4cdf046296e1dbe9fb2025d732e61284f0181f91aa
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1734e120ebe6d462724fd5504f549c3d0f559cc05321283f05c86dd80169adc0
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:88d7039654fe4b6dc9c31628af4bb93bd0262dd25441b67895f5e4d589730591
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:f8cb972c7a5c32a42e6cfc5b0199e7c3b7958f68ae240461cb57b42fea9acc40
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:ba2c41a28e0162d7d1f6c801fb537378701db95a541cb1749314574efffc605e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:cc67d15f1994d0ffc743653c7015fb12e86d402022498e07df433cc62e5ef0ab
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:2f7bb0f510b03ce5c6decdffcf20322e7a78f43a893a23865c5f2f271ee039a1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:1bd26d143f07e44f8463e076d81e3c0adff190229a727f8ca43ded3c7edaef3d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d29535526a943ac94d6d727c4478033659c20838b899f34f57bd0a6515af4536
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0988c00c99c518c2a687e3f098e7530cadae160020483769929ea62c89b695d3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:47c92be81f926e8622e17773c396f1b599d9a6796e4a3c222e3bbd78b2d7907c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:197d628f44ff519f879ea5407e1ad294cccafa1ab3c179a04a05f8acfb7c1122
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:78245effa24552e9070affab99be0a5cbd1c36f9df9f279220bb44e892b61801
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:a9d3ae311b413b9e5c671eccbf64faf18c8bb6312c59f6bb539c025c9f7b2bf2"
    registry: registry.mender.io
    repository: mender-server-enterprise
