auditlogs:
  image:
    tag: main@sha256:e022d8ebaba6fd0e2a1feb726e41df6de4175cd85c318e3adee0a44413e5d2ed
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:ff88d76a478b8a748587d5d750c3a5f95bf667028321a2d8f7e02fc328d3e16f
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:4b4fe516f3c284fb89ae3dda630220370da1bd64e2e9f1407cdb7571bb0c0cb9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:9befd556a1ab7fb090c59a8c3846e66fb8256034495334d0521a368330ea3069
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:61682f967e3c43b20fb792c516d4f3b8208086a51d1f5ed89ee1f05d60a6323e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0b7d5a46eb135d7c6b8c9dbcf77744d9d2a9abf593531a486be4ad108d3c7dba
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:accf5d968ff3f47a9c156eb67d45d5123521d465be5b6af01b13c0e717a31a58
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:a958b1cc76a43f5bdc4ca27af1ba99e4a216deb975cd4f49e4556d495ac2c365
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:18443fd3b7fe39d489b048f737f495ad4b82a9a574b74c7d2772c8eb00a2df2c
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:745dd129ccfd6e6cd330d149fb3a8eb59c3810cbf1ae7c7a3adc7d63483ed287
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:24374591dec0808307d7548388d473fb1832fe0df6aa13119905d4916b0d7349
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:560d973c808847db75f74b898309ad6dc7eca0d85292c62ab9e9f70757156827
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:01457ee3d3dc537834d13781490d22f3530bf5032527b06d1caa2280cdf66e39
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9ad1eead3d142d28f01b8a51fdd396e197a808e9b6fc80eae0189d625c02e4dd"
    registry: registry.mender.io
    repository: mender-server-enterprise
