auditlogs:
  image:
    tag: main@sha256:feddd7c3824c2eb8caa18a81cab0b6527c69b2dfcb400366ef757b011b154c82
deployments:
  image:
    tag: main@sha256:c75409af11de380dc6e938c6041e87ef3419f9fa424c78d078417a069b06df56
inventory:
  image:
    tag: main@sha256:548b473a7cc69524bab71e00d7df38bf0ca5114ed3961133781d3a3de29c68db
create_artifact_worker:
  image:
    tag: main@sha256:7259768707bc752642835b63cd6bff7f68c79ada585cc813f26a0548bd8e491c
generate_delta_worker:
  image:
    tag: main@sha256:86caa0b4fa45a8f2aed767463678e8a0388466fa4aaf83782e1ad7d982e51b28
deviceconnect:
  image:
    tag: main@sha256:f6dfbe33d4c37aec99e161b2a51c5dfe43f363a7e868de9889f48915c45fc1f6
device_auth:
  image:
    tag: main@sha256:d17f459e4b64d64badd05cfbd27c9acc16e55d5d196d1cac36110da3ece86d49
tenantadm:
  image:
    tag: main@sha256:c63146235d2a9a2650a82e4d374779805062a5013efd8c6c12581548a03d20cd
devicemonitor:
  image:
    tag: main@sha256:b9d8fc75e7c68dd30f07c35d216eeac66b37b666db548d191b3ac78685109ca2
useradm:
  image:
    tag: main@sha256:1d314d3ba9e7878c59353424924e6721435bb46f3a4f98d09904a3cecee61a8b
deviceconfig:
  image:
    tag: main@sha256:7f11cf443804ff7a5c08d0c4eeee7c8564d028c922da06ee4b2219b5ce992b31
iot_manager:
  image:
    tag: main@sha256:5fda9bcab4d10c3e185d51284553a4385276692c4445a1aa6a4086832a030e85
workflows:
  image:
    tag: main@sha256:3e75e47e2d89390500d3091de0d5e19c1799470f125bb959fb9b7c91a5ebbd63
gui:
  image:
    tag: main@sha256:1b7e0bb59c49ccdde780af4ff5931bc0e7060ed83abd5d112b791aad4fe55cb0
