auditlogs:
  image:
    tag: main@sha256:96f8919f277bb6d60f48c2bcb63d563fe8dd3ebbdc1cdca3ebaf897a67a5f5e4
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9387c28c5d590523816a3e77280ea6305f8b5c743474521699173c713259feb8
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:20176cfdca9a45c1d70716195c2a41bf81c5f6226b516d3b5296353d4c0d30d6
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:65a3fdd2193b51d85d72b7a6624f9e5aa029d548b855c11f0c6b251bf17477a8
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:26f58118188642579cc5524a5b893484615fb596e043bf17d397388680baab02
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:53795953040e0243792bff13017b9a3d31eb4332d3311222504083608286a20f
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:74d3c8af95205ea0441eaf8c1b8b6fcef9aee2992da02cc973795cb287c8e964
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:90b2cc1da4fbda6f6de5efb9ae1e5a577642ec0e9d374a70761b3c4cae531da3
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b3ec83973c21a3f03788d86e76a8da92f83bd45671ab2e68df4a38ce75ef3294
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:7fad25affab31b9b29171d9cc7bfa57484ab7e88dff0125002bd138b5a28da67
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:12a341c050e1aeaa306fb557269531fc0a3ba56bc4ed50e959e9686f48fe7910
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:352732623c9a6fadce925b21b28a8466def169ed0bf177de5b0e3e7c8a2fd6ed
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:bfbea55fd5079bcbadddf4d5ba4cf3f93fa09411248041584cbb141417fc2229
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e702cc077e8bf38b00c252dfbb70b4d5a778de8f61c77e4368ca9b8b2291d41b"
    registry: docker.io
    repository: mendersoftware
