auditlogs:
  image:
    tag: main@sha256:d0fb1d405f57313228b235b50c19fa45a321504458dd6213ebbec56a52404ee0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:66210e4ac12e6bf62a46957570212747c4120e048616fb54d463257a5ccffcdb
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:c605ddf48060b58a862750fabc9959efc178602194990b10321512a9cf49091d
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0ca060df1ec2888b54cb2f20f0bc34ccc38768d39730de6cd4711fc40932461e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:0cb9eca87d43d7fc54cd4af9e3b862b4aba5d4fb174125fd60c30dc37a5f8cee
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b9bf98660c5a9ee59e83f6e0b2e58cfb97a134061212870300daa400823442a8
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:3f19dba2d041b3244433c5f79aeff7f9564e8a4616c301204add5bf5ddbf5ec0
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:ca820e17e7c52433ff7283f1a2207b478a28df3716aae495942a9d38e32f1a0d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:71fefc4027e3bc198732955e50545b67647a1c3a5378bc0cd3452a875944910b
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:8d5f98ede26ea2b3c4bb5fa2344be084c24e700a8f60eb41c28aea7cebebc9b7
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:56b976f9b695482212fcbb45bb7084dad4061787bc90f946cc8d60c6c468d595
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:bcb2201def098da384401fa73a5de87006edc4295f204b54a2b1ea763dc7bc23
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:9b901e34f24baecde9e689f7792e09c218927178f57193c87b4fc732610a8179
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:809ed7f95690d69773450b97a4d930f39cc14a1b16e7f907891e580dc3c867d0"
    registry: docker.io
    repository: mendersoftware
