auditlogs:
  image:
    tag: main@sha256:55afc6e77f6cf98ab053924fb3f413854f4e2040656ebd5b6c5d5ed1a1627a61
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:0c86aaa5aed4a0a07bb281b24a9000adda385f66e707613d0e93622a10520728
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:bff282109557f06554d8e02b7fa34333a26436dc3c52d471a07cd007076a1fce
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0f0dca8e5df19ff1c51270c8217e9b652b4bf768a6751fb5e87be28d2532b3d4
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:216d2af4e1575ebaa1d9317ccd28ddf70d9937827fd142406317bf374bbfd0b1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:6c8f07b0f91649e7aab50f7bd744884e8175828e8cd0dcc85b13633543cc20a5
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f52a116393c5e58996f23534c10edd75dabe3adce496c48e70ad787194284706
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:98da2b554bcfac24ac258c0cee4021a92f5ec47d067a55f4b99dc2ba71b7f17d
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:a5198cea243eb89c6dd199c43184a066cb2489e633a3a05678b4616c17a383bd
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:34091c043125fb575e8b8bac785df61dc77b552447cdfc0a26a60b8de7f089f4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:2a6860c130dfbac1a9b1cf4fbe90083636652836afb117c8db4c948e07bbdfee
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1ff48fd2c301bc06c78f5656daecda0e25484663d6079a6ecca8ee94f0421234
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:041f8724798cf9dc7be8b2e1090d5e892a7a7ba21779394202623d8d0ac004ea
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:9f9f669af06463fbe787f8254dc17e857e88509f4157c7b907e0183ffbde6623"
    registry: docker.io
    repository: mendersoftware
