auditlogs:
  image:
    tag: main@sha256:f53530e925cd2d16816c443df9b9e91b23c48087bb3955cb8c23daf1f8d5d040
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b511592036e53e5fa261ee9bea666239aed9e01c6b6e309b3c26bdd1df2c0cf2
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:af9cff3d3c7e0f42d22ac1188417f05d42867852bfe4f26bf332659df25c0969
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:e597ecb200365f9f19ca7dbc193ea4712b376aa475f1cc8e1ce9e1779f3a244f
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:e9237e5f56f37cc53d7babbcbcd7a0362c0fecff64f9e19387ace4a143ac2385
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:9e33e9b7cb0f87df54d9709a3f5c33baac1f75c31a3d99e70f195d2e8d9d1d8a
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d5ce6215f5d44e42874a8797797e873852c0bad579ab741d7edd824ceaf5a2a8
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:adea30765eee643aba73569bf22af49906585f671f0e79da597be9bde172bc09
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d6759c33ff096dad2a5a0f40c9a7c66d008dc655ad13d4d8ffcf61b0eb771f37
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:105f755f34161eae561e9dc0e8a021a24763fcbcb3d0106132dc819a9e624b23
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:82e2831fa18c1c1d99778418f87bbd663e8dbebbb4a967704e1781048392778f
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:4ddb0ebd22d6feb56780c106b52e8c3cb2d8c4d0ed3989d85f6f0e4a0b46fa04
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:8394baa0c6d58e0a7dcdf7d71cdc623d9fa65f2ac9d10991614634ecc44920d6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ad92697843f19841fa997c8be0f6a7e1f92dcf0cc282d6849e57b07ec7e24f25"
    registry: docker.io
    repository: mendersoftware
