auditlogs:
  image:
    tag: main@sha256:6d868d36a4baadcdaea10098d4e5e7b08926110dc0249e96873057ebd067af33
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:974e590baa2517dc511a8f84e947e27d025667b8758b5c42af0441ab7a3e9147
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:42979396e9f24781fb4d99bc8459419df1d38b28d660db38e05bbf4d3c463a8c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:5f7126b716f2784a8f89b35e3dd9dfbbf95030fa357cc1c2eb4d51047a456518
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:db906bd9ab1fd479a7f63287c395a7e97e3da943600e9e578bb17cc4d748721d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f896b6575e6565bf6b92748e9d8f2b7dcd835f0c7d5ad467e90e59f1c4f26c6b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:10c9010a38a61bfc05e664dceeb61232ecdda58c6867ebf6e9644fe646acf330
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f3c1fae87b22af5849943968bc25f5749eaf926090097d049f023ef50957ac3c
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:af0dfab8e9a0ab12df7ac4c84a6c8692834180cd06c0b502f79da65d8297e913
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:1c1b66c9e395a7140bb9748fe24608caa7673108771518f092438c5ad20e917c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:0e3820082a0977bc0435b95c9180ea0b0a610b2f19f3ac328d12d0d4df17b439
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:5a68d2fbc66e6f0a3e748892a8c074f58104a24d32eeb85960a9d59b8e0daa4b
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:69d8b74a816522048fc27048ce37b0b3dadf9fdbca25d2ecdf710599d8a5f462
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:575ba84e8faab4e6eb8d24f06691e00dce0f757631de7732e0d17eb8254e6a5d"
    registry: docker.io
    repository: mendersoftware
