auditlogs:
  image:
    tag: main@sha256:5e53975824ca0af1c60248bbae7ed17aade91921fdab32858c2e431fcd6e66fd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:9c15773e740f8f746987ba9dfd89a65a43bec585b5dbde220b495db60b868362
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:af943890bf914fa1c965e55f551e9e232f86e26a856134894acfabaab8865194
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:487ab4c807870a5e49ac8b86573466fd980790db0b2dc311fa207e12562bcb57
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:77336aca0aa83167729413837824258877bd2bc8f103fb15c2ef6045a5baa50e
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f1679389e18ca52afd5b9d5c1a241179722088c89e909b45c462e978b6955fa7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:6f8bd84b7785a5f36071d212c865bfd3860124952a844f4da32ef13ac2c0b704
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:9b9aff09b0751ae02ffdd0da6f79db47c0f898d4d775610ee9ff62ade8cf529a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:81ccc0204d026fc2e87d28012325b58e950f6359fa85dbc137aa2f7820ca1810
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6df9c636a0d1d2970b17e03650487718ed4ddcb170a32e0023d6bad703e7ecea
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:cef339752992f629728f0f537501f45014906d94167dfb1c83fb158a9ae95e7c
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d280a4cf113faa5d526a9e2320c3600e73c389e7831604de6f632762495d2aad
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:b68078b9eb0ccc20decb36dc88e84635304309d3fbbf2f878001eba2985614f1
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:6adc7e82761bff795b514ae509a1b938c91e2a47e4b26faa0bf7e06f0eb76f28"
    registry: docker.io
    repository: mendersoftware
