auditlogs:
  image:
    tag: main@sha256:0d460b4265875988a48ab05598159cd5919d9dfd57c04954dbc395a278bd5bbb
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:bf74aa9a57b6307709113639411f5d7207e2bf84a31277ffb8ecd1440e5ee262
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:fa8840fd4777375842f2b8d2224dda73f4d5f0a7a1d3a8c250de7ae7856576fe
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:27d67094830de559395745369ef7cc03102ba42757f4dbfb813d6c55454e904a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:55950f024406a04cd90f375ec35b65228d1b56c2341d21a218ffeac3ca431681
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:f75f0ac9b05fead20b3201664469900987e72de950e8f4bac0b16147e6a21678
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:d2c0c8af78acd839c6b643cef325ad34a5a5c819f6dec853a8c1c3ce7874b273
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:c103bc2434b3447184350f615689f7794b2c9656fb596f05662b7a9c2e941344
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:dbc47bb513317871e44fb74ce6623f94fb0ead18e285b54c647d4b3fa71a4f06
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:d7c74033cbfa5cc7f4dfe56d64f16c5f8ed25a3b114d054f489d1b16d919fc65
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:aebdf25aed5e4beb9dcff1eae1cd1605f0ba5157d00a62ced0482b1ec1817af3
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:64a0b8e3f7413be5dcc2a57c63826393ecf083a3f95b5f1076b4869c15029917
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:22635dffc6e7993fc1fe952ff8e0cec38a7c5890d56b102dd5a9bf9e0582bab3
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:44074f5aab853adf794c6992780870f8f37954234fee71f2248031e838187fc3"
    registry: registry.mender.io
    repository: mender-server-enterprise
