auditlogs:
  image:
    tag: staging_a3d45bf02b189dce509872419b5266e77c53d526
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_288aa0be69488aa11143b4e50aa5883c2cd4efc4
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_a1ba5fbc311f37f78e3987ed840826f13b9fdec8
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_6cda58cf8649b202774ecaf53f89452e51899cd1
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_7ff438dedd1569c7c9ae79d421d0343181d4e992
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_b6d5272b45c620cdb28c4462f4f1ee873866f1c0
    registry: mendersoftware
    repository: deviceconnect
