auditlogs:
  image:
    tag: staging_6c85a423efd4cf124eb822b54a5f34e299e11237
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_a7ec382fa61af88f4e33faf5eb1e7a698de5aa0e
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_6c3df85a4d6f85c67daba5df71f10da73e3678b2
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_6ed128633cbbd0105eb7932ae89b387c8a6fef61
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_6884b3e77be030166ce74ffdb6b47101df1def8c
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_d6de4e76483e2ca75842ca1c82632cb88c631d80
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_24e005ac886230c68b66c70042342581e1c43fb1
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_95fe06cdb6c69da3f6eeb0b2aaa336ca04772da1
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_2b998f4fd0edd5c61c464affd2c9611623fd08e4
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_48d4d650618a45dc1368700556dee806e049ec55
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_5d0bbb3cde82cc01c4afa712156c29a33a216228
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_dbb4c171b78d8508086e5c90bf2649f33f23c930
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_1b4a3041dd02e2eda41e501971f3c30b90bb21c9
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
