auditlogs:
  image:
    tag: main@sha256:c1c1bfb3cb2c8da0090eac9446bd6194cc40ca862b60db6322ac937300d16fcd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:cabc6793655d97fb15df341021c721ca5b5770b22d119c426e27da5e38dd83d8
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:548b1553cb0f01e1d9b9fa4f92e09ddbc10d0907b904ab7ed17450089d66f3c0
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:5f689885cf78e08d302a0507deb80bf76b9711044e78ec7e23a92c89787cbaee
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7770abd2e37eba77ce82dc5b27655eda2d7ddd8a9a3908f61386278d977c59ab
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a3b3c0d3964529a2adf50e0b06ed3ff4fd53721caba3ae0ce2c9b31bb853d542
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:67ca92875eb9486deeb6ff4d63f3107afd9356273c0d6b8331d0ff76a7336da3
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0804c0a1b7872f950764f12f67bb4f1bd43a3f412e3d38b3d5b601d65ecb7b27
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f0ef3450363c23546d40f6a5400dcfa2b61c476a3dd6fe0579a740a2dd0bcdc9
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:21975581ad4b22150f67f5b57ec1ad5310143f82c680b47e9c6776584bd93c9d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:7260e92c012e111cc2fe4b4784eeed09dc46a351205a9411e54ccfac1e52cfc3
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8d4af46a659b70b8d963f56f98189c63afe4077e587aff62b9965d34aac53d08
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:4338ba18381d0df2b9a1bd042586b24b4b15562b282bf9f8144c9ddbb2865b39
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4c289dbba0dacc23232190fceeeb2964d8ad64a18a26ee734e17cdbcc8688886"
    registry: registry.mender.io
    repository: mender-server-enterprise
