auditlogs:
  image:
    tag: main@sha256:0b67007f39fa109acb68281007a642ef4a3c1a10af4b133122347f252c3eedaa
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:1a45e2b82e4f3a03b4ad5af27da59f5167adfe857bb4d122436f629f1be56168
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6e52f3a005bc78a2d0009b124eb599b99f0f6d937b63ba124737ed573defdcb1
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:0e48edf5afa438ba48fd6d8fad2b811749dd07f081b852bef93aea140df5714a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:86a893b89fe6716cff344be97043111a619391eaec5b3abe88380287a8517cbd
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:0ef1eb51f324c2f5bd504f0f4877430c31cbdf81a0f9e44767a84562a2185b2b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e21a458934180c7b35ce1dd82e761db5dc4d9cc71cabb326c13ac70ae862e737
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b0209fd4e9e5e9160b26d8200edab3b280fab4435025f51d86a987670a846358
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f3056aa80754f5b9ef981b420983a0931448f19a5979214b29287f2c5280d6e2
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3479d157f44b021e56e9435c13cd982fbdb50d49e9ec0b93d7edd462e866def1
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c8d494a4f2241448ddf626b7f1da8e6ccfc6881c89d74e36b47538e9c56ae8f2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:876feaee6cba13c5c79056555cf547c660a7c8b621cda79bf7696a566ccc43e4
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:383a234aaca5279ae7c80e38187b502518b5783ded54dfc0f5d3e7551bae487a
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:25c5cb73e4f784e4aa6ea531665c3af955be2c2076b432c144981de837799d80"
    registry: docker.io
    repository: mendersoftware
