auditlogs:
  image:
    tag: main@sha256:911253eb28c3e441d9d93718efd26a205403ecba9ef8cd42603b9c9ea2962031
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:a308e50b9045f654f9f1228feb055644423dfc72e2f5ca352b9d41b3b12a5d7a
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:74f62f097da29bb94b09156c210daab4a8e029f87e26ac38015d66c121e6b01a
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:87c248bbe777bb90e9cd82ca5ec7563fd22c5683a4cd9e1a06cb1b71349ec6d7
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:b1c1a84ffb152c6f3aaa5b771aa3cc502aeb45e7cf9f1d08ba588afa4a6c2e40
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:daade3d06862f3bca1099768dc7b453d7b098bfac9834d6dcb1a7e43f62d47c7
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:26ec1c5d1f188ca3d3c3f27494b9ba3c35057f62d6e4aac4f88ee3e01b327dad
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:f18e42fc6f46b8879b5aef8596835c871cf0904909b69225ce5a6c3940c5a133
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:3f59c987af3255418e620bc501ad1bb80d13cbe83459daad253062e8b08a57e5
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:6c16e79353a2dd08323effe6f4d5063bd97fc7e6bdec0bfdf4f0eefaf0abac83
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:623f5babfa24aa5225a2be0da5e8ce15af05c9d5b0ff57bfdab309ab8b40ab90
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:29185414cf2e10186b53a1ec41c8cfd8c396aa0ff1d9ef998e3a8e6f2777e2fc
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:25afc82f58ad28ac40e8c71048ea73537c42db17e017abf639efac95e5900ccd
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8a801ace45e0a59c94a7dc9a0ced6c9cf61d0adbaa821541ed6c9951feda0dc5"
    registry: docker.io
    repository: mendersoftware
