auditlogs:
  image:
    tag: main@sha256:7655ae7ec4d46176d55ec7c9c6d0729dc013daa969ef08b27b3a0a32ea3dbddd
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6c78220eba41cd10cf77f00c0a5567adc668666903fdaf9631d76da64f718e76
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:87d249de898c09dfff6f361e25f6edd3a36ad813b33b1cfa969f387661229948
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1f65c42d865d95e578b54c506a745d7b29b1ecb7cafbef1510940b4f3d72f3b9
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:626e13d481a1498ff23ae4025bb959dbc81702466d2202b3655ba0c5b9456fb8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:118e1a412e9e48aef64dc479fb0d0f343fe9c4c247009c26ed67336d8f271246
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e28e60df4c333ceda22541661a3275d060736e957f5a0d363f6050e5ce07b38d
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:60cd4ee426ded1953b2698cc14446fa03f5e7f77457a3b425a66628ec9a796a6
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:d61e9aa3bd21dc0da96afc741458b43131fd41d261dfbb96b938b2b06f67c474
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:790e8cf1a177a4c6e5f9979ea471949c5918f2d63c0178703866e115c74c4237
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:baef0bd52b88b6fbae62023908d68828e3640540f57a9263f0b38aafdf87d4b5
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:ba8a1ceef676b0d78982853563aad3b3ce5f541cecf10d2ca8cc32ca0590ea0a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f01e257f63ad65a732d190085b978bfb25c12a579370ef2c721b303245e0fda8
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:c1458e8dc6b9342e5d0d1e1ba8e4f5f87157be55cba157616689c118e28ada23"
    registry: registry.mender.io
    repository: mender-server-enterprise
