auditlogs:
  image:
    tag: main@sha256:0b801ba11edeb2303217761be8fa9c30feca7c08f79a4f029ca04ccf13f6147a
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b08f10aa6a5e58d55c1e11558cdcc279f585cab2458587ff76e204dd52565f54
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:ef23875369e692528e79fb307628dcb6d6e385281e034520c9713d3e874121d9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:289c193771a8d09d50b28d9672565265e8e3c32f7d3a37efa73cb128da3d18f3
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7fa9ddccb2e0d436820b132616aac223833327f653822902c51418c0f433a74d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:d8e0eb793fb78758dfd31bfeab37ab7abf42e7673c11ff58e9ef97f2dcbc78a9
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:902261a3d13290006fb46e7e732b04c00f0ce2596d9a80d752744279245d7600
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:08ec810bf1b201b08d83696fcf14a18796734437dac4b14d509c077607a30299
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f8db4dd8579e617900f33bc355e339580a17cba481a77557decb3de1030f1f6f
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:752efce9b343b243a28219c843ff4a6b0bf94e190c9129e3956d2288eae051d4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:db0359b8b51fab0b5b5fb8dd662a963c5205cc3c18d1beba7b5793479b07ec18
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:fa36f492eba8996cd1c715dce77fc42f6cad0fe2daade9241b192510b9ed35d8
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:6363e037c8370048d4277eb075c7ca6663a076a78dce082976d7d75fe651f564
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:4de787132c30c97613ac8bf5709fccc22c668a9eb9f122377724b2d7062a37e8"
    registry: registry.mender.io
    repository: mender-server-enterprise
