auditlogs:
  image:
    tag: main@sha256:146fbaca84952d2bd955a7bd17cbf10f7d68d897723e6128f1a8f81b62705ba0
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:3532da0f7f01d004fc1fd4ed5339ed066557ca549a9e39df9ad06ce9a11e0617
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:0f75f440e630394abd160ac9c19a772765f5d4fa5a59a814c56bdea60d8174a4
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ce12be950bf61f51f5ea56d8a21b04622b0f91612881330a9d5c04a1a9c82c2a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:5cc7563111d38f17289ab9afe256df90bff45cf025d1dff03b595d494fd91538
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:21d9aabcd8def085f10e40b69d7f0a243e73d947f047c2136535402ae28486f3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:ad97c3caf6272e96fbbbb302f12ead8ef71546a9cc652aec243b2e00b190c33f
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:76f7e0963a42da0a91f4128249a99e0e3b3823e8bee637242f03a8e6802261b3
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:1e767d60c522df8eb1cd04222819b2f8ad5db9a388f9f45e43545982b4e14868
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:f46c817c5a6c5821fecd282e3805785d9ea5687a81d5c528ea2a7c42f3110b20
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:dac6d2ec7ac122087aa743a183e10a93e423a9ed12765da93d9805b99598cff4
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e1d50c2d1e7fd6f2cbc313946f466bb58a3016b8bb8db7a0f6b92afc37bda6c5
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:f73c9be57842b5297fb9a2b74073abc415e7dfe9fea297dffa49332395d67ee6
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:b142e98d9c65dfdca811a2f24a32beee14b6f943f59e1294790fc6f8790a40d5"
    registry: docker.io
    repository: mendersoftware
