auditlogs:
  image:
    tag: main@sha256:47fc9f68ff7ce1e56868b5f0ffe61986be496395b8eba889fd0e207e88597272
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:85e0e6264e7658d0649b90279ad9b76b423aedcc75a86abab230c614c2415798
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:3014ba41fc82606fa73bce79318a3ccf1e60b4aac72868ccd3c54b2a15d110b2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1f57377d12cb25cdfdf71d58c42b4402899594fd6fd16e806a0160b3d7aeb88d
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:80784d62d3558c66c6680d0e5495d1d475a9016fc45ccfb5e95a4d080aa27e02
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:b61182b3cfa7c572cdccb5dbd334d58efb62f661ab07691e428f4884418a3aee
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:a5ce1c71590e743497f6cb0ed734f00bf9d4a516878b8c4f099a176785f875b7
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:4a2c32fbf669fa0364d9e162e13c1c913126e21baae5fbf8f1df17d8b38ef948
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:05729915039a0c2c9444c9f09580c21998cefd19b2a6784b9f885cde818ce138
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:3fea6bfdb6385fc3728917b7c140a7c928486f8383675b62b7ae97369aae9292
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:04c0ee1222c700fbc2b82bb6c1a00a367b6db5dfcfe2e173e297698035865dfb
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a8f1c7df3f233abd8623c552e18ad7ada5a5a5561d1d7aec09d5d6d3ec4394ff
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:904516ae933cde08d70df3e9fbe8290cb96236858dff8a930b5e7d9c430f741c
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e76d07820d0556ba1f19a4d637c09c8424616104ab929218a1bb968803912154"
    registry: docker.io
    repository: mendersoftware
