auditlogs:
  image:
    tag: main@sha256:28464ccd7fb857a68c935b5e63c27974a14e357348f96ed4d3a2e00662043f77
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:d42438b57b798053e4c73af3d0e5f158579017e922ffd8c0f8b10de761daedfd
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:f0945e25b17f1fed45203012f18af0d694eef172e72857539f4bcd71035d0677
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:cc86b751aabc3f9f7a8dd3086549235460f0c17226ac424f33d458ad979413fc
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:64d6d696a215d25a4b3bb8138c993ff61973da626346ecbb78054ffdf96e1b3b
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:5561d2475691fc1f7858c90dc58631c91bcdc90abe9488fc0dea037e5a5e7299
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:70b0e90c14a6c0e46d4314e7b5e0d764a115d20ba6a9ee5e2792075cfb6436f1
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0b03ec3d21e4eccfce8322c6435c55932785866921b78824d50f4a5a49e91b6a
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:b4499b64f6f502ab16f6e2611b970adea672b8cd25ed34d9f2eb5e9c123dbd75
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:ac18d56ffa242b14fd48d26b04a23768ff47c1d31f2499f8470e897b8692eb70
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:8079bbfe3de1be3e8096fcba083fb8c7f61c9c9bdddbdf752ba67af3d7922ea2
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:8f2a9509cdb1d9935cc8a35a38d9ee15dfc4e0e4ff6c0807937bf9de3dce6c50
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:b7a32a565835e76790a3c26558d5a902d7e3a2a791a977fbb3f7420a8b8a1986
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:473fad9adc27e845c32c240353142ae4f0872fff5fc036c1fc995f9e9f2ebf41"
    registry: registry.mender.io
    repository: mender-server-enterprise
