auditlogs:
  image:
    tag: staging_30ef14b41e93112296a60b254dbe173a03d05f3d
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_5bff60e92b96bcebc5549b182d4ab5976d32be93
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_b3e9735322c9a5a22adc552806500fa8b2086ba1
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_cefd1ece55f7aff4d32d9f57fc485a84ba7387e1
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_325a5afd0020bf7333338699789c39c16f3b5ab3
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_92aaa95434687a01ed4450a9d1e79aa6803a836f
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_f6ebe13223fe5ab62fc84a76fd92c9c3cc435a32
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_8de6f5791fe5381677b409e1660fd9ed5282f93d
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_07ab86e98a67280af2c1b5d54f9983a033ac9ce1
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_51f1bab5aaa01d8105e83f3ffa52b49036c9e0ff
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_506fe908ecd9f6f2fb50ac0dd98b5e54b6a1fbe9
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_7e4b0a94405f4c622c48b5ec22446e79d3c681c8
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_415a8e4bbcd489897df41728f090af668d661a05
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_a408616743bc97e5f8d5c81a426193b4b71d9033
    registry: mendersoftware
    repository: gui
