auditlogs:
  image:
    tag: main@sha256:ddd992b47ee57c1b7d643ffc51a6260cec47b33e438b0e1c7b1626bc0573b186
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:42019775f7a1663cc8d4d4cc8a836dd207f6cf523d89137e0ddf21447dc83901
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:097e52f61080bc8a1c88a97c9c4603a667f8770aa5616ab3bc6eec0fffec49fd
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:827582fbc8994dc64e35f5f6f9112f0e4a4211bc8f0f0d3583ce59cdfe7c0e87
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:f00aff8051dc4d9060f80abe8364cfe0916ea25c4eed2dd24d975124d6755b9d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:e437b9768af177c65f4508327ed3ec0b0a4ee8df9ea4606942db51a7c8e1529d
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:047b055ac24593dffbb13de85a409cd87530d588f0765923a344eef8134189dc
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:7c1b3a2ba3e4c5b551c46b6ceeef2eb2814c5ba33700e2d13073c9edadfb73b2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:38a0edd2a419e68f2cc647279ef662994752d937cc6b5ae80fcf74328ce34d62
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:bd25d2d1ed04c966640f662053d5dffbd13d30368e33d4ea043420a6c27370ce
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c259e4b90fcd5f34595d4a257cd6c8655eeefd3c0b1d1f38da6d07ec2d5b9d07
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:e40164a55c460ca263f994a1e688c5d379226ad708cf560d3afee6c07ef01b9f
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:1a6323d44d00fdb018d44a2f78749384f8b2fefe34c8aa81bd6e40ee505624a0
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:ce85a95183293d12b45b93a9b8bcf41dc5ea4e0f304315a7b87be64660b5c0e8"
    registry: registry.mender.io
    repository: mender-server-enterprise
