auditlogs:
  image:
    tag: main@sha256:d0aa4249923a9014447ca7d84c103f814a1d51062d439355d0e48733db38f76b
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:df08c23ae0cf96ec4bf7e63cbfd1d717ae69514464f3f2c5d6cf2512a6c6d716
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:a9ce5bf4db0e15a42ba816d93fd07eabfba17237bcf5ada73f972727d38a768c
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:1e441a782a127040c8bb5c497d661455af546164ae1fb655b6ad8a054d1ec72e
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:60bf7cd58273ea1be1ff179d9dd5efee19acc0af8c4c045bae86979df71ff88a
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:176fd12e38b81f514bf44b4c5bb0637c738039541aaeac2efd27073f8c1b13f6
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:782cff05a2104abe02a03360f393d4b959954df8a828e16d3866c0912a22dfaf
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:c631b6c3bb9f970b2b060b7b2107d70203c0dcf73dac13a18012b6402cdd4fca
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4830445bd3fb03c52a2c4fb946e0f7cfe5e79b367afe5c1c86e4f4802f4b7111
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:c856106b33c8d3da4032b47000e2e189aa8fc94799b898ae18f4a5ae57fe33e3
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:01f9324dc72bab9aeca0af4570ac78086168e2e913b726ab9e75c2ca65ea9073
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:34c0eb034ed32bae75b4af240e54f41b7ec6444d0b921e7809503f064a0fb0bf
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:75aaa5b8c90af2ecbfd04445698b89ce009ed8f79ea13603a8ad736180051780
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:35f5c1891fe903cae2430f91d2b16c0d4b31cedbff823636251e565264ad24ec"
    registry: docker.io
    repository: mendersoftware
