auditlogs:
  image:
    tag: main@sha256:802d7efe066b792218e2900bac43fff1e85281ccbd77b6feb7221e27a235e865
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:87fe15334529af813aee7e64fcacf472bdc544edce4e3e9d117a7d49374b1f8b
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:92aa1a074493e2470de1fc9da95266e0747bbd5fe95070436620f0ecac1d5228
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:a0b48c896d645c563a57e8bc1c272faba04603abbecc1d6de0d2087f44e0ec4a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:7950b92f5d6db976cb71abc1b9bd3275b0ec31a04613f5149167a2dd762fdb06
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:fdb81c11fd87f563f94f9edd423b2e292b77a82983ac23afb01910063cd021e3
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:e2aa246ca5a2e60c1d1c42577a112a21d07c6d69a1b6406062c17fa1034c2d49
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d9a243040b1a20f2697c9854fc53d7338f249fde5c2be203bde9436b92b939aa
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:9a06b15483f66787283c34bdcc23f2d2b533ce68061286423ec80db487d29d46
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:260ddbcb9bc9c1e8cbb584dfcfd9a7c3d3eaea92785ea5955757aec817ce9b5f
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9e9699319af3e8c6e5ec048cedc44ef943f6c7bd4a64878e4ad4cc3035ef8edc
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:1251ab4193a4173e19a0897406e971f26447b1f04743aa921c60f0c139a37de7
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:eba145313b77efb27f4bc500dab1edba070d2b17636066c5e0e2c8b040d85804
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:d676bdfb7745ccdf3b627a5b605c5a41698f63734c926cbd6756464874e9a4ac"
    registry: registry.mender.io
    repository: mender-server-enterprise
