auditlogs:
  image:
    tag: main@sha256:5ffd69ff829a4b4622383e0e8e0fe6d9a36bf3d06965b869238c059af857a877
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e8dd71855be8996533cadbac7e4ae115b5387483e1a2af515bc103b2547aea42
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:370665b8a9b70f5b78ebb14c7ada1a6e0f51ca80e6ed1c1ca4c2a78d30a7e2d2
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:6230d98f786d5c4a252d7ff8df224c1f835bd769f1eb46788849d24093dd7142
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:a27b9666eed0a7b0123298b602f1faf0ae10c728343ad95b93f9966399e6ca95
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:df45a03ee1d735775cd59d7f06faa92ebeb30c00560ca8ecb911f3c631828288
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:10849be1dceb77e0902d9f3add61d6e1c1f334fa1c9f1510ae665535f204781c
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0fbe0d117045084114300b796f49689877b85fe7a1ffe9bc85af38659b6f1f5e
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:438f2c4b701085e42b905cb369ae07c1ad9e039de313dadebdd502fa8a065b4c
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:0c376922d1cbc35f88fcaef27572ff6f78e89e9eff8677736b2f7befb35da98c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:eb787639df0f27cdb982d6670c6362f07b34f8a1ed7c0226d1321ad9aa8df3e6
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:ad0aa9cc4dd0f7f2361dedaa8dedec09065e6757b022cd896a40d2ba5f5926a0
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5e49f214eeac54bebf302bd653b0f801b6f7826b33a1f16239b1910403df4ef5
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:44b8df6d15a932420f09bde077d17e4cdad1457b6c98df1c82a8f874d0d272b0"
    registry: docker.io
    repository: mendersoftware
