auditlogs:
  image:
    tag: main@sha256:99451b80fd4368485c91163694b6c126b24fdf9b7b5a2f44d48f8ab204102f27
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:afbea8b533cc0acbfc4309d9b539634d6bc77c92b00c345c15b800d61d564390
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:6d799bfeaad9d50fd0997dc14c070276cd2561d0519c94420da739d0510fbc76
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:ffdc49b4ba2d1b806e5dc164bfeedd1fdd6eb30f44dcdd510c2a77fccec3f435
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:fa964a0cb5c55f4955a093226077d7aa4a3e26f5bfd1e1be78dd220af32d4cdf
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:eb46532db5b07542958576e03bb38bbd20c5544f52997996b5ad7524e93e80ca
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:4e62598ce8a037bbe7ff87d0fcc8fdb7178466c4b8ce6eb0fe3a2e4890f17cad
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:b46958aa40e59756f0d3b66fb1e115198b394a944352c9ccd98e9f658a342d96
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:fbc29b61297e1410c31f87c8021b99952ce2aa26bb83912e77f1a8f51b214f86
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:abf1dfc7f852009ee68ec1697949942862c90936fa534e954e72e33272e441a0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:9d9c1245772d4f0810ecb3ff25f54b364196975d812028fccd0244f49f4b0036
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:977b28f165f41154c493f90006e5b78a2b57e5f5f294459a54fdc6d688703635
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:c4eaaf3197fef91bde100a029f1acb07b97b579b295df948d0403ffd17db38f2
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f4ecece618e464dfe92c7e11dc3d3559de2b225095aca18003f4705ed5f911a5"
    registry: docker.io
    repository: mendersoftware
