auditlogs:
  image:
    tag: main@sha256:893e543d3594b402d35a5ec32a9f06f153868c165e202277c7b87821e98d1b58
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:e23ee6c038920f281e59d925a54a701d30827a328c0107823150f7a1bcefbf18
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:d8f43756b0d22ccedda4baee1e88f3e563340a12b14c0e12408900e355db4bb9
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:b381517941cd601eed94d920bd1581466ee433bca3a9b3d42bd1b47e5ece6be2
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:8cd94307c1c1133744f6d0a93338420ac6ad39d7910b32e6e2a83160d535a469
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:44dac3e8bc1df3ae7fec5bf40dd51ee9611da4b89911fe7cf54b3ef2839be3bc
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:8b8462c24a7f0dffe2b6bdc69c667f8be1c3f6d9250a4feb3dc9c1dda8ed0880
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:0d0b64f51926b87937deb91390147eda77a1e5bb39e8fbdd8541cee5de2de9ac
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f10e6c3a77009a841c9114a419509893c7e1a115e850bdd6aaea21a8ea47b2dc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:a958d186f4c0e8bc67d5c65558420218b50180d610ef69875363150ffa466af0
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:43d7274ff41f25692fc81de73b755b8e5da7d99bbaedd33483848c358594d7e1
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:b842cda552c570993db8170041a07e7e96569e1c484f1c5830be9aa73b0328d8
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5db50972fd2fa884dbe15ac2b3d89f1b444530a456a9b94d2a86841729f2f7fe
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:f66833673674234071b1641f6f67c21844d400cb9701f28ef786f69765064607"
    registry: docker.io
    repository: mendersoftware
