auditlogs:
  image:
    tag: main@sha256:e7b3db470a5d1b44caae30ebd40a2771887a29ec69834a3869a0829988cc3004
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:6b5296150274cd3bdcafaf37fea1c5449e9ec5028c77dafdb0b84c4b5caae3bc
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:61f3e79e2e9b2c8763bfe14e95cf012d1990ab2e5128043b3bb00d4b97c5152f
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c4b5c4eb5ebff67fc7efcb4e45a5174b5e64d8108e5dbc6ad4cecbf5ab22500a
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:20f7b313dcd45c7044ca1f15d33bed73bafab9f9febbd85f0aa02a7904bd8b8d
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:2a6875eb6b47ca76de87399370cbcc40426ec3992265b31354cbb05f6c4d3a9e
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:dbb44e1789fdef973777b6d45a24db6769cace843646f84e926040fbad56a91b
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:223fe55b1849912bc8aaaaf3e5f939e143ebe47ecb517bd4fcdbb698a30099f2
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:2778192772929e3194fc358bb5c6e07139ec20a397b7579a7b88bb242bc0e3e4
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5bbfcffb3b9fdb55e0a14c0194c0e7af0d5c7b4191931e0eff2b185329173ec8
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:f10f15c66df1d4fd2cb373276fc46c5f61804fc5fc98b0f3e6f55ad0f7f56dc0
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:13c824c955919d36d02e3b1b6107a311c4e73497db66f163e72533dcf7bfe059
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:e2f5f55a83e44226e143213ecd67d79454f7a48fcfb39a1577bd466975dd79a4
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:2ed01719abd2cde9571b56100cc308965db99e2b5e82f52ebc09640a1c6d602f"
    registry: docker.io
    repository: mendersoftware
