auditlogs:
  image:
    tag: main@sha256:a7ebcd4c6dc66d7b0c9684a068816b28781854df044a554f83e446b6798af376
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:5bf7818b2fa0fcac6edd52594fa0c9acf80c414a30d8ea1cfd577d6a706b09b9
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:659e997a7c1c7231bd8d1c690b8723e101b1fbcb28c6dbe92555adb7118ccee5
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:c47b28df61f09e389d1a0f07ba612f6ae281581b3f673289393a29c750ffdb32
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:20294f6f6a662368f6913576de93d4e1165fd834ba86e6b254f9a07b8c11a2aa
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:a4a930091b9ca34d40a649dee01eff9e6ea0e4af66bea87436af2fffca7b926c
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f3703a371ca485e689753e302da6416b601042b9a0fcbddbd2f5a9aa9492d305
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:d358502f353dc9be4a1f21a2abeb9e01c66cb12684fee33c91cf83f8c817cfe7
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:f003837246b775459d22c03e0526e0dd8546ec057b62ad6e5bf96d9ac0d42453
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:5605a4c187236b2f286d34cdeb69e0a73b58336316493dd8fea722d62980a3d4
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:c4048be2a4b3d4b91f1b162618d2b652b0a1862069a549cbceb9494c058fac05
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:854eb1be1401311c156d3a19399f8a63282ed9ebb7f1e8469eafc7afd9286f2c
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:b3e2911dbe4789216cb890e33f24947c286c4fee5923cd9a4eaff270bcbb3b89
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:8e5021de6616b7df8f541bbcfc2d4f280f5cacd9ffd291955ef8879f8ca3768d"
    registry: docker.io
    repository: mendersoftware
