auditlogs:
  image:
    tag: staging_8fafacdbc9762979a590a2fe580899f1b9dda5b4
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_34ffa11c359660cf1e47ca67ff9b6cce1cf00b16
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_e3e924b021131b9d8f473933b903fad81725cbc9
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_7bdd1b5b6b899addfc39bb21015656333734f576
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_ba1010d82fdb1f8420fd36ab2dc76252028f139a
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_d6de4e76483e2ca75842ca1c82632cb88c631d80
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_35c8db966f0c8dfd2f88a7f1b89686730abfe942
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_fe23b056bd8d7a56f4bc1daf437c611cee9ae370
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_8053b908ff936aa9c065c47221ddbbd83738d57e
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_9e10ae611edff48a1783c5ae0f483c8d35e36b62
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_630719591b75ae642b822e9221161213b713ec77
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_45d5eec5ea9703edce3ef26bee1426eab730d36c
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_9b8a9b980291fb788e0c18edf779c464e6f95dab
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_d07bb5c47fdaa370f5bb164e588b06d77ccb12ee
    registry: mendersoftware
    repository: gui
