auditlogs:
  image:
    tag: main@sha256:19b9c7fe3eb242463ad6d82fd0bfee74d2be2821d2be8c355adaa695bffb0a4e
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:b066508289904ef5df7e2d90c56fd2cda852793997ed8093e140b28346e9c0e8
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:b4ad2d20e02839e1491d94e26e4796814f4f96041bc4cc43985ad407ca271952
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:61afa7ddbb8189c0af88f294c8f4f28f4f3597041069ad4cef1522ea056d43fb
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:3383827b318a68e762289216879e70ef1942d9b39bbe86a7ebe0db4df5db8389
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:af3c9f08a71dbbb34e1d723ada3ae5560cc465a602fd89a0dc9ed4b20b81aa5b
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:55551358b4dc1079d6b4d50311c261539615a519af78d12ebc65030c304e68ae
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:417c61530a3c1ab1213727155dd0afd63e9280af0a83f573b5ee7f4bac10a542
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:4cfb2ade0d852213f20780d2e0f44d32434e69be76a99073679d42cbf04414dc
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:64109ef4f1f4f002fbe4a4824596be7a6bf772c31e145741ec16c29d2c8495f9
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:5513aae40badb783d52e0e87490a52bd042421039289bdf18ad12a5cbf93cf30
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:a342f73168536bcf5c6cdf90acd888a22f4775be84983c1ca407d165fa10755a
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:ea4cf073d19526bdea951c2fb12723df3b28980b38f1529783b39553a1487801
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:577763297206c199e3384471f3c78ec89046a8c5a06c7271b881b66bf47c9051"
    registry: docker.io
    repository: mendersoftware
