auditlogs:
  image:
    tag: main@sha256:94c7246c707b6f99c2a96b794f425d89bfbb143a1529b977e55e44238afd1933
    registry: registry.mender.io
    repository: mender-server-enterprise
deployments:
  image:
    tag: main@sha256:698c41e59155cfd0bec46801090c1a104c2bb7671833e4bcc8d5f4358c56f34e
    registry: registry.mender.io
    repository: mender-server-enterprise
inventory:
  image:
    tag: main@sha256:5c97b4cab52ec9777dae04474dca640dfff3bafb69c0a1576996e72ddcaf3b91
    registry: registry.mender.io
    repository: mender-server-enterprise
create_artifact_worker:
  image:
    tag: main@sha256:788d883589a2f2f70c9adfa238a522e538de22b330d58cbb840e2b8f91eb6335
    registry: registry.mender.io
    repository: mender-server-enterprise
generate_delta_worker:
  image:
    tag: main@sha256:54217d6700e5316d26f66b9d2bcbd156608ec949925c317e6df1970126695a96
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconnect:
  image:
    tag: main@sha256:04203de2880d99997e682c51dc73354ea8be60a19e91db5c1fa20841e36d1016
    registry: registry.mender.io
    repository: mender-server-enterprise
device_auth:
  image:
    tag: main@sha256:f2640db5f55a492dee4e6695bbd2812dce18c7a2250344b64ba499def3cf00f6
    registry: registry.mender.io
    repository: mender-server-enterprise
tenantadm:
  image:
    tag: main@sha256:5bcf2a19e5abe118750cfe0fbe2f7183812ffd754e40f06c69b53718247d89a3
    registry: registry.mender.io
    repository: mender-server-enterprise
devicemonitor:
  image:
    tag: main@sha256:904b9029224cebc8e3966d4bb0b149eba7f61c13ea111d25c7d0af37f82afab8
    registry: registry.mender.io
    repository: mender-server-enterprise
useradm:
  image:
    tag: main@sha256:b48d9bc6ad3afda095967b18034e973cd0287fa821589d1c23dc499066cecb9c
    registry: registry.mender.io
    repository: mender-server-enterprise
deviceconfig:
  image:
    tag: main@sha256:62406c18847f7b158fa64cc2afa7e4d5c25373e124021185c467833202f28975
    registry: registry.mender.io
    repository: mender-server-enterprise
iot_manager:
  image:
    tag: main@sha256:d2c37d95fa6045afad51b3bddd50e07c72381cf5b7022bbc6d3957cbef72ab24
    registry: registry.mender.io
    repository: mender-server-enterprise
workflows:
  image:
    tag: main@sha256:5e6142bad991cfd003fa9d94d3425a71a3335e6862c6272cf6522cf53629d3ba
    registry: registry.mender.io
    repository: mender-server-enterprise
gui:
  image:
    tag: "main@sha256:e604368cfac5b05565927277dc7d21aa469967996c668fcd436611533de9c2c0"
    registry: registry.mender.io
    repository: mender-server-enterprise
