{{- if .Values.workflows.enabled }}
{{- $context := dict "dot" . "component" "workflows-server" "imageComponent" "workflows" "override" .Values.workflows -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mender.fullname" . }}-workflows-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "mender.fullname" . }}-workflows-server
    app.kubernetes.io/component: workflows
spec:
  replicas: {{ .Values.workflows.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mender.fullname" . }}-workflows-server

  # if deployment is not completed within 10 min, consider it failed,
  # as result deployment Reason=ProgressDeadlineExceeded
  # needs to be big enough to rollout to complete
  progressDeadlineSeconds: 600

  # Rollout upgrade
  {{- $updateStrategy := coalesce .Values.workflows.updateStrategy .Values.default.updateStrategy }}
  {{- if $updateStrategy }}
  strategy: {{- toYaml $updateStrategy | nindent 4 }}
  {{- end }}

  template:
    {{- include "mender.workflowsPodTemplate" $context | nindent 4 }}

{{- end }}
